### ISSUE TITLE
Git log looks cluttered

### ISSUE THREAD

**Issue by LalatenduMohanty** [redhat-developer/odo#100]
The git log contains git commits for all merges which makes it not developer friendly. Specially when we want to back track some commits.  The merge commit are important when there are many committers and we want to keep a track of who committed the code. But it makes the commit history bad to read. 

To merge without the *merge commit* only rebase and merge (when using CLI) and using github UI, use *Rebase and merge*.  You can change the project settings to only allow *Allow rebase merging * Please check Minshift commit log to see the difference. 

For example check below commits

```git
commit f1819dec1038f77e777191c435ecac918f70d256 (HEAD -> move-ocdev-to-gobin-after-make, upstream/master, origin/master, origin/HEAD, master)
Merge: f71b16c 32cc76b
Author: Shubham <shubham@linux.com>
Date:   Fri Feb 16 13:01:38 2018 +0530

    Merge pull request #95 from kadel/add-make-test

    Add 'make test'

commit 32cc76b8b18326a4c09af4f347aa63d06b0a3776
Author: Tomas Kral <tomas.kral@gmail.com>
Date:   Thu Feb 15 17:48:45 2018 +0100

    Add 'make test'

    runs unit tests for all packages
```
If you run `git show f1819dec1038f77e777191c435ecac918f70d256` you will only get 
```
$ git show f1819dec1038f77e777191c435ecac918f70d256
commit f1819dec1038f77e777191c435ecac918f70d256 (HEAD -> move-ocdev-to-gobin-after-make, upstream/master, origin/master, origin/HEAD, master)
Merge: f71b16c 32cc76b
Author: Shubham <shubham@linux.com>
Date:   Fri Feb 16 13:01:38 2018 +0530

    Merge pull request #95 from kadel/add-make-test

    Add 'make test'
```

**Comment by kadel** [comment]
I think that this is more of personal preference.

I personally don't mind merge commits.

**Comment by LalatenduMohanty** [comment]
@kadel In my experience  it makes a lot of difference. From a clean code point of view why do you want to have extra commits if does not have any real value?

**Comment by kadel** [comment]
I really like the fact that for every commit I'm able to find from which PR it came.
Isn't this going to be lost if we start doing rebase?

**Comment by LalatenduMohanty** [comment]
@kadel I think keeping a track of discussions related to an issue for a corresponding PR is very relevant.  Because issues are more persistent than PR(PRs can be created an closed). You want to have issue for each PR (and mention it in the commit message), so that things (that matter) can be discussed first in the issue and then PR gets created. So it is really easy to find out the issue number any code change and easy to find the PR too. It works beautifully for me.

**Comment by cdrage** [comment]
What we've started to do is put each change into a separate commit when a PR is open. When it comes down to merging, we've done a squash + merge which combines all descriptions / titles of the commits into one. It's been working quite well for us these past few months! :+1: 

I'm going to go ahead and close this, if you wish to discuss this more, feel free to open this back up @LalatenduMohanty !
