### ISSUE TITLE
Improve the code layout of ocdev

### ISSUE THREAD

**Issue by LalatenduMohanty** [redhat-developer/odo#101]
In the current layout we have the `main.go` in the root directory, which IMO is a bad choice.  
There are few reasons behind it.
* From long term point of view it is better to keep main.go in the cmd code.
* It allows to have add more code to create another binary i.e. you can add another directory under `ocdev/cmd/` which can use the same packages but Makefile can be modified to create a new binary.  
* Also the layout should not cause an issue when you want to expand the project. 

Current layout. 

```
├── cmd
│   ├── application.go
│   ├── completion.go
│   ├── component.go
│   ├── documentation.go
│   ├── root.go
│   ├── storage.go
│   └── version.go
├── main.go
```

Suggested layout. 
```
.
└── redhat-developer
    └── ocdev
        └── cmd
            └── ocdev
                ├── cmd
                │   ├── application.go
                │   ├── completion.go
                │   ├── component.go
                │   ├── documentation.go
                │   ├── root.go
                │   ├── storage.go
                │   └── version.go
                └── main.go
```
Some supporting articles
* https://medium.com/@benbjohnson/standard-package-layout-7cdbc8391fc1
* https://peter.bourgon.org/go-best-practices-2016/#development-environment

**Comment by LalatenduMohanty** [comment]
@containscafeine @kadel I have the patch ready(almost) for this. Let me know what you feel about it. Then I can send the PR for it.

**Comment by kadel** [comment]
Yep, we can change it to this structure. 

A small downside for this is that to "go get" this. it will look like this `go get github.com/redhat-developer/ocdev/cmd/ocdev`. But "go get" is not preferred way to install this anyway, so I'm OK with new structure.

**Comment by cdrage** [comment]
This is hard.. one part of me feels that Odo should be `go get`-able, the other part is conflicting since this directory change is for the best.

Do you still believe that we should implement this change @LalatenduMohanty / do you still have your patch available?

**Comment by surajnarwade** [comment]
I assume this issue is moreover about code refactoring and reorganization and which is being tracked here actively: https://github.com/redhat-developer/odo/issues/785

Closing this issue as duplicate.

Feel free to reopen :smiley:
