### ISSUE TITLE
Error message for a missing component was clearer in 0.14 than in 0.15

### ISSUE THREAD

**Issue by apupier** [redhat-developer/odo#1016]
[kind/bug]

## What versions of software are you using?
- Operating System: Windows
- Output of `odo version`:

```
odo v0.0.15 (2f7ed497)

Server: https://172.18.93.44:8443
OpenShift: v3.10.45
Kubernetes: v1.10.0+b81c8f8
```

## How did you run odo exactly?

from command-line

## Actual behavior

odo push --local c:\ws\workingDirectoryForTest\fuse-rest-http-booster
Pushing changes to component:
unable to get component source

## Expected behavior

something more explicit like in odo 0.14:

odo push --local c:\ws\workingDirectoryForTest\fuse-rest-http-booster
No component is set as active.
Use 'odo component set <component name> to set and existing component as active or call this command with component name as and argument.

**Comment by amitkrout** [comment]
@apupier Could you please have look https://github.com/redhat-developer/odo/pull/1139#discussion_r241714074

Is this make sense to you ?

**Comment by amitkrout** [comment]
@girishramnani @mik-dass ^

**Comment by apupier** [comment]
> @apupier Could you please have look [#1139 (comment)](https://github.com/redhat-developer/odo/pull/1139#discussion_r241714074)
> 
> Is this make sense to you ?

yes, having the explanation why it is failing and how to "fix" it is better.
