### ISSUE TITLE
odo login returns incorrect help message when user has no projects

### ISSUE THREAD

**Issue by jankleinert** [redhat-developer/odo#1017]
[kind/bug]

## What versions of software are you using?
- Operating System: macos 10.14
- Output of `odo version`:
odo v0.0.15 (29a07286)

Server: [REMOVED]
OpenShift: v3.11.16
Kubernetes: v1.11.0+d4cacc0

## How did you run odo exactly?
odo login -u user1 -p [REMOVED]

## Actual behavior
odo new-project is not a valid command

```
Login successful.

You don't have any projects. You can try to create a new project, by running

    odo new-project <projectname>

```
## Expected behavior

```
Login successful.

You don't have any projects. You can try to create a new project, by running

    odo project create <projectname>
```

**Comment by surajnarwade** [comment]
Hey @jankleinert , thanks for raising this issue. Unfortunately, We don't have control over what text we print  after login, because openshift takes care of it.
Now to tackle this solution, what we can do is, create alias `odo new-project` for `odo project create`.
WDYT @kadel @cdrage ?

**Comment by kadel** [comment]
This is a side effect of how we implemented the `odo login` :-(
We don't control the message as it comes from the openshift code.


The only option, if we don't want to reimplement login ourselves is to add `odo new-project` alias. This alias should be hidden from the `--help`, as this is only placed where it will be used.

@surajnarwade I remember that we discussed this a while back, I thought that this was in the original PR :-(

**Comment by jankleinert** [comment]
Does the entire message come from openshift? It has 'odo' in the message text, so are you already doing some kind of search/replace on text you get back from openshift? I 100% realize I don't know how this all works, so this may not be possible,  but could we do something similar with the new-project part of that string? 

I worry that if we make an alias for new-project that it's still confusing since someone could see it here but not find it in help or docs, and it takes away from some of the nice simple grammar of odo (even though it's just an optional alias).

**Comment by kadel** [comment]
> Does the entire message come from openshift? It has 'odo' in the message text, so are you already doing some kind of search/replace on text you get back from openshift? I 100% realize I don't know how this all works, so this may not be possible, but could we do something similar with the new-project part of that string?
> 

Sadly the whole message comes from  openshift :-(
Lucky for us it is cleverly implemented to autodetect the command name, this is why you can see `odo` and not `oc`. (https://github.com/openshift/origin/blob/c236a874abc06c08b1253b5a1db6cc7a87442a3a/pkg/oc/lib/errors/login.go#L61 https://github.com/openshift/origin/blob/02d8ae1ed77da9fea9e3deb7fecade8bf3117445/pkg/oc/cli/login/loginoptions.go#L301)


> I worry that if we make an alias for new-project that it's still confusing since someone could see it here but not find it in help or docs, and it takes away from some of the nice simple grammar of odo (even though it's just an optional alias).

I agree, it could lead to some confusions :-( But this is our only option :-( We can't realy controll that message because of the way it is implemented. 
OpenShift doesn't provide good library for login api. The choice was between reimplementing everything in `odo` in our own way and risking buggy implementation, or calling openshift code. This discussion might give you more context https://github.com/redhat-developer/odo/issues/555

**Comment by jorgemoralespou** [comment]
We need to know from `oc/kubectl` cli developers whether changing the behavior there is simple, and if the shift they are going to go though to move all these commands to plugins would provide a way to customize this behavior.

Addinc @soltysh and @juanvallejo for their insights.

**Comment by jorgemoralespou** [comment]
@soltysh so, in the path to move these commands to plugins there is no intent on changing some of this behavior?

@simo5 gave us hope (https://github.com/redhat-developer/odo/issues/555#issuecomment-420811773) in that in a not too distant future code would be more reusable. What @kadel explained is that currently is not. 

What I'm asking here is if it code will eventually be more reusable, and if the `odo` team can get more information of the work as it happens. 

Even going the route @simo5 mentions here (https://github.com/redhat-developer/odo/issues/555#issuecomment-420734463) of calling out to `oc` would make our CLI buggy.

So it seems for now we're going to have some `bad` behavior.

**Comment by jorgemoralespou** [comment]
@kadel, can we just not "eat" the message we get back from `oc` when it's called? Is it directly outputting the message to stdout?
Can we not provide a streams implementation on the call to oc.login so that where can later strip that message, for the time being?

**Comment by kadel** [comment]
@syamgk It looks like we might be able to "eat" the message as Jorge suggested.


Check this out https://github.com/redhat-developer/odo/blob/c3c906ffe2e3a394833962a51e682863a31d4a36/pkg/auth/login.go#L25

**Comment by jorgemoralespou** [comment]
We should probably open a PR for oc to fix the fact that is using fmt.Sprintf directly. Then, in the near future, we might be able to "eat" the message with oc 4.0 :-D

**Comment by cdrage** [comment]
Solution: Temporary solution would be adding an alias

**Comment by cdrage** [comment]
I've unassigned @syamgk temporarily if anyone else wants to pick this up.

**Comment by mohammedzee1000** [comment]
Looking at two options here:

1. Adding it to Aliases parameter of cobra command. This instantly fixes the required case, and it also does not appear in the docs but means user will be able to do `$ odo new-project blah` for all `$ odo project blah`
1. Adding a new command specifically for `$ odo new-project create` which triggers same process as` $ odo project create`. This should ensure only `$ odo new-project create` is possible but will bring in complication of how to not have it appear in help. As far as i see in cobra docs, this may not be possible.

**Comment by geoand** [comment]
> Looking at two options here:
> 
>     1. Adding it to Aliases parameter of cobra command. This instantly fixes the required case, and it also does not appear in the docs but means user will be able to do `$ odo new-project blah` for all `$ odo project blah`
> 
>     2. Adding a new command specifically for `$ odo new-project create` which triggers same process as` $ odo project create`. This should ensure only `$ odo new-project create` is possible but will bring in complication of how to not have it appear in help. As far as i see in cobra docs, this may not be possible.

I would go with the alias.

**Comment by mohammedzee1000** [comment]
I have successfully implemented both. The first option involves one liner change and the second one, a few.

**Comment by geoand** [comment]
I'm probably not the most qualified to answer, but for the alias would be the most natural

**Comment by mohammedzee1000** [comment]
Commits are present for both. so PTAL

**Comment by geoand** [comment]
Both seem simple enough, so I'm fine with whichever :)

**Comment by metacosm** [comment]
I'd go with the alias as well since the other option duplicates code.

**Comment by mohammedzee1000** [comment]
Had a discussion with @kadel and we might have a altogether better option.

https://github.com/mohammedzee1000/odo/blob/master/pkg/auth/login.go#L25

Looking at that line, it looks like we are supplying os.stdout as output stream. If we provide another stream, we could catch the message, read it for information, discard it and paste our own message.

I will be digging deeper into this approach

**Comment by mohammedzee1000** [comment]
@metacosm @geoand

**Comment by geoand** [comment]
Sounds good to me @mohammedzee1000

**Comment by mohammedzee1000** [comment]
@metacosm @geoand @kadel
