### ISSUE TITLE
Ocdev version should be part of Makefile

### ISSUE THREAD

**Issue by LalatenduMohanty** [redhat-developer/odo#103]
As a best practice you do not want to keep the version information in the code because you do not want to touch the code if it is actually not a code change. In long run it helps as git commits related to version change will be only in the Makefile. It also looks clean IMO. Usually contributors find it easy to just change the Makefile vs changing the version.go.

**Comment by kadel** [comment]
For me, one big downside for keeping it in Makefile is that it is easy to get confused what version you have. If someone builds it with just `go build` then they don't get the right version output. And the same thing for `go install` and `go build`.

I don't mind moving it to Makefile, I just want to make sure that we are also aware of the downsides.

**Comment by cdrage** [comment]
We now have versioning in both `build/VERSION` as well as `cmd/version.go` files. I'm going to close this for now :+1: If users would like to see what version they are using / they originally build they can check either file.
