### ISSUE TITLE
Support for .odoignore file

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#1036]
[kind/Feature]

## Which functionality do you think we should add?
We need to support having an `.odoignore` file in the code directory so that when the users do `odo watch` and `odo push` these files are not monitored or pushed to the server.

Initially the creation and management of this file should be manual, but once #803 is done, the initial configuration for this file should come from global configuration tuneable by the user.

The content of this file should support similar syntax to `.gitignore` and should behave the same way.

## Why is this needed?
To improve on push and watch behavior and speed.

**Comment by jorgemoralespou** [comment]
The list of default ignored files is tracked in #1011

**Comment by mik-dass** [comment]
@kadel How will be handle multiple .gitignore files in sub folders? And will .odoignore support multiple files in sub folders?

**Comment by jorgemoralespou** [comment]
.odoignore should be honored when doing `odo push` and `odo watch`

**Comment by mik-dass** [comment]
> .odoignore should be honored when doing odo push and odo watch

Agreed. @kadel WDYT?

**Comment by kadel** [comment]
Reopening this, as this was implemented only for `odo watch`. Push is still missing support for ignore file

**Comment by girishramnani** [comment]
@tkral do you think we should consider multiple `.odoignore` in this sprint?
