### ISSUE TITLE
Creating structs and related functions for Odo entities

### ISSUE THREAD

**Issue by mik-dass** [redhat-developer/odo#1087]
Odo entities should be represented as structs and they should have related functions like CREATE, DELETE, GET, LIST. This will help in machine readable output and also help in reducing the number of parameters passed to functions.

I would like to work on it and will create a simple sample PR for discussing design patterns

**Comment by mik-dass** [comment]
@kadel I have raised a WIP PR for the project code refactoring #1101 Please have a look and let's decide on a pattern to follow for other components

**Comment by kadel** [comment]
@mik-dass  Can you please estimate size for this task and add size label?

**Comment by mik-dass** [comment]
> @mik-dass Can you please estimate size for this task and add size label?

I have assigned a M size to it

**Comment by kadel** [comment]
This should be handled as part of https://github.com/redhat-developer/odo/issues/1263
