### ISSUE TITLE
Interrupting odo doesn't reset the terminal colors 

### ISSUE THREAD

**Issue by girishramnani** [redhat-developer/odo#1091]
[kind/bug]

## What versions of software are you using?
- Operating System: Fedora
- Output of `odo version`:
```
odo v0.0.17 (6fd59191)

Server: https://api.engint.openshift.com:443
OpenShift: v3.11.43
Kubernetes: v1.11.0+d4cacc0
```

## How did you run odo exactly?
`./odo create ruby --git https://github.com/girishramnani/ruby-ex.git --ref develop -v 4`

## Actual behavior
![screenshot](https://user-images.githubusercontent.com/6551988/49517267-c73f6f80-f8c1-11e8-91c0-575386b35c18.png)

## Expected behavior
The terminal color should be restored to white

**Comment by kadel** [comment]
It looks like this is fixed.

@girishramnani If this is still an issue, feel free to reopen this issue. But I wasn't able to reproduce this in v0.0.18
