### ISSUE TITLE
local .odo config file

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#1092]
We could start with implementing `<app-dir>/.odo/odo-config`.

`odo utils config set componentType 2Gi  ` will save memory value to `<app-dir>/.odo/odo-config`
`odo utils config set componentType 2Gi --global ` will save memory value to `$HOME/.odo/odo-config`

similarly:
 -  min-memory
 - max-memory
 -  min-cpu
 -  max-cpu
 - cpu
 -  ignore (for push and watch)
 - **component type (builder image)**
 - component name

if  `odo create`  is run and there is a `.odo/odo-config` in current directory `odo create` should read its content and use values that are there for flags that were not specified, and lastly check the value from `$HOME/.odo/odo-config` based on https://github.com/redhat-developer/odo/blob/master/docs/proposals/odo-config-file.md#-configuration-precedence

_Originally posted by @kadel in https://github.com/redhat-developer/odo/issues/1060

**Comment by kadel** [comment]
lets do builder image first

**Comment by girishramnani** [comment]
@kadel should I consider a file lock for managing the config file? just in case if two people try to update the file at once. But this could give us annoying errors in case where the locks stay held.

**Comment by jorgemoralespou** [comment]
@girishramnani 
> @kadel should I consider a file lock for managing the config file? just in case if two people try to update the file at once. But this could give us annoying errors in case where the locks stay held.
How can 2 people modify a local (to the laptop) file at the same time?

>I also observe that there is already a config file in $HOME/.kube/odo, so should that be removed and then $HOME/.odo/odo-config gets created? I this is the case we have to consider a migration plan as well.
No migration plan required.

**Comment by girishramnani** [comment]
so we can just document if people want to manually rename the config files.

**Comment by jorgemoralespou** [comment]
@girishramnani Not only document the config file name change but also format. I would document users that for upgrade scenarios, one would need to start from scratch. In any case, this is most likely what the workflow users should follow. Remember, currently odo is only for iterative development. Non iterative (inner looped) applications should not be tracked in odo configuration files (even currently).

**Comment by girishramnani** [comment]
No blockers for now, was going through the .kube/odo related code. Will
open a PR tomorrow

**Comment by girishramnani** [comment]
Currently the odo config can be broken into two parts - 
1) OdoSettings
2) ActiveApplications
When we move to the `global` and `local` config files, the `ActiveApplications`  as per my understanding shouldn't be part of the local config as it holds active applications for all components

So essentially both the settings mentioned above will be part of the global config file and only the parameters in the `OdoSettings` will be part of the local config file.

**Comment by kadel** [comment]
What has been skipped in  #1168:
 - Show effective configuration 
> There's no way to see all configuration at once, you need to do either nothing (local) or --global to see the configuration, but you can see both at same time. I think a `--all` would probably make sense, and in this case, you would also need to print out the scope where the config exist.!

- When component is created, save configuration flags to the local file
> * ISSUE: Flags that I provide to `odo create` are not persisted. I guess again, this is not part of this PR.

- When creating component `odo create` and there is a local config file, use values from the file
> * ISSUE: I guess it's not part yet of this PR, but once I have set the componentType locally, I can not just create a component with `odo create`

more in https://github.com/redhat-developer/odo/pull/1168#issuecomment-460339666

**Comment by girishramnani** [comment]
removing from 161 sprint

**Comment by kadel** [comment]
This was replaced by https://github.com/redhat-developer/odo/issues/1294
Does it make sense to close this?

**Comment by girishramnani** [comment]
Yeah, a lot has changed after this issue got created. For clearity lets
close this.

**Comment by girishramnani** [comment]
Closing this
