### ISSUE TITLE
odo watch pushes files to the wrong directory

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#1099]
a good way to reproduce this is with  https://github.com/openshift/nodejs-ex

```
git clone  https://github.com/openshift/nodejs-ex
odo create nodejs mynode
odo push
odo url create
odo watch
```
now  change something in views/index.html

after watch triggers, refresh you won't see your changes in the webpage

The reason is that if you check `/opt/opt-root/src/` you will see that `index.html` is there instead of `/opt/opt-root/src/views`  where it should be. Basically, it ignores where the file is and always puts it into the document root folder.

`odo push` works correctly

**Comment by kadel** [comment]
This might be nodejs specific. I wasn't able to reproduce this with java

**Comment by geoand** [comment]
I just tried it with Java and was not able to reproduce it either

**Comment by kadel** [comment]
Starting to think  that using `io.openshift.s2i.destination` was not a good idea :-( we might go back to pushing files directly to `/opt/app-root/src`

**Comment by geoand** [comment]
We have more e2e tests now, so if we do that we should be able to see if anything breaks. 
Should perhaps add watch e2e tests as well?

**Comment by geoand** [comment]
Maybe this is just a bug in the NodeJS s2i image that we should work around?

**Comment by anmolbabu** [comment]
Yeah I tend to agree with @geoand with may be a bug on nodejs s2i image repo

**Comment by kadel** [comment]
> Given that the current approach(relying on labels) is a perfectly legal approach as per s2i docs

not really, as we are not copying the whole application, but only a single files, that is something that s2i was never designed to do

I supsect that if you try python image, you will see the same problem. 
I also think that we haven't this problem before we started using this label.

Both are just my working theroies that I haven't verifed yet and I'm not sure if I get change to try it today :-(

**Comment by anmolbabu** [comment]
@kadel I'll try it post lunch

**Comment by kadel** [comment]
@anmolbabu  have you been able to determine why this affects python and nodejs but not java based images?

**Comment by kadel** [comment]
@jorgemoralespou @jankleinert @sspeiche  Please be aware of this bug, when you are demoing nodejs apps. `odo push` works but `odo watch` can break the app if you edit file that is subdirectory and not in the root folder of the project :-(

**Comment by kadel** [comment]
@geoand Is it possible that this was introduced with changes in https://github.com/redhat-developer/odo/pull/954 ?

**Comment by geoand** [comment]
It can't exclude the possibility, but that change should only affect cases were a single non-directory file is specified. When the file is a directory, the old behavior should still be present

**Comment by kadel** [comment]
> I can't exclude the possibility, but that change should only affect cases were a single non-directory file is specified. When the file is a directory, the old behavior should still be present

This is actually why I was starting to look at those changes. This is exactly this situation. Only one single file is being transferred  and it hits this part of the code https://github.com/redhat-developer/odo/pull/954/files#diff-6025e9b620e9321c03c11bf29e5c4dbdR2497

I still haven't figure out what is happening there with all the paths, but my current suspission is that the problem is somewhere around there.

**Comment by geoand** [comment]
I see what you mean... 
However it strikes me as odd that this is not problem in Java

**Comment by geoand** [comment]
I will test it again and make sure

**Comment by geoand** [comment]
Actually I may be seeing this as well with Java, I still need to check

**Comment by anmolbabu** [comment]
@amitkrout As discussed on chat feel free to cover even this issue via e2e tests

Pointers: https://github.com/redhat-developer/odo/pull/820 and https://github.com/redhat-developer/odo/pull/975

Possible improvements:
1. Move watch tests to a separate file(with a new ginko target and hence independently testable) with more coverage of more scenarios
2. Trigger file modifications via simple shell commands(for ex: sed) rather than the currently used os#Open#WriteString(as in https://github.com/redhat-developer/odo/blob/master/pkg/testingutil/fileutils.go#L99)
3. Watch currently checks only if watch detected a triggered file change(as in https://github.com/redhat-developer/odo/blob/master/tests/e2e/cmp_test.go#L238)... we should instead check the end-to-end behaviour perhaps via a change in api o/p etc.. ? curl the component url and verify previous and current state of o/p.

Cc: @geoand

**Comment by geoand** [comment]
I agree :100: with @anmolbabu

**Comment by amitkrout** [comment]
@anmolbabu Cool!!! Thanks for the pointers
