### ISSUE TITLE
Add link to command completion index in getting-started.md file

### ISSUE THREAD

**Issue by amitkrout** [redhat-developer/odo#1118]
[kind/Documentation]

## What did you find missing in the documentation?
Like a major feature is is not hyperlinked as other functionality

## What is the relevence of it?
I believe command completion for odo is a great feature and this should be highlighted in getting-started.md file like other major feature. For example

```
Your first application
1. Running OpenShift
2. Create an application
3. Create a component
4. Accessing the component
5. Pushing new changes to the component
6. Adding storage to the component
Command completion
* Command completion

[…]
```
It helps the user to find command completion feature and easily navigate down just by clicking it.

**Comment by amitkrout** [comment]
@cdrage @metacosm Is this make sense ?

**Comment by metacosm** [comment]
Yes, indeed, I missed that. You're welcome to open a PR, @amitkrout.
