### ISSUE TITLE
Integration test coverage for watch on binary component

### ISSUE THREAD

**Issue by amitkrout** [redhat-developer/odo#1121]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
Integration test

## Why is this needed? 
This is a follow up issue of #1117. Adding this test coverage helps to catch the regression for  watch on binary component

**Comment by kadel** [comment]
@amitkrout Can you please estimate size for this task and add size label? You can find more info about labels https://github.com/redhat-developer/odo/wiki/Issue-labeling-system#size

**Comment by anmolbabu** [comment]
@amitkrout Yes considering that the infra(all utility methods required for this along with samples) is in place for it It may be `S` to me bcoz I am used to this e2e framework in odo but it might be `M` until you get used to odo e2e tests. But importantly, please note that this will be blocked by progress on https://github.com/redhat-developer/odo/issues/1117

**Comment by amitkrout** [comment]
> @amitkrout Yes considering that the infra(all utility methods required for this along with samples) is in place for it It may be S to me bcoz I am used to this e2e framework in odo but it might be M until one gets used to odo e2e tests. But importantly, please note that this will be blocked by progress on #1117

Right, Any guesstimated time for fix of #1117 ?

**Comment by anmolbabu** [comment]
@amitkrout I anyway need to be sure #1117 is fixed as part of existing PRs @ https://github.com/redhat-developer/odo-supervisord-image/pull/10 and https://github.com/redhat-developer/odo/pull/1125... bcoz as part of manual testing I see it fixed so if you don't mind I can pick this back up only if you are ok with it

**Comment by anmolbabu** [comment]
PR(https://github.com/redhat-developer/odo/pull/1125) to fix this is merged now so closing this issue
