### ISSUE TITLE
Change deployment strategy to Recreate

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#1141]
[kind/Enhancement]
## Which functionality do you think we should update/improve?
We need to provide a way to configure odo's generated deployments to have a nodeselector (or similar) so that they are always scheduled to the same node, or else, to configure pods with `Recreate` strategy instead of `Rollout` so that they can work in cloud deployments where only block storage is available.

## Why is this needed? 
Any action that requires a redeployment (e.g. link, config,... ) can potentially leave the pod in `Pending` state. 

This can easily be tested in OpenShift online.

**Comment by jorgemoralespou** [comment]
Tested that `Recreate` strategy is easiest to support and works ok.

**Comment by kadel** [comment]
nodeselector is not a good way to approach this. 
If we use nodeselector  to pin pod to a specific node and that node goes down, the pod becomes unschedulable.





> Tested that `Recreate` strategy is easiest to support and works ok.

+1 We should change this

**Comment by jorgemoralespou** [comment]
I agree that `Recreate`is better, but in any case, would be good if configurable (one config is available). For now would just go with Recreate.
