### ISSUE TITLE
Refactor CLI code to follow kubectl/oc practices

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#1142]
Original issue: Refactor CLI code to follow kubectl/oc practices #785 and PR #871  just laid down basic structure and refactored `odo service` command. But the rest of the commands are not following this principes.

Update the following commands to follow the same principles as #871
- [x]  application #1188
- [x] catalog #1189
- [x] component #1190
- [x] project #1191
- [x] storage #1192
- [x] url #1193
- [x] utils #1194
- [x] version #1195
- [x] login #1268 
- [x] logout #1269

**Comment by metacosm** [comment]
When will this be worked on?
