### ISSUE TITLE
No services being listed

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#1156]
Seems really odd.. but I'm unable to get any services, despite the databases being shown in the OpenShift GUI.

```sh
▶ ./odo catalog list services   
 ✗  No deployable services found
```

Using Minishift command:
```sh
    MINISHIFT_ENABLE_EXPERIMENTAL=y minishift start --extra-clusterup-flags "--enable=*,service-catalog,automation-service-broker"

```

Attached is a screenshot of the OpenShift UI.
![screenshot from 2018-12-19 14-03-03](https://user-images.githubusercontent.com/6422176/50242007-1512a800-0397-11e9-9023-e88f9ff818e5.png)

**Comment by geoand** [comment]
@cdrage have you tried using svcat to see what you get?

**Comment by kadel** [comment]
I think that you don't have a service catalog deployed in your cluster. Sometimes it can take time to start.

Even if web console says "Browse Catalog" it doesn't mean that items that you see there are from ServiceCatalog. Catalog in web console also includes regular OpenShift templates.

**Comment by geoand** [comment]
if you do `svcat get brokers` you'll be able to see which brokers are running if any

**Comment by geoand** [comment]
I must have closed this by accident... Sorry about that...

**Comment by cdrage** [comment]
@kadel I left the Minishift running for over 2 hours but it still hadn't provisioned despite passing in the command line parameters. I'll do a simple `minishift delete` and up again and see what happens :+1:

**Comment by jorgemoralespou** [comment]
@cdrage that one is provided by the template-service-broker as it's a template.

**Comment by cdrage** [comment]
@geoand Similar to Andrew's extensive Minishift issues, this was just another one! Closing. Deleting and re-creating minishift deleted the issue I had.

**Comment by geoand** [comment]
Good to know!
