### ISSUE TITLE
misleading  error message if there is no project

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#1160]
[kind/bug]

## What versions of software are you using?
- Operating System:
- Output of `odo version`:

## How did you run odo exactly?

when there is no project
```
odo create redhat-openjdk18-openshift:1.4
```

## Actual behavior
```
unable to get current application
```

## Expected behavior
show a message about no existing project or automatically creating one

**Comment by mohammedzee1000** [comment]
@kadel which would you recommend, asking user to first create project or creating one for them?

I personally would prefer asking them to create project so that we dont have to deal with another name generation

**Comment by jorgemoralespou** [comment]
The project needs to be asked to the user (created or set as active) and not created on his behalf. Many developers will not have project provisioning capabilities on the platform.

**Comment by mohammedzee1000** [comment]
> The project needs to be asked to the user (created or set as active) and not created on his behalf. Many developers will not have project provisioning capabilities on the platform.

Agreed, PR ups that asks user to create or set a project
