### ISSUE TITLE
Multiple users working on the same Odo project

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#1185]
I see certain scenarios in the future causing an issue with multiple-users working on the same Odo project.

1. When you use context-switching (future feature), wouldn't each local directory be different for each user? For example, I would change to /home/foobar/nodejs, but another user would use /home/myuser/nodejs, if, for example, the second user tried to use the project, Odo will try to search for the "/home/foobar/nodejs" directory.

2. Should we provide documentation that --local and binary is recommended for development, git  for production / working with multiple users?

**Comment by kadel** [comment]
related to https://github.com/redhat-developer/odo/issues/600

**Comment by jorgemoralespou** [comment]
I don't think doing "inner loop" with multiple users makes sense, but definitely having 2 users trying to push to the same pod could happen if the second imports the component created by the first, else, he would not even see it.

Adding some mechanism to prevent multiple users to push to the same component could make sense, but definitely this would make more sense as documentation/best practices.

**Comment by amitkrout** [comment]
For me it's hard time to understand properly the concept of ```inner loop``` and ```outer loop```. Would you please refer some doc that describes the concept in details.

**Comment by jorgemoralespou** [comment]
@amitkrout in short:

- __inner loop__: When you're developing the app and before the code is ready for "productization", which typically means, before you push it to git. The tasks that you typically do are: code, build, deploy, test, code changes, build, push, code, build, push, test,.... Also you would do debug and possibly unit tests.
- __outer loop__: When the code is in Git, and everything that happens to make it available to the user, which means CI (tag, build from tag, unit test, functional tests, promotion between environments, integration tests,....)

As you can see, in the outer loop, typically the developer is less involved.

There should be plenty of documentation in the internet, but basically this is the difference you need to understand.

**Comment by amitkrout** [comment]
Thanks, make sense to me

**Comment by kadel** [comment]
@cdrage Is it ok, if we close this isssue?

**Comment by cdrage** [comment]
Yeah, let's close this, this has been addressed.

So in short:

**inner-loop:** single-user / testing deployment

**outer-loop:** when the code is in Git / multiple people can push to it.
