### ISSUE TITLE
Refactor storage command to follow complete-validate-run pattern

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#1192]
more info in #1142

**Comment by mik-dass** [comment]
@kadel Can we close this?

**Comment by kadel** [comment]
> @kadel Can we close this?

Don't see any references to PR. :-(
Has this been merged?

**Comment by mik-dass** [comment]
> Don't see any references to PR. :-(

#1245

**Comment by metacosm** [comment]
Closed via #1245.
