### ISSUE TITLE
odo update does not update a component's configuration

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#1198]
Currently `odo update` can only change the mode strategy (binary/local/git). Update command should be able to update a component's configuration, moreover when config file #1092 is there.

I should be able to do:

```
odo update --mem 2GB
odo update --env XYZ=ABC
```

This should only be able to change component configuration, but not component type.

**Comment by girishramnani** [comment]
@cdrage @tkral can we add this to sprint 161

**Comment by kadel** [comment]
@girishramnani  @anmolbabu 
can you please define how new update command will look like before you jump into implementation?

**Comment by sspeiche** [comment]
@kadel we discussed at f2f that this was post-1.0, should the work stall on this and milestone assigned to backlog? If this has progressed enough. it would be fine to pull it in.

**Comment by anmolbabu** [comment]
@jorgemoralespou 
I have the following questions based on the issue description:

1. Wouldn't updating the config + component deployment with `odo update` vs updating only config file via `odo utils config set` potentially confuse the user?
2. Wouldn't this be a lot of flags each to create and/or update making the usability of the command difficult?
3. Would the below instead be ok:
    a. Update/Create config using any of the config update/create methods. ex: `odo utils config set` or config created due to `odo create`
    b. Use odo update to reflect the state in config file onto the component container or to change the source of the container(as it is used for currently)

It is just my opinion/idea please feel free to provide any suggestions/corrections or even reject the above if it doesn't make any sense

**Comment by jorgemoralespou** [comment]
@anmolbabu good points, and we need to think this though.

IMHO I would rather update a component better than have to use `odo utils config set` on a regular basis, but there might be times where I just want to deal to persisting configuration into that files while still not messing with a component I have deployed. On the one hand, if you run update, the change will happen immediately, this can be what you want or not what you want, hence I think having both options could still make sense.

In odo update you can provide many flags, yes, but you would only provide those that would need to change something in the component. Still, not sure how one would be able to unset a value, and that can be a thing.

What you describe as "would it work in question 3". I want you to experience it for some time, and let me know if that would be an acceptable optimal workflow that you would like. The goal for the tool is to simplify the users workflow and make many things still possible. Sometimes, that would mean that one thing can be done in two ways, and depending on how you're doing things you'll opt for one or the other way.

Hope this helps view my opinion.

But in any case, you've raised a good concern, and glad to see where challenging decisions, as from discussions comes a better solution :-D

**Comment by anmolbabu** [comment]
@jorgemoralespou 

The above makes sense to me if: 

Update does not update the config files but only enforces a requested state on the cluster

But I have 1 more question(which was probably the one that led me to the proposal I made in my previous question):

How would a user enforce all the config (updated) in the config files on to the cluster?

I would probably not prefer passing all the config I want via many different flags which makes my command so much complex to use and necessitates the presence of a way to have all my config in a file and enforce the state in config file onto the cluster or in essence a simple way other than having to write every config as a flag to the update command. do we plan on some sort of precedence mechanism which says take the config passed as arguments to update command(on precendence over the the same config in the config file) along with the other configs in accordance with precedence rules from config files at the time of update? @jorgemoralespou

**Comment by jorgemoralespou** [comment]
@anmolbabu 
Options can be provided in different ways (and thanks for the discussion as it's the only way to see if the proposed workflow works or not, keep thinking :-D )
- You check out source code with an .odo/odo-config file, and the options in that file will be applied when you do `odo create`
- You check out source code with an .odo/odo-config file, and the options in that file will be applied when you do `odo create` except for those you overwrite via flags, that the flags will be applied.
- You check out source code without any .odo config. The flags you provide via flags will be applied and persisted in `.odo/odo-config.local`
- You update a component, and options that you provide via flags will overwrite those in the component and `.odo/odo-config.local`

And as I wrote this, I see the flaw you're describing. I would need to write down all the use cases, to see how they work, as now I'm not sure they work (e.g. removing a config that was set via flag so it's no longer applied)

**Comment by anmolbabu** [comment]
> @anmolbabu
> Options can be provided in different ways (and thanks for the discussion as it's the only way to see if the proposed workflow works or not, keep thinking :-D )
> 
> * You check out source code with an .odo/odo-config file, and the options in that file will be applied when you do `odo create`
> * You check out source code with an .odo/odo-config file, and the options in that file will be applied when you do `odo create` except for those you overwrite via flags, that the flags will be applied.
> * You check out source code without any .odo config. The flags you provide via flags will be applied and persisted in `.odo/odo-config.local`

Yes but while passing the flags to the update command, if I forget some/any of them, then what does it take for me to apply it again? re-run update with all of those flags(ex: min-memory, max-memory, min-cpu, max-cpu and anything else that we add and that user wants to change) + the missed out ones? what if I again miss one/some of it when I run update the 2nd time?

> * You update a component, and options that you provide via flags will overwrite those in the component and `.odo/odo-config.local`
> 
> And as I wrote this, I see the flaw you're describing. I would need to write down all the use cases, to see how they work, as now I'm not sure they work (e.g. removing a config that was set via flag so it's no longer applied)

**Comment by anmolbabu** [comment]
Based on my conversation with @kadel following would be the way to go:

1. Cmd A would be used to update the configurations
2. Cmd B would be used to push/apply the configurations(in accordance with precedence of various config files) onto the component

Now, at the moment it seems like
cmdA = `odo update` with various flags
cmdB = `odo push` with flags like `--only-source`(to indicate push of only source) --only-config(to indicate push of only configs onto the remote component) and by default push both source and configs but eventually odo can be thought to learn intelligently if there's any source change or config change and push only that which changed

But what cmdA and cmdB correspond to is still being brainstormed

**Comment by anmolbabu** [comment]
@jorgemoralespou @kadel Did we arrive at a final decision on what cmdA and cmdB would be?

**Comment by jorgemoralespou** [comment]
I think cmdA should be a set of commands:
odo create
odo config set/unset
odo storage...

cmdB should be only:
odo push

**Comment by girishramnani** [comment]
Outcome of one of the discussions -
- `odo utils config --global` becomes `odo preference`
- `odo utils config` becomes `odo config`
This means that the global `preference` will not have anything common with local config. They can have a relationship like a `ComponentType` in local can be related to `DefaultComponentType` in global `preference`

**Comment by girishramnani** [comment]
so once I have local place holder for memory and other params in place, @anmolbabu can use them and set them as per mentioned in this issue

**Comment by kadel** [comment]
replaced by https://github.com/redhat-developer/odo/issues/1365 and https://github.com/redhat-developer/odo/issues/1366
