### ISSUE TITLE
odo link wrong output

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#1200]
[kind/bug]
When there are several ports to link to, `odo link` shows a message that says `Multiple secrets exist for component`

```
$ odo link backend --component frontend
Multiple secrets exist for component backend.
Please select one of the following ports: '8080,8443,8778'
```

It should say something like: 
```
$ odo link backend --component frontend
Backend component exposes multiple ports: 8080,8443,8778 
To specify a port for the target component run: 'odo link backend --port 8080' (use the appropriate port)
```

**Comment by mohammedzee1000** [comment]
Taking this up

**Comment by mohammedzee1000** [comment]
@kadel if you could add this to current sprint?

**Comment by geoand** [comment]
@mohammedzee1000 added :P

**Comment by mohammedzee1000** [comment]
@jorgemoralespou I can't find the source of this message in the code. Could you link the example you tried so i reproduce and debug further?

**Comment by geoand** [comment]
Actually i think this is dup of ##1174

**Comment by mohammedzee1000** [comment]
Looks to me like it as well.

**Comment by mohammedzee1000** [comment]
Closing as duplicate
