### ISSUE TITLE
Update test suite function runCmd to handle stderr

### ISSUE THREAD

**Issue by amitkrout** [redhat-developer/odo#1205]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
```func runCmd()``` in test suite

## Why is this needed? 
Right now in test suite function ```runCmd``` doesn't handle/capture the reported error.

**Comment by kadel** [comment]
@amitkrout Can you please estimate size for this task and add size label? You can find more info about labels https://github.com/redhat-developer/odo/wiki/Issue-labeling-system#size

**Comment by amitkrout** [comment]
> You can find more info about labels https://github.com/redhat-developer/odo/wiki/Issue-labeling-system#size

@kadel Thanks for the link. I suppose to set the size when the issue was first created but certainly could not do it because i was not so confident on size labels ;)

**Comment by metacosm** [comment]
Hmm, I just looked at this issue right now and I'm not sure that the resulting code would be an improvement: looking at the tests, having `runFailCmd` made it explicit that the command is expected to fail with a specified error code (granted, we only ever return `1` as error code right now as I recall but that might change). It's my fault for looking at this so late in the process but could you explain why this new way of doing things is better?

**Comment by amitkrout** [comment]
> Hmm, I just looked at this issue right now and I'm not sure that the resulting code would be an improvement: looking at the tests, having `runFailCmd` made it explicit that the command is expected to fail with a specified error code (granted, we only ever return `1` as error code right now as I recall but that might change). It's my fault for looking at this so late in the process but could you explain why this new way of doing things is better?

@metacosm No issue, thanks for the feedback. As of now in case of command failure (ExitCode 1) the output was reported in stdout rather in stderr which is technically wrong. For example 

```
$ ./odo login -u developer -p developer
 ✗  dial tcp 192.168.64.2:8443: i/o timeout - verify you have provided the correct host and port and that the server is currently running.

//looks good
$ echo $?
1

//Wrong
$ ./odo login -u developer -p developer 2>test
 ✗  dial tcp 192.168.64.2:8443: i/o timeout - verify you have provided the correct host and port and that the server is currently running.
```

This fix will enforce of fixing issue like reported in [1]. Moreover the fix is inclined towards how the [error](https://github.com/redhat-developer/odo/pull/1307/files#diff-833606e3adfff6920346104aa5beb0fe) is handled in case of failure, the ```runCmd``` is modified as per the fix.

[1] https://github.com/redhat-developer/vscode-openshift-tools/issues/501

**Comment by metacosm** [comment]
> This fix will enforce of fixing issue like reported in [1]. Moreover the fix is inclined towards how the [error](https://github.com/redhat-developer/odo/pull/1307/files#diff-833606e3adfff6920346104aa5beb0fe) is handled in case of failure, the `runCmd` is modified as per the fix.

Sorry but I still don't get it: I fail to see how `runCmd` that now handles both `out` and `err` more or less the same way helps us enforce anything. If anything, it seems to me it's even harder now to figure out which commands need to be modified because they all use `runCmd` and the result of that call will be pretty much what's expected whether that happens on `out` or `err` without a way for the caller to know.

**Comment by amitkrout** [comment]
> Sorry but I still don't get it: I fail to see how `runCmd` that now handles both `out` and `err` more or less the same way helps us enforce anything.

@metacosm I would suggest please have look to the pr #1307. Probably it could answer your concern

> If anything, it seems to me it's even harder now to figure out which commands need to be modified because they all use `runCmd` and the result of that call will be pretty much what's expected whether that happens on `out` or `err` without a way for the caller to know.

Right, I think for better understanding and readability purpose we can add function like 
```
func runCmdShouldPass(cmd string) string {
	cmdStdout := runCmd(cmd)
	return cmdStdout
}

func runCmdShouldFail(cmd string) string {
	cmdStderr := runCmd(cmd)
	return cmdStderr
}   
```

**Comment by metacosm** [comment]
@amitkrout I've looked at the PR and that's why I'm asking here because the PR doesn't seem to help enforcing things. Can you explain concretely how the PR helps enforcing that `odo login` properly sends the error to `err` or identify other cases where that would be the case?

**Comment by amitkrout** [comment]
Hang on
Let me modify the pr

**Comment by amitkrout** [comment]
@metacosm I think the pr now somehow resolves your concern. Please have a look.
