### ISSUE TITLE
service create completion shouldn't offer service class again if it has already been completed

### ISSUE THREAD

**Issue by metacosm** [redhat-developer/odo#1212]
[kind/bug]

## What versions of software are you using?
- Operating System: `Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64`
- Output of `odo version`: 
```
odo v0.0.17 (28fea2b3)

Server: https://195.201.87.126:8443
OpenShift: v3.11.0+06cfa24-67
Kubernetes: v1.11.0+d4cacc0
```

## How did you run odo exactly?
`odo service create mysql-ephemeral <tab>`

## Actual behavior
`odo` offers the list of available service classes

## Expected behavior
`odo` should either not offer anything, show possible flags or possible service instance names but not show the service classes again.

## Any logs, error output, etc?
No.

**Comment by jorgemoralespou** [comment]
@metacosm Is `mysql-ephemeral` taken as service class or taken as the name for the service you want to create?

I think that having arguments that are not flags might confuse us in the future, so probably we need to convert all these methods:

from:
```
odo service create <service_type> --plan <plan_name> [service_name] [flags]
```

to:
```
odo service create <service_type> [--plan <plan_name>] [--name <service_name>] [flags]
```

And have just one single positional argument which will prevent this confusion.

@kadel your thoughts?
