### ISSUE TITLE
odo catalog list component shows hidden builders

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#1220]
[kind/bug]
## What versions of software are you using?
- Output of `odo version`: odo v0.0.17 (78a050bc)

## How did you run odo exactly?

```
odo catalog list components
```
## Actual behavior
Show all imagestreams that have a builder tags.

## Expected behavior
Show only builder images that don't have the `hidden tag`

**Comment by geoand** [comment]
Is this a duplicate of #1180 ?

@girishramnani If you aren't working on it, I can certainly pick it up

**Comment by jorgemoralespou** [comment]
@geoand In fact. I thought that was only about services. Since it also covers components, I'll close this one.
