### ISSUE TITLE
`component.SetCurrent(name string)` should error out if setting to component that doesn't exist

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#127]
`component.SetCurrent(name string)` should error out if setting to component that doesn't exis

Currently, it is not erroring out because `component.List()` is not yet implemented (#53).
When we add it, it should be used in `component.SetCurrent(name string)` to verify that component that is requested to be set as current actually exists.

**Comment by ashetty1** [comment]
The issue below because of this, I assume.

```
# ocdev component delete nodejs
buildconfig "nodejs" deleted
imagestream "nodejs" deleted
deploymentconfig "nodejs" deleted
pod "nodejs-1-24d6r" deleted
service "nodejs" deleted

# ocdev component get
The current component is: nodejs

```

**Comment by kadel** [comment]
@ashetty1 not really,
what you are describing is a different issue (#50), that should be fixed once https://github.com/redhat-developer/ocdev/pull/126 is merged

**Comment by kadel** [comment]
`component.List` was implemented, so we can proceed with this

**Comment by cdrage** [comment]
I've assigned this to myself and started the work here: https://github.com/cdrage/ocdev/tree/check-setcurrent-exists I'll push a PR ASAP.

**Comment by containscafeine** [comment]
Hey @cdrage, I think this should be a pretty similar approach as in #384

**Comment by cdrage** [comment]
Closed via: https://github.com/redhat-developer/odo/pull/388/files
