### ISSUE TITLE
Create interactive mode for odo create

### ISSUE THREAD

**Issue by geoand** [redhat-developer/odo#1272]
[kind/Enhancement]

## Which functionality do you think we should update/improve?

`odo create` is very commonly used and could benefit from an interactive mode.

## Why is this needed? 

A general consensus (see #1242) is that component create should be the command to have an interactive mode

**Comment by geoand** [comment]
@jorgemoralespou @kadel @metacosm I started looking into this and I immediately have a question:

Basically should the interactive mode try to get all the necessary info? For example, setting the cpu and memory resources can be tedious and I am guessing that in most cases isn't needed...
So how should we handle this? Should we only ask the user for the necessary info? Should flags also be allowed?

**Comment by jorgemoralespou** [comment]
@geoand When you look into the service creation, you see there are some "required" arguments and some "optional" arguments.
For this interactive mode, I would treat as required:
- componentType
- componentName
- Type (binary/local/git) and the argument to this selection.

Then everything else as optional. Probably displaying the list of optional parameters, and allowing the users to type and filter or navigate through the list.

Does it make sense?

**Comment by geoand** [comment]
> @geoand When you look into the service creation, you see there are some "required" arguments and some "optional" arguments.
> For this interactive mode, I would treat as required:
> 
> * componentType
> * componentName
> * Type (binary/local/git) and the argument to this selection.
> 
> Then everything else as optional. Probably displaying the list of optional parameters, and allowing the users to type and filter or navigate through the list.
> 
> Does it make sense?

It does yes. I'll hopefully start an implementation tomorrow and see what it looks like. I might have the resource limits as a whole option where the user can just skip the whole thing.
