### ISSUE TITLE
login e2e tests are incorrect / dangerous

### ISSUE THREAD

**Issue by metacosm** [redhat-developer/odo#1278]
login e2e tests currently attempt to delete all projects. This might not work and is quite dangerous if the tests are run by an unsuspecting user on a cluster with elevated rights. Moreover, it might be difficult to ensure that the state is appropriate (i.e. no projects) when the tests are launched so end to end testing of the different login scenarios might be difficult/impossible.

**Comment by amitkrout** [comment]
@mohammedzee1000 Please look to this issue with priority

**Comment by mohammedzee1000** [comment]
I am already working on alterering it in fix PR,  will push it out
