### ISSUE TITLE
managing the active component & application in the local odo config

### ISSUE THREAD

**Issue by girishramnani** [redhat-developer/odo#1294]
Currently we have a list of `activeComponents` present globally in `$HOME/.odo/odo-config.yaml`, soon we will have support for local odo config which means that the local odo config can track the active `Component` and `Application` in the file replacing the need of a global list of directories -> active components.

In this issue, we need to set all the active component and application in all possible cases:
- `odo create`
- `odo application set`
- `odo push`

we will not be using the active component and application from the local odo config just set them. they will come from the global odo config ( which will change in a subsequent PRs and not a part of this issue)
Sub tasks of this issue are -

- [x] Create `min-memory`,`max-memory`, `min-cpu`, `max-cpu`, `cpu`, `ignore ( for push and watch)`,`component name` in local odo config

**Comment by kadel** [comment]
First step should be modifing `odo create`. 
This command should create local config and save all flags (--env, --mem, --cpu, --application, component type (builder image), --port .... ) that has been used to create the component  into local config  

Second step, modify all commands `odo push`, `log`, `storage`, `url` to read active component from the file.

If storage, or url is added to the component, it should be persistent in the local config but we will add that later, lets first make sure that we are using local config everywhere.

**Comment by girishramnani** [comment]
Outcome of one of the discussions -
- `odo utils config --global` becomes `odo preference`
- `odo utils config` becomes `odo config`
This means that the global `preference` will not have anything common with local config. They can have a relationship like a `ComponentType` in local can be related to `DefaultComponentType` in global `preference`

**Comment by kadel** [comment]
> Outcome of one of the discussions -
> 
> * `odo utils config --global` becomes `odo preference`
> * `odo utils config` becomes `odo config`
>   This means that the global `preference` will not have anything common with local config. They can have a relationship like a `ComponentType` in local can be related to `DefaultComponentType` in global `preference`

@girishramnani  any progress on this

**Comment by kadel** [comment]
replaced by https://github.com/redhat-developer/odo/issues/1365 and https://github.com/redhat-developer/odo/issues/1366
