### ISSUE TITLE
Consuming the active component and application when performing operations

### ISSUE THREAD

**Issue by girishramnani** [redhat-developer/odo#1296]
Follow up to - https://github.com/redhat-developer/odo/issues/1294
Once the `Active Component` and `Active Project` are set in the local odo config, it has to be used in all the commands e.g.
- `odo create`
- `odo url`
- `odo link`
- `odo unlink` and more

Also cleanup the global `activeComponents` from `$HOME/.odo/odo-config.yaml` as part of this issue

**Comment by kadel** [comment]
replaced by #1365 and #1366
