### ISSUE TITLE
odo list -o json does not output json

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/odo#1326]
[kind/bug]

## What versions of software are you using?
- Operating System: Win10 Pro
- Output of `odo version`:

```
odo v0.0.19 (61f278a1)             
                                   
Server: https://172.17.247.235:8443
OpenShift: v3.9.31                 
Kubernetes: v1.9.1+a0ce1bc657      
```

## How did you run odo exactly?
`odo list -o json`

## Actual behavior

```
$ odo list -o json
 ✗  There are no components deployed.
```

## Expected behavior
```
odo list -o json
some JSON output
```

**Comment by amitkrout** [comment]
cc_ @surajnarwade

**Comment by surajnarwade** [comment]
@jeffmaury , Thanks for reporting , @amitkrout , I'll look into it

**Comment by kadel** [comment]
If there are no components `odo list -o json` should return an empty list.

```json
{
  "kind": "List",
  "apiVersion": "odo.openshift.io/v1alpha1",
  "metadata": {},
  "items": []
}
```
