### ISSUE TITLE
odo app list list -o json does not output json

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/odo#1327]
[kind/bug]

## What versions of software are you using?
- Operating System: Win10 Pro
- Output of `odo version`:

```
Server: https://172.17.247.235:8443
OpenShift: v3.9.31
Kubernetes: v1.9.1+a0ce1bc657
```

## How did you run odo exactly?
`odo app list -o json`

## Actual behavior

```
$ odo app list -o json
There are no applications deployed in the project 'myproject'.
```

## Expected behavior

```
$ odo app list -o json
Some JSON output
```

**Comment by amitkrout** [comment]
@surajnarwade Would you please address this

**Comment by surajnarwade** [comment]
@amitkrout sure

**Comment by kadel** [comment]
If there are no applications `odo app list -o json` should return an empty list.

```json
{
  "kind": "List",
  "apiVersion": "odo.openshift.io/v1alpha1",
  "metadata": {},
  "items": []
}
```
