### ISSUE TITLE
odo app create fails after odo project create

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/odo#1329]
[kind/bug]

I discovered this when writing integration tests for the IntelliJ OpenShift Connector (which is odo based) and one of my test is first creating a project then creating an application in that project

## What versions of software are you using?
- Operating System: Win10 Pro
- Output of `odo version`:

```
odo v0.0.19 (61f278a1)             
                                   
Server: https://172.17.247.235:8443
OpenShift: v3.9.31                 
Kubernetes: v1.9.1+a0ce1bc657
```      

## How did you run odo exactly?
`odo project create jeff1 && odo app create --project jeff1 app1`

## Actual behavior

```
 ✓  New project created and now using project : jeff1
 ✗   jeff1 project does not exist
```

## Expected behavior

```
 ✓  New project created and now using project : jeff1
 Creating application: app1 in project: jeff1
Switched to application: app1 in project: jeff1
```

**Comment by amitkrout** [comment]
I am able to reproduce this, However it works if you do small pause of 1sec between the commands. 

```
$ odo project create amit8 && sleep 1 && odo app create --project amit8 app8
 ✓  New project created and now using project : amit8
 Creating application: app8 in project: amit8
Switched to application: app8 in project: amit8
```

@jeffmaury Was it working in previous releases ?

**Comment by jeffmaury** [comment]
Same with 0.0.18 but works with 0.0.17

**Comment by kadel** [comment]
Verified. This worked in 0.0.17 we need to look at what happened there.

**Comment by metacosm** [comment]
Unable to reproduce here… (slow network, probably making things work).

**Comment by metacosm** [comment]
> Verified. This worked in 0.0.17 we need to look at what happened there.
> 
> I've quickly looked at the code, at it looks like nothing has changed there. We might need to add some checks to make sure that `odo project create` exits only after the project has been created.

The consistent way would be to use a `--wait` flag for `project create`…

**Comment by metacosm** [comment]
@jeffmaury Take a look at #1367 and let us know how it goes, please.
