### ISSUE TITLE
odo project list does not return just created project

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/odo#1340]
[kind/bug]

## What versions of software are you using?
- Operating System: Win10 Pro
- Output of `odo version`:

```
odo v0.0.19 (61f278a1)             
                                   
Server: https://172.17.247.235:8443
OpenShift: v3.9.31                 
Kubernetes: v1.9.1+a0ce1bc657
```

## How did you run odo exactly?
`odo project create test1 && odo project list`

## Actual behavior

```
 ✓  New project created and now using project : test1
ACTIVE     NAME
           myproject
```

## Expected behavior

```
 ✓  New project created and now using project : test1
ACTIVE     NAME
           myproject
           test1
```

## Any logs, error output, etc?
Reproduced with 0.0.18, not with 0.0.17

**Comment by surajnarwade** [comment]
works for me though

```
 $ odo version
odo v0.0.19 (HEAD)

Server: https://192.168.42.67:8443
Kubernetes: v1.11.0+d4cacc0
```

```
$ odo project create test1
 ✓  New project created and now using project : test1
```

```
$ odo project list
ACTIVE     NAME
           myproject
*          test1
```


I think `odo project create test1` takes some seconds to settle but you were running `odo project create test1 && odo project list` where `odo project list` don't give time to `odo project create` to settle.

**Comment by surajnarwade** [comment]
this seems to be worked also:

```
odo project create test1 && sleep 1 && odo project list
```

**Comment by kadel** [comment]
I was able to reproduce this.

This will have the same root cause as https://github.com/redhat-developer/odo/issues/1329.
