### ISSUE TITLE
Unable to login to OpenShift 4.0

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#1355]
[kind/bug]

## What versions of software are you using?
- Operating System:
- Output of `odo version`: odo v0.0.19 (e66549fb)

## How did you run odo exactly?
```
▶ odo login (url)
yes
 ✗  invalid character '<' looking for beginning of value

```

## Actual behavior

```
▶ odo login (url)
yes
 ✗  invalid character '<' looking for beginning of value
```

## Expected behavior
ask to accept the insecure connection (message is hidden, but I can still answer "yes")
and then ask for the username and password

**Comment by amitkrout** [comment]
@kadel Congrats, you found the first bug on OpenShift 4.0 ;)

I guess in the next week i will get the access to the cluster then only i can run some more odo test. Till then if possible you can spend some of your available capacity for odo testing on 4.0  :)

**Comment by jorgemoralespou** [comment]
@kadel Openshift 4 don't have yet authentication enabled (I mean some of the endpoint in the API, AFAIK).
You need to use the unique user `kubeadmin` provided and use the `token` provided.

I don't think this error is valid, as of now.

**Comment by kadel** [comment]
It was just a quick test. I was looking for the token in webconsole (in the same place as it was before) and didn't find it :-(
I didn't put that much effort into it to be honest :-)

**Comment by kadel** [comment]
It was something on the OpenShift side.
With the latest OpenShift 4.0 everything works OK
