### ISSUE TITLE
odo service create with invalid plan does not fail

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/odo#1359]
[kind/bug]

## What versions of software are you using?
- Operating System: Win10Pro
- Output of `odo version`:

```
$ odo version
odo v0.0.19 (61f278a1)

Server: https://172.18.11.130:8443
OpenShift: v3.10.45
Kubernetes: v1.10.0+b81c8f8
```

## How did you run odo exactly?

`odo service create postgresql-persistent --plan s1`

## Actual behavior

```
$ odo service create postgresql-persistent --plan s1
 ✓  Service 'postgresql-persistent' was created
Progress of the provisioning will not be reported and might take a long time.
You can see the current status by executing 'odo service list'
```

## Expected behavior
Invalid plan should be reported

**Comment by metacosm** [comment]
@jeffmaury try the binary from #1364 and let us know if it fixes the issue.
