### ISSUE TITLE
machine readable output: odo app create

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#1380]
`odo app create -o json` should return JSON formatted output describing the newly created app.

**Comment by mik-dass** [comment]
@kadel What kind of output are we looking for in case of create commands?

**Comment by kadel** [comment]
the same as you would run `odo describe -o json` against the newly created app.

**Comment by mik-dass** [comment]
>  the same as you would run `odo describe -o json` against the newly created app.

What if a error occurs?

**Comment by kadel** [comment]
@surajnarwade said that he will look how other tools (kubectl, ...) are handling errors in this case and we will do the same.
For now, until we figure this out, I would just do what we are doing in case of regular "human" output, no need to block on this.

**Comment by mik-dass** [comment]
> I would just do what we are doing in case of regular "human" output, no need to block on this

I will move forward with the implementation

**Comment by mik-dass** [comment]
Closing because the new odo workflow deprecates the `app create` command
