### ISSUE TITLE
add better help messages for flags and commands

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#139]
We have been neglecting help messages and examples in for command line flags and arguments.

for example `ocdev component  create -h` doesn't show that there are some positional arguemnts
```
▶ ./ocdev component  create -h
create new component

Usage:
  ocdev component create [flags]

Flags:
      --binary string   binary artifact
      --dir string      local directory as source
      --git string      git source
  -h, --help            help for create

Global Flags:
  -v, --verbose   verbose output
```

It would be great if we could follow http://docopt.org/ convention for describing optional and required arguments

**Comment by kadel** [comment]
component messages improved in https://github.com/redhat-developer/ocdev/pull/247

**Comment by kadel** [comment]
related to https://github.com/redhat-developer/odo/issues/516

**Comment by kadel** [comment]
Short and Long descriptions are kind of OK right now. 
But flags description  still needs to be improved
```
odo create -h
.....
.....
Flags:
      --binary string   Binary artifact
      --git string      Git source
  -h, --help            help for create
      --local string    Use local directory as a source for component
```

`--local` is ok, but  messages for `--binary` and `--git` doesn't help at all.

**Comment by cdrage** [comment]
#695 Will close this issue!
