### ISSUE TITLE
Add prow style OWNERS to odo repository

### ISSUE THREAD

**Issue by mohammedzee1000** [redhat-developer/odo#1400]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
Add appropriate OWNERS files to odo repository (ref : OWNERS docs: https://git.k8s.io/community/contributors/guide/owners.md).

Files can be declared at any level. Eg, we can have global owners file that will apply to entire repo, and child owners which will apply to particular directory

## Why is this needed? 
Prow has plugins which mostly used this to decide who needs to be pinged (blunderbuss plugin) and whose approvals count as approvals for automatic merge (tide) .

This will make it easier to integrate with OpenShift prow automated workflow.

Ref : https://github.com/redhat-developer/odo/issues/1167

**Comment by amitkrout** [comment]
Cool!!!

If you think you are overloaded with such CI related task feel free to assign some of them to my name aswell
