### ISSUE TITLE
Route URL autogenerated when using "odo url create" can be too long when component name close to 63 characters

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/odo#1442]
[kind/bug]

## What versions of software are you using?
- Operating System: Windows
- Output of `odo version`: 0.0.20

## How did you run odo exactly?

* create component with name close to 63 characters 
* create url for component ^

## Actual behavior

After opening openshift console there are errors in networking section ({see 686](https://github.com/redhat-developer/vscode-openshift-tools/issues/686) for details

## Expected behavior

Should create correct URL

**Comment by kadel** [comment]
Thank you @dgolovin for reporting, but this is duplicate of https://github.com/redhat-developer/odo/issues/1213

Feel free to re-open if not.
