### ISSUE TITLE
Implement import and annotate calls

### ISSUE THREAD

**Issue by lordofthejars** [redhat-developer/odo#1445]
[kind/Enhancement]

## Which functionality do you think we should update/improve?

Currently, you don't need to install `oc` to do a login, but you need to install it for a typical operation like importing or annotating images to build the project.

`oc import-image openjdk18 --from=registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift --confirm`

`oc annotate istag/openjdk18:latest tags=builder --overwrite`

## Why is this needed? 

Well this will help in the integration between `odo` and `odo-java` to automate the registration of java image.

**Comment by jorgemoralespou** [comment]
@lordofthejars I don't think this should be done by odo. Whether the images are or not are available is out of the scope what a developer workflow is/should be. It's responsibility of the platform administrator.

I think though, that we could support using an image for which an imagestream is not created, just like `oc new-app` does:

e.g. 
`odo create registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift frontend --local .`

**Comment by kadel** [comment]
closing as duplicate for https://github.com/redhat-developer/odo/issues/882
