### ISSUE TITLE
UC 1: As a developer, I want to create applications using a command line tool

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#146]
As a developer, I want to be able to use a command line tool for my operating system of choice to build/deploy my application (or source code) on OpenShift. 
This CLI will understand the concept of an “application”.

__*NOTE:*__ Technical requirement

**Comment by slemeur** [comment]
Use case that is defining the whole goal of the tool.

**Comment by cdrage** [comment]
@slemeur Yup. Closing this for now as we've created a CLI tool to interact with OpenShift (via the API as well without the binary).
