### ISSUE TITLE
UC 2: As a developer, I want to have a command line tool that is easy and intuitive

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#147]
As a developer, I want a CLI that is intuitive and easy to understand.

__*NOTE:*__ Technical requirement

**Comment by cdrage** [comment]
This is our main goal, and that is to create an easy tool for developers to on-board to OpenShift. I believe that this issue is too encompassing and we have plenty of other issues that talk about making certain commands easier.
