### ISSUE TITLE
UC 3: As a developer, I want to not be forced to learn OpenShift / Kubernetes language (resources) and commands

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#148]
As a developer, I want to be able to use non openshift/kubernetes specific language(resources)/commands.

- A user should not need to know what is a pod, a Deployment, DeploymentConfig, Service, PersistenVolumeClaim, … to use this tool.
- A user should not need to know how “oc” or “kubectl” works. As a user of this CLI, I’d be working on an “existing OpenShift project” and only care about what I can do within this project with the commands provided by this tool.

This tool will interface with an existing OpenShift cluster. The user will be logged into a project.

__*NOTE:*__ Technical requirement

**Comment by cdrage** [comment]
I'll keep this open for now, but as of right now, all of our commands don't involve terminology such as PVC, DeploymentConfig, etc. 

We have:

```sh
Component Commands:
  component   Components of application.
  create      Create a new component
  delete      Delete an existing component
  describe    Describe the given component
  link        Link target component to source component
  list        List all components in the current application
  log         Retrieve the log for the given component.
  push        Push source code to a component
  update      Update the source code path of a component
  watch       Watch for changes, update component on change
```

**Comment by jorgemoralespou** [comment]
Agree. @kadel we can close this issue
