### ISSUE TITLE
404 on https://openshiftdo.org/getting-started/

### ISSUE THREAD

**Issue by MikGue** [redhat-developer/odo#1496]
[kind/Documentation]

A link from here: https://openshiftdo.org/getting-started/

A few requirements before we proceed!
     A running OpenShift cluster (we recommend using minishift)
     odo binary (**installation guide here**)

goes to here which returns a 404: https://openshiftdo.org/README.md#installation

**Comment by cdrage** [comment]
Woops. 

Updated here: https://github.com/redhat-developer/odo/pull/1498
