### ISSUE TITLE
UC 13: As a developer, I want to easily export/import my application with a single command

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#158]
As a developer (A) , I want to be able to easily export and import my application with one command so that I can share the configuration with other people.  
- As a developer (B), I want to be able to take the export given to me by developer (A) and run a single command to have a environment that matches what developer (A) built. I should be able to define custom name for the application that I am importing.

__*NOTE:*__ This is a stretch goal - initial work may need more refinement

__*NOTE:*__ Bound to the openshift capabilities, hence not a complete use case for this tool, but rather a way to integrate into whatever capabilities are provided by the platform around import/export.

**Comment by kadel** [comment]
Stretch goal. Not part of MVP.

**Comment by dharmit** [comment]
Adding the odo config values (`.odo/config.yaml`) to git helps achieve this for a component. Unless this is really for applications (accessed by `odo app`), I think that should suffice.
