### ISSUE TITLE
UC 14: As a developer, I want to list all applications in a project

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#159]
As a Developer, I want to be able to list all of the applications that I currently have in a project.

```
$ ocd app list [--project=<name>] (star next to current app)

You have the following the applications in project [name]

App
MyAwesomeApp (*)
```

Tasks (create new issues if deferring some work):
- [x] #205 If name of the project is not specified, then list apps in current project. (MVP)
- [x] #206 List apps in project passed as argument

**Comment by kadel** [comment]
Create subtasks.
`--project` argument is not a requirement for MVP

**Comment by surajnarwade** [comment]
Now you can list applications from other projects as well with `--project` flag

```
odo app list  --project myproject
```

and if it not specified, it will list application from current project,

```
odo project list
```

Closing this issue :+1:
