### ISSUE TITLE
UC 21: As a developer, I want to be able to specify the application and component name on every command

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#166]
As a developer, I want to be able to specify the application and component name on every command so that it can the command can target a different application or component than the one I’m currently working with and is active

Push component to 2 apps and also push to 2 components of same app:
```
$ cd my-code-frontend                   // app=app
$ ocd create httpd                          // app=app; name=httpd
$ ocd create httpd httpd2               // app=app; name=httpd2
$ ocd create app example              // app=example
$ ocd app      
   Output: app=example
$ ocd create httpd                         // app=example name=httpd
$ ocd push httpd  --app=app        // app=app; name=httpd 
$ ocd push httpd2  --app=app      // app=app; name=httpd2 
$ ocd push httpd                          // app=example; name=httpd
```

**Comment by kadel** [comment]
we need to decompose this. This doesn't have to be in MVP.
MVP can assume working with current application

**Comment by surajnarwade** [comment]
closing this since we now have `--app`  flag
