### ISSUE TITLE
`odo watch` constantly redeploying when running in the background

### ISSUE THREAD

**Issue by rhuss** [redhat-developer/odo#1674]
[kind/bug]

## What versions of software are you using?
- Operating System: macOs
- Output of `odo version`: beta1

## How did you run odo exactly?

odo watch &

## Actual behavior

![grafik](https://user-images.githubusercontent.com/99080/56925852-a5dd5b00-6ad0-11e9-881e-db1a84e99290.png)

Interestingly this doesn't happen when `odo watch` is running in the foreground.

## Expected behavior

odo watch should not constantly redeploy when nothing changes.

**Comment by cdrage** [comment]
I'm going to set this as priority medium as it's not very high at the moment on the list (not many people run `odo` in the background in this way...)

**Comment by girishramnani** [comment]
We are aware of this limitation and we will revisit this soon.
/lifecycle frozen

**Comment by valaparthvi** [comment]
/close
No longer relevant with v3.
Feel free to reopen if you think otherwise.
