### ISSUE TITLE
confusing installation instruction in new version notification

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#183]
ocdev displays following message when there is a newer version.

```
A newer version of ocdev (version: v0.0.1) is available.
Update using your package manager, or run
curl https://raw.githubusercontent.com/redhat-developer/ocdev/master/scripts/install.sh | sh
to update manually, or visit https://github.com/redhat-developer/ocdev/releases
```

problem is that it says that you can use `curl https://raw.githubusercontent.com/redhat-developer/ocdev/master/scripts/install.sh | sh` to update it which is not true.

If you run that command and have ocdev installed it exists with following message:
```
ocdev version "v0.0.0 (d33a4ca)" is already installed on your system, running this installer script might case issues with your current installation. If you want to install ocdev using this script, please remove the current installation of ocdev from you system.
Aborting now!
```

**Comment by kadel** [comment]
realted to #122

**Comment by cdrage** [comment]
Three PR's have been merged in, in order to improve this functionality. I'm going to close this (for now)

Issue:
https://github.com/redhat-developer/odo/issues/122

PRs:
#613
#593
#589
