### ISSUE TITLE
ocdev output should follow verbosity rules in oc,kubectl with --log-level

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#189]
I started a cluster (minishift) that I had stopped for some time, so my credentials were expired. It gave me a bad error, and changed the context to -q.

```
$ ocdev app list
unable to list applications: unable to get current project info: command: [/Users/jmorales/repositories/jorgemoralespou/openshift-evangelists/oc-login.git/oc-origin project] failed to run:
error: You must be logged in to the server (the server has asked for the client to provide credentials (get projects.project.openshift.io -q))
: exit status 1
```

If I want verbose output, I see the flag verbose, which gives a lot of output.

In oc, minishift, kubectl and other go binaries it seems standar to follow logging by levels, with --log-level=(0-10)

```
--loglevel=0: Set the level of log output (0-10)
```

This should then yield by default on such above error:

```
$ ocdev app list
Unable to list applications
error: You must be logged in to the server (the server has asked for the client to provide credentials  (get projects.project.openshift.io -q))
```

**Comment by kadel** [comment]
fixing state when credentials are expired is already reported in #125 


I agree that we should clean up our verbose messages.

But I'm not sure about using loglevels. My experience is that It is hard to know what level you actually want to display. So I end up with using just the highest log level for debuging

Maybe we could reduce it from current 2 levels (normal and verbose) to good old 3 levels (normal, info, debug)?

**Comment by kadel** [comment]
Currently, we have "normal mode" and "verbose" mode for debugging. 
This system works pretty well for us right now.
I'm closing this issue. If there is a need to have more log levels, we can revisit this in the future.

**Comment by kadel** [comment]
ODO is getting to be more complex and it is starting to make sense to have multiple log levels.

For example, one log level should show detailed information about API calls that odo is making to OpenShift cluster.

Doing multiple log levels right might be tricky. We should first define how many levels we need, and what information should be in each level.

**Comment by jorgemoralespou** [comment]
@kadel I agree, but it would be awesome to follow the conventions established for oc and kubectl to make the use from "ops" who are the ones that most likely will use this feature easier.
https://kubernetes.io/docs/reference/kubectl/cheatsheet/#kubectl-output-verbosity-and-debugging

**Comment by kadel** [comment]
## Task
Switch from `log` to `glog`.

- update imports
- go through all `log.Debugf` messages and update it to appropriate `glog` call based on [Kubernetes logging conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/logging.md)
