### ISSUE TITLE
odo service create crash under Win/Cygwin

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/odo#1907]
[kind/bug]

Please note that the crash does not occur under native Windows shell (cmd)

## What versions of software are you using?
- Operating System: Win10/Pro
- Output of `odo version`:

```
odo v1.0.0-beta3 (c2b402e3)      
                                 
Server: https://172.17.24.92:8443
Kubernetes: v1.11.0+d4cacc0      
```

## How did you run odo exactly?

`odo service create`

## Actual behavior

> 
> $ odo service create
> ? Which kind of service do you wish to create  [Use arrows to move, type to filter]
> > database
>   datagrid
>   decisionserver
>   eap
>   fuse
>   hawtio
>   instant-app
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xc0000005 code=0x0 addr=0x10 pc=0x13fb8d6]
> 
> goroutine 1 [running]:
> github.com/openshift/odo/pkg/service.NewServicePlan(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
>         /home/travis/gopath/src/github.com/openshift/odo/pkg/service/service.go:360 +0xf6
> github.com/openshift/odo/pkg/odo/cli/service/ui.enterServicePropertiesInteractively(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
>         /home/travis/gopath/src/github.com/openshift/odo/pkg/odo/cli/service/ui/ui.go:246 +0x99
> github.com/openshift/odo/pkg/odo/cli/service/ui.EnterServicePropertiesInteractively(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
>         /home/travis/gopath/src/github.com/openshift/odo/pkg/odo/cli/service/ui/ui.go:240 +0x7d
> github.com/openshift/odo/pkg/odo/cli/service.(*ServiceCreateOptions).Complete(0xc000742680, 0xc00081f500, 0x6, 0xc0006f8b40, 0x2bced18, 0x0, 0x0, 0xc000a402d0, 0x18f9970)
>         /home/travis/gopath/src/github.com/openshift/odo/pkg/odo/cli/service/create.go:117 +0x5c2
> github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun(0x1b2eac0, 0xc000742680, 0xc0006f8b40, 0x2bced18, 0x0, 0x0)
>         /home/travis/gopath/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:15 +0x75
> github.com/openshift/odo/pkg/odo/cli/service.NewCmdServiceCreate.func1(0xc0006f8b40, 0x2bced18, 0x0, 0x0)
>         /home/travis/gopath/src/github.com/openshift/odo/pkg/odo/cli/service/create.go:243 +0x65
> github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute(0xc0006f8b40, 0x2bced18, 0x0, 0x0, 0xc0006f8b40, 0x2bced18)
>         /home/travis/gopath/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:702 +0x2da
> github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00078d200, 0x8, 0xc000002180, 0x1519649)
>         /home/travis/gopath/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:783 +0x2e3
> github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute(0xc00078d200, 0x19fe890, 0xc000648ae0)
>         /home/travis/gopath/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:736 +0x32
> main.main()
>         /home/travis/gopath/src/github.com/openshift/odo/cmd/odo/odo.go:65 +0x357

## Expected behavior

No crash

**Comment by amitkrout** [comment]
@jeffmaury I am able to reproduce it on ```Cygwin``` terminal, However it works on Windows ```PowerShell``` and ```Command prompt``` terminal.

ping @kadel @cdrage 

<img width="1342" alt="Screen Shot 2019-07-15 at 5 27 16 PM" src="https://user-images.githubusercontent.com/19851115/61214599-e9398400-a725-11e9-9c91-f289e0f45c62.png">

**Comment by cdrage** [comment]
From looking at the error messages, looks to be something happening upstream / the library? @metacosm

**Comment by girishramnani** [comment]
We are aware of this issue and we will revisit it soon
/lifecycle frozen
