### ISSUE TITLE
ocd list should list components in the provided application

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#192]
List all components that the argument **provided** application (database, datagrid, storage, etc.) has. This application has to be in the current user's logged in project.

```
$ ocd list --app=MYAPP
You have deployed:
myeap using the eap:6.4 component
postgres using the postgresql:8.4 persistent component
```

Part of #153

**Comment by kadel** [comment]
This will should be solved as part of https://github.com/redhat-developer/odo/issues/656

**Comment by surajnarwade** [comment]
Closing as #656 is merged, we now can list components from application provided with flag
