### ISSUE TITLE
ocd list should allow to filter components by type

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#193]
List all components that the current application has (or the one specified via CLI when #192 is complete) by type of component.

Component types need to be specified.

Initial list would be the those that can be found in the **tags** for the [imagestreams](https://github.com/openshift/library/blob/master/official/mongodb/imagestreams/mongodb-rhel7.json#L18) [definitions](https://github.com/openshift/library/blob/master/official/ruby/imagestreams/ruby-rhel7.json#L20) or the [templates](https://github.com/openshift/library/blob/master/official/mongodb/templates/mongodb-persistent.json#L17)

```
$ ocd list [--type=database|java|whatever]
You have deployed:
myeap using the eap:6.4 component
postgres using the postgresql:8.4 persistent component
```

Part of #153

**Comment by surajnarwade** [comment]
@jorgemoralespou , I didn't understand this, can you please elaborate what is `type` or a `filter` in our case?

**Comment by jorgemoralespou** [comment]
@surajnarwade It should filter based on the type of component, which is the what you choose when you create that component.

If you do `odo create wildfly ...` the type would be `wildfly`.

The signature for this query should be consistent, so maybe change `--type` to something that matches, or use something like `--filter` or `--search`.

Additionally, when we wrote this use case, there were no services, but I think this should also list all the services that the application has, and also search/filter the same way. In case of services, filtering could be extended to filter on other fields/metadata of the service.

So, if you have an application with `wildfly`, `java`, `postgresql`, `keycloak`, ìnfinispan`, you could just list the one you want.

I would defer this issue, as for now applications are really small, and we have not yet seen the specific need to implement this feature. This is similar to the feature existing in `odo catalog search`

**Comment by kadel** [comment]
closing in favor of https://github.com/redhat-developer/odo/issues/926
