### ISSUE TITLE
odo delete enters an infinite loop after project is deleted and component name is set

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/odo#1952]
[kind/bug]

## What versions of software are you using?
- Operating System: Win10Pro
- Output of `odo version`:

```
odo v1.0.0-beta3 (c2b402e3)

Server: https://172.17.159.174:8443
Kubernetes: v1.11.0+d4cacc0
```

## How did you run odo exactly?

first:
`oc delete project/demoproj`

then
odo create
once you see  `What do you wish to name the new component`, enter a different name and you will enter the infinite loop

## Actual behavior

```
$ odo create
? Which component type do you wish to create java
? Which version of 'java' component type do you wish to create 8
? Which input type do you wish to use for the component local
? Location of path component, relative to 'C:\work\src\tmp\springboot-rest' C:\work\src\tmp\springboot-rest
X Sorry, your reply was invalid: Unable to determine if component 'comp1' exists or not
? What do you wish to name the new component (java-nqmv)
```

## Expected behavior

Accept the provided name

**Comment by girishramnani** [comment]
we will revisit this issue soon
/lifecycle frozen
