### ISSUE TITLE
Get full description of a component

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#196]
Be able to get full description of what is part of a component.

```
$ ocd describe [name]
Component ABC with source in https://git and scaled to 2 instances, exposed via http://blabla and connected to component DB1, and component DB2
Application context
Parameters were …
Env vars ...
````

The very basic information a component should provide is:
- name
- where's source code for the component
- number of active instances
- connections (routes, services consumed)
- configuration

Subtask of #155

**Comment by kadel** [comment]
related to #197
