### ISSUE TITLE
Get full description of what is part of a component given as argument

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#199]
Be able to get full description of what is part of a component given as argument.

```
$ ocd describe <name>
Component ABC with source in https://git and scaled to 2 instances, exposed via http://blabla and connected to component DB1, and component DB2
Application context
Parameters were …
Env vars ...
````

The very basic information a component should provide is:
- name
- where's source code for the component
- number of active instances
- connections (routes, services consumed)
- configuration

Subtask of #155 
Dependency on #196

**Comment by kadel** [comment]
Describe is implemented.
It is showing name, component source, and linked storage. But some of the information is still missing.

There is no information about active instances, configuration, and connection to other components

**Comment by kadel** [comment]
Closing this, as the basic functionality is implemented. 
We don't have support for scaling, or configuration right now, those informations will be added once we implement it.
