### ISSUE TITLE
delete components with a single command

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#201]
As a developer, I want to be able to delete components with a single command.

```
$ ocd delete
```

Should delete current active component.

Dependency on #200 as it should ask for confirmation on deletion

Subtask of #156

**Comment by kadel** [comment]
Currently, it is implemented as `ocdev component delete`.
All what is remaining is to rename it to `ocdev delete`

**Comment by cdrage** [comment]
This has been implemented :+1: 
```sh
▶ ./ocdev delete
Error: Please specify component name to delete.
Usage:
  ocdev delete <component_name> [flags]

Examples:
  # Delete component named 'frontend'. 
  ocdev delete frontend


Flags:
  -f, --force   Delete component without prompting
  -h, --help    help for delete

Global Flags:
  -v, --verbose   Verbose output

Please specify component name to delete.
```

Via: #279

**Comment by containscafeine** [comment]
I think @jorgemoralespou wants to delete the current component just by running `ocdev delete`, that's not the current behavior.

**Comment by cdrage** [comment]
Closed via PR: https://github.com/redhat-developer/odo/pull/387
