### ISSUE TITLE
Add json support for `odo service delete`

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#2076]
[kind/Enhancement]

## Which functionality do you think we should update/improve?

We should add json support for `odo service delete`

This is what is currently being used in VSCode:

```sh
odo service delete ${name} -f --project ${project} --app ${app}
```

## Why is this needed? 

Proper json support will make implementing parts of the VSCode plugin more intuitively rather than relying on output errors of 0 and 1.

**Comment by valaparthvi** [comment]
Changing the title since `odo service create` now supports json output.

**Comment by valaparthvi** [comment]
/close
Not relevant to v3. If the command is implemented for v3, I am sure we will take JSON output into account.
Feel free to reopen if you think otherwise.
