### ISSUE TITLE
sync a binary to an existing component

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#208]
I want to be able to code locally and have it sync my changes to my running component and be smart enough to let me know when a restart of the container is required if dependencies have changed. This should work across PHP, Node.JS, Python, Ruby, and Java.

```
$ cd myfrontend
$ ocd create wildfly --binary=target/my-app.war
$ ocd push
$ ocd watch [--binary=target/mybetterapp.war]
                                         ^ override
Output:
Watching for changes on target/my-app.war.  To stop, use control-c
[13:45:10] target/myapp.war was pushed
[14:05:32] target/myapp.war was pushed
```

Subtask of #160 

There's work in progress to demonstrate how this could work done by @grahamdumpleton and @jorgemoralespou

**Comment by kadel** [comment]
implemented in #408
