### ISSUE TITLE
All machine output should have "kind" related to their function.

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#2106]
[kind/bug]

## How did you run odo exactly?

`odo project create -o json`

## Actual behavior

The `kind` in the JSON output is just "Project"

## Expected behavior

'kind' should be ProjectSuccess

## Any logs, error output, etc?

See below code:

```go
  // ProjectSuccess outputs a success output that includes
  // project information and namespace
  func ProjectSuccess(projectName string, message string) {
    machineOutput := GenericSuccess{
      TypeMeta: metav1.TypeMeta{
        Kind:       "Project",
        APIVersion: "odo.openshift.io/v1alpha1",
      },
      ObjectMeta: metav1.ObjectMeta{
        Name:      projectName,
        Namespace: projectName,
      },
      Message: message,
    }
  
    OutputSuccess(machineOutput)
  }
```

All machine readable output should have `Kind` related to their function. For example, when using `odo project create -o json` it should have `Kind` as `ProjectCreate` rather than generic `Project`.

**Comment by kadel** [comment]
I don't think that `Kind` should change in this case.

When the operation is `create` the output should return the object that was created.
- `odo project create -o json` should return the `Project` `Kind` that represent the project that was created. Essentially the same output as if you would do `odo project get myproject -o json`
- `odo component create -o json` should return the `Component` `Kind` that represents the component that was just created. The same as `odo component describe -o json` on just created component.

**Comment by cdrage** [comment]
@kadel 

The problem with this, is what about differentiating between `component delete` and `component create` success messages?

I'm assuming it'd be fine for both to just have `Component`
