### ISSUE TITLE
configurable random name generator for app (and component)

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#216]
When an app is created, we can provide a name for the app, or if not we will create the app name ourselves. We should provide a "random" generated name for the app, so that I can deploy twice a component as different apps, and I'll be able to easily identify them.

e.g. 

```
cd my source-code-dir
$ od create app
App "app-xyz" has been created
$ od create httpd
httpd component created in app-xyz

$ od create app
App "app-abc" has been created
$ od create httpd
httpd component created in app-abc

$ oc app list
- app-xyz
- app-abc (*)
```

There should be a prefix, which should be configurable, default could be **app**, and then a suffix.
The suffix will be random, and can be a set of random chars within a range (e.g. 4[a-zA-Z]) or can be a value within a list ([a la Docker](https://frightanic.com/computers/docker-default-container-names/))

Subtask of #164 
Dependency on #218

**Comment by cdrage** [comment]
This is the last task that needs to be completed for the epic https://github.com/redhat-developer/odo/issues/164 to be closed. :tada:

**Comment by anmolbabu** [comment]
> @anmolbabu @kadel
> I did not review the PR as I'm not qualified for that, but from the comments or what I gathered, I would like to make some comments, that can be discussed here.
> 
> Default name I would create would follow something that to me is understandable, so maybe take the name of the folder where my code is as base, or the repository where the code lives, e.g.
> 

@jorgemoralespou 
But how can we be sure that the command executed is from source directory? It can be completely random right specially considering we even support component creation from git url ...
And its not necessary at the app creation time even from local source for the user to be in source directory right? and there's always a possibility that the user even at the time of component creation from local source, use absolute src path and trigger app and component creates from literally any directory right?

> ```
> (jmorales: wildwildwest-frontend) $ odo app create
> Application wildwildwest-frontend-af1h has been created
> ```
> This would help me identify when listing things. I think that most likely many developers would have the folder named to something meaningful and recognizable to them.
> 
> We can maybe limit the name to a specific number of characters (e.g. 12) plus 4 random chars, to be able to create multiple applications under the same (or similar) folder.
> 
> Same thing should apply for components. In this case, we might take either the name of the directory or the type of component (e.g. nodejs) or a combination of both (e.g. wildwi-nodej-s1gr)
> 
> Not sure about limiting each part of the name to a fixed length, or the total final name, so if we choose to limit to 16 characters, we can have long first token if second token is short, or the opposite.
> 
> This supersedes the "default configurable name" that was mentioned in the issue, or making this behavior configurable via an odo variable. If the value of the variable is "app", that is the prefix, if it's "$DIR" will be the directory where the information is based.
> 
> This comments can be taken into a new issue as follow up if they make sense.

**Comment by jorgemoralespou** [comment]
@anmolbabu You're right. Sometimes (I would hope most of the times) the user will create things from within the appropriate directory, where his work is, but sometimes that will not happen.  We need to think about all possible scenarios and see what would make sense, as when not in correct directory, or using git, we should be able to determine via the provided flags to `odo create`.

`odo create` should set current directory for the component as the working dir. If i want to specify another directory, we are setting a flag (maybe not), and when using a git, where providing the git url via a flag again.

So, as far as I know, we can do:

```
odo create wildfly                          # Will use current directory
odo create wildfly --local=DIR      # Will use DIR as directory to push
odo create wildfly --binary=FILE   # Will use FILE in current directory (or relative to it) to push
odo create wildfly --git=GIT_URL  # Will use GIT_URL for source
```

In these scenarios, as we're not providing an explicit name for component, this should be "auto generated" based on what I described. Additionally, if there's no app, and none has been provided via --app flag, then the app could also be auto-generated.

The most common and fastest scenario to get started would be:

```
$ cd  my_dir_with_code
$ odo create wildfly
$ odo push
```

In this scenario, I should be autogenerating the application name and the component name. If I create it explicitly, or provide a flag `--component` or `--application` I should not create it, or I should create it with the provided names.

Does it make sense?

**Comment by anmolbabu** [comment]
> @anmolbabu You're right. Sometimes (I would hope most of the times) the user will create things from within the appropriate directory, where his work is, but sometimes that will not happen. We need to think about all possible scenarios and see what would make sense, as when not in correct directory, or using git, we should be able to determine via the provided flags to `odo create`.
> 
> `odo create` should set current directory for the component as the working dir. If i want to specify another directory, we are setting a flag (maybe not), and when using a git, where providing the git url via a flag again.
> 

> So, as far as I know, we can do:
> 
> ```
> odo create wildfly                          # Will use current directory
> odo create wildfly --local=DIR      # Will use DIR as directory to push
> odo create wildfly --binary=FILE   # Will use FILE in current directory (or relative to it) to push
> odo create wildfly --git=GIT_URL  # Will use GIT_URL for source
> ```
> In these scenarios, as we're not providing an explicit name for component, this should be "auto generated" based on what I described. Additionally, if there's no app, and none has been provided via --app flag, then the app could also be auto-generated.
> 
> The most common and fastest scenario to get started would be:
> 
> ```
> $ cd  my_dir_with_code
> $ odo create wildfly
> $ odo push
> ```
> In this scenario, I should be autogenerating the application name and the component name. If I create it explicitly, or provide a flag `--component` or `--application` I should not create it, or I should create it with the provided names.
> 
> Does it make sense?

Ack, I agree we can generate the name of source(in absence of source dir) using the passed flags(like you stated generate from git url in case of component created from git, binary or local source path in case of component creation using binary or local source deployments). And we can also use the passed in chosen names if passed to the commands.. but there's still a flow possible that puts me into doubt:

1. Create app using `odo app create`
2. Now create component using `odo create ....`

So, in 1 we have no clue about the component :) in which I think you are suggesting to use the current directory name itself right(which if desired by user can always be avoided by the user using the flags or passing the name to the command itself as in `odo app create $desired_app_name` for example)? I think it also better than the completely random names which can sometimes even sound odd :)

Makes sense I'll change the implementation accordingly.. Thanks a lot @jorgemoralespou

**Comment by anmolbabu** [comment]
> @anmolbabu I think that you're right. In case of 1. we should probably take the prefix-dir_name if no explicit name is provided, or that command should explicitly require a name, which would avoid confusion.

I think I'll go with the first part of the proposal i.e, "we should probably take the prefix-dir_name if no explicit name is provided"

@jorgemoralespou Sounds super good to me... Will modify my PR(https://github.com/redhat-developer/odo/pull/741) accordingly and hope to have it ready ASAP
