### ISSUE TITLE
When creating a component, use component type as name by default

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#217]
When you create a component, name of the component is not mandatory. If not provided, use component name as default.

```
$ od create httpd
# This will create a component with that name
```

If there's already one component with that name in the current application, give an error before create anything.

```
$ oc create httpd
ERROR: There's already one component deployed in app (app-xyz) with that name. Provide a name as argument
```

Subtask of #164

**Comment by containscafeine** [comment]
@jorgemoralespou how about we create a component with a random prefix.
e.g. `ocdev create httpd` creates a component named as `httpd-0xna3`.
This will allow the user to run `ocdev create httpd` multiple times

**Comment by kadel** [comment]
@containscafeine yes, it might make sense, lets look into it after MVP
