### ISSUE TITLE
push command should push contents and start a build

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#222]
I want to be able to start a build when **push** command is executed. If the component is configured to  use local or binary content, the content will be uploaded to the build process. If the build is configured with git source, the build will just start.

Depending on how the implementation is done, the build will not be an "OpenShift build" but rather a sync and build with a supervisor process in the container.

Subtask of #169 
Dependencies on #219, #220, #221

**Comment by slemeur** [comment]
This user story is already in place. For the purpose of the MVP release, we are fine. 

If we have time to address the different refinements that we are looking for, that would be wonderful, but I think we should postpone those to after the mvp release. 

Maybe we should be splitting this story, between the user story (already implemented) and the improvements to clarify that here we need to iterate to make the user story better.

**Comment by LalatenduMohanty** [comment]
@kadel We should have added documentation for functionality. I did not see any documentation in the PR. @surajnarwade pointed me to https://github.com/kadel/bootstrap-supervisored-s2i but a normal user can not find out unless documentation is added.
