### ISSUE TITLE
update configured storage

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#227]
As a developer, I want to be able to update storage to a component in an easy way, only requiring the common minimal information (type, size and path)

```
$ ocd storage update [name] [--size=1GB] [--access=single/multi] [--path=/opt/data/mongodb] [--component]
```

Depending on the previous and new configuration, actions that can happen are:
- Unmount
- Delete
- Create
- Mount

ocd storage update while providing a new size should add additional GB to the current PVC.

Depends on #226, #228, #229 and #230 
Subtask of #170

**Comment by kadel** [comment]
`--path` is easy and straightforward.
`--size` not sure if it can be modified without recreating underlying PVC.
`--access` - might be also tricky to update, as it depends what underlying storage supports.

**Comment by jorgemoralespou** [comment]
--size will be possible when resizing lands in OpenShift, it's a k8s 1.10 feature (https://kubernetes.io/docs/concepts/storage/persistent-volumes/#expanding-persistent-volumes-claims) and depends on the backend storage system.

--access, yes, it'll be tricky as it might need to create a new claim. The mode might instruct to use a different storage backend.

I would recommend opening a conversation with OpenShift engineering as to how to best achieve this. Maybe @bparees can help or point us in the right direction.

**Comment by bparees** [comment]
@jorgemoralespou you'll probably want the storage team, which is @childsb
