### ISSUE TITLE
delete storage

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#228]
As a developer, I want to be able to delete storage to a component in an easy way, only requiring the common minimal information

```
$ ocd storage delete [name]
Do you really want to delete storage for component <name> (y/n)?
```

$ ocd storage delete, should unmount the storage if still mounted.
Dependency on #230 

Subtask of #170

**Comment by cdrage** [comment]
See: https://github.com/redhat-developer/ocdev/issues/226 can we close this @kadel ?

**Comment by kadel** [comment]
Remove currently works slightly differently

**Comment by kadel** [comment]
Let's keep this open until it is fixed
