### ISSUE TITLE
mount storage

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#229]
As a developer, I want to be able to mount storage to my container. 

```
$ ocd storage mount [name] [--path=] [--component]
```

$ ocd storage mount will link a pvc to a component at the specified path

Dependency on #226 
Subtask of #170

**Comment by cdrage** [comment]
See: https://github.com/redhat-developer/ocdev/issues/226 can we close this @kadel ?

**Comment by kadel** [comment]
We don't have mount implemented, just create and list.

**Comment by kadel** [comment]
closed in #472
