### ISSUE TITLE
unmount storage

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#230]
As a developer, I want to be able to unmount storage to a component in an easy way, only requiring the common minimal information

```
$ ocd storage umount [name] [--component]
```

$ ocd storage umount will just unlink the pvc from the component but does not delete the volume or claim

Dependency on #226 
Dependency for #228 
Subtask of #170

**Comment by cdrage** [comment]
See: https://github.com/redhat-developer/ocdev/issues/226 can we close this @kadel ?

**Comment by kadel** [comment]
We don't have unmount command

**Comment by kadel** [comment]
fixed in #349
