### ISSUE TITLE
Speed up autocompletion.

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#2339]
## Which functionality do you think we should update/improve?

Currently auto-completion is *very* slow (1-2 seconds put tab) which instead should be either instantaneous or within a few milliseconds. 

This was found when implementing https://github.com/openshift/odo/pull/2326

## Why is this needed? 

Speed up autocompletion

**Comment by kadel** [comment]
it is really slow, and so slow that is is almost unusable.

doing `odo push --co` and waiting 2 seconds to see something is unbearable :-( 
Autocompletion is supposed to speed up things, but our is not doing that.

/kind bug
/priority medium

**Comment by kadel** [comment]
this has been fixed in odo v3

/close
