### ISSUE TITLE
UX is pretty inconsistent

### ISSUE THREAD

**Issue by containscafeine** [redhat-developer/odo#265]
We have been putting in a lot of code, but the UX is pretty inconsistent.
e.g., the way we list components, applications, projects, xyz, should be consistent.

Or the way logs are streamed to the screen should be consistent, do we stream or do we not stream?

The way the output looks, does it always start with `-- building image`, or does it not?

We need to figure this out. If the UX is not consistent or polished, this looks of a hack than a project.

**Comment by kadel** [comment]
UX improved a lot since this issue was opened.

**Comment by containscafeine** [comment]
Yeah, I agree :yum:
