### ISSUE TITLE
Add e2e tests

### ISSUE THREAD

**Issue by containscafeine** [redhat-developer/odo#267]
There's a lot of code moving around, and the best way to keep the tool stable is via e2e tests.

We should work towards adding e2e test for most (if not all) the commands.

ping @ashetty1 @kadel

**Comment by containscafeine** [comment]
client-go has `fake` package for almost all the code in there, we could leverage that.

**Comment by kadel** [comment]
> client-go has fake package for almost all the code in there, we could leverage that.

but that is not for e2e tests but for unit tests

**Comment by ashetty1** [comment]
@containscafeine I haven't pushed many changes yet because I was waiting for a few changes to be merged over last week. Will \be pushing tests for more commands this sprint.

**Comment by kadel** [comment]
@ashetty1 It will be better if we can add them continuously. As soon as you have something (even a single test) please open PR with it.

**Comment by kadel** [comment]
@ashetty1 please link all PRs related to e2e tests to this issue so we can keep track of what is happening

**Comment by ashetty1** [comment]
Listing the PRs so far merged:

PR #242 
PR #268

**Comment by ashetty1** [comment]
A complete coverage matrix for e2e tests maintained here: https://github.com/redhat-developer/ocdev/tree/master/tests/e2e

**Comment by containscafeine** [comment]
This is going awesome :fire:

**Comment by containscafeine** [comment]
This is ongoing work, I guess we can close this
