### ISSUE TITLE
`ocdev project notexistin_subcommand` should exit with error

### ISSUE THREAD

**Issue by ashetty1** [redhat-developer/odo#274]
Looks like `ocdev project delete` doesn't delete the project as expected:

```
$ ocdev project create projtmp
New project created and now using project : projtmp

$ ocdev project get
The current project is: projtmp

$ ocdev project delete projtmp -v
DEBU[0000] getOcBinary - searching for oc binary        
DEBU[0000] envKubectlPluginCaller = 
                   
DEBU[0000] envOcBin = 
                                 
DEBU[0000] using oc from PATH                           
DEBU[0000] using oc from %s/usr/bin/oc                  
DEBU[0000] Trying to connect to server 127.0.0.1:8443 - %!v(MISSING) 
DEBU[0000] Server https://127.0.0.1:8443 is up          
DEBU[0000] isLoggedIn err:  <nil> 
 output: "developer\n" 
DEBU[0000] running oc command with arguments: /usr/bin/oc project
 
DEBU[0000] running oc command with arguments: /usr/bin/oc project -q
 
The current project is: projtmp
DEBU[0000] Could not get the latest release information in time. Never mind, exiting gracefully :) 

$ ocdev project get
The current project is: projtmp

$ ocdev project list
The current project is: projtmp
```

**Comment by mik-dass** [comment]
@ashetty1 ocdev project delete is not implemented yet

**Comment by ashetty1** [comment]
Oh okay. closing this then.

**Comment by kadel** [comment]
`ocdev project delete` is not implemented.
Problem is that it is not obvious as `ocdev project delete` matches to `ocdev project` that gets current active project.

**Comment by kadel** [comment]
I have reopened this as we need to make sure that any random `ocdev project asdf` shows error instead of showing current project.

**Comment by containscafeine** [comment]
This also happens with other subcommands -
```console
$ ocdev application random
There's no active application.
You can create one by running 'ocdev application create <name>'.
```

**Comment by surajnarwade** [comment]
@kadel sounds good to me, but this is not implemented in `application` either. I am creating issue for the same

**Comment by kadel** [comment]
We need to find some systematic solution for this.
If we can't then we might allow switching only with `set` subcommand.

**Comment by kadel** [comment]
> @kadel sounds good to me, but this is not implemented in application either. I am creating issue for the same

hold the horses ;-) lets think about it first ;-)

**Comment by kadel** [comment]
the same problem is also with `component`

**Comment by surajnarwade** [comment]
@kadel , currently for `application` & `project`, if we do,

```
odo app someapp
The current application is: myapp
```

and for project,

```
$ odo project asdf
The current project is: myproject
```

they just show current thing

**Comment by containscafeine** [comment]
> odo project can have have argument. odo project myproject should switch to the project myproject (the same as odo application myapp switches to myapp)

I disagree :( I think we should be switching only using `set`

**Comment by containscafeine** [comment]
`odo project xyz`, `odo app xyz`, `odo xyz` should all returns errors.
Set should happen using `odo project set xyz`, `odo app set xyz`

**Comment by surajnarwade** [comment]
@kadel what do you think on @containscafeine comment ? I liked this way. (I mentioned this earlier too)

**Comment by kadel** [comment]
I don't have anything against it, but the problem is that it is inconsistent with how you switch components. `odo component xzy`

**Comment by surajnarwade** [comment]
I am confused now :|

**Comment by kadel** [comment]
`odo project set xyz`
`odo app set xyz` 
vs. 
`odo component xyz` 

`set` is used for project and app, but not for `component`. That is the inconsistency I'm talking about.
