### ISSUE TITLE
Add `odo deploy` command for initial transition from inner to outer loop

### ISSUE THREAD

**Issue by bbrowning** [redhat-developer/odo#2756]
/kind feature

## Which functionality do you think we should add?

Today odo helps a developer with their inner loop workflow. Once the developer is ready to deploy that application, they need to go outside of odo to make that happen. I propose odo have an `odo deploy` command to allow an initial transition from inner loop to outer loop.

The result of an `odo deploy` command should be the component gets deployed to the cluster in a configuration suitable to receive production traffic.

## Why is this needed?

This is meant primarily for new user experience, demos, and such as a developer learns how to deploy applications to the cluster. Best practice for real production usage would still be integration with pipelines (#1238) or integration with gitops workflows (#2617). There's a gap between `odo push` for in-cluster inner loop and pipelines or gitops workflows that this intends to fill.

## How should it be added?

As a strawman proposal, I'd suggest bringing this in following the recent devfile support by having a convention for metadata in the devfile that odo can understand to deploy an application. This would allow devfile-aware pipelines to reuse that same devfile metadata to do the actual deployment at the output of those pipelines.

What the exact metadata in the devfile should look like needs to be decided. I believe the existing devfile 2.0 spec covers the need here, but we'll need to verify that.

## User stories

- [x]  #5109
- [x]  #5110

**Comment by sspeiche** [comment]
This is the "same" related to this discussion https://github.com/openshift/odo/issues/1229

**Comment by girishramnani** [comment]
We are planning a proposal issue which would break this epic down https://github.com/openshift/odo/issues/2703

**Comment by lance** [comment]
In addition to pipelines, I would like to see another devfile command supported by odo. Currently, if I understand correctly, odo supports two commands in the devfile: `devBuild` and `devRun`. Could there be a supported command that will deploy your image without the supervisor and possibly using a different image component?

**Comment by kadel** [comment]
> Could there be a supported command that will deploy your image without the supervisor and possibly using a different image component?

Yes, this is what the deploy command should do. 
"deployed to the cluster in a configuration suitable to receive production traffic." means that the supervisor won't be present and different image can be optionally used (for example this image should be completely stripped form any development tools, and should be as small as possible).

Not sure how we exactly we will achieve this but defining another command like `prodRun` or `prodBuild` could be one way of doing this.

**Comment by serenamarie125** [comment]
Moved out to 2.2 milestone due to dependencies on devfile 2.2

**Comment by dharmit** [comment]
The devfile library doesn't have outer loop support yet. Ideally, this should be sorted at devfile library end first and then implemented in odo.

**Comment by kadel** [comment]
> The devfile library doesn't have outer loop support yet. Ideally, this should be sorted at devfile library end first and then implemented in odo.

It does now (https://github.com/devfile/library/releases/tag/v1.2.0). We can start working on this


Created user story to cover initial `odo deploy` work https://github.com/openshift/odo/issues/5109
