### ISSUE TITLE
Showcase odo's ability to develop non-trivial applications

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/odo#2781]
/kind documentation

## What mistake did you find / what is missing in the documentation?
So far, odo documentation talks mostly about simple getting started applications. These are just starter applications and do nothing to demonstrate odo ability to help develop non-trivial micro-services architecture based projects/applications.

Documentation explaining how to spin up and link something like below would be helpful:
1. Frontend application
2. Message queue
3. Backend application
4. Database service

## What is the relevance of it?
This will help demonstrate odo's capabilities to help develop non-trivial applications that enterprise devs care about.

**Comment by cdrage** [comment]
We do have documentation on this :) using multiple components  as well as a database:

https://docs.openshift.com/container-platform/4.2/cli_reference/openshift_developer_cli/creating-an-application-with-a-database.html

**Comment by dharmit** [comment]
> We do have documentation on this :) using multiple components as well as a database:
> 
> https://docs.openshift.com/container-platform/4.2/cli_reference/openshift_developer_cli/creating-an-application-with-a-database.html

Agreed. However, the idea is to have an example that's more complex than what we have right now.

**Comment by dharmit** [comment]
This is blocked on improving the UX as well as fixing issues with `odo link` and addressing #3423 which in turn is blocked on #4160 & #4159.

/lifecycle frozen
/status blocked

**Comment by dharmit** [comment]
Few non-trivial examples that we could try making work with odo:
* https://github.com/Emergency-Response-Demo/findmyrelative-frontend
* https://github.com/GoogleCloudPlatform/microservices-demo

**Comment by slemeur** [comment]
You can also look at this one: https://developers.redhat.com/articles/2021/06/14/bee-travels-microservices-coding-adventure#microservices_in_action__the_bee_travels_application

**Comment by dharmit** [comment]
/remove-lifecycle stale

We have made progress on this by adding a Quickstart guide. In my personal opinion, it's definitely not a trivial example.

However, one thing that I feel is still not really done is showcasing how to develop such applications using odo. What the quickstart guide does is clone an existing project and deploy that with odo.

**Comment by cdrage** [comment]
This is being worked on and added by @valaparthvi on v3.
