### ISSUE TITLE
check if namespace/project exist 

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#2823]
`odo push` should check that the project or namespace exist and fail with nice error explaining what should user do to fix it (create namespace/project)

```
▶ odo push
 •  Push devfile component backend  ...
 ✗  Failed to start component with name backend.
Error: Failed to create the component: unable to create or update component: unable to create Deployment backend: namespaces "demo" not found

```

This is still problem in v3 for both odo dev and odo deploy

/kind bug
/priority medium
/area devfile

**Comment by rm3l** [comment]
Closing in favor of https://github.com/redhat-developer/odo/issues/4447
