### ISSUE TITLE
Better make test-e2e output

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#283]
More information would be helpful determining what exact command didn't work:

```sh
 make test-e2e
go test github.com/redhat-developer/ocdev/tests/e2e
Running Suite: ocdev test suite
===============================
Random Seed: 1522247597
Will run 9 of 9 specs

New project created and now using project : ocdev-1522247597
ocdev-1522247597
•Creating application: usecase5
Switched to application: usecase5
usecase5•ocdev-1522247597
•Creating application: usecase5-2
Switched to application: usecase5-2
usecase5-2Switched to application: usecase5
usecase5•2018/03/28 10:33:26 exit status 1
FAIL    github.com/redhat-developer/ocdev/tests/e2e     8.934s
Makefile:72: recipe for target 'test-e2e' failed
make: *** [test-e2e] Error 1
```

Perhaps outputting what runCmd is into the logs and adding more spacing between the log outputs too?

https://github.com/redhat-developer/ocdev/blob/master/tests/e2e/e2e_test.go#L151

ping @ashetty1

**Comment by kadel** [comment]
For this, I would like to output those commands only if there was an error. Please don't make verbose output if tests are passing, It is really hard to find something if logs are polluted with useless lines.

**Comment by ashetty1** [comment]
@kadel @cdrage sure, will do that.

**Comment by ashetty1** [comment]
Pushed a minor fix here: #286

**Comment by cdrage** [comment]
Hey @ashetty1 what's the status on this? I recently received a failure here: https://travis-ci.org/redhat-developer/ocdev/jobs/362277540#L584 but there was still no error or stdout, I don't see anything unfortunately that could help debug error outputs.

**Comment by cdrage** [comment]
Output:

```sh
Running Suite: ocdev test suite                                                                                                                                                                                                                                                                                                                                     [12/1980]
===============================
Random Seed: 1522867639
Will run 9 of 9 specs

New project created and now using project : ocdev-1522867639

ocdev-1522867639

•Creating application: usecase5
Switched to application: usecase5

usecase5
•ocdev-1522867639

•Creating application: usecase5-2
Switched to application: usecase5-2

usecase5-2
Switched to application: usecase5

usecase5
•exit status 1:
FAIL    github.com/redhat-developer/ocdev/tests/e2e     8.123s
Makefile:72: recipe for target 'test-e2e' failed
make: *** [test-e2e] Error 1

```

**Comment by cdrage** [comment]
Could we please output `runCmd` command to fmt.Println when the tests are running so we can see the *exact* command line we're failing ont?

**Comment by cdrage** [comment]
I think we should to two things:

 - Change names "usecase", etc. to something more descriptive
 - Better command-line output / information when running `make test-e2e` so we may diagnose the error.

@kadel @ashetty1

**Comment by cdrage** [comment]
I did a quick look through http://onsi.github.io/ginkgo/#organizing-specs-with-containers-describe-and-context and there's some functions related to logging that may help.

**Comment by ashetty1** [comment]
@cdrage, Taking this up on priority:

1. Print trace when any operation fails
2. Organise logging when we have VERBOSE=yes

**Comment by cdrage** [comment]
@ashetty1 I tried with the Ginko testing and unfortunatley I can't get any tracing. I used `ginko --trace` and nothing..

**Comment by ashetty1** [comment]
@cdrage I am try and see if I can improve the output of `runCmd`. If that fails, we should we do away with `runCmd` function and handle the errors with assertions (that's too much manual work thought).

**Comment by kadel** [comment]
This is something that might be helpful @ashetty1  https://onsi.github.io/ginkgo/#marking-specs-as-failed

**Comment by cdrage** [comment]
This has been vastly improved by @ashetty1 's recent contributions. I'm going to close this! :grinning: thanks @ashetty1 !
