### ISSUE TITLE
Orphaned components should not be created

### ISSUE THREAD

**Issue by containscafeine** [redhat-developer/odo#291]
State - fresh installation of ocdev, no applications, components, etc exist
Step 1 - `ocdev component create nodejs`
Step 2 - `ocdev component list`

This does not return any components.

Basically the logic is broken because the component creation should not even begin binding itself to the application. We need to get the `GetCurrentOrDefault` logic from inside `component.Create()` and move it outside. `component.Create()` should be passed the application name as a parameter.

**Comment by kadel** [comment]
> If an application has not been created, then we should not be able to create a component.

this is against https://github.com/redhat-developer/ocdev/issues/151 as it clearly states "If no application exists, a default application will be created."

We need to fix implementation rather than removing this feature.

**Comment by containscafeine** [comment]
@kadel reworded the description

**Comment by kadel** [comment]
> component.Create() should be passed the application name as a parameter.

+1

**Comment by kadel** [comment]
fixed in #358
