### ISSUE TITLE
Listing *everything* under `ocdev list`

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#297]
One of the things we should work on is simplification. With `create` `delete` and eventually `logs` being added. I believe that we should work on consolidating each list command into *ONE* command.

For example:

Instead of having:
```sh
github.com/redhat-developer/ocdev  master ✗                                                                                                                                 2h33m ⚑  
▶ ocdev component list
The current component is: list

github.com/redhat-developer/ocdev  master ✗                                                                                                                                 2h33m ⚑  
▶ ocdev project list
The current project is: myproject

github.com/redhat-developer/ocdev  master ✗                                                                                                                                 2h34m ⚑  
▶ ocdev application list
ACTIVE   NAME
  *      nodeapp
         foobar
```

This can be replaced by *one* command, just `ocdev list` which will list everything in a neatly formatted table (using: https://golang.org/pkg/text/tabwriter/)

For example (hypothetical table):

```sh
$ ocdev list
ACTIVE          PROJECT               APPLICATION       COMPONENTS
  *             myproject             nodeapp           nodejs, nodebuilderjs, nodejs2    
                myotherproject        ruby              rails 
                java                  maven             openjdk  
```

**Comment by jorgemoralespou** [comment]
ocdev list should provide same output as ocdev component list
See https://github.com/redhat-developer/ocdev/pull/225

**Comment by containscafeine** [comment]
@cdrage I agree. How about `ocdev status`? #314

**Comment by surajnarwade** [comment]
@kadel @containscafeine @cdrage , as per the @jorgemoralespou's comment, `odo list` & `odo component list` should be the same. But, I am confused here,

* Are we going to deprecate `odo component <command>` ?

* if not, we should have consistency between `odo <command>` & `odo component <command>` ?

**Comment by kadel** [comment]
> Are we going to deprecate odo component <command> ?

`odo component` used should be only for setting and getting current component


`odo component mycomponent` - set current component to mycomponent
`odo component` - get current component

`odo list` - display list of components

**Comment by kadel** [comment]
> For example (hypothetical table):
> 
> $ ocdev list
> ACTIVE          PROJECT               APPLICATION       COMPONENTS
>   *             myproject             nodeapp           nodejs, nodebuilderjs, nodejs2    
>                 myotherproject        ruby              rails 
>                 java                  maven             openjdk


I'm not sure if this table will work.
One project can have multiple applications, and one application can have multiple components.
So it could look like this. 

```
 ACTIVE         PROJECT               APPLICATION       COMPONENTS
                myproject             nodeapp           nodejs, nodebuilderjs, nodejs2    
                                      otherapp          ffrontend, golang, backend    
                myotherproject        ruby              rails 
                                      ruby2             rails 
 *                                    ruby3             rails 
                java                  maven             openjdk
```

I'm not sure if output like this will be usefull for user.

**Comment by syamgk** [comment]
Is this also an expected out put when there are no applications or components deployed?

```
ACTIVE      PROJECT                      APPLICATION      COMPONENTS
            0final                       frontend         php
  *                                      pysample         python                                    
            testproject                           
            test-integrations                        
            mmpush                                         
            mock      
```

**Comment by kadel** [comment]
it is getting confusing :-) I don't think that there is a real need to display all applications with all components in one output.

**Comment by syamgk** [comment]
or we can also list all components and skip showing projects without components 
ie,
```
$odo list                                                                                                                     
ACTIVE      PROJECT      APPLICATION      COMPONENTS
            0final       frontend         php
  *                      pysample         python
```
this way we will be showing all components and its meta information. WDYT?

**Comment by kadel** [comment]
I should clarify one thing.
 **`odo list ` should just list components in the current application and nothing more.**

If we are talking about something that will show all application and all components that it should be a completely new command.  

But that is right now ultra low priority. I don't see any usecase for it right now.

**Comment by kadel** [comment]
This was sorted out, closing
