### ISSUE TITLE
odo deploy should support creation of Knative:Service

### ISSUE THREAD

**Issue by sspeiche** [redhat-developer/odo#3026]
## Description
As a developer, I'd like a way to have `odo deploy` to utilize deployment guidance in devfile to create a `kn:Service` instead of a kubernetes Deployment or OpenShift Deployment config.

## Acceptance criteria
* Developer can create a new application component as a Knative Service and match the behavior in OpenShift's web ui.

## Possible cli flows

Ability to use odo to deploy as a Knative Service, using deployment guidance in devfile

**Comment by kadel** [comment]
I think that this is something that should be captured in devfile and than odo will act on that information.
The reason why I think it would be better to captured this in devfile is to make it consistent across all tools. If I have an application that assumes that will be run as Knative Service I don't want to configure odo and again Che to make sure that my apps get deployed correctly. I would just define this in devfile, and then tools should handle it.

**Comment by serenamarie125** [comment]
Moved out to 2.2 milestone due to dependencies on devfile 2.2

**Comment by kadel** [comment]
with `odo deploy` implemented and devfile having support for outer loop. It is fairly straight forward to create a devfile that utilizes KNative Service for outer loop deployment

I've created a simple example https://github.com/kadel/devfile-nodejs-deploy/blob/e42112fe1256ea2a18b93e19f6919f1c5f5513dd/devfile.yaml#L55-L69
