### ISSUE TITLE
we should pass `os.Writer` to FollowBuildLog instead of assuming STDOUT

### ISSUE THREAD

**Issue by containscafeine** [redhat-developer/odo#312]
In pkg/occlient/occlient.go, $SUBJECT

**Comment by kadel** [comment]
You are reading my mind ;-)

**Comment by cdrage** [comment]
@kadel @containscafeine Began working on this to find that we don't actually use this function anymore (with FollowBuildLog).

I believe both could be removed, or am I missing something?

https://github.com/redhat-developer/odo/search?l=Go&q=StartBinaryBuild

**Comment by kadel** [comment]
But FollowBuildLog is also used in component.Build https://github.com/redhat-developer/odo/blob/e85a324dc14809851d7f5d7fad52809f66cd0cbf/pkg/component/component.go#L241

**Comment by kadel** [comment]
If there is some code that is not used anymore than we should remove it.

**Comment by cdrage** [comment]
I believe this can be closed now that #531 is closed (this was the only part that didn't have io.Writer not being passed in)

**Comment by kadel** [comment]
`FollowBuildLog` function is still used. It doesn't have `io.Writer` as an argument, and instead it writes directly to stdout.

https://github.com/redhat-developer/odo/blob/6a287f86e1eca225bfa1a7a51ba430e8b937877c/pkg/occlient/occlient.go#L963

**Comment by cdrage** [comment]
@kadel PR here: https://github.com/redhat-developer/odo/pull/548

**Comment by kadel** [comment]
We still need to add test for FollowBuildLog function

**Comment by cdrage** [comment]
https://github.com/redhat-developer/odo/pull/548 has been merged
