### ISSUE TITLE
Error while following buildLogs 

### ISSUE THREAD

**Issue by mik-dass** [redhat-developer/odo#313]
[mdas@localhost ocdev]$ ./ocdev create nodejs nodejsnew --git https://github.com/kadel/nodejs-ex
    Cloning "https://github.com/kadel/nodejs-ex" ...
        Commit: 371a6d09a052b126016858563bc5c71ba56deec8 (save counter to file if db is not available)
        Author: Tomas Kral <tkral@redhat.com>
        Date:   Mon Feb 12 12:25:30 2018 +0100
    ---> Installing application source ...
    ---> Building your Node application from source
    npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-
    string instead.
    unexpected stream type ""

This happens occasionally, not always, and the stream shuts down after this error but the build is running and logs are visible in the minishift console.

**Comment by containscafeine** [comment]
not always reproducible. Let's keep it open just in case this happen often.

**Comment by cdrage** [comment]
Removing priority/medium tag as this isn't always reproducible (I have yet to encounter this error)..

**Comment by kadel** [comment]
There was no other occurrence of this. I'm closing this.
