### ISSUE TITLE
Display what components / build builds work (nodejs, ruby, java, etc.) and detect custom ones.

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#318]
`ocdev create` should provide better help / description outlining what you can do with the components. For example, listing that: 

 - Ruby
 - Node.JS
 - Java
 - PHP

All work with OpenShift.

Also, instead of erroring out, `ocdev` should also check OpenShift for what custom Image Builds are available and list them all.

**Comment by containscafeine** [comment]
@cdrage part of this can be resolved with using `ocdev catalog list` -
```console
$ ocdev catalog list
The following components can be deployed:
- httpd
- nodejs
- perl
- php
- python
- ruby
- wildfly
```
Do you suggest that we add more description with every component?

> Also, instead of erroring out, ocdev should also check OpenShift for what custom Image Builds are available and list them all.

So besides the error, do you suggest that we list all the available components?

**Comment by cdrage** [comment]
@containscafeine Yes on both. I suggest we improve the description as well as the error out better :+1: I'll assign this to myself.

**Comment by cdrage** [comment]
PR: https://github.com/redhat-developer/odo/pull/335

**Comment by cdrage** [comment]
This has been merged :+1:
