### ISSUE TITLE
`create --local` should NOT trigger build

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#327]
When a local component is created the build shouldn't be triggered.
It should just create a component and wait for the user to run `ocdev push` to build component.

If the component is created from remote git than it is ok to start building component right away.

**Comment by jorgemoralespou** [comment]
When the component is created:
- A build configuration should be created as binary build
- There should be no triggers happening (if they happen automatically) don't create with triggers and add them after in a second action
- If trigger was removed (add it)
- Give some hint about the component being created (and need to run push to start a build)

When push happens:
- Start a binary build from the local directory (or file)
- Stream the logs from the build

There's some discussion on related topic here:
https://github.com/openshift/origin/issues/15429
