### ISSUE TITLE
Support Katacoda scenario

### ISSUE THREAD

**Issue by slemeur** [redhat-developer/odo#329]
## Description
The OpenShift developer CLI will be demoed during RH Summit. It will be an hands-on interactive Katacoda course highlighting `ocdev` workflow that visitors will be able to take at OpenShift booth. 

For that, the OpenShift evangelist team is building a Katacoda scenario which will be available similarly to https://learn.openshift.com/.

(A first draft of the scenario is available here: https://www.katacoda.com/mjelen/courses/introduction/developing-with-odo

The goal of this epic is to list all the different aspects that we need to handle in order to deliver a successful hands-on lab and complete scenario which will demonstrate the value of the project.

## Goals
- [ ] Complete MVP Milestone
- [x] Make sure the scenario is running smoothly

## Tasks
(we should be cross linking the different issues that we will identify while working on this epic)
 the

**Comment by surajnarwade** [comment]
@bmicklea , from the two goals mentioned above, some task from MVP milestones are still in progress.
Reference: https://github.com/redhat-developer/odo/milestone/2

**Comment by kadel** [comment]
> @bmicklea , from the two goals mentioned above, some task from MVP milestones are still in progress.
> Reference: https://github.com/redhat-developer/odo/milestone/2

That is true, MVP milestone is not complete, but issues that are left there were not part of the final Katacoda scenario.
I would say that we can close this.

**Comment by slemeur** [comment]
Agree. Let's close this one. Thanks!
