### ISSUE TITLE
odo command timings maybe a little too precise?

### ISSUE THREAD

**Issue by deboer-tim** [redhat-developer/odo#3375]
/kind bug

## What versions of software are you using?

**Operating System:**
Mac OS

**Output of `odo version`:**
odo v1.2.2 (53530e0e5)

Server: https://c101-e.us-east.containers.cloud.ibm.com:32744
Kubernetes: v1.16.2+18cfcc9

## How did you run odo exactly?
odo create (or odo push)

## Actual behavior
The current output from 'Validation' currently looks something like this:
 ✓  Checking devfile compatibility [275970ns]
 ✓  Creating a devfile component from registry: DefaultDevfileRegistry [164528ns]
 ✓  Validating devfile component [247367ns]

## Expected behavior
Whenever I see these nanosecond values I find them a little hard to read (is that 2.3s, 0.23s, or 0.023s?), and I wonder if anyone really cares about the values being this precise. My suggestion is to keep them as second values with only 2 or 3 significant digits to make them easier to read, e.g.:
 ✓  Checking devfile compatibility [0.275s]
 ✓  Creating a devfile component from registry: DefaultDevfileRegistry [0.164s]
 ✓  Validating devfile component [0.247s]

**Comment by GeekArthur** [comment]
https://github.com/openshift/odo/blob/87cae3b5d1c1c1a2654dcfff0e345e56bb248792/pkg/log/fidget/spinner.go#L132-L149

From the source code above, currently the spinner timestamp unit and precision are dynamic depends on the command/spinner execution time, I think we have that design is because the big execution time difference exists between different commands/spinners. To make spinner timestamp unit and precision static (eg. use seconds with 3 significant digits) would result in some command/spinner execution time is [0.000s] and some command/spinner execution time is very big I think.

**Comment by deboer-tim** [comment]
Sorry, I didn't mean to suggest this for all times, just for nanoseconds. Times like '23s' are clear, it's just the nanoseconds that are harder to read for me. i.e. 0.2s or 0.24s is easier to read than 247367ns.

**Comment by GeekArthur** [comment]
> Sorry, I didn't mean to suggest this for all times, just for nanoseconds. Times like '23s' are clear, it's just the nanoseconds that are harder to read for me. i.e. 0.2s or 0.24s is easier to read than 247367ns.

Ah, I see. Only make the changes to nanoseconds is a great improvement for readability. I totally agree with you.

**Comment by jichenjc** [comment]
275970ns = 275970/1000000000 = 0.00027597 sec 
do we really want to update to this format?

**Comment by deboer-tim** [comment]
Yeah, I agree that's no better, and I should have shown equivalent times.

My main point is that the output text is for humans, and anything with too many digits or too much precision is hard to read or meaningless. If timings really are that small, then IMHO it'd be better to say '0s', use ms ('0.28ms'),or just use '<0.01s'.

**Comment by deboer-tim** [comment]
Just watched a live demo and noticed this again. The ns are a bit distracting, my preference would be to decide the minimum granularity (IMHO 1ms would be fine, but could be 0.1ms too) and then just use '<' if it's less than that (e.g. '<1ms').

i.e. just change:
   return fmt.Sprintf("%dns", timeElapsed.Nanoseconds())
to:
   return "<1ms"

**Comment by deboer-tim** [comment]
I'm gonna keep this one open.

/remove-lifecycle stale

**Comment by valaparthvi** [comment]
/close
I think this is already covered.

Feel free to reopen if you still see it.
