### ISSUE TITLE
Add link command 

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#342]
subtask of #171 

example:
link current component with backend component:
``` 
odo link backend
```
```
odo link backend --component frontend
```
Link frontend component to the backend.

What that means is that env variables describing how to connect to backends Service will be injected to frontends DeploymentConfig.

Steps to do this:
Find service for `backend` component.
Get ip and port of that service.
Add following env variables to DeploymentConfig for `frontend` component.
```
COMPONENT_BACKEND_ADDRESS=<some address>
COMPONENT_BACKEND_PORT=<some port>
```

update
`COMPONENT_BACKEND_ADDRESS` should be the hostname of the Service lets use  `COMPONENT_BACKEND_HOST` instad

**Comment by containscafeine** [comment]
Fixed in #354
