### ISSUE TITLE
We're using errors.Wrapf() way too much.

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#347]
I've noticed that debugging is fairly difficult with our error messages.

What's happening is that we're losing a lot of context with regards to erroring... We're ending up with giant massive error messages that (usually) make no sense.

Instead of using:

```go
return false, errors.Wrapf(err, "unable to retrieve list of components")
```

We should be returning the *context* the "deepest" error message within the code like so:

```go
return false, err
```

What's happening is that we end up wrapping around wrapping around wrapping and we're getting this mess:

```go
unable to delete component nodejs: unable to set  component as active, application myproject in app project doesn't exists
```

When in reality, we should be outputting the *last* statement of that error, which is the most important:

```go
 application myproject in app project doesn't exists
```

Which in reality should be formatted like this:

```go
ERROR (in red): Application "myproject" in project "app" does not exist
```

See: https://blog.golang.org/errors-are-values

This blog is also really good too that outlines as to *why* we should just simply return:

```go
return err
```

rather than wrapping: https://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully

Especially this part:

**Donovan and Kernighan’s The Go Programming Language recommends that you add context to the error path using fmt.Errorf**

```go
func AuthenticateRequest(r *Request) error {
        err := authenticate(r.User)
        if err != nil {
                return fmt.Errorf("authenticate failed: %v", err)
        }
        return nil
}
```

**But as we saw earlier, this pattern is incompatible with the use of sentinel error values or type assertions, because converting the error value to a string, merging it with another string, then converting it back to an error with fmt.Errorf breaks equality and destroys any context in the original error.**

Another blog that outlines how errors should be done: https://morsmachine.dk/error-handling

I suggest we go through all the errors that we have and eliminate / improve them, for example, these vastly need improvement: https://github.com/redhat-developer/ocdev/blob/master/pkg/component/component.go#L164-L176 since despite each error being different, each error is confusing to the end-user as we're simply wrapping below the previous one.

ping @containscafeine @kadel

**Comment by containscafeine** [comment]
I agree that user facing errors should be way better formatted than what we are printing right now, but while debugging, then wrapped errors really help me going to the root cause very quickly, so I'd like to keep that.
I think we need to have a set of pre-formatted errors which we send to the user by checking the underlying error. Need to think more about this, and also need to read the blogs that you've posted.
I'd also want to look at how other projects like Kube, OpenShift are handling this.
But yes, this is important.

**Comment by kadel** [comment]
I'm a little bit torn here. I don't like wrapping also, but I see its benefits.

How you find where the error was raised if the function is called in multiple places in code?  
Error wrapping gives you nice context what path the code took.

```
return fmt.Errorf("authenticate failed: %v", err)
```
Is different than what errors.Wrap does. `errors.Wrap` doesn't' destroy any context, bu it adds more context to it the error. For example, you can get strack trace out of it (we are just not doing it right now)


I think that bigger problem with our current system is that we are bad it writing error messages. I'll be first to admit that I'm guilty of this :-(

**Comment by cdrage** [comment]
We've started to switch to `glog` now so I'm closing this.

**Comment by cdrage** [comment]
I feel as though we've improved in terms of error messages since I last re-opened this issue. I'm going to close this for now :+1:
