### ISSUE TITLE
Add Validate(), Execute() to cmd/

### ISSUE THREAD

**Issue by containscafeine** [redhat-developer/odo#356]
We should uniformly follow the execution of every command. First we should validate the input, e.g. validate if the component exists, or application exists, etc. Then we should execute the program.

It would be worthwhile to refactor code such as to accommodate an interface that helps us with this.

Something like -
```golang
func (c *command) validate(comp component, app application) error {
  if !comp.Exists() {
    return err
  }
  if !app.Exists() {
    return err
  }
  return nil
}

func main() {
  c := command{
  action: "create",
  }

  checkError(c.valdate())
  c.execute()
}
```

**Comment by cdrage** [comment]
@kadel I think we should cose this for now. We have enough validation within the commands already!
