### ISSUE TITLE
Implement `background` flags from devfile v2 spec 

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#3580]
devfile/kubernetes-api#64

Let's implement support for `background` field as defined in the above issue

/triage needs-information

**Comment by adisky** [comment]
posting my question here, we could easily distinguish a command has to be run in foreground/background with
`kind`
kind: `build` `test`  : run in foreground
kind: `run` `debug` : run in background.
so i am not clear with the purpose of background flag.

**Comment by dharmit** [comment]
@kadel is this still relevant?

**Comment by kadel** [comment]
`background` was eventually implemented as `hotReloadCapable` flag for `command` components, and its support has already been added to do
/close
