### ISSUE TITLE
Unit tests for Operator Hub integration

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/odo#3605]
We need more unit tests coverage for Operator Hub integration. At the time of opening this issue, the unit test coverage for `pkg/kclient/operators.go` is nil.

_Originally posted by @girishramnani in https://github.com/openshift/odo/pull/3564/files#r455591391_

/area service-operators
/area testing

**Comment by dharmit** [comment]
As far as I understand, I need to come up with a simple Operator to write the unit tests. I've tried doing so using [operator-sdk](https://docs.openshift.com/container-platform/4.5/operators/operator_sdk/osdk-getting-started.html#building-memcached-operator-using-osdk_osdk-getting-started) but it didn't work out. And due to shortage of time, I've not spent more time learning about it.

If there's another approach to do it, I'd be glad to be corrected.

**Comment by dharmit** [comment]
Very relevant. More unit tests needed for overall service package. We should ideally be working on this along with #4242.

/lifecycle frozen

**Comment by kadel** [comment]
operator hub integration is going to be reworked in v3 together with testing
Pclo
