### ISSUE TITLE
Logging should be using `log` not fmt.Println

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#364]
Logging should be using INFO  / WARN / ERROR from the log package rather than using `fmt.Println` for all output.

This cleans up the UX / UI as well as makes logging uniform throughout the code (we use log for debug, but for warnings and normal output we use `fmt.Println`

**Comment by kadel** [comment]
I'm not sure about this. What is wrong with using `Println`?

**Comment by cdrage** [comment]
Nothing wrong with using Prinln for communicating (better than INFO being everywhere), it's more for debug messages as well as warning messages and errors that should be outputted via `logrus` or `log`.

**Comment by kadel** [comment]
One more thing. Is it possible to modify logrus output? 
I don't that showing `ERR[0000]` is good UX.

**Comment by cdrage** [comment]
@kadel I've already removed the timestamps so that it only shows ERR, however, yeah, we can change it to "ERROR" instead.

**Comment by cdrage** [comment]
Going to close this for now (see my comment here: https://github.com/redhat-developer/odo/pull/365) there's no point switching to a different logging system until we stop developing / moving so fast.
