### ISSUE TITLE
Switching to a non-existing project

### ISSUE THREAD

**Issue by mik-dass** [redhat-developer/odo#373]
[mdas@localhost odo]$ ./odo project list
     ACTIVE   NAME
              blah-project
              myproject
       *      reed
     [mdas@localhost odo]$ ./odo project set nodejs 
     Now using project : nodejs

Without creating currently we can switch to a non-existing project

**Comment by kadel** [comment]
the same is true for component https://github.com/redhat-developer/odo/issues/127

**Comment by containscafeine** [comment]
Closed in #384
