### ISSUE TITLE
Unable to list devfile components in catalog if no Kube config exists

### ISSUE THREAD

**Issue by johnmcollier** [redhat-developer/odo#3779]
I downloaded the alpha-2 (note this affects master too) release of odo on a fresh VM with no Kube config downloaded yet, but hit errors telling me to log in when I tried to list the devfiles in the catalog. I was able to reproduce on my laptop by moving the `~/.kube` folder and running `odo catalog list components`:

```
Johns-MacBook-Pro-3:~ johncollier$ mv ~/.kube ~/.kube_backup
Johns-MacBook-Pro-3:~ johncollier$ odo2 catalog list components
 ✗  invalid configuration: no configuration has been provided
Please login to your server: 

odo login https://mycluster.mydomain.com
```

We should be able to list devfiles in the devfile registries without a Kube config, as it doesn't require any connection to a cluster to list them.

(As a side note, we might also want to consider retooling the login message now that odo is kube generic? i.e. maybe change it to say "If targeting an OpenShift cluster, run `odo login ...`, otherwise configure your Kube context ...")

/kind bug
/area devfile

**Comment by dharmit** [comment]
/lifecycle frozen

@kadel would this make sense to have after #4436 goes in? 
@mik-dass do you think it would be easy for someone to take a cue from the work you have done on #4436? Asking because if that's the case, I'd prefer adding `/good-first-issue` to this.

**Comment by mik-dass** [comment]
> @mik-dass do you think it would be easy for someone to take a cue from the work you have done on #4436? Asking because if that's the case, I'd prefer adding /good-first-issue to this.

Yes, I think it would be easier once #4436 is merged.

**Comment by kadel** [comment]
> @kadel would this make sense to have after #4436 goes in?

yes

**Comment by kadel** [comment]
in odo v3 this command was reworked into `odo registry list` and now it works without cluster
/close
