### ISSUE TITLE
README installation instructions are broken

### ISSUE THREAD

**Issue by ryanj** [redhat-developer/odo#381]
The binary path listed in the README instructions is incorrect:
https://github.com/redhat-developer/odo#installation

Feel free to disregard if a new release of `odo` is due soon, as the README's install URL will likely get patched as a part of that update process.

**Comment by kadel** [comment]
Yep, said this was caused when we renamed the project to ODO.
Release 0.0.4 will be today, it will fix this.

**Comment by kadel** [comment]
fixed in #386
