### ISSUE TITLE
`odo delete` shows unnecessary information

### ISSUE THREAD

**Issue by surajnarwade** [redhat-developer/odo#389]
`odo delete` also shows buildconfig, imagestream and other stuff, which developer will not care

```
odo delete frontend
Are you sure you want to delete frontend from someapp? [y/N] y
buildconfig "frontend" deleted
imagestream "frontend" deleted
deploymentconfig "frontend" deleted
service "frontend" deleted

No default component has been set
```

**Comment by cdrage** [comment]
Shouldn't we have "confirmation" information too within commands?

"Component blahblah has been deleted"

@kadel

**Comment by surajnarwade** [comment]
@cdrage it's already there,

```
Are you sure you want to delete frontend from someapp? [y/N] y
```

**Comment by cdrage** [comment]
@surajnarwade I'm recommending a message *after* it's been deleted (confirmed with the oc command that's being used)

**Comment by surajnarwade** [comment]
@cdrage I have added the `information` part in PR, please check #390
