### ISSUE TITLE
Update release script?

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#392]
Found a few things missing on the release page:

- md5 hash
- installation instructions
- generated CHANGELOG using https://github.com/github-changelog-generator/github-changelog-generator)

Should we convert one of our previous projects release scripts (kedge/kompose) for `odo`?

**Comment by kadel** [comment]
Installation instructions are in README.md

We are doing a poor job in naming our PRs and Issues. If you try to generate changelog from that, it gets messy :-(  If we would like to generate some useful changelog we have to get better in describing and labeling PRs. But currently, we can't even properly label Issues :-(

Building release artifacts are already fully automated.
All you have to do is run `script/bump-version.sh` and create a new tag and add changelog. Everything else is handled automatically https://github.com/redhat-developer/odo/blob/master/docs/contributing.md#making-a-release

**Comment by cdrage** [comment]
@kadel Installation instructions on the release page :+1: 

Okay, no worries. I was looking at automating the PR creation too (going through and updating versioning as well) as well as tagging / releasing similar to what we had in other projects instead of having to do the PR manually!

But let's do this as super low-priority? I like how we have the bot to create the binaries and all.
