### ISSUE TITLE
Nit: flag matching should look at entire flag, not HasPrefix

### ISSUE THREAD

**Issue by deboer-tim** [redhat-developer/odo#4037]
/kind bug

## What versions of software are you using?

**Operating System:**
Mac OS Catalina

**Output of `odo version`:**
odo v2.0.0 (6fbb9d9bf)

## How did you run odo exactly?
Ok, this is a nit :) . I wanted to confirm I had installed v2 correctly, so I automatically typed "odo -version" (some other clis I have use the single - approach).

## Actual behavior
 ✗  invalid argument "ersion" for "-v, --v" flag: strconv.ParseInt: parsing "ersion": invalid syntax

## Expected behavior
 ✗  unknown flag: -version
or
 ✗  Invalid command - see available commands/subcommands above

**Comment by girishramnani** [comment]
we do provide `odo version` not even `--version` or `-version`.

**Comment by deboer-tim** [comment]
Yes, I know and figured it out. Some other tools use -version so I did that out of habit, and the output is just odd - it should say something like 'invalid command' instead of the current error.

**Comment by kadel** [comment]
I'm afraid this is "normal" behavior for the cobra library we are using for cli handling. 

even `kubectl` has the same behavior

```
$ kubectl -version
error: invalid argument "ersion" for "-v, --v" flag: strconv.ParseInt: parsing "ersion": invalid syntax
See 'kubectl --help' for usage.
```
