### ISSUE TITLE
Push appears to be hung, need some indication it is trying

### ISSUE THREAD

**Issue by deboer-tim** [redhat-developer/odo#4051]
/kind bug

## What versions of software are you using?

**Operating System:**
macOS Catalina

**Output of `odo version`:**
odo v2.0.0 (6fbb9d9bf)

## How did you run odo exactly?
I created a Spring component and tried to push it to a CRC instance that was short on memory. It failed the first time, so after adjusting memory I tried again:
```
>odo push

Validation
 ✓  Validating the devfile [176418ns]

Creating Kubernetes resources for component spring
 ✗  Waiting for component to start [5m]
 ✗  Failed to start component with name spring. Error: Failed to create the component: error while waiting for deployment rollout: timeout while waiting for spring deployment roll out
```
I increased CRC memory here, then tried again (below).

## Actual behavior
```
>odo push
--- Four minute 'hang' before any output ---
 ✗  Failed to start component with name spring. Error: Failed to create the component: unable to get pod for component spring: error while waiting for pod component=spring: waited 4m0s but couldn't find running pod matching selector: 'component=spring'
```

## Expected behavior
Because there was no command line output for 4 minutes, I thought odo had hung. Suggestion: odo push should always output at least one line before any 'remote' or possibly delayed operation.

e.g. even if it output
```
>odo push
Creating Kubernetes resources for component spring
```
I would likely know that it is trying to do something with the cluster and not 'it hung immediately'.

**Comment by kadel** [comment]
Closing this one, I assume this is no longer an issue in odo v3 
/close
