### ISSUE TITLE
Improve output for slow/hung connections

### ISSUE THREAD

**Issue by deboer-tim** [redhat-developer/odo#4079]
/kind feature

## Which functionality do you think we should add?
When I use any cli I expect it to have output within a short time after launching (lets say 10s) and have periodic output if it is going to take a really long time. Otherwise, I assume it has hung and kill it.

To avoid this, any command like odo that uses a network connection should ensure three things:

1. Output so that the user knows it is waiting on the network/remote system, within the first 10s.
2. Periodic output so that the user knows it's still waiting/doing something.
3. A reasonable timeout.

Note that there are multiple ways to do this, e.g.:

- If the timeout is under 10s, nothing else needs to change.
- If the timeout is 20s, the command could output a message before connecting and nothing else.
- If the timeout is 20s, the command could be optimistic and not output any initial message, but output something if the command hasn't returned yet after 10s.
- If the timeout is really long, start with either of the previous 2 options, but then periodically output another message.

I know this request is kind of generic, but I've seen problems with several odo commands so IMHO there should be a quick review of most commands. Here are three specific cases where I think changes need to be made:

- 'odo version': There is currently no output when it is trying to connect, and the timeout is way too long. My preference would be to just use a much shorter timeout (e.g. 5-10s), but another option would be to output a message when it is trying to connect or it hasn't responded within 10s so that the user knows what's going on.
- 'odo push': The current message and long timeout is good, but after waiting a minute the user can't tell if it is hung or still doing something. It needs a periodic new message or some indication that it is waiting, e.g. 'Component not started, waiting another 3 minutes', 'Component not started, waiting another 2 minutes'...
- 'odo push': If I get bored and kill the step above and try again, it now goes straight to the connection without any console output. It needs to at least repeat the previous message ('Waiting for component to start'), and once again needs some kind of periodic output (this is covered by bug #4051).

## Why is this needed?
odo is great when you've got a good connection to a stable Kubernetes cluster. However, when the cluster is slow or network is bad, the usability is not good and it looks like a local problem in odo instead of the remote Kubernetes system.

**Comment by kadel** [comment]
I think this has been fixed in all v3. The most problematic command, `odo dev` outputs the header when it is started to indicate that something is happening, and there is a spinner for each phase to show that something is happening. 


There is one bug that is related to this (#6575), but that is limited to macOS and broken podman. 

/close
