### ISSUE TITLE
Warning creating ingress, after I had deleted it

### ISSUE THREAD

**Issue by deboer-tim** [redhat-developer/odo#4108]
/kind bug

## What versions of software are you using?

**Operating System:**
macOS Catalina

**Output of `odo version`:**
odo v2.0.0 (6fbb9d9bf)

## How did you run odo exactly?
I forgot about an old ingress url (created during a previous test against another kube) and did an odo push, so I deleted it and pushed again. It still said it was trying to create it.

## Actual behavior
```sh
deboer-mac:node2 deboer$ odo url list
Found the following URLs for component node2
NAME           STATE      URL                                       PORT     SECURE     KIND
node2-3000     Pushed     http://node2-3000.192.168.64.3.nip.io     3000     false      ingress
deboer-mac:node2 deboer$ odo url delete node2-3000
? Are you sure you want to delete the url node2-3000 Yes
 ✓  URL node2-3000 removed from component node2

To delete the URL on the cluster, please use `odo push`
deboer-mac:node2 deboer$ odo push

...
Creating Kubernetes resources for component node2
 ✓  Waiting for component to start [13s]
 ⚠  Unable to create ingress, missing host information for Endpoint http-3000, please check instructions on URL creation (refer `odo url create --help`)
```
## Expected behavior
I would have expected an error deleting the url or no output, not 'unable to create ingress' when it didn't exist anymore.

**Comment by deboer-tim** [comment]
Thinking about it, maybe this is just the standard warning that it couldn't determine the host and couldn't auto-create an ingress? Still, it was confusing to me that I got the same message when I had a url created with an incorrect host and when I had deleted it and didn't have one.

**Comment by kadel** [comment]
in v3 this is not going to be a problem anymore, as odo is not going to automatically create Ingress or Routes. Odo will use port forwarding this won't be a problem there.
