### ISSUE TITLE
Extra odo ignore (.gitignore) entries created across Windows, non-Windows platforms

### ISSUE THREAD

**Issue by scottkurz** [redhat-developer/odo#4114]
/kind bug

## What versions of software are you using?

**Operating System:**  Win10, Linux

**Output of `odo version`:**  odo v2.0.0 (6fbb9d9bf)

## How did you run odo exactly?

1. Start with **.gitignore** with entry:

     .odo/

2. From Linux, `odo create ... `     (gitignore updated with .odo/env)
3. From Linux, `odo push`           (.gitignore updated with .odo/odo-file-index.json)
4. Commit changes to .gitignore and push
5. From Win10, git clone repo
6.  From Win10, `odo create ... `     (gitignore updated with .odo\env)
7.  From Win10, `odo push `     (gitignore updated with .odo\odo-file-index.json)

## Actual behavior

In the above sequence, I started with .odo/ in .gitignore and didn't expect to see any changes.   Instead I get all the changes I have to commit or undo in my .gitignore file which should be under my control, not odo's.

## Expected behavior

Expect odo doesn't need to update .gitignore; it's already covered.

**Comment by girishramnani** [comment]
I can take a look at this

**Comment by scottkurz** [comment]
/remove-lifecycle rotten

@girishramnani  @kadel  this is perhaps a minor annoyance but IMHO any tool that pollutes your git repo with unexpected changes can be pretty annoying.   

Couldn't we just have odo write:   

> .odo/    
OR
> /.odo/     # if we want to leave things open for further levels of nesting

Is there any content within .odo/  that we're trying NOT to ignore?  
https://github.com/openshift/odo/issues/3386

If I take a project with an existing .gitignore or .odoignore and bring it to Windows, and do a create/push, I'm going to end up with these extra entries:

> .odo\env
> .odo\odo-file-index.json

even if I already have 
> .odo/    
and/or 
> .odo/env
> .odo/odo-file-index.json

Are we trying to differentiate between content odo puts in .odo vs. the user?

**Comment by scottkurz** [comment]
/remove-lifecycle stale

Still noting in odo v2.2.3

**Comment by scottkurz** [comment]
@dharmit @girishramnani  - do you think we could just ignore everything in .odo/  or do you think it's safer to ignore file-by-file ?

**Comment by kadel** [comment]
> @dharmit @girishramnani - do you think we could just ignore everything in .odo/ or do you think it's safer to ignore file-by-file ?

Not sure why we started adding records to `.gitignore` on per-file basis.
It should be completely ok to add a whole `.odo` to `.gitignore`

**Comment by dharmit** [comment]
/triage needs-information

Adding needs-info so that someone takes time reproducing the issue and figuring where we need to make changes.
