### ISSUE TITLE
Cannot delete devfile component from cluster without context folder

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/odo#4135]
/kind bug

## What versions of software are you using?

**Operating System:** Linux

**Output of `odo version`:** 2.0.0

## How did you run odo exactly?
Current project is `p1`

```
~/component$ odo create nodejs --app app1
Validation
 ✓  Checking devfile existence [27213ns]
 ✓  Checking devfile compatibility [37570ns]
 ✓  Creating a devfile component from registry: DefaultDevfileRegistry [40669ns]
 ✓  Validating devfile component [81577ns]

Please use `odo push` command to create the component with source deployed

~/component$ odo push

Validation
 ✓  Validating the devfile [25241ns]

Creating Kubernetes resources for component nodejs
 ✓  Waiting for component to start [6s]

Applying URL changes
 ✓  URL http-3000: http://http-3000-nodejs-p4.apps-crc.testing/ created

Syncing to component nodejs
 ✓  Checking files for pushing [879948ns]
 ✓  Syncing files to the component [455ms]

Executing devfile commands for component nodejs
 ✓  Executing install command "npm install" [4s]
 ✓  Executing run command "npm start" [1s]

Pushing devfile component nodejs
 ✓  Changes successfully pushed to component
```

## Actual behavior
```
~/component$ cd ..

~$ odo delete nodejs --project p1 --app app1
✗  Component nodejs does not exist on the cluster
```

## Expected behavior

```
~$ odo delete nodejs --project p1 --app app1
? Are you sure you want to delete the devfile component: nodejs? Yes

Gathering information for component nodejs
 ✓  Checking status for component [19ms]

Deleting component nodejs
 ✓  Deleting Kubernetes resources for component [12ms]
 ✓  Successfully deleted component
~$
```

**Comment by sbouchet** [comment]
Still present in odo 2.0.3

**Comment by dharmit** [comment]
This bug still exists.

Stepping through the code, I found that the `Exists` function searches only for a `DeploymentConfig` (s2i type components) but not for `Deployment` (devfile components): https://github.com/openshift/odo/blob/b9a3b1463d74f29088aa5625bf01b17fd7ffcbb4/pkg/component/component.go#L1448-L1456

I think, searching the cluster for `Deployment` should do the trick. We already had a function `GetDeploymentByName` in the `kclient` package in the past but, it has been removed.

So the scope of this issue should be:
* add the `GetComponentByName` function that was removed by some commit.
* if that doesn't suffice, look for what's missing.

**Comment by dharmit** [comment]
@kadel Like you mentioned last week, this is indeed not as simple as I thought it was. It seems to me that at the time of devfile integration, we missed adding support for this scenario.

From odo's perspective, this is more like a feature than a bug. While from users' perspective, this is a bug that's breaking backward compatibility.

**Comment by dharmit** [comment]
A few things to note about this problem.

1. Right now, odo relies on the existence of `devfile.yaml` to deduce that the underlying component is a devfile component. If it can't find the file in `pwd` (that is, from the location where the `odo delete` is executed), odo assumes that it's an s2i component and thus runs the set of actions required to delete the s2i component.

    If we remove the check for existence of devfile at below places, we hit the Deployment Config vs. Deployment problem (specifically in the `Validate` function) that I have mentioned in https://github.com/openshift/odo/issues/4135#issuecomment-777267393: https://github.com/openshift/odo/blob/2180507a4850dfac98559cc94aa9d55441007c0b/pkg/odo/cli/component/delete.go#L82 https://github.com/openshift/odo/blob/2180507a4850dfac98559cc94aa9d55441007c0b/pkg/odo/cli/component/delete.go#L107 https://github.com/openshift/odo/blob/2180507a4850dfac98559cc94aa9d55441007c0b/pkg/odo/cli/component/delete.go#L134

    If we remove the `util.CheckPathExists` call, how can we identify if the user asked to delete an s2i component or a devfile component? One way I can think of deducing this is based on Deployment Config vs. Deployment. Meaning, if the cluster has a DC of the name provided by the user, they're requesting to delete the s2i component whereas if the cluster has a Deployment of that name, it's a devfile component. 

    Is this check relevant when #4281 is fixed? Considering the number of surprises we're hitting on it, is it worth waiting for #4281 to get fixed? I think we shouldn't wait for it and just fix the problem at hands.
    
1. Look at this bug https://github.com/openshift/odo/issues/4451. Should we not have a validation that prohibits the user from passing `-a`/`--all` flag when they're trying to delete a component from a directory other than the component's own directory? I think yes. So, a user can't pass `--all` flag if they have passed `--app` and `--project`. Also, `--app` and `--project` both must be provided to delete a component just by it's name, right?

1. For a devfile component that is linked with an Operator backed service, when a user does `odo delete`, odo deletes the secret created at the time of doing `odo link`. odo also deletes the link information from `.odo/env/env.yaml`. We need to think more about this situation from the point of view of:
    2. odo operates with the approach of deleting all resources that belong to a component. Should a service be considered as something owned by a component? What if other component is also linked to it?
    3. How would things look like when we have service information getting stored in `devfile.yaml`? A link is essentially an instance of SBO and hence we must store it in `devfile.yaml`.
    I'm not spending too much time thinking about this one but, there might be scenarios we want to consider.

ping @kadel @mik-dass @girishramnani @valaparthvi

**Comment by kadel** [comment]
> 1. Is this check relevant when #4281 is fixed? Considering the number of surprises we're hitting on it, is it worth waiting for #4281 to get fixed? I think we shouldn't wait for it and just fix the problem at hands.

no, we should not wait for it. Even after #4281 us implemented you will have to deal with DeploymentConfig. That PR will make it impossible to create new LocalConfig based components, but users might still have an existing LocalConfig s2i components that they did not converted to devfiles.

**Comment by kadel** [comment]
> 1. If we remove the `util.CheckPathExists` call, how can we identify if the user asked to delete an s2i component or a devfile component? One way I can think of deducing this is based on Deployment Config vs. Deployment. Meaning, if the cluster has a DC of the name provided by the user, they're requesting to delete the s2i component whereas if the cluster has a Deployment of that name, it's a devfile component.

This could work.

**Comment by valaparthvi** [comment]
I was debugging it and at first look it seemed simple to me, if the right devfile is not being deleted, it must not be taking in account the right path.
[pkg/odo/cli/component/delete.go::DevFileRun](https://github.com/openshift/odo/blob/master/pkg/odo/cli/component/delete.go#L273), while performing the deletion, it doesn't really take context into account, 
```
		if do.componentForceDeleteFlag {
			if !util.CheckPathExists(DevfilePath) {      <-------
				return fmt.Errorf("devfile.yaml does not exist in the current directory")
			}
			if !do.EnvSpecificInfo.IsUserCreatedDevfile() {
				err = util.DeletePath(DevfilePath)       <--------
				if err != nil {
					return err
				}

				log.Successf("Successfully deleted devfile.yaml file")

			} else {
				log.Info("Didn't delete the devfile as it was user provided")
			}

		}
```
If we were to change `DevfilePath` to `do.devfilePath` it seems to delete the right devfile. 
I checked with `odo delete -f --all --context <context_folder>`.
I am not sure if this answers [point 3](https://github.com/openshift/odo/issues/4135#issuecomment-783174485) that you made here though.

**Comment by valaparthvi** [comment]
My bad, the problem in account still exists, it still has problem checking the status of component.

**Comment by valaparthvi** [comment]
It seems to me that if we implement something like `odo describe <component_name> --app <app_name> --project <project_name>` for the delete command it would at least fix the problem of component deletion from a non-component dir, if not devfiles and odo env.
For `--all` flag and all the other delete related flags, we could discuss all the valid and invalid commands like @kadel mentioned in #4451. I also think that to prevent further corner cases like these, we could write a bunch of integration tests for delete option, follow a test-driven development approach.

**Comment by dharmit** [comment]
There was no tangible progress on this one in the last sprint. What I understood is that I grossly underestimated the scope of this problem. Things that need to be done:

- [ ] Need to remove the usage of `util.CheckPathExists(DevfilePath)` from all places in `odo delete` code. This function is currently used to determine if we're using a devfile component or s2i component.
Instead, we will rely on `Deployment` vs. DeploymentConfig` to determine if underlying component is devfile or s2i. (https://github.com/openshift/odo/issues/4135#issuecomment-783432330)
- [ ] Currently, thanks to `ownerReferences`, the link (a `ServiceBinding`) gets deleted when a devfile component is deleted. This also deletes link information from `.odo/env/env.yaml`. But when `odo delete` is executed without `context` information, we can't delete the link info from `env.yaml`. This would lead to a situation where if the user does `odo push` for the component after doing `odo delete` as required by this issue, odo won't be able to find the link (a `ServiceBinding`) and `odo push` fails with:
    ```
     odo push
    
    Validation
     ✓  Validating the devfile [35357ns]
    
    Creating Kubernetes resources for component nodejs
     ✗  Waiting for component to start [5m] [WARNING x7: Failed]
     ✗  Failed to start component with name nodejs. Error: Failed to create the component: error while waiting for deployment rollout: timeout while waiting for nodejs deployment roll out\nFor more information to help determine the cause of the error, re-run with '-v'.
    See below for a list of failed events that occured more than 5 times during deployment:
    
     NAME                                      COUNT  REASON  MESSAGE                        
    
     nodejs-8485c6fb59-xvsmk.166924a4336b72e9  7      Failed  Error: secret                  
                                                              "nodejs-etcdcluster-myetcd"    
                                                              not found                      
    ```

**Comment by dgolovin** [comment]
It is still an issue in 2.2.1 and that make impossible to delete component pushed to cluster without context.
