### ISSUE TITLE
Modify `component.Exists` function

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#416]
Using this issue so I can track a few things that I've been coming across within the code.

The component.Exists function should have applicationName first and then componentName:

```sh
exists, err := component.Exists(client, componentName, applicationName, projectName)
```

Should actually be:

```sh
exists, err := component.Exists(client, applicationName, componentName, projectName)
```

since all other odo functions are in that order (app name and then component name)

**Comment by kadel** [comment]
almost every function in `component` actually follows the rule where the component name is first, and the application name is after that.

```
func Delete(client *occlient.Client, name string, applicationName string, projectName string) 
func GetComponentDesc(client *occlient.Client, cmpnt string, currentApplication string, currentProject string)
func GetComponentType(client *occlient.Client, componentName string, applicationName string, projectName string)
func SetCurrent(client *occlient.Client, name string, applicationName string, projectName string)

```

**Comment by cdrage** [comment]
@kadel Heck, you're right. 

Should we go with component name first then application name then?

**Comment by kadel** [comment]
> Should we go with the component name first then application name then?

yes. I would standardized on the following order: component, application, project.

**Comment by kadel** [comment]
Is this issue still valid? Do we need to fix it this somewhere? Or we can close it?

**Comment by kadel** [comment]
ping @cdrage

**Comment by cdrage** [comment]
We can close this, thanks!
