### ISSUE TITLE
Example in `odo service create -h` doesn't work

### ISSUE THREAD

**Issue by jdob** [redhat-developer/odo#4172]
/kind bug

## What versions of software are you using?

**Operating System:**
Fedora

**Output of `odo version`:**
odo v2.0.1 (a9fff7da4)

Server: https://api.cluster-rdu-d666.rdu-d666.example.opentlc.com:6443
Kubernetes: v1.17.1+3f6f40d

## How did you run odo exactly?
odo service create -h  

That shows this:

```
Examples:
  # Create new postgresql service from service catalog using dev plan and name my-postgresql-db.
  odo service create dh-postgresql-apb my-postgresql-db --plan dev -p postgresql_user=luke -p postgresql_password=secret
```

But when I run it, I get:

```
 ✗  invalid service name, use the format <operator-type>/<crd-name>
```

More to the point, I'm unable to create _any_ service catalog backed service, all showing me the message about the format requiring operator-type/crd-name, which isn't relevant in the service catalog case.

**Comment by dharmit** [comment]
This would be handled as a part of #4242.

**Comment by valaparthvi** [comment]
@dharmit is it okay to add the lifecycle/active label here? I see you have been working on the related issue #4242, so this issue is definitely not stale.

**Comment by dharmit** [comment]
@jdob I understand that this issue is for cli help message. So my response is tangential. Can you see if a recently added piece of documentation helps you with java+database example - https://odo.dev/docs/deploying-java-app-with-database/?

@valaparthvi it's

/lifecycle frozen
