### ISSUE TITLE
initcontainer runs with root id

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#4174]
/kind bug

## What versions of software are you using?

**Operating System:** MacOS

**Output of `odo version`:** 2.0.1

## How did you run odo exactly?
Tried to run odo with a Kubernetes cluster not OpenShift

## Actual behavior
Failed to run as initContainer was configured to not runAsRoot by the PSPs in my system but the user in the image is root, which is a bad practice.

## Expected behavior
That the deployment started succesfully.

**Comment by dharmit** [comment]
> How did you run odo exactly?
> 
> Tried to run odo with a Kubernetes cluster not OpenShift

Can you please share a command that you tried but failed to execute?


> Actual behavior
> 
> Failed to run as initContainer was configured to not runAsRoot by the PSPs in my system but the user in the image is root,

Might be a silly question but what's a PSP? What kind of setup are you using?

**Comment by jorgemoralespou** [comment]
This was more than 2 months ago so I can not reproduce it anymore since I don't use odo anymore.

The command I tried probably was:

`odo create java ... && odo push`

A PSP is a PodSecurityPolicy. It's kind of an SCC but from Kubernetes (https://kubernetes.io/docs/concepts/policy/pod-security-policy/) I was using a Kubernetes cluster provisioned on a public cloud but not a managed Kubernetes.

PSPs are not enabled by default on minikube and on many other Kubernetes clusters by default although it's a recommendation to prevent images to run as root, the same way OpenShift provides SCCs.

**Comment by kadel** [comment]
/close
odo v3 no longer users init container
