### ISSUE TITLE
functions in converter are currently relying on schema definition

### ISSUE THREAD

**Issue by yangcao77** [redhat-developer/odo#4175]
Functions in convert.go, which being called when converting s2i components to devfile components are currently replying on devfile 2.0 schema definition, example:
https://github.com/openshift/odo/blob/6a33350ad9baffef3a47b916872b8b718a1e467d/pkg/odo/cli/utils/convert.go#L275-L301

https://github.com/devfile/api/issues/200 I have created this issue in devfile common library to provide consumers a way to generate devfile objects based on schema version wanted with given info. 

After the feature has been implemented, odo should make use of functions in common library, so that the converter code will be independent with schema definition

**Comment by kadel** [comment]
this code was removed
/close
