### ISSUE TITLE
build log streaming doesn't work in Katacoda

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#419]
In katacoda the build output logs are shown at once after it finishes instead of streaming it line by line.

This has big impact on user experience.

`oc logs -f` works ok and it actually streams the progress, it doesn't look like problem on katacoda side

**Comment by mik-dass** [comment]
@kadel I had this problem, but since the new changes in the component create code base, it seems to be gone for me

**Comment by kadel** [comment]
In Katacoda? For me streaming still doesn't work there.

**Comment by mik-dass** [comment]
@kadel I meant on my local machine it wasn't working earlier but now it works

**Comment by kadel** [comment]
> @kadel That's strange because for me it works now

on Katacoda?

**Comment by kadel** [comment]
Ahh, you are right, that is strange.

**Comment by marekjelen** [comment]
it's better, we are on the right path 😃 

When I do 

```
$ odo push
```

First I see this line almost instantly

```
Pushing changes to component: frontend
```

then with short delay the next line

```
Receiving source from STDIN as archive ...
```

so far, so good, but after that I do get the build log in a batch, it's not streamed

```
---> Installing application source...
=> sourcing 20-copy-config.sh ...
---> 11:35:00     Processing additional arbitrary httpd configuration provided by s2i ...
=> sourcing 00-documentroot.conf ...
=> sourcing 50-mpm-tuning.conf ...
=> sourcing 40-ssl-certs.sh ...
```

then the container push seems to be streaming

```
Pushing image 172.30.80.245:5000/myproject/frontend:latest ...
Pushed 0/10 layers, 3% complete
Pushed 1/10 layers, 11% complete
Pushed 2/10 layers, 21% complete
Pushed 3/10 layers, 31% complete
Pushed 4/10 layers, 40% complete
Pushed 5/10 layers, 51% complete
Pushed 6/10 layers, 61% complete
Pushed 7/10 layers, 75% complete
Pushed 8/10 layers, 87% complete
Pushed 8/10 layers, 99% complete
Pushed 9/10 layers, 100% complete
Pushed 10/10 layers, 100% complete
Push successful
```

then there is a short delay and finally see

```
changes successfully pushed to component: frontend
```

**Comment by kadel** [comment]
Marek, it is streamed. There is just a short delay pause after
`Receiving source from STDIN as archive ...`
that is simply because it is receiving and openshift is doesn't show any progress of that.
It looks like Katacoda environment is just a bit slower, so it takes longer than on local.

The following part is also streamed
```
---> Installing application source...
=> sourcing 20-copy-config.sh ...
---> 11:35:00     Processing additional arbitrary httpd configuration provided by s2i ...
=> sourcing 00-documentroot.conf ...
=> sourcing 50-mpm-tuning.conf ...
=> sourcing 40-ssl-certs.sh ...
```
it is just that quick that you don't notice that.

When you look at the build logs in the OpenShift web ui, you see exactly the same behavior. I'm afraid that there is not much that we can do with that.

**Comment by kadel** [comment]
I'm closing, this as streaming logs actually works.
There are just steps that take a bit longer.
