### ISSUE TITLE
odo can't create an Operator backed service if the Operator is not installed in current working namespace

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/odo#4191]
As mentioned in https://github.com/openshift/odo/pull/4140#discussion_r514244848, once an Operator is installed in one of the namespaces on a k8s cluster, it's possible using `kubectl` to create an Operator backed service in a different namespace. For example:
```sh
# here the etcd Operator is installed in "default" namespace
$ kubectl get csv -A                        
NAMESPACE   NAME                  DISPLAY          VERSION   REPLACES   PHASE
default     etcdoperator.v0.9.4   etcd             0.9.4                Succeeded

# but EtcdCluster has been created in "newproject" namespace
$ kubectl get EtcdCluster -A
NAMESPACE    NAME      AGE
newproject   example   5m13s
```
In this case, however, I was working as the same user that installed the Operator in `default` namespace. As a different user and with RBAC policies, it might be the case that another user can't create an Operator backed service in their namespace of their choice.

What should odo do in this situation? Should odo support creation of Operator backed service in the current working namespace if the Operator was installed in a different namespace?

/area service-operators
/kind discussion

**Comment by kadel** [comment]
no longer valid in v3

/close
