### ISSUE TITLE
odo url list shouldn't crop url names

### ISSUE THREAD

**Issue by deboer-tim** [redhat-developer/odo#4218]
/kind bug

## What versions of software are you using?

**Operating System:**
macOS Catalina

**Output of `odo version`:**
odo v2.0.0 (6fbb9d9bf)

## How did you run odo exactly?
```
deboer$ odo url create --host myhost
 ✓  URL java-[quarkus-80](https://issues.redhat.com/browse/quarkus-80)80 created for component: java-quarkus

To apply the URL configuration changes, please use `odo push`
deboer$ odo url list
Found the following URLs for component java-quarkus
NAME                  STATE          URL                                 PORT     SECURE     KIND
java-[quarkus-80](https://issues.redhat.com/browse/quarkus-80)80     Not Pushed     http://java-[quarkus-80](https://issues.redhat.com/browse/quarkus-80)80.myhost     8080     false      ingress
There are local changes. Please run 'odo push'.
deboer$ odo push
Validation
 ✓  ...
------ came back on a different day ------
deboer$ odo url list
Found the following URLs for component java-quarkus
NAME                STATE      URL                               PORT     SECURE     KIND
java-[quarkus-80](https://issues.redhat.com/browse/quarkus-80)     Pushed     http://java-[quarkus-80](https://issues.redhat.com/browse/quarkus-80).myhost     8080     false      ingress
deboer$ odo url delete java-[quarkus-80](https://issues.redhat.com/browse/quarkus-80)
? Are you sure you want to delete the url java-[quarkus-80](https://issues.redhat.com/browse/quarkus-80) Yes
 ✗  the URL java-[quarkus-80](https://issues.redhat.com/browse/quarkus-80) does not exist
deboer$ odo url delete java-[quarkus-80](https://issues.redhat.com/browse/quarkus-80)80
? Are you sure you want to delete the url java-[quarkus-80](https://issues.redhat.com/browse/quarkus-80)80 Yes
 ✓  URL java-[quarkus-80](https://issues.redhat.com/browse/quarkus-80)80 removed from component java-quarkus
```

## Actual behavior
Note the different url names above (80 vs 8080). After I've pushed the app, the url name that shows is shortened and missing the last two characters (80). If you try to do anything with it (with an incorrectly shortened name) it doesn't work.

In my case I was coming back to an app that had been pushed previously and I didn't remember that the url name ended in 8080. It took a bit to realize that the name was cropped, and then I had to guess the final characters.

## Expected behavior
Any fix that would mean by default that I don't need to understand this problem and guess what the full url name is. e.g. a shorter default url name, not cropping the names, or treating names on the cli as if they ended in wildcards (i.e. "odo url delete java-" would be treated like "java-q*").

**Comment by deboer-tim** [comment]
openshift-ci-robot keeps editing and adding weird urls to the description above - look at the previous edit if it's confusing.

**Comment by kadel** [comment]
There are no URLs in odo v3. In v3, port-forwarding is used instead of Routes/Ingress. This avoids all issues around url names or hostnames 
/close
