### ISSUE TITLE
odo link fails with devfile component

### ISSUE THREAD

**Issue by sbouchet** [redhat-developer/odo#4233]
/kind bug

## What versions of software are you using?

**Operating System: RHEL**

**Output of `odo version`: 
odo v2.0.0 (6fbb9d9bf)

Server: https://192.168.42.158:8443 ( minishift OC 3.11 )
Kubernetes: v1.11.0+d4cacc0
**

## How did you run odo exactly?
odo link fails to link a service with a devfile component.
i created a simple devfile spring component and a jenkins service and want to link both.

## Actual behavior
actual state of component/services in the cluster
```
sbouchet@sbouchet:spring-petclinic [master]$ /home/sbouchet/.odo/cache/2.0.0/odo describe --app app
Component Name: spring
Type: java-springboot
Environment Variables:
 · PROJECTS_ROOT=/projects
 · DEBUG_PORT=5858
URLs:
 · http://8080-tcp-spring-myproject.192.168.42.158.nip.io exposed via 8080
sbouchet@sbouchet:spring-petclinic [master]$ /home/sbouchet/.odo/cache/2.0.0/odo service list --app app
NAME     TYPE                  PLAN        STATUS
j2       jenkins-ephemeral     default     ProvisionedAndBound
```
link trials
```
sbouchet@sbouchet:spring-petclinic [master]$ /home/sbouchet/.odo/cache/2.0.0/odo link j2
 ✗  no Deployment Config was found for the selector: app.kubernetes.io/part-of=app,app.kubernetes.io/instance=spring
sbouchet@sbouchet:spring-petclinic [master]$ /home/sbouchet/.odo/cache/2.0.0/odo link j2 --component spring
 ✗  Component spring does not exist in application app
```

## Expected behavior
link should work as expected

## Any logs, error output, etc?
may be related to #4136  ? as I only have a devfile component in the application..

**Comment by dharmit** [comment]
Can't move this before addressing #4242 because the code is tonnes of `if..else` blocks to differentiate between Service Catalog, Operator Hub, s2i and Devfile. It's a maintenance mess as well development mess currently. :confused:

**Comment by sbouchet** [comment]
CC @dgolovin

**Comment by kadel** [comment]
there is no `odo link` in odo v3
/close
