### ISSUE TITLE
Refactor tests so that odo CI doesn't fail when devfiles or example repos are updated

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/odo#4239]
odo CI has broken multiple times when some change was made in devfile or the code of example repositories. Two such examples are:

1. #3318
1. #4238 

At one point we started working on addressing this in #3752 but closed it since it wasn't a small task. We never managed to look at it again.

This needs to be addressed so that odo CI is not in a sorry state because of changes happening in places out of odo repo. We could either make our integration tests smarter or rely more on unit tests wherever possible.

/kind discussion
/kind failing-test
/area testing
/priority high

Setting high priority because we've hit this multiple times already.

## Proposed solution:
We depend on other repos for some integration tests, it is not recommended to create a local server or replica as those could get out of sync.
Proposed solution is to parse the content of the target repo (if not forbidden) to always get the latest patterns to be used. For example, for the case of devfile registry supported components we can parse https://github.com/odo-devfiles/registry/tree/master/devfiles. The directory names provide the devfile specs names to be used. 
By doing this we can reduce the number of test scripts as we iterate through the list of devfile specs. Furthermore, the script will automatically include any newly added specs

**Comment by dharmit** [comment]
https://github.com/openshift/odo/pull/3739

**Comment by rnapoles-rh** [comment]
From research:
Travis is not running on https://github.com/odo-devfiles/registry and therefore any breaking changes will not be caught.
We need to onboard OpenShift CI to move away from travis.
Will need to follow the following to get onboarded:

- https://github.com/openshift/release
- https://docs.ci.openshift.org/docs/how-tos/onboarding-a-new-component/
 then we need to validate any PRs in the registry against odo master

**Comment by rnapoles-rh** [comment]
Removing from sprint 199 for now. I will get back to this once PSI is stable for openshift/odo PRs

**Comment by rm3l** [comment]
This looks very similar to https://github.com/redhat-developer/odo/issues/6138

Closing it in favor of #6138.
