### ISSUE TITLE
Refactor underlying code for "odo service" commands

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/odo#4242]
Currently `odo service` supports two service backends:
1. Service Catalog
1. Operator Hub

Because of the numerous `if..else` blocks and short term thinking we did on this during v2 release, we've accumulated code that's:
1. not easy to read
1. difficult to debug
1. buggy ([list of bugs](https://github.com/openshift/odo/issues?q=is%3Aissue+is%3Aopen+label%3Aarea%2Fservice-operators+label%3Akind%2Fbug))
1. difficult to add features without adding more `if..else` blocks

Besides that, we might plan to add support for other service backends future. Thus, making the code easy to add more pending features w.r.t Operator Hub integration (#2613), and easy to plug that extra backend (if we decide to) is of utmost importance.

### Acceptance Criteria / Related Issues / Dependent Issues
- [x] #3098 
- [ ] #3197
- [ ] #3605
- [x] #3803
- [ ] #4172
- [ ] #4233

/kind code-refactoring
/area service
/area service-operators

**Comment by dharmit** [comment]
Scope of work for refactoring **`odo service create`**:
1. We will decide between using Operator Hub or Service Catalog backend by looking at the arguments passed.
    ```sh
    # below command will assume Operator Hub backend because of a forward slash
    $ odo service create etcdoperator.v0.9.4/EtcdCluster
    
    # below command will assume Service Catalog backend because there's no forward slash
    $ odo service create dh-postgresql-apb --plan dev -p postgresql_user=luke -p postgresql_password=secret -p postgresql_database=my_data -p postgresql_version=9.6 -w
    ```
1. We need an interface that would have methods to create a service.
1. I will be modifying the struct `ServiceCreateOptions` to use this interface. https://github.com/openshift/odo/blob/5544b25ec083506393090faad5b4205126e4f675/pkg/odo/cli/service/create.go#L61-L62 Fields specific to Service Catalog and Operator Hub will be moved to their respective structs and these types will implement the interface we create for `odo service create`. In its simplest form, all the code from `Comlpete`, `Validate` and `Run` functions will be moved to methods of the same name implemented by the two structs.
1. As for the integration tests, the ones written currently should pass without any major modification.
1. As for the unit tests, more of those will be added in this refactor.

**Comment by faysou** [comment]
@dharmit I'm looking forward to be able to add a postgres db with odo for local development in CRC. It seems no service is available when using CRC, except ones added though an operator, but this makes things harder, I've been spending a few hours on adding one of the postgres operators available and making it work in odo but still didn't manage to.

**Comment by dharmit** [comment]
> Acceptance criteria has not been met.
> 
> /reopen
> /lifecycle frozen

This issue was opened as a part of "refactoring" the odo code right after v2 was released. But the time we had taken to "refactor" things didn't go well.

After that, it was decided that we would refactor the code when opening PRs for features/bugs, but won't dedicatedly work on refactoring things. If you look at #4465, it refactors a lot of code of `odo service` commands so that we use Go interfaces instead of `if..else` mess we were stuck with.

I'm removing the lifecycle frozen from this issue, but I'd urge you to close it, as we're not going to work dedicatedly on refactoring things.

/remove-lifecycle frozen
/triage unresolved
