### ISSUE TITLE
containerObject cpuLimit in devfile

### ISSUE THREAD

**Issue by NissesSenap** [redhat-developer/odo#4266]
/kind feature

## Which functionality do you think we should add?

I want to be able to define cpu limits for my devfile

## Why is this needed?

In my namespace I have cpu and memory limits set by default that is kind of low.
It's not a problem on the memory side since I can define memoryLimit: 1512Mi in my devfile as described in: https://odo.dev/file-reference/#containerobject

But I can't set cpuLimit, due to this I have to manage two default limits for my developers. One that is running odo and one that is not using it and I can't set a default limit that is something like 50m because it won't work with odo so it's a bigger risk of over commitment from my odo developers.

**Comment by mik-dass** [comment]
Currently the devfile schema doesn't support cpuLimits. There is a issue about adding additional resources in future https://github.com/devfile/api/issues/131

**Comment by gorkem** [comment]
In an ideal world users should set a proper LimitRange to the namespace that they are working against and odo should inherit those values. However sometimes users does not have that privilege and the default LimitRange may set default values that is not suitable. 
For those cases we should have a configuration on odo that users can set that will work well against the cluster they are working with that will allow them to override the default limits.

**Comment by kadel** [comment]
> In an ideal world users should set a proper LimitRange to the namespace that they are working against and odo should inherit those values.

@gorkem  What do you mean by inherit? Do you mean that if there is for example memory LimitRange min: 1Gi, max: 2Gi on the namespace, odo should try to detect those values and automatically set memory limit within the range? 


I thought that the problem defined in the issue description could be just solved if we have an option to specify cpu limit in Devfile, which we are currently missing.

**Comment by gorkem** [comment]
> @gorkem What do you mean by inherit? Do you mean that if there is for example memory LimitRange min: 1Gi, max: 2Gi on the namespace, odo should try to detect those values and automatically set memory limit within the range?
> 
Correct, bypassing the LimitRange default values which are usually not defined with development activities in mind

> I thought that the problem defined in the issue description could be just solved if we have an option to specify cpu limit in Devfile, which we are currently missing.

It can be done through devfile. I am concerned that the values on devfile will be set without taking cluster configuration into account and may cause the deployment to fail.

**Comment by kadel** [comment]
> It can be done through devfile. I am concerned that the values on devfile will be set without taking cluster configuration into account and may cause the deployment to fail.

@gorkem , I would argue that it is correct to set resource limits without taking the cluster into account. Limits should be set based on the application requirements. Yes, it could lead to a situation where the given devfile can't be deployed to the cluster because it simply can't fit the namespace LimitRange. But I would say this is correct, as in this situation application might not be stable.

**Comment by kadel** [comment]
this has been implemented 
/close
