### ISSUE TITLE
Make "checkConflictingFlags" function part of "Runnable" interface

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/odo#4313]
Currently, `checkConflictingFlags` function is defined in `genericclioptions` package and is called once every time any command is executed. It takes care of ensuring the `--context` flag is not provided with `--app` and/or `--project` flags for any of the command. https://github.com/openshift/odo/blob/7d3341dcdabad37a7efa9a2cf7657fb5841dea54/pkg/odo/genericclioptions/runnable.go#L34-L37

However, there could be cases where we would like to make sure for individual commands that certain conflicting flags are not provided. For example:
* `odo create` cannot be called with both `git` and `binary` flags.
* Even in current implementation, we have `if` block to allow it for `odo create`
* Local implementation for validating conflicting flags for s2i components and devfile components at https://github.com/openshift/odo/blob/802ce80bd120d2bd2be817e5eca0a9081dfadb70/pkg/odo/cli/component/create.go#L289-L299

At the time of writing this, I can only think of above ~two~ three examples, but I feel there would be more such scenarios where doing this at command level would be helpful.

Would it help if we could fine tune this and modify the `Runnable` interface in `genericclioptions` to:
```go
type Runnable interface {
    CheckConflictingFlags(cmd *cobra.Command) error
    Complete(name string, cmd *cobra.Command, args []string) error
    Validate() error
    Run() error
}
```

/kind discussion
/kind code-refactoring

**Comment by girishramnani** [comment]
I would suggest making it more generic - like `PreFlightChecks` because on many occasion we have validations that we want to do even before running the complete function 
e.g.
- checking if the envfile exists without devfile to `force` and override
- we even have validations in complete function because there are some more values derived from them

**Comment by valaparthvi** [comment]
/close
Looks like it is already taken care of.
