### ISSUE TITLE
Automate build and release of "odo-init" image

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/odo#4314]
We need to automate the build and release process for ["odo-init" image](https://github.com/openshift/odo-init-image/).

/area release-eng

**Comment by dharmit** [comment]
@mohammedzee1000 to research this and list down things that need to be done from our side.

/assign @mohammedzee1000

**Comment by mohammedzee1000** [comment]
We need to update the configurations in an internal repo and face down any issues that we face along the way. It is sort of a separate schema in its own right, so the main challenge will be to learn the new config schema and work alongside Red Hay IT

**Comment by dharmit** [comment]
@mohammedzee1000 do we have everything that we need from the IT on this? What are the next steps to automate this?

**Comment by mohammedzee1000** [comment]
No, I have gone through the docs and we already have the repo. I think its time to start writing up the configuration

My goal right now will be to setup the base pipeline. Automated testing will have to be added later as we will have to configure  CPaaS jenkins and PSI jenkins to work together

**Comment by mohammedzee1000** [comment]
This is almost done. Hammering out some chinks. Should be done in 2 more days from today max

**Comment by mohammedzee1000** [comment]
Next release should let us know if pipeline is ready

**Comment by dharmit** [comment]
@mohammedzee1000 what's going on with this one? It's got `triage/needs-information` label - are we still looking for some info?

/remove-lifecycle stale

**Comment by valaparthvi** [comment]
/close
No longer relevant since we've stopped using the init image.
