### ISSUE TITLE
Move odo-init image tests to IBM Cloud

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/odo#4315]
Currently, odo-init image tests are blocked on Travis and it's preventing PRs from getting merged. We need to move these tests to PSI along with moving our integration tests, unit tests and Kubernetes tests on PSI.

/area testing
/area infra

**Comment by anandrkskd** [comment]
scope of this issue can be divided into either or 
If we want to implement test on 3.11 cluster as it is for now on the repo using travis we will need 
Either
- [ ] add odo-init-image in release repo and Create prow job
- [ ] Create sendqueue and exchange (may require to add a secret for amqp server)
- [ ] Create a vm with 3.11 will be similar to #4288 
- [ ] create nodessh file for same
- [ ] Script to execute the test
OR to use 4.x for test
- [ ] Add odo-init-image in release repo and Create prow job
- [ ] Create sendqueue and exchange (may require to add a secret for amqp server)
- [ ] Create a Linux vm and configure it for test and use existing 4.x psi cluster
- [ ] create nodessh file for same
- [ ] Script to execute the test

**Comment by dharmit** [comment]
I'm not sure why we would want to test on 3.11 cluster. Why not test it on latest 4.x cluster?

Also, how were we doing this in the past? Since odo is supposed to work on both 3.x and 4.x, should we run tests on both cluster types?

I really don't mean to overdo this than what's required.

@kadel @mohammedzee1000 wdyt?

**Comment by anandrkskd** [comment]
As per cabal discussion we will use PSI cluster to test on odo-init-image repo. And will use Openshift built-in container image registry to store PR build image and use the built-in container image registry to perform tests.

**Comment by anandrkskd** [comment]
As per Sprint 198 I was able to understand we will require to give permissions to access to use OpenShift image registry to the OpenShift user which is used for CI purposes, I have created Prow configuration for the tests.

To accomplish this task we need write a script that will create a project and push the image on OpenShift internal image registry and then will be used by the tests. For cleanup delete the container image from  cluster's internal registry by deleting
container's image stream.

**Comment by anandrkskd** [comment]
Acceptance Criteria for sprint 199:
- [ ] Setup existing 4.x cluster to use internal registry for tests
- [ ] Create sendqueue and exchange 
- [ ] Configure existing Linux vm for test
- [ ] Create Jenkins Jobs for tests
- [ ] Scripts to execute the test and cleanup

**Comment by dharmit** [comment]
Something more relevant for Sprint 201.

**Comment by anandrkskd** [comment]
If we are thinking to use external registry then,
updated Acceptance Criteria:

- [ ] Create prow job 
- [ ] Scripts build and push init-image to image registry and to execute tests/cleanup

**Comment by dharmit** [comment]
In https://github.com/openshift/odo/issues/4315#issuecomment-796459778, it's mentioned that on a cabal call, we discussed to use OpenShift internal registry to build odo-init image and test it.

I'm not sure why we're proposing the scope for an external registry in https://github.com/openshift/odo/issues/4315#issuecomment-888145926.

I could be missing something.

> * [ ] Scripts build and push init-image to image registry and to execute tests/cleanup

Have you tried building a container image and push it to the OpenShift internal registry? Were you successful? Are the steps documented anywhere? Or do you have a link to OpenShift docs using which you are sure to be able to successfully do it repeatedly? I'm asking all these questions because "Script" can be created only if answer to these questions is yes.

> * [ ]  Create prow job

Isn't this just about creating a Jenkins job using the Jenkins Web UI?

**Comment by anandrkskd** [comment]
> Have you tried building a container image and push it to the OpenShift internal registry? Were you successful? Are the steps documented anywhere? Or do you have a link to OpenShift docs using which you are sure to be able to successfully do it repeatedly? I'm asking all these questions because "Script" can be created only if answer to these questions is yes.

No we were not able to push a container image into OpenShift internal registry. 
I followed these steps [doc1](https://docs.openshift.com/container-platform/4.7/registry/accessing-the-registry.html) & [doc2](https://docs.openshift.com/container-platform/4.7/registry/securing-exposing-registry.html), but was not able to do it .

> Isn't this just about creating a Jenkins job using the Jenkins Web UI?

No, we have to create prow config on release repo to create a job to run the test.

**Comment by kadel** [comment]
> I followed these steps [doc1](https://docs.openshift.com/container-platform/4.7/registry/accessing-the-registry.html) & [doc2](https://docs.openshift.com/container-platform/4.7/registry/securing-exposing-registry.html), but was not able to do it .
> 
> >

what was the problem?

**Comment by dharmit** [comment]
> > Have you tried building a container image and push it to the OpenShift internal registry? Were you successful? Are the steps documented anywhere? Or do you have a link to OpenShift docs using which you are sure to be able to successfully do it repeatedly? I'm asking all these questions because "Script" can be created only if answer to these questions is yes.
> 
> No we were not able to push a container image into OpenShift internal registry.

I don't see a mention of that anywhere on this issue so far. Did you try to raise it as a problem/blocker anywhere? Why not on the GH issue?

**Comment by kadel** [comment]
I've just tried to follow that docs and was able to sucesfully do it:
```
# login as kubeadmin for setup

▶ oc login --token=<redacted> --server=https://api.testocp47.psiodo.net:6443

Logged into "https://api.testocp47.psiodo.net:6443" as "kube:admin" using the token provided.

You have access to 102 projects, the list has been suppressed. You can list all projects with 'oc projects'

▶ oc patch configs.imageregistry.operator.openshift.io/cluster --patch '{"spec":{"defaultRoute":true}}' --type=merge  
config.imageregistry.operator.openshift.io/cluster patched

▶ oc policy add-role-to-user registry-editor tkral
clusterrole.rbac.authorization.k8s.io/registry-editor added: "tkral"

▶ oc policy add-role-to-user registry-viewer tkral
clusterrole.rbac.authorization.k8s.io/registry-viewer added: "tkral"
▶ HOST=$(oc get route default-route -n openshift-image-registry --template='{{ .spec.host }}')

▶ echo $HOST 
default-route-openshift-image-registry.apps.testocp47.psiodo.net

▶ podman pull docker.io/busybox
Trying to pull docker.io/library/busybox:latest...
Getting image source signatures
Copying blob b71f96345d44 done  
Copying config 69593048aa done  
Writing manifest to image destination
Storing signatures
69593048aa3acfee0f75f20b77acb549de2472063053f6730c4091b53f2dfb02

▶ podman tag docker.io/busybox:latest default-route-openshift-image-registry.apps.testocp47.psiodo.net/tkral-test/busybox:latest


Using project "tkral-test".

# login as a normal user 
▶ oc login -u tkral  --server=https://api.testocp47.psiodo.net:6443                                                 

Logged into "https://api.testocp47.psiodo.net:6443" as "tkral" using existing credentials.

You have access to the following projects and can switch between them with 'oc project <projectname>':

    cmd-devfile-app-test96ncp
    cmd-devfile-delete-test97oyx
    cmd-devfile-push-test442yqx
    cmd-devfile-storage-test72dvb
  * tkral-test

Using project "tkral-test".

▶ podman login --tls-verify=false -u tkral -p $(oc whoami -t) default-route-openshift-image-registry.apps.testocp47.psiodo.net
Login Succeeded!

▶ podman push --tls-verify=false default-route-openshift-image-registry.apps.testocp47.psiodo.net/tkral-test/busybox:latest   
Getting image source signatures
Copying blob 5b8c72934dfc done  
Copying config 69593048aa done  
Writing manifest to image destination
Storing signatures



```

**Comment by anandrkskd** [comment]
> I don't see a mention of that anywhere on this issue so far. Did you try to raise it as a problem/blocker anywhere? Why not on the GH issue?

I raised it on a call but I should have mentioned the blockers on the issue and updated it.

**Comment by anandrkskd** [comment]
Acceptance Criteria 

- [ ] Setup existing 4.x cluster to use internal registry for tests in the Linux VM.
- [ ] Scripts to execute the test and cleanup 
- [ ] Create prow job

**Comment by dharmit** [comment]
> Acceptance Criteria
> 
>     * [ ]  Add user developer on 4.x cluster to use internal registry
> 
>     * [ ]  Scripts to execute the test and cleanup
> 
>     * [ ]  Create prow job

Can we do these same steps on IBM Cloud @rnapoles-rh ?

**Comment by dharmit** [comment]
First try to get the entire thing done manually as research and then specify what needs to be done to automate it.

/triage needs-information

**Comment by anandrkskd** [comment]
Steps need to be done 
1. assign role of `registry-editor` and `registry-viewer` to the user and expose the registry using DefaultRoute 
    - Note: need to do only for 1st time 
2. Script to 
    - Login into cluster and podman as user
    - create temporary namespace to store image 
    - build image with tag and push image
    - export image with env var ODO_BOOTSTRAPPER_IMAGE
    - clone odo and run test
    - delete temporary namespace containing image
3. Script to start test from prow side
    - setting env for starting the test and a ci-firewall command starting the test from prow
4. Create job on prow side for test.

**Comment by anandrkskd** [comment]
Closing this as we will be using github-actions for the tests [PR](https://github.com/redhat-developer/odo-init-image/pull/102) 
/close
