### ISSUE TITLE
Add support for customizing the storage class used by odo through the devfile.

### ISSUE THREAD

**Issue by tmicheli** [redhat-developer/odo#4331]
/kind feature

## Which functionality do you think we should add?

Make it possible to configure the storage class that is used to provide persistent storage for containers through odo/devfile.

## Why is this needed?

In some cluster setups the default storage class can not be used to provide persistent storage for containers created through odo. This can have multiple reasons, e.g. the default storage class is not available, or it does not fit the needs.  To enable developers to use different storage classes would enhance the user experience and increase the usability of odo.

**Comment by gorkem** [comment]
Cluster specific information should not be on devfile but odo preferences/config is probably the right place for it.
