### ISSUE TITLE
`odo status` explicitly asks for `--flag` and `-o json` flags even though they are required by default

### ISSUE THREAD

**Issue by valaparthvi** [redhat-developer/odo#4335]
/kind bug

## What versions of software are you using?

**Operating System:** Fedora 32

**Output of `odo version`:**

odo v2.0.3 (9ae754023)

Server: https://192.168.42.152:8443
Kubernetes: v1.11.0+d4cacc0

## How did you run odo exactly?
```
➜  tmp odo status         
 ✗  this command must be called with --follow
➜  tmp odo status --follow
 ✗  this command only supports the '-o json' output format
➜  tmp odo status --follow -o json
{"urlReachable":{"name":"http-3000","url":"http://http-3000-nodejs-myproject.192.168.42.152.nip.io","port":3000,"secure":false,"kind":"route","reachable":true,"timestamp":"1609399191.239415"}}
^C
➜  tmp odo status -o json         
{
	"kind": "Error",
	"apiVersion": "odo.dev/v1alpha1",
	"metadata": {
		"creationTimestamp": null
	},
	"message": "this command must be called with --follow"
}
```

Ignore the _tmp_ in the above block, it just points to the directory I ran the commands from.

## Actual behavior
The command does not run without `--follow` and `-o json` flags, they are required to be passed explicitly. 
Same is the case with `odo component status`.

## Expected behavior
If the flags are required by default, why ask for them explicitly, why not enable them by default?

There is nothing about the flags being mandatory in the help doc either. Even though the example shows the flag, intuitively the flag seem as if they're optional. Excerpt from the help doc -
```
Usage:
  odo status [component_name] [flags]

Examples:
  # Get the status for the nodejs component
  odo status nodejs -o json --follow
```

**Comment by girishramnani** [comment]
I can work on this

**Comment by girishramnani** [comment]
seems like a simple fix, but cli doc change could be interesting

**Comment by kadel** [comment]
> should I also just assume `-o json` is set? I mean that might be unconventional because all other commands need `-o json`

no the only reason why its done like this is that while this was implemented the json output was a priority and there was no need for normal output. 

The correct way how this should be fixed is to implement normal output for this command and make `-o` optional. 
The same for `--follow`. Non follow mode should be implemented and this flag should be made optional.

**Comment by girishramnani** [comment]
now that increases the scope and makes this a feature instead of a bug @kadel

**Comment by girishramnani** [comment]
also can we scope out the work and behavior of
- [X] ~~`odo status --follow -o json`~~
- [ ] `odo status`
- [ ] `odo status --follow`
- [ ] `odo status -o json`

**Comment by kadel** [comment]
> now that increases the scope and makes this a feature instead of a bug @kadel

this was never a bug. It is wrongly labeled

**Comment by valaparthvi** [comment]
Can we mark this for Hacktoberfest? It seems easy enough with some research on our end.
cc: @dharmit @feloy

**Comment by dharmit** [comment]
Yeah, sure. I'm wondering if @girishramnani is still interested in participating in the Hacktoberfest as he said on k8s slack. 😉

**Comment by feloy** [comment]
If we want to implement the non-follow and the plain text output, we will need to define before what are the exact scopes of the commands `odo status`, `odo status --follow` and `odo status -o json`.

**Comment by dharmit** [comment]
We don't want to implement the non-follow or plain text output. This was discussed in https://github.com/openshift/odo/pull/3177#discussion_r427029634. I don't mean that we shouldn't change it. But `odo status` requiring those two flags by default was by design.
