### ISSUE TITLE
Update README -  ODO - OpenShift Do

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#434]
It looks like that consesus on what `odo` means is settled on "openshift do". Lets reflect that i our readme

**Comment by cdrage** [comment]
@kadel Where was the discussion? I quite like "OpenShift Developer Optimization". Will `Odo` still stand for anything?

**Comment by cdrage** [comment]
PR here: https://github.com/redhat-developer/odo/pull/435

**Comment by kadel** [comment]
devtools-deploy mailing list

Odo stands for Openshift DO.

**Comment by cdrage** [comment]
PR: https://github.com/redhat-developer/odo/pull/435 has been merged, so closing this now :+1:
