### ISSUE TITLE
Proposal for Helm integration with odo

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/odo#4368]
Document a proposal for integrating Helm and odo. This is limited to `odo link` command only. This is a part of the epic #4236.

/area linking
/assign @kadel

**Comment by girishramnani** [comment]
Lets keep this on the size for now. We need a fix from SBO side to support helm.

**Comment by dharmit** [comment]
> Lets keep this on the size for now. We need a fix from SBO side to support helm.

"on the size"? What does that mean?

SBO already has support for using it as a library, IIUC. @kadel played with it as well. Or maybe he played with the PR that enables it.

**Comment by kadel** [comment]
/close 
in favor of https://github.com/redhat-developer/odo/issues/4236
