### ISSUE TITLE
odo doesn't honor directory .gitignore entries like `/target`

### ISSUE THREAD

**Issue by scottkurz** [redhat-developer/odo#4389]
/kind bug

## What versions of software are you using?

**Operating System:**  Win 10

**Output of `odo version`:**
odo v2.0.4 (5544b25ec)
Kubernetes: v1.18.3+47c0e71

## How did you run odo exactly?
1. git clone git@github.com:scottkurz/multi-module-devfile.git
2. mvn install    # populate 'target' subdirs on host system
3. odo push -v 7

## Actual behavior

You can see ./war/target* , ./ear/target/*,  ./jar/target/* files get copied into the pod container, both with the odo verbose logging and if you exec into the container.

E.g.:

> I0125 21:43:15.735257   12928 sync.go:127] Corrected destinations: base: /projects file: ear/target/test-classes/it/io/openliberty/guides/multimodules
> I0125 21:43:15.735257   12928 sync.go:121] recursiveTar arguments: srcBase: C:\git, srcFile: multi-mod-dev\ear\target\test-classes\it\io\openliberty\guides\multimodules\IT.class, destBase: /projects, destFile: ear\target\test-classes\it\io\openliberty\guides\multimodules\IT.class
> I0125 21:43:15.735257   12928 sync.go:127] Corrected destinations: base: /projects file: ear/target/test-classes/it/io/openliberty/guides/multimodules/IT.class
> I0

## Expected behavior

The .gitignore entry of:
> target/

should be honored by odo and it should prevent the above files from getting copied into the pod container.

## Any logs, error output, etc?

See above.

**Comment by dharmit** [comment]
IIUC, it's `.odoignore` file that needs to have the entry for `target/` for odo to ignore it. Can you please verify if odo still pushes/copies the files after you add an entry to `.odoignore`?

**Comment by dharmit** [comment]
> EDIT: please specify full path. Meaning, specify `ear/target/` if you're referring to `target/` directory inside the `ear/` directory.

This is what I'm observing at my end:
```sh
$ cat .odoignore 
ear/target/
war/target/
jar/target/

$ kubectl exec multi-module-devfile-6b954bb754-8zgfx -- ls jar/ ear/ war/
ear/:
pom.xml
src

jar/:
pom.xml
src

war/:
pom.xml
src
```

**Comment by mik-dass** [comment]
> EDIT: please specify full path. Meaning, specify ear/target/ if you're referring to target/ directory inside the ear/ directory.

Yes the path in `.gitignore` or `.odoignore` should be the full path like `ear/target/` etc.

**Comment by scottkurz** [comment]
I think it's confusing to accept `.gitignore` in place of `.odoignore` but to interpret it differently.  

It seems like .odoignore can use:

> */target

for the use case I have in mind, but note this does NOT work equivalently in Git for .gitignore. 

Perhaps projects with nested directories are in the minority.   

I wonder though if it would be worth investigating alternatives to simply use the gitignore format instead of inventing a different one for odo.    Maybe it'd be worth exploring a project like this:
https://github.com/monochromegane/go-gitignore
?

**Comment by dharmit** [comment]
> I think it's confusing to accept `.gitignore` in place of `.odoignore` but to interpret it differently.

One way to think of it is:
* `.gitignore` is for stuff you'd like to be ignored by git commands.
* `.odoignore` is for stuff you'd like to be ignored by odo commands.


> I wonder though if it would be worth investigating alternatives to simply use the gitignore format instead of inventing a different one for odo.

Inventing a different ignore file for odo was done deliberately. Checkout #1036 for more discussion/commentary around this. However, the behaviour you've described is a bug if we consider @kadel's comment about following the approach used by .npmignore file https://github.com/openshift/odo/issues/1036#issuecomment-441637493.

@mik-dass this looks like a bug to me since there's no `.odoignore` file but odo is not honouring what's there in `.gitignore` file. WDYT?

**Comment by scottkurz** [comment]
> Inventing a different ignore file for odo was done deliberately. Checkout #1036 for more discussion/commentary around this. However, the behaviour you've described is a bug if we consider @kadel's comment about following the approach used by .npmignore file [#1036 (comment)](https://github.com/openshift/odo/issues/1036#issuecomment-441637493).

Yeah, I haven't really used `.npmignore` but the [doc](https://docs.npmjs.com/cli/v6/using-npm/developers#keeping-files-out-of-your-package) seems to say it follows the same syntax, with the addition of a list of special values, some of which are always ignored, some never ignored.  

Sounds like we're agreeing then since you said this looks like a bug.

**Comment by mik-dass** [comment]
> @mik-dass this looks like a bug to me since there's no .odoignore file but odo is not honouring what's there in .gitignore file. WDYT?

Works fine for me. I have a `.gitignore` and not a `.odoignore`.

```
[mrinaldas@localhost project]$ odo create nodejs
 ⚠  odo may not work as expected in a default project, please run the odo component in a non-default project. To create a new project, use `odo project create`.
Validation
 ✓  Creating a devfile component from devfile path: /home/mrinaldas/project/devfile.yaml [37012ns]
 ✓  Validating devfile component [107386ns]

Please use `odo push` command to create the component with source deployed
[mrinaldas@localhost project]$ odo push

Validation
 ✓  Validating the devfile [26609ns]

Creating Kubernetes resources for component nodejs
 ✓  Waiting for component to start [9s]
 ✓  Waiting for component to start [5ms]
 ⚠  Unable to create ingress, missing host information for Endpoint http-3000, please check instructions on URL creation (refer `odo url create --help`)


Applying URL changes
 ✓  URLs are synced with the cluster, no changes are required.

Syncing to component nodejs
 ✓  Checking files for pushing [272796ns]
 ✓  Syncing files to the component [157ms]

Executing devfile commands for component nodejs
 ✓  Waiting for component to start [1ms]
 ✓  Executing install command "npm install" [5s]
 ✓  Executing run command "npm start" [1s]

Pushing devfile component nodejs
 ✓  Changes successfully pushed to component
[mrinaldas@localhost project]$ odo exec -- ls /project/
devfile.yaml
new.js
node_modules
package-lock.json
package.json
python-file
server.js
test
[mrinaldas@localhost project]$ odo exec -- ls /project/python-file
red.js
[mrinaldas@localhost project]$ tree
.
├── devfile.yaml
├── new.js
├── package.json
├── python-file
│   ├── filesJunk
│   │   ├── caesar.py
│   │   ├── railfence.py
│   │   └── xor.py
│   └── red.js
├── server.js
└── test
    └── test.js

3 directories, 9 files
[mrinaldas@localhost project]$ cat .gitignore 
.odo/env
.odo/odo-file-index.json
/home/mrinaldas/project/.odo/env
python-file/filesJunk/
```

**Comment by scottkurz** [comment]
> Works fine for me. I have a `.gitignore` and not a `.odoignore`.

My point though is that this should be treated as a bug, because, from your example, a .gitignore including:

> filesJunk/

would cause git to ignore `python-file/filesJunk/xor.py`  but odo will NOT ignore this content, and would push that into the container.

**Comment by mik-dass** [comment]
> However, the behaviour you've described is a bug if we consider @kadel's comment about following the approach used by .npmignore file #1036 (comment).

The `.gitingore` and `.odoignore` pattern matching behavior isn't supposed to match `.npmignore`. They both should follow the same behavior as `.gitignore`.

**Comment by mik-dass** [comment]
> would cause git to ignore python-file/filesJunk/xor.py but odo will NOT ignore this content, and would push that into the container.

The logs in https://github.com/openshift/odo/issues/4389#issuecomment-769782902 shows that `python-file/filesJunk/xor.py` is ignored by `odo` and is not pushed.

```
[mrinaldas@localhost project]$ odo exec -- ls /project/python-file
red.js
```

**Comment by scottkurz** [comment]
But my point is simply that with this .gitignore, 
>    filesJunk/

the file: `python-file/filesJunk/xor.py` will be ignored by Git and not ignored by odo.

**Comment by mik-dass** [comment]
OK so you mean only `filesJunk/`. That doesn't work with odo currently as it uses simple blob matching. We need to check if libraries like `https://github.com/monochromegane/go-gitignore` can handle such cases.

**Comment by dharmit** [comment]
/remove-lifecycle stale
/priority low

@kadel please change the priority if it looks incorrect to you.

**Comment by scottkurz** [comment]
Actually I'm realizing the performance aspect is a non-issue on Linux.. only on Win10.    But you still might want the ignore applied to keep a clean container, to avoid certain side effects, etc.    

I might open a performance issue separately for Win 10 synch.

**Comment by kadel** [comment]
bumping priority as for larger application this can get quite annoying

**Comment by feloy** [comment]
Normal behaviour of a `target` entry in `.gitignore` is to ignore all directories `target`, including the nested ones. odo only ignores the `/target` directory.

`odo` should use a library similar to `https://github.com/monochromegane/go-gitignore` to check for file inclusion

**Comment by feloy** [comment]
This also needs to be fixed for `odo dev` command
