### ISSUE TITLE
Set up disconnected env on psi

### ISSUE THREAD

**Issue by prietyc123** [redhat-developer/odo#4409]
/kind user-story

## User Story
As a QE I want disconnected cluster set up on psi to reduce dependency on openshift qe flexy job env and full access control over env.

## Acceptance Criteria 
- [ ] Analyse the approach involved in the process
- [ ] Create our own flow or Use flexy job script/template (depends on analysis) to set up the environment
- [ ] Resolve blockers
- [ ] Should be able run test and validate odo major feature behaviour on disconnected cluster using psi

## Links 
- Feature Request: 
- Related issue: https://issues.redhat.com/browse/ODO-37 

/kind user-story

**Comment by prietyc123** [comment]
@mohammedzee1000 Could you please verify the acceptance criteria and feel free to add in case i skipped any other criteria.

**Comment by kadel** [comment]
/priority low

This is an ultra-low priority right now. Currently, we don't have any stable testing environment. To me, it doesn't make sense to start with something as complex as running our own disconnected cluster if we don't even have our current tests running on PSI cluster.

**Comment by kadel** [comment]
we are not using psi anymore
