### ISSUE TITLE
Increase unit tests using Gomock

### ISSUE THREAD

**Issue by prietyc123** [redhat-developer/odo#4421]
/kind user-story

## User Story
As a Dev/Qe I want to assure most of our code are being tested to increase quality of the product

## Acceptance Criteria 
- [ ] Unit test refactoring
- [ ] It should cover at least 60% of the code.

## Links 
- Feature Request: NA
- Related issue: https://github.com/openshift/odo/issues/4076

/kind user-story

**Comment by prietyc123** [comment]
I think this should be an epic and tasks can be added here.

/remove-lifecycle rotten

**Comment by kadel** [comment]
> @kadel @dharmit Could you please help in adding the unit test tasks for ex - #3605

Yes, it needs unit tests, but we are not going to have a dedicated effort to add unit tests.

Missing unit tests should be added when the code gets modified while updating existing features or fixing bugs

**Comment by valaparthvi** [comment]
/close
We are actively working on adding unit tests using gomock.
