### ISSUE TITLE
odo project create -w does not wait enough for the project to be available

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/odo#4426]
/kind bug

## What versions of software are you using?

**Operating System:**
Win10Pro

**Output of `odo version`:**
odo v2.0.4 (5544b25ec)

## How did you run odo exactly?
`odo project create project -w && odo project list`

## Actual behavior
New project is not listed

## Expected behavior
New project should be listed

## Any logs, error output, etc?

```
odo project create jeff1 -w && odo project list
 V  Waiting for project to come up [947ms]
 V  Project 'jeff1' is ready for use
 V  New project created and now using project: jeff1
ACTIVE     NAME
           jbosstools
           jeff
```

**Comment by girishramnani** [comment]
We have faced this issue multiple times and multiple developers from odo have gone over this error but if I remember correctly  we never found a solution,
There was a question also posted upstream about this.

Let me find some relevant issues and PRs to confirm this

**Comment by kadel** [comment]
If I remember @mik-dass found a solution for original problem after talking to OpenShift guys.
This was supposed to solve this problem https://github.com/openshift/odo/blob/2180507a4850dfac98559cc94aa9d55441007c0b/pkg/project/project.go#L50
It looks like it is not that reliable as we thought.

**Comment by mik-dass** [comment]
> It looks like it is not that reliable as we thought.

As mentioned in https://github.com/openshift/odo/pull/2330#issuecomment-578611401, the fix wasn't reliable as back then the namespace creation as an object was synchronous upon the request but provisioning the resources inside that project was asynchronous - like serviceaccount, serviceaccount tokens (secrets) etc was asynchronous. But since it did reduced the number of occurrences, we decided to merge the changes.

**Comment by kadel** [comment]
There is no reliable solution for this. Odo tries the best it can, but due to Kubernetes eventual consistence nature, there can still be some corner cases that odo can't reliably detect. 

/close
