### ISSUE TITLE
odo should handle errors in a better way

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/odo#4447]
/kind bug
/area UX

## What versions of software are you using?

**Operating System:** all

**Output of `odo version`:** master (2.0.4)

## How did you run odo exactly?
When not logged into or connected with the cluster, I tried to run `odo delete`, `odo list`, `odo project` commands. None of the commands except `odo list` indicated that I was unauthorized to run the commands because I was not logged into the cluster.

## Actual behavior
```sh
$ odo delete
 ✗  You don't have permission to create or set namespace 'manderse-dev' or the namespace doesn't exist. Please create or set a different namespace
$ odo list
 ✗  Unauthorized
$ odo project set manderse-dev
 ✗  The project manderse-dev does not exist
```

## Expected behavior
The error messages should be more indicative of why a user is not able to perform some action.

## Acceptance Criteria
- [x] #5121
- [x] #5122

**Comment by dharmit** [comment]
/remove-lifecycle rotten

@kadel can you help set priority on this one? IMO a medium and targeting 2.4 should be good.

**Comment by cdrage** [comment]
Experienced this today using odo for the first time in 14 months. Pain in the butt!

```
~/test/nodejs-ex  master ✔                                                                                                                                                      81d
▶ odo create nodejs
? Help odo improve by allowing it to collect usage data. Read about our privacy statement: https://developers.redhat.com/article/tool-data-collection. You can change your preference ? Help odo improve by allowing it to collect usage data. Read about our privacy statement: https://developers.redhat.com/article/tool-data-collection. You can change your preference later by changing the ConsentTelemetry preference. Yes
Devfile Object Creation
 ✓  Checking if the devfile for "nodejs" exists on available registries [85534ns]
 ✓  Creating a devfile component from registry "DefaultDevfileRegistry" [568ms]
Validation
 ✓  Validating if devfile name is correct [78330ns]
 ✓  Validating the devfile for odo [7ms]
 ✓  Updating the devfile with component name "nodejs-nodejs-ex-epmu" [488464ns]

Please use `odo push` command to create the component with source deployed

~/test/nodejs-ex  master ✗                                                                                                                                                  81d ⚑ ◒  
▶ odo push
 ✗  Unauthorized
```

Let's make this a priority, since just having "unauthorized" is an awful touch.

**Comment by dharmit** [comment]
> Take this for example:
> resource project validation check failed.: Unauthorized
> Or
> forbidden: User "system:anonymous" cannot get path "/apis/route.openshift.io/v1"

These type of errors should be wrapped IMO. 

I think that at CLI layer, we should be using more of `fmt.Errorf()` and at lower layers, we should be using more of `errors.New()`. However, if at lower layer, we are using a library from `vendor` or something from standard library, we should wrap that as well.

**Comment by kadel** [comment]
this has been improved in odo v3
/close
