### ISSUE TITLE
`odo test` should have subcommand to list available tests to run with `--test-command`

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/odo#4449]
/kind feature

## Which functionality do you think we should add?

`odo test` run default test and in case there are many test commands 'odo test --test-command <test-command-name can>`  command can be used. In this case user have to go and find it in devfile. For IDE's it means parsing devfile and looking for commands in test group if I understand that correctly.

Would be good if `odo test` would be able to list available test commands as `odo test list` with `-o json` support as well.

## Why is this needed?

For user that would be the same experience as as with other commands sub-commands odo has already. That would eliminate necessity to open devfile and search for it.

IDEs would be able to fetch list of available test commands for component without parsing devfile.

**Comment by kadel** [comment]
/reopen
/remove-lifecycle rotten
still valid

**Comment by kadel** [comment]
we first need to implement `odo test` in odo v3 (https://github.com/redhat-developer/odo/issues/6070)

**Comment by kadel** [comment]
/status blocked 
by #6070
