### ISSUE TITLE
Werror while downloading git starter project with "main" as a default branch

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#4555]
When downloading starter the project from git repo that uses `main` as a default branch.

` ✗  couldn't find remote ref "refs/heads/master"`

**Comment by mezarin** [comment]
/reopen
This is still an issue.

**Comment by scottkurz** [comment]
@kadel can we please reopen this?  Thanks.

**Comment by scottkurz** [comment]
As far as I can tell this same issue exists in odo v2.5.0.   And I'm not seeing if this is duplicated by some other issue.   To reiterate, this is an issue with a non-master 'default' branch, not a question of using a specified non-default branch (which https://github.com/redhat-developer/odo/pull/4260 maybe seems to touch on?).   @kadel  can we reopen this one?   Thanks.

**Comment by valaparthvi** [comment]
/close
In favor of #6232.
