### ISSUE TITLE
`odo dev` and `odo deploy` should display binding connection information

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#4570]
## User Story
- As a developer linking to a service
- I want to know what connection information link made available
- So that I can easily configure my app without searching for this information somewhere else. 

## Acceptance Criteria
- [ ] when `odo dev` or `odo deploy` creates a "link" (ServiceBinding) it should display what env variables or file pahts (in case of `--bindAsFiles`) were made available for application to use.
- [ ] It needs to work for both scenarios - When SBO is installed on cluster, or if ServiceBinding library is used by odo. 

```
▶ odo link  Database/mydb
 ✓  Successfully created link between component "mynode" and service "Database/mydb"

To apply the link, please use `odo push`
```

```
▶ odo push
...
...

You can use following environment variables to connect to the service.
- DATABASE_DB_NAME
- DATABASE_DB_PASSWORD
- DATABASE_DB_USER
- SERVICE_CLUSTERIP
-

...
...
```

```
▶ odo link --bindAsFiles  Database/mydb
 ✓  Successfully created link between component "mynode" and service "Database/mydb"

To apply the link, please use `odo push`
```
```
▶ odo push
...
...
You can use  following files to connect to the service.
- /binding/java-mydb/DATABASE_DB_NAME
- /binding/java-mydb/DATABASE_DB_PASSWORD
- /binding/java-mydb/DATABASE_DB_USER
- /binding/java-mydb/SERVICE_CLUSTERIP
...
...
```

/kind user-story

**Comment by dharmit** [comment]
> - [ ] after `odo link` creates a "link" it should display what env variables were made available for application to use

#4009

**Comment by kadel** [comment]
> > * [ ]  after `odo link` creates a "link" it should display what env variables were made available for application to use
> 
> #4009

ah, I knew that I saw this already somewhere, but I was not able to find it.


are you ok if I close #4009 in favor of this one? It has more information.

**Comment by ajm01** [comment]
This looks good to me, exactly the information I am looking for from a successful odo link.

**Comment by dharmit** [comment]
How does odo decide which env vars it should print when doing linking? Since we're moving to using SBO for every link operation, I think it would make sense to print this based on the annotations in the service/component being linked.

Thoughts?

**Comment by kadel** [comment]
after creating ServiceBinding SBO create Secret. You can read information from ServiceBinding status to check if the Secret was already created and its name. Then odo can just read that print Secret keys

**Comment by girishramnani** [comment]
I can work on this
/assign

**Comment by dharmit** [comment]
@girishramnani it's not directly connected to the Milestone we're targeting https://github.com/openshift/odo/milestone/15. Although I understand it helps improve the UX for the users who do `odo link`. Considering how close we are to due date for the milestone, I would request not to prioritize this for time being.

**Comment by girishramnani** [comment]
understood, but whenever we plan to work on this, could I be assigned to it?

**Comment by kadel** [comment]
This is not planned for the current sprint, nor this is in progress. 
It should not be assigned to anyone
/unassign

**Comment by girishramnani** [comment]
according to this issue https://github.com/openshift/odo/issues/3734 we already have this env information but only for non `--bindAsFiles` scenerio.
We still need to update the output of `odo link` for env approach.

**Comment by girishramnani** [comment]
we need to reconsider the whole idea here as `odo link` now doesn't create any link and instead adds the information into devfile

**Comment by mik-dass** [comment]
The steps for fetching the required details are here https://github.com/openshift/odo/blob/4ba144d5168e2196f930331e30e66961b12c83a7/pkg/component/component.go#L1540-L1545
