### ISSUE TITLE
Integrate codecov.io in odo OpenShift CI job

### ISSUE THREAD

**Issue by prietyc123** [redhat-developer/odo#4631]
/kind user-story

## User Story
As a odo team we want to integrate codecov.io with CI So that we can measure unit test coverage on prs.

## Acceptance Criteria 
- [ ] We should see codecov comment on pr with unit test coverage percentage

## Links 
- Feature Request: NA
- Related issue: NA

/kind user-story

**Comment by dharmit** [comment]
We removed this in https://github.com/openshift/odo/pull/4628. Can you elaborate on what we might be able to do here?

**Comment by kadel** [comment]
/close
we use sonarcloud to track coverage now
