### ISSUE TITLE
Automate generation of Release Readiness document

### ISSUE THREAD

**Issue by rnapoles-rh** [redhat-developer/odo#4649]
/kind user-story

## User Story
As a Quality Engineer I want to get an automated Release Readiness document So that it requires minimal effort to get it available.

## Acceptance Criteria 
- [x] Complete the [Data Driven Release Basics Program training](https://start.learning.redhat.com/catalog/learning-path/159)
- [x] Complete the [Product Quality Index (PQI) Basics Program training ](https://start.learning.redhat.com/catalog/learning-path/142)
- [x] Research GitHub and Google Sheets APIs

Develop scripts to pull issues (bugs) from GitHub into Google sheets to generate defect metrics for:
- [x] Connect Google sheets and GitHub using APIs and OAuth authentication 
- [x] Defect backlog 
- [x] Defect arrival
- [x] Defect regression
- [x] Defects resolution
- [ ] Defects reopen
- [ ] Defects verification
- [ ] Defects rejected
- [ ] Defects failed QE
- [ ] Investigate process to track test results (automated and manual) in Polarion
- [x] Create Polarion Project

The generated test metrics and test results will be used to populate the Release readiness document and should reduce effort to produce Release Readiness document to no more than 30 minutes:
- Define frequency of test results to be published in Polarion 
- Define test suite to be included in Polarion test results
- Develop scripts to create test cases in Polarion project 
- Develop scripts to update test results in Polarion project 
Polarion is out of scope for now. 

## Links 
- [Sample release readiness document](https://docs.google.com/document/d/1w7AwKDtEe-LfvSc3m18_7Gi2ILIINbe7I_C4CaVmma0/edit?ts=606d4d75)

/kind user-story

**Comment by rnapoles-rh** [comment]
Researching how to integrate GitHub and google sheets for tracking defect metrics

**Comment by rnapoles-rh** [comment]
Requested creation of Polarion project.

**Comment by prietyc123** [comment]
> The generated test metrics and test results will be used to populate the Release readiness document and should reduce effort to produce Release Readiness document to no more than 30 minutes:
 
@rnapoles-rh Do we really need polarian for release readiness doc to populate automatically. I feel polarian is completely different task, no?

**Comment by rnapoles-rh** [comment]
> > The generated test metrics and test results will be used to populate the Release readiness document and should reduce effort to produce Release Readiness document to no more than 30 minutes:
> 
> @rnapoles-rh Do we really need polarian for release readiness doc to populate automatically. I feel polarian is completely different task, no?

@prietyc123 yes, we do need Polarion. The Release Readiness document has two components, defect metrics (pulling data from GitHub) and test metrics (pulling data from Polarion). For this to happen, the automated test results have to be pushed to Polarion (this includes two steps, 1) create test cases (or test execution records), 2) update those test execution records with the test results). I created ticket 63 in JIRA to start tracking this effort.

**Comment by prietyc123** [comment]
> > > The generated test metrics and test results will be used to populate the Release readiness document and should reduce effort to produce Release Readiness document to no more than 30 minutes:
> > 
> > 
> > @rnapoles-rh Do we really need polarian for release readiness doc to populate automatically. I feel polarian is completely different task, no?
> 
> @prietyc123 yes, we do need Polarion. The Release Readiness document has two components, defect metrics (pulling data from GitHub) and test metrics (pulling data from Polarion). For this to happen, the automated test results have to be pushed to Polarion (this includes two steps, 1) create test cases (or test execution records), 2) update those test execution records with the test results). I created ticket 63 in JIRA to start tracking this effort.

You are right, but my point was, as we don't have polarian currently. So IIUC at least to track test results `pass/fail` rate and some more data can be fetched from [periodic job status](https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/?type=periodic&job=periodic-*odo*) atm. I feel this should not be more of a task. 
Later on when we have polarian we will automate the flow accordingly. I think we can scope out `polarian` part as separate issue and this can be said as done. Correct me If I am wrong.

**Comment by rnapoles-rh** [comment]
> > > > The generated test metrics and test results will be used to populate the Release readiness document and should reduce effort to produce Release Readiness document to no more than 30 minutes:
> > > 
> > > 
> > > @rnapoles-rh Do we really need polarian for release readiness doc to populate automatically. I feel polarian is completely different task, no?
> > 
> > 
> > @prietyc123 yes, we do need Polarion. The Release Readiness document has two components, defect metrics (pulling data from GitHub) and test metrics (pulling data from Polarion). For this to happen, the automated test results have to be pushed to Polarion (this includes two steps, 1) create test cases (or test execution records), 2) update those test execution records with the test results). I created ticket 63 in JIRA to start tracking this effort.
> 
> You are right, but my point was, as we don't have polarian currently. So IIUC at least to track test results `pass/fail` rate and some more data can be fetched from [periodic job status](https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/?type=periodic&job=periodic-*odo*) atm. I feel this should not be more of a task.
> Later on when we have polarian we will automate the flow accordingly. I think we can scope out `polarian` part as separate issue and this can be said as done. Correct me If I am wrong.

@prietyc123  "more data can be fetched from periodic job status atm", this can be a temporary solution. However, according to DDR and PQI processes across Red Hat, test metrics are tracked in Polarion. ODO issue 64 in JIRA tracked the creation of our Polarion project, EPIC 63 is the parent. You created 6 other issues in JIRA related to Polarion that are part of what needs to be done for Polarion, so we can make them children of Epic 63. The goal is to automate the generation of RRD as much as possible. Generation defect metrics is step one, generating test metrics is step 2.

**Comment by rnapoles-rh** [comment]
Oath2 authentication steps in https://docs.google.com/document/d/19papcuzd1t7OKEH01DjX4yq2qckiEhsQh318cG5VOjs/edit

The ODO Defect Metrics google sheet: https://docs.google.com/spreadsheets/d/1RSuSS_0jJtnfHer4AmQbhMJUBRLt9Ik3XND7jJUIEHM/edit#gid=63137954
Completed:

- Scripts to add GitHub menu to google sheet
- Script  to authenticate using OAuth2
- Script to retrieve defect backlog count for DefectBacklog metrics. 

Issues:
Exception: Invalid argument: https://api.github.com/search/issues?q=repo:openshift/odo+is:issue+label:kind/bug+state:open+created:<2021-06-01
However, using that query in a browser returns the expected result

**Comment by rnapoles-rh** [comment]
@prietyc123 The defect backlog sheet is done and working properly. You can use the code from this as the template for the rest and adjust the query a make any adjustments that might be needed in the code to set date ranges for the query.
![image](https://user-images.githubusercontent.com/72166315/122914684-e63f6900-d328-11eb-914d-1ef54a442784.png)

**Comment by prietyc123** [comment]
> The defect backlog sheet is done and working properly. You can use the code from this as the template for the rest and adjust the query and make any additions/adjustments that might be needed in the code to set date ranges for the query.

Thanks @rnapoles-rh for fixing the initial phase error for `defect backlog`. I feel apart from this we have lot many implementation left out with `Defect backlog` like defect count wrt start and end date, stop execution of the script if date exceed current date and much more. Currently focusing on proper and robust implementation of whole scenario with one sheet. Once Its done, IMO rest of the defect implementation should be similar. As of now completed the start and end date concept with proper customisation and cleanup, fixing the failures. 
**How defect board looks like:**
![image](https://user-images.githubusercontent.com/51620925/123111291-6d402e80-d45a-11eb-8063-a9825b769b3a.png)

**Comment by prietyc123** [comment]
Polarian onboarding will be done in two phase:

**1 Phase**
- [ ] Automated creation/updating of automated/manual test cases in Polarion
- [ ] Automated or manual creation of Test Runs in Polarion
- [ ] Manual test case execution results are entered by hand in Polarion
- [ ] Automated test cases execution results are entered by hand in Polarion

**2 Phase**
- [ ] Integration with CI - Send test results -> Polarion

**Comment by rnapoles-rh** [comment]
Scope:

- [ ] Reestablish connection between Google Sheets and GitHub Repo
- [ ] Ensure all automated test metrics work as expected

**Comment by rnapoles-rh** [comment]
I Was able to reestablish the connection.
We are getting a 422 error when running the script for Defect backlog:


![Image](https://user-images.githubusercontent.com/72166315/172760758-f8effdf0-1061-49ec-8595-02b246f5155e.png)

Under investigation

**Comment by rnapoles-rh** [comment]
Issues had been fixed in the google sheet
