### ISSUE TITLE
Wrong link to install ODO

### ISSUE THREAD

**Issue by cmoulliard** [redhat-developer/odo#466]
The doc page points to a wrong link to install odo 

When we click on `Install odo using this installation guide` link on the page : http://openshiftdo.org/getting-started/

<img width="974" alt="screenshot 2018-05-22 15 42 25" src="https://user-images.githubusercontent.com/463790/40366212-e02ebe46-5dd6-11e8-81ab-5d1e0e252606.png">

**Comment by cdrage** [comment]
I'll take this up, I need to update the link as well as get the documentation synced! Thanks @cmoulliard

**Comment by kadel** [comment]
The website was put on hold for now. For time being we are going to use github repo page as landing side for odo project.
