### ISSUE TITLE
Define the structure of docs on odo.dev

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/odo#4664]
/kind documentation

## What mistake did you find / what is missing in the documentation?
Currently, the docs on odo.dev are quite haphazard. As a user just starting with odo, it is confusing and misleading at places. It is outdated at places as well.

## What is the relevance of it?
Keeping docs updated is relevant from the users' perspective as that's likely the most preferred way to understand what features exist and how to use them

## Acceptance Criteria

- [x] A doc describing the desired structure/flow of the docs on odo.dev (https://github.com/openshift/odo/pull/4851)
- [ ] An epic based on above doc
- [ ] Break the epic into user stories and take help of SMEs (devs who implemented the feature(s)) to write the docs

**Comment by dharmit** [comment]
Scope for Sprint 201:
- [ ] Prepare a doc that describes the desired structure/flow of docs on odo.dev

I'll be working with people across various devtools projects to get this done.

**Comment by dharmit** [comment]
We have a high level structure/flow for the site. It can be viewed on - https://odo-docusaurus-preview.netlify.app/docs/intro/

Draft PR for that is available. I'll be changing the location for docs from `./docs/odo.dev` to `./website` and opening up that PR for review.

**Comment by dharmit** [comment]
For Sprint 203, we have to take things further from #4851. We need to add content to below pages on the site:

### Gettings Started
This section gives users an overview about odo. Please suggest if something needs to be added/removed from this:
- [ ] Quickstart (@kadel you need to help us here with Springboot example)
- [ ] Basics
- [ ] Cluster Setup
  - [ ] Development Cluster (this doc clarifies that odo docs help setup development clusters only.)
  - [ ] Kubernetes
  - [ ] OpenShift
- [ ] Installation 
- [ ] Import applications (talk about how existing git repo can be deployed to k8s using odo)
- [ ] Configuration (talk about odo preference file)

### Using odo
This section needs to be an end-to-end story where a user can follow every guide in a sequential order and achieve results using odo; OR they can pick up any guide from the middle and still be able to understand and follow the steps as long as they have followed the earlier guides in the sequence.

If we agree upon above idea, we need to have one example that can be used across the guides. @kadel, IMO we should use Springboot Petclinic. Or suggest something that you think would be a good choice here.

#### NOTE: we might need to add something in the below sequence, or need to change order; it's not 100% complete or accurate.
- [ ] Create Component
- [ ] Environment Variables
- [ ] Continuous Development
- [ ] Create URL
- [ ] Debug Applications
- [ ] Lifecycle Events
- [ ] Persistent Storage
- [ ] Push Specific Files
- [ ] Create and Link Services

### Command Reference
The list below is incomplete on current preview site. We need to cover each odo command. Let's sort them alphabetically so that it's easy for a reader to find it.
In the doc for the commands, we should to explain what the command does on Kubernetes cluster when the user executes it.
- [ ] app
- [ ] catalog
- [ ] component
- [ ] config
- [ ] debug
- [ ] env
- [ ] preference
- [ ] project
- [ ] registry
- [ ] service
- [ ] storage
- [ ] test
- [ ] url

### Architecture
This section talks about the building blocks of odo. This section is for the users who want to know about odo internals.
- [ ] Overview
- [ ] odo init image
- [ ] Service Binding
- [ ] Devfile

### Contribute to odo
This section is for people who want to contribute to odo
- [ ] Feature Proposals (I'm not fully convinced about putting this up on the website)
- [ ] Code
- [ ] Documentation

**Comment by kadel** [comment]
Is it correct that this is closed?
I see a lot of unmarked checkboxes in https://github.com/openshift/odo/issues/4664#issuecomment-875511836

**Comment by dharmit** [comment]
No, it's a mistake because the PR I opened had this issue as "Fixes".

/reopen

**Comment by dharmit** [comment]
Unassigning myself. It's mostly Charlie working on tasks related to this.

@kadel PTAL if you want to keep this open.

/unassign @dharmit
