### ISSUE TITLE
Add function to odo create to create a child/extension of a given devfile registry entry (as parent)

### ISSUE THREAD

**Issue by scottkurz** [redhat-developer/odo#4673]
/kind user-story

## User Story
As an app developer and user/consumer of a stack devfile (e.g. java-openliberty) I want odo to create a devfile in my project working directory that is a thin or sparse "child" extension of the devfile in the registry, which it will refer to as a "parent".  

It could even be useful to offer a choice, e.g.:
* odo create java-openliberty                              # proposed new behavior, here suggested as default
* odo create java-openliberty  --clonedevfile       # today's behavior, makes a copy 

The decision on which the default should be could be made separately.

This relieves the devfile owner from having to maintain parent vs. child versions of the devfile for each devfile, or making a decision as to which usage is preferable, and also provides tooling for creating a child/extension when the devfile author did not do so.

It might be useful to generate some commented-out text that gives a starting point for showing where to add the child extensions. 

## Acceptance Criteria 
- [ ] It should provide a way for `odo init ...` to create a standard child extension devfile for a given entry in a devfile registry, possibly/probably with an option for choosing to extract/copy the existing devfile as-is (without making the extension).
- [ ] customize child devfile with name / env vars, endpoints, etc (if possible, or skip the customization if not possible)
- [ ] same for odo dev/deploy with no devflie
- [ ] interactive mode: add a question to ask for child or full devfile
- [ ] flag mode: `--child`

## Links 
- Related Epic (mandatory): 

/kind user-story

Example of child devfile:
```
parent:
  id: go
  registryUrl: https://registry.devfile.io
metadata:
  name: my-child-go
schemaVersion: 2.2.0
```

**Comment by dharmit** [comment]
/remove-lifecycle stale
/area devfile

@kadel @elsony @deboer-tim, can you folks PTAL at this one?

**Comment by deboer-tim** [comment]
Sample/starter projects may include a devfile, and if one exists we should keep it essentially as-is.

For other cases, I'd lean toward creating a child by default (so you can easily pick up future improvements to the parent) but having a second command to merge/flatten/make-standalone. I don't have a problem allowing this at creation time too, but I think there will be cases where you may need it later.

Others thoughts?

**Comment by scottkurz** [comment]
One thought is that if the devfile variables are going to be the easiest, most common extension points (debatable if that could be proven true within a single devfile let alone devfiles in general) then maybe the variables could be "cloned" into the child extension... so you don't have to jump back to the parent to see what values you have to work with.    They could even be commented out perhaps (I'd think keep them  uncommented but just noting).
