### ISSUE TITLE
"odo create nodejs"  creates a service for the wrong port for a default express app

### ISSUE THREAD

**Issue by stephanosbacon** [redhat-developer/odo#468]
By default, express generates an app that starts a server listening on port 3000, not 8080.  However, "odo create nodejs" creates a service that uses port 8080, and I can't seem to find a way to control this.

What this means is that someone trying a what would be a more or less canonical node app won't see something working out of the box.  This should either be documented and/or there should be a way to control it.

**Comment by kadel** [comment]
Current logic is similar to what `oc new-app` does. `odo` inspects s2i builder image and create service for ports that are marked as exposed in that image.

We should probably allow users to define custom ports when creating a component and creating url (Route).

**Comment by stephanosbacon** [comment]
I think that adding such an option would be very useful, as well as documenting the current behavior explicitly.  After trying odo, I tried nodeshift and it has the same behavior, but it does allow one to specify ports.

**Comment by cdrage** [comment]
We now allot specifying a port when using `odo create`. Closing this issue: https://github.com/redhat-developer/odo/issues/552
