### ISSUE TITLE
Archive odo-devfiles/registry

### ISSUE THREAD

**Issue by johnmcollier** [redhat-developer/odo#4703]
Corresponding devfile/api issue: https://github.com/devfile/api/issues/391

Now that odo v2.2.0 is now released, and the [registry.devfile.io](https://registry.devfile.io) is now used instead of the [odo-devfiles/registry](https://github.com/odo-devfiles/registry) repository, the [odo-devfiles/registry](https://github.com/odo-devfiles/registry) repository should be archived and marked as read-only. While we don't want to delete the registry repository, because there will likely be a number of older odo installs still pointing to it, we should archive it so that new stacks are not contributed to it.

A note indicating that the registry has been deprecated and moved to [registry.devfile.io](https://registry.devfile.io) / [devfile/registry](https://github.com/devfile/registry) should also be added to the repository.

**Comment by johnmcollier** [comment]
@kadel Thanks Tomas, I've merged your PR.

**Comment by kadel** [comment]
repo is archived.

/close
