### ISSUE TITLE
Show detailed information about storage before it is deleted

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#473]
It would be good if user could see if the storage is mounted or not and if yes then to what component.

If storage is not mounted:
`Are you sure you want to delete the storage %v?`

if mounted:
`Are you sure you want to delete the storage %v mounted to %s in %s component?`
For example:
`Are you sure you want to delete the storage data mounted to /data in backend component?`

**Comment by kadel** [comment]
fixed in #447

**Comment by surajnarwade** [comment]
@kadel Let's close this since #447 is merged

**Comment by kadel** [comment]
There is quite a serious bug in #447 -  #475
