### ISSUE TITLE
Improve tests readability and spec clean up

### ISSUE THREAD

**Issue by prietyc123** [redhat-developer/odo#4741]
We have currently a messy tests spec which pretty hard to analyze multiple test spec description quickly in the same test file because the implementation of the spec happens in the same file. As a user, he or she will be pretty happy to see the test spec description in the very next line. For example 
```code
func ProjectTestScenario() {
    When("Machine readable output tests", func() {
        It("Help for odo project list should contain machine output", HelpCommand) // HelpCommand will be expanded in a separate package
        It("should be able to get project", GetProject)
    })
    When("when running help for project command", func() {
        It("should display the help", HelpCommandProject) // HelpCommandProject will be expanded in a separate package
    })
}
```
Advantages:
1. Our test will get an index page like a book having an index
2. Test Readability 
3. Easy to figure what test case we are missing
4. Scenario integrity 
5. Easy to understand

**Comment by prietyc123** [comment]
Test needs to be refactored:
S2i Integration Test:
- [x] test-cmd-project
- [ ] test-cmd-app
- [ ] test-cmd-cmp
- [ ] test-cmd-cmp-sub
- [ ] test-cmd-pref-config
- [ ] test-cmd-push
- [ ] test-plugin-handler
- [ ] test-cmd-service
- [ ] test-cmd-link-unlink-311-cluster
- [ ] test-cmd-link-unlink-4-cluster
- [ ] test-cmd-login-logout
- [ ] test-generic
- [ ] test-cmd-storage
- [ ] test-cmd-url
- [ ] test-cmd-watch
- [ ] test-cmd-debug
Devfile:
- [ ] test-cmd-devfile-catalog
- [ ] test-cmd-devfile-create
- [ ] test-cmd-devfile-push
- [ ] test-cmd-devfile-exec
- [ ] test-cmd-devfile-status
- [ ] test-cmd-devfile-watch
- [ ] test-cmd-devfile-app
- [ ] test-cmd-devfile-delete
- [ ] test-cmd-devfile-registry
- [ ] test-cmd-devfile-test
- [ ] test-cmd-devfile-url
- [ ] test-cmd-devfile-debug
- [ ] test-cmd-devfile-storage
- [ ] test-cmd-devfile-log
- [ ] test-cmd-devfile-env
- [ ] test-cmd-devfile-config
E2E Tests:
- [ ] test-e2e-beta
- [ ] test-e2e-java
- [ ] test-e2e-source
- [ ] test-e2e-images
- [ ] test-e2e-devfile

**Comment by kadel** [comment]
> Advantages:
> * Our test will get an index page like a book having an index

This can be easily done even with the current structure. 

> * Test Readability

This new proposed structure actually decreases test readability as the test scenario (implementation) is disconnected from its `Context` and `It` blocks. 

> * Easy to figure what test case we are missing

> * Scenario integrity

To me, this new approach is actually disturbing scenario integrity by moving test implementation away from `Context` and `It` blocks. 

> * Easy to understand

For me this makes tests harder to read.

**Comment by dharmit** [comment]
/reopen

Closed erroneously due to PR description. 😄

**Comment by anandrkskd** [comment]
/close 
all the tests now follow the new approach of readable test structure, closing this issue
