### ISSUE TITLE
`odo link` error message for unpushed component should be more understandable

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/odo#4810]
## What versions of software are you using?

**Operating System:** all

**Output of `odo version`:** `main`

## How did you run odo exactly?
```sh
$ odo create nodejs node

# Tried self-linking without pushing the component
$ odo link node
```

## Actual behavior
```sh
$ odo link node
 ✗  deployment not found for the selector: app.kubernetes.io/instance=node,app.kubernetes.io/part-of=app
```

## Expected behavior
```sh
odo link node
 ✗  cannot find requested component on cluster; deployment not found for the selector: app.kubernetes.io/instance=node,app.kubernetes.io/part-of=app
```

/good-first-issue
/area linking
/kind bug

**Comment by valaparthvi** [comment]
@dharmit Do you think this issue is still relevant and that we can use it for Hacktoberfest?

**Comment by kadel** [comment]
no link in odo v3

**Comment by kadel** [comment]
no longer makes sense in odo v3
/close
