### ISSUE TITLE
Add ability to view/set devfile variables via subcommand like: `odo config view/set` 

### ISSUE THREAD

**Issue by scottkurz** [redhat-developer/odo#4838]
/kind user-story

## User Story

As a developer working with odo, I want to:

1. view "variables" defined by the 2.1 spec and their values
2. set the variable values

using something simple like `odo config set/view` or `odo env set/view`.

### Related Thoughts

* Should there be a different command for adding new (not yet in devfile) vs. setting existing (i.e. already appearing in the devfile) variables?

* Should `odo env set DebugPort` be phased out and replaced with a stack variable?   (In this interpretation, if it appears in the devfile using a substitution, then it should be in the form of a devfile variable).

* Should we use this as an opportunity to do any further revisiting of `odo config` vs. `odo env` ?   (E.g. as suggested in [this](https://kubernetes.slack.com/archives/C01D6L2NUAG/p1614763347024900) Slack thread.  E.g. `odo config-devfile` vs. `odo config-odo`, etc.?   (That's sounding like it'd turn this into a whole new epic).

* Reminder:  stack variables can only substitute in _string_ type fields. Furthermore, quoting the [spec](https://docs.devfile.io/devfile/2.1.0/user-guide/api-reference.html)

> Replacement cannot be used for:     schemaVersion, metadata, parent source - element identifiers, e.g. command id, component name, endpoint name, project name - references to identifiers, e.g. in events, a command's component, container's volume mount name - string enums, e.g. command group kind, endpoint exposure

## Acceptance Criteria 
- [ ] It should provide a get/view command
- [ ] It should provide a set command

## Links 
- Related Epic (mandatory):   Not an epic per se, but could be grouped within: https://github.com/openshift/odo/issues/4589

/kind user-story

**Comment by kadel** [comment]
/lifecycle frozen
This is still a valid proposal, and once we have some bandwidth we should look into this.
