### ISSUE TITLE
Create umount alias for unmount.

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#484]
Linux users have muscle memory for typing `umount`.
Opposite to that Windows users don't have any idea what umount is and unmount will make more sense for them.

We can add `umount` alias to `unmount` command to allow both variations.

But our documentation and examples should use only one variation of this - `unmount`.
Let's make sure that all our examples and docs are using `unmount`.

**Comment by piyush1594** [comment]
We are good to close this. :+1:
