### ISSUE TITLE
Fix leaky abstractions in url

### ISSUE THREAD

**Issue by mohammedzee1000** [redhat-developer/odo#4840]
/kind code-refactoring

We are leaking Kubernetes level objects such as ingresses and routes into levels above url
For eg: https://github.com/openshift/odo/blob/4ef651aeb16d0aec0d9fde6d5da8f20a81ba7acd/pkg/odo/cli/url/list.go#L98

We should fix all such leaks in the code, such as information from routes and ingresses from lower levels is wrapped URL package structures. The URL spec should be the only thing going to and from the URL layer to the layers above, essentially making the URL spec the source of truth for information related to lower-level packages. We should not have Kubernetes stuff imported at the higher levels at all.

For eg, the above function could become `urlspec.GetURLString()`

**Comment by kadel** [comment]
doesn't make sense i context of v3
/close
