### ISSUE TITLE
devfile for nodejs-ex is not exposing the right port

### ISSUE THREAD

**Issue by guillaumerose** [redhat-developer/odo#4847]
/kind bug

## What versions of software are you using?

**Operating System:**

Linux with CRC

**Output of `odo version`:**

```
odo v2.2.2 (93b7dd5f9)

Server: https://api.crc.testing:6443
Kubernetes: v1.20.0+df9c838
```

## How did you run odo exactly?

I followed the tutorial.

```
 git clone https://github.com/openshift/nodejs-ex && cd nodejs-ex
 odo create nodejs
 odo push
```

Output:
```
$  odo push
...
Applying URL changes
W0624 09:42:10.876239   13617 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
 ✓  URL http-3000: http://http-3000-nodejs-nodejs-ex-nzdq-foobar.apps-crc.testing/ created
```

## Actual behavior

The link is not working

## Expected behavior

The link is working.

## Information

It appears that the pod is exposing the port 8080 and not 3000. If I update the devfile to the port 8080, it works fine.

**Comment by kadel** [comment]
new `odo init` command can autodetect application ports and automatically change it
/close
