### ISSUE TITLE
Deleting a linked service/component should be done with proper unlinking

### ISSUE THREAD

**Issue by valaparthvi** [redhat-developer/odo#4871]
/kind bug

## What versions of software are you using?

**Operating System:**
Fedora 34

**Output of `odo version`:**
odo v2.2.2 (97b523a5a)

## How did you run odo exactly?

1. Create a component and push it.
2. Create another component or a service and push it.
3. Create a link to the other component/service and push it.
4. Delete the component/service created in step 2.
5. Try un-linking the deleted component/service from step 4.

## Actual behavior
```
 ✗  couldn't find service named XXX. Refer "odo service list" to see list of running services

 ✗  couldn't find component named XXX. Refer "odo list" to see list of running components
```

## Expected behavior
odo should forbid deletion of a service/component that's linked to another component. But that should not be the case if the component initiated the link (step 1). For such components, odo should delete the binding (which it already does, thanks for ownerReferences.)

**Comment by valaparthvi** [comment]
Quoting discussions from #4801.
> > Should `odo` forbid to delete a service/component when a link references it, or should `odo` delete the link when deleting the service/component?
> 
> IMO, odo should forbid deletion of a service/component that's linked to another component. But that should not be the case if the component initiated the link (step 1 in [#4801 (comment)](https://github.com/openshift/odo/issues/4801#issuecomment-872169765)). For such components, odo should delete the binding (which it already does, thanks for `ownerReferences`.)
> 

cc: @dharmit @feloy

**Comment by dharmit** [comment]
@kadel please share your thoughts regarding https://github.com/openshift/odo/issues/4871#issuecomment-872899703 and help set the priority of this one.

**Comment by kadel** [comment]
`odo delete` should delete everything that `odo push` created. That means that it should delete everything that is currently in devfile.yaml.
If it tries to skip something that is defined in the devfile it might lead to the situation where you are left with thinks that can't be deleted using odo. 


odo should be more clear with the user what is going to happen when `odo delete` is executed.
```
▶ odo delete
Items that will be deleted deleted:
 - Component petclinic 
 - Service  Pgcluster/mydb
 - Link to Pgcluster/mydb service
 
? Are you sure you want to delete the devfile component  petclinic and all its dependencies? (y/N)

```


Ideally odo should also detect a situation where a service has multiple links (it is linked to a different component than the one that is being deleted). In this case odo should show additional warning.

```
▶ odo delete
Items that will be deleted deleted:
 - Component petclinic 
 - Service  Pgcluster/mydb
 - Link to Pgcluster/mydb service

Another component (petclinic2) is linked to Pgcluster/mydb.
Deleting this might might make petclinic2 not functional.

Are you sure you want to delete the devfile component  petclinic and all its dependencies? (y/N)
```
