### ISSUE TITLE
enable monitoring for CI jobs

### ISSUE THREAD

**Issue by prietyc123** [redhat-developer/odo#4872]
Sometimes CI jobs fails continuously for real failures and we get to know about it may be after 2 days and more. To reduce such case we need to get notified if something is really fishy around CI jobs. Hence we need to monitor our jobs constantly so that we address such failure at earliest.

**Acceptance Criteria**

- [ ] Research the process to monitor CI job constantly on may be IBM cloud or if there is some process on prow
- [ ] If a particular CI fails more than 3 times in a row, notify QE  team

/area testing

**Comment by dharmit** [comment]
> * [ ]  Research the process to monitor CI job constantly on may be IBM cloud or if there is some process on prow
> * [ ]  If a particular CI fails more than 3 times in a row, notify QE team

We use Jenkins to orchestrate every job, no? Could we use some Jenkins plugin to send notification when a job fails for 3 consecutive times? Also, isn't 3 too low a number considering how flaky/unreliable our tests and test infra has been so far?

Should it notify the dev team as well instead of just QE team? Or do you plan to automate relaying the information to devs as soon as this happens?

**Comment by prietyc123** [comment]
> Could we use some Jenkins plugin to send notification when a job fails for 3 consecutive times?

AFAIK, yes we can do that. However I am not aware of the exact process atm. We do have `post-build` actions in jenkins for such scenarios but we don't want to notify for each and every failure. Considering failure count with notification is kind of tricky part for me. 

> Also, isn't 3 too low a number considering how flaky/unreliable our tests and test infra has been so far?

3 represents 3 consecutive job failure on the same pr. We can also consider looking into a job, failing for all the prs. Or we should try to cover both edge cases.

> Should it notify the dev team as well instead of just QE team?

Yes, I think it should be notify either in `#odo-notifications` slack channel or via email to the whole odo Team. IMO we already have channel created for such things, I would prefer to use that. WDYT?

**Comment by prietyc123** [comment]
Sprint 206

- [ ] Research the process to monitor CI job constantly on may be IBM cloud or if there is some process on prow

**Comment by rnapoles-rh** [comment]
Not required now using  BM Cloud pipelines
