### ISSUE TITLE
odo push interactive bootstrapping

### ISSUE THREAD

**Issue by deboer-tim** [redhat-developer/odo#4885]
/kind feature

## Which functionality do you think we should add?
When I want to use odo today I need to create a component first. While creating a component I need to pick a devfile as well. These are two concepts that the user likely hasn't been exposed to before, making the process seem confusing and a high barrier to start.

There are two use cases: creating a starter project from scratch, and starting with an existing project. My proposal is to leave starter project creation to odo create (which maybe could be simplified independently later), and use this issue to add an interactive mode to odo push so that it can be used even if you haven't created a component/devfile yet.

If a devfile exists, odo push would work as it does today. If there is no devfile, an interactive mode similar to odo create would prompt you with the minimal questions necessary to get started. Think of it as automatically switching over to odo create before proceeding, e.g.:

```
> odo push
This folder has never been deployed before, we need to ask a few questions to get started!
? Select the project type (devfile) from the following list [Use arrows to move, enter to select, type to filter]
> java-maven
  java-openliberty
  java-quarkus
...
```

## Why is this needed?
Lower the barrier to entry and make it easier to get started with odo and devfiles.

**Comment by valaparthvi** [comment]
/close
v3 implements this for `odo dev`.
