### ISSUE TITLE
Add tutorials under "Using odo" section to docusaurus based site

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/odo#4895]
/kind documentation
/kind task

## What mistake did you find / what is missing in the documentation?
This is a child issue of spawned from https://github.com/openshift/odo/issues/4664#issuecomment-875511836.

## What is the relevance of it?
"Using odo" section needs to be an end-to-end story where a user can follow every guide in a sequential order and achieve results using odo; OR they can pick up any guide from the middle and still be able to understand and follow the steps as long as they have followed the earlier guides in the sequence.

We will use [odo quickstart](https://github.com/dharmit/odo-quickstart) project across these guides. 

#### Sprint 206

- [ ] Environment Variables
- [ ] Continuous Development using `odo watch`
- [ ] Create URL to access the project
- [ ] Create and Link Services

#### Sprint 205

<details>

- [x] Create a component and push it (#4982)
- [ ] Environment Variables
- [ ] Continuous Development using `odo watch`
- [ ] Create URL to access the project
- [ ] Create and Link Services

</details>
All these to be shown for both k8s (using minikube) and OCP (using CRC) clusters.

#### Sprint 204

<details>

#### NOTE: we might need to add something in the below sequence, or need to change order; it's not 100% complete or accurate.
- [ ] Create Component
- [ ] Environment Variables
- [ ] Continuous Development
- [ ] Create URL
- [ ] Debug Applications
- [ ] Lifecycle Events
- [ ] Persistent Storage
- [ ] Push Specific Files
- [ ] Create and Link Services

</details>

**Comment by dharmit** [comment]
> "Using odo" section needs to be an end-to-end story where a user can follow every guide in a sequential order and achieve results using odo; OR they can pick up any guide from the middle and still be able to understand and follow the steps as long as they have followed the earlier guides in the sequence.

One more thing that we could aim for is to give the reader a way to pull a `devfile.yaml` in every tutorial. This `devfile.yaml` will help user set things up till the previous guide in the flow.

**Comment by dharmit** [comment]
Unassinging myself since it's mostly Charlie carrying this effort forward.

/unassign @dharmit

**Comment by valaparthvi** [comment]
/close
I think we have got this covered.
Feel free to reopen if you think otherwise.
