### ISSUE TITLE
Create VMs in IBM Cloud 

### ISSUE THREAD

**Issue by rnapoles-rh** [redhat-developer/odo#4897]
/kind task

## task
Create Windows VMs to run automated tests on IBM Cloud

## Acceptance Criteria 
- [x] Windows VM is available in IBM Cloud (requires Microsoft licensing, checking with IBM Cloud Migration team on this)
- [x] Linux VM

## Links 
- Related (mandatory): 
#4800 
#4798 
#4988 
#4989 
#4990

**Comment by dharmit** [comment]
In various calls we discussed using a VM on PSI for Jenkins or at least for the purpose of communicating with the worker nodes on IBM Cloud. But we're deciding to move even that VM to IBM Cloud so that we can circumvent network issues on PSI.

**Comment by rnapoles-rh** [comment]
Setting as Story, tasks will be created an linked to this one.
/kind story

**Comment by anandrkskd** [comment]
Windows VM on IBM cloud is now UP and configured, it can be used for test. 
Thus, Closing this issue
/close
