### ISSUE TITLE
End to end tests are doing something weird with OpenShift logins

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#491]
@ashetty1 

After each `make test-e2e` on my local machine with Minishift I'm getting this:

```
github.com/redhat-developer/odo  namespace ✔                                                                                                                                 18h17m
▶ ./odo list
User "developer" cannot list deploymentconfigs.apps.openshift.io in project "odo-1527689641"
```

when I try to go back to using Odo.

Are we doing something funky with oc login? I'm logged into "developer" the entire time, but I think we're doing e2e tests using an administrator account and it's not reverting back to the normal logon after...

Either way, I think that `make test-e2e` should use whatever account is currently logged in rather than the administrator account, the reason being is that it would be dangerous to do to a production / public cluster if the user runs `make test-e2e`.

**Comment by kadel** [comment]
> Either way, I think that make test-e2e should use whatever account is currently logged in rather than the administrator account, the reason being is that it would be dangerous to do to a production / public cluster if the user runs make test-e2e.

+1

**Comment by kadel** [comment]
ping @ashetty1

**Comment by ashetty1** [comment]
@cdrage @kadel we specifically do `oc login -u developer` before running the e2e tests.

**Comment by kadel** [comment]
> After each make test-e2e on my local machine with Minishift I'm getting this:
> 
> github.com/redhat-developer/odo  namespace ✔                                                                                                                                 18h17m
> ▶ ./odo list
> User "developer" cannot list deploymentconfigs.apps.openshift.io in project "odo-1527689641"
> when I try to go back to using Odo.

@cdrage I think that problem that you have there is that e2e tests are creating new projects, and deleting it afterwords. 

After last test is run, it deletes the project and leaves it activated in the kubectl config.
You can fix it easily wiht `oc project myproject` or some other project that you have there.

@ashetty1 could we save current project (`oc project -q`) before the first test is run and than get back to it after all test are done (`oc project`)?
