### ISSUE TITLE
Rollback new services and storage when starting a component fails

### ISSUE THREAD

**Issue by mik-dass** [redhat-developer/odo#4953]
/kind bug

## What versions of software are you using?

**Operating System:** Fedora

**Output of `odo version`:** master

## How did you run odo exactly?

- `odo create` && `odo push`
- Make push fails at `Waiting for component to start`

## Actual behavior

If push fails at the first waiting stage, `odo` should rollback the new storage and services.

## Expected behavior

`odo` cleans up the new storage and services if push fails.

**Comment by kadel** [comment]
this should not be an issue with new odo v3
/close
