### ISSUE TITLE
"app" is not a parameter in the odo environment file

### ISSUE THREAD

**Issue by mik-dass** [redhat-developer/odo#4959]
/kind bug

## What versions of software are you using?

**Operating System:** Fedora

**Output of `odo version`:** master

## How did you run odo exactly?

- Remove the app parameter from the env or use a old env file with no app support.
- `odo push` tries to write the default app name to the env but it fails.

## Actual behavior

`unknown parameter: "app" is not a parameter in the odo environment file`

## Expected behavior

`odo push` to succeed and write the default app name to the env file.

## Any logs, error output, etc?

Currently `app` is not marked as a supported parameter for the env file https://github.com/openshift/odo/blob/b2ca2a81a03d076cf1c6d24c3991363d6f1124e4/pkg/envinfo/envinfo.go#L420-L428

**Comment by tdiesler** [comment]
A newly generated env.yaml looks like this ...

```
ComponentSettings:
  Name: camel-quarkus-ticker2log
  Project: tdiesler-dev
  AppName: app
  RunMode: run
```

I would probably want to have AppName initialized a little better as well.
What is the difference between Name/AppName?

**Comment by tdiesler** [comment]
I also get ...

```
$ odo env set AppName camel-quarkus-ticker2log
 ✗  "AppName" is not a valid parameter to set, please refer `odo env set --help` to set a valid parameter
 ```

**Comment by mik-dass** [comment]
> What is the difference between Name/AppName?

`Name` is the component's name and `AppName` is the name of the app it belongs to in the project.

**Comment by valaparthvi** [comment]
/close
No longer relevant. We have stopped taking custom value of app.
