### ISSUE TITLE
odo should automatically show logs for long running `odo push` command

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/odo#4976]
/kind user-story

## User Story
As a user, I want odo to automatically display the logs on stdout for a component that takes more than a couple of minutes to push (`odo push`) so that I can know what odo's trying to do.

## Acceptance Criteria 
- [ ] It should start displaying logs (generally available via `odo push --show-log`) when a component takes more than X minutes to push successfully.

## Links 
- Related Epic (mandatory): NA

/kind user-story
/area component
/area UX

**Comment by dharmit** [comment]
This issue is the result of `odo push` taking exorbitantly long when trying to `odo push` the [Spring Boot petclinic](https://github.com/spring-projects/spring-petclinic) project for the first time:
```sh
 ✓  Executing build command "mvn clean -Dmaven.repo.local=/home/user/.m2/repository package -Dmaven.test.skip=true" [50m]
```
It took 50 minutes for the first push to go through!

This long duration is due to Java dependencies being pulled from the Internet. But for a user, this could be extremely frustrating. After a few minutes have elapsed since the starting of `odo push`, odo should start showing logs that it would otherwise show only if `--show-log` was passed.

**Comment by valaparthvi** [comment]
> when a component takes more than X minutes to push successfully.
We can use the `PushTimeout` or `BuildTimeout` value for X in this case.

**Comment by kadel** [comment]
/close 
in favor of https://github.com/redhat-developer/odo/issues/5716
