### ISSUE TITLE
odo reports several applications when a component is deployed with a service

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/odo#4991]
/kind bug

## What versions of software are you using?

**Operating System:** Win10Pro

**Output of `odo version`:** 2.2.4

## How did you run odo exactly?
 See the complete video

## Actual behavior

odo app list reports several applications

## Expected behavior

Only a single application should be reported

## Any logs, error output, etc?

https://user-images.githubusercontent.com/695993/129233639-7cd24755-8149-4c79-9181-84427d14a74c.mp4

**Comment by jeffmaury** [comment]
Still valid with 2.4.1

/remove-lifecycle stale

**Comment by kadel** [comment]
no longer with odo v3
/close
