### ISSUE TITLE
Add unit tests for operator hub based services

### ISSUE THREAD

**Issue by mohammedzee1000** [redhat-developer/odo#4997]
Currently, operator hub services are only tested as integration tests. We should add more testing(unit tests) for operator hub.

References:
https://github.com/openshift/odo/pull/4906#discussion_r690164035
https://github.com/openshift/odo/pull/4906#discussion_r690161466

**Comment by dharmit** [comment]
I can't find the issue where this was recently discussed, but we don't want to be having issues for adding tests. We want to try and add as many tests as we can while working on PRs for features/bugs.

**Comment by mohammedzee1000** [comment]
> I can't find the issue where this was recently discussed, but we don't want to be having issues for adding tests. We want to try and add as many tests as we can while working on PRs for features/bugs.

this is for tracking
