### ISSUE TITLE
Document `odo link` without Service Binging Operator (SBO)

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/odo#5000]
/kind documentation

## What mistake did you find / what is missing in the documentation?
`odo link` works without SBO for kubeadmin users. This needs to be documented on https://odo.dev.

## What is the relevance of it?
It's a pretty important feature that's lacking documentation.

/priority high
/area linking
(High because this was the sole reason we delayed 2.3 release by more than a Sprint!)

**Comment by kadel** [comment]
/close
not valid for v3
