### ISSUE TITLE
Document support for `preStart` events

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/odo#5001]
/kind documentation

## What mistake did you find / what is missing in the documentation?
odo now supports `preStart` events in devfile. We must document how advanced users (mainly devfiles authors) can use the feature.

## What is the relevance of it?
It's a feature that's not documented.

**Comment by dharmit** [comment]
IMO, this should be put in "Tutorials" section that will be added by the #4934.

**Comment by dharmit** [comment]
We already had something on the old website - https://github.com/openshift/odo/blob/gh-pages/docs/using-devfile-lifecycle-events.md.

**Comment by kadel** [comment]
> We already had something on the old website - https://github.com/openshift/odo/blob/gh-pages/docs/using-devfile-lifecycle-events.md.

shouldn't the migration of that document be part of  the https://github.com/openshift/odo/pull/5233 ?

**Comment by dharmit** [comment]
> shouldn't the migration of that document be part of the #5233 ?

https://deploy-preview-5233--odo-docusaurus-preview.netlify.app/docs/tutorials/using-devfile-lifecycle-events

**Comment by rm3l** [comment]
@dharmit @kadel Can we close this issue as complete? It seems that the documentation for this is available at https://odo.dev/docs/user-guides/advanced/using-devfile-lifecycle-events
