### ISSUE TITLE
Cleanup odo-init image of unnecessary logic

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/odo#5007]
odo-init image has certain hacks (variables and checks) in it to ensure things work well when using s2i builder images. Devfile provides support for adding these custom variables, which then odo should simply re-use. 

## Acceptance Criteria
- [ ] TBD

/kind cleanup
/triage needs-information

**Comment by dharmit** [comment]
/remove-lifecycle stale

@mohammedzee1000 @anandrkskd I vaguely remember one of you working on something along the lines of what this issue is about.

**Comment by anandrkskd** [comment]
TBH, I don't  remember working on anything similar.

**Comment by valaparthvi** [comment]
/close
We are no longer using odo-init image.
Feel free to reopen if I got this wrong.
