### ISSUE TITLE
Inconsistency between `odo list` and `odo list --path` outputs

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/odo#5029]
## What versions of software are you using?

**Operating System:** all

**Output of `odo version`:** `main`

## How did you run odo exactly?
See outputs of `odo list` and `odo list --path`.

## Actual behavior
```shell
$ odo list
APP     NAME          PROJECT       TYPE                STATE          MANAGED BY ODO   <---------
app     petclinic     petclinic     java-springboot     Not Pushed     Yes

$ odo list --path ~/src/spring-petclinic
Devfile Components:     <--------
APP     NAME          PROJECT       STATE          CONTEXT
app     petclinic     petclinic     Not Pushed     /home/dshah/src/spring-petclinic
```

## Expected behavior
* `odo list --path` should not have `Devfile Components` at the top.
* `odo list --path` should have `MANAGED_BY_ODO` column.

/area component
/kind bug

**Comment by dharmit** [comment]
Please refer to the discussion https://github.com/openshift/odo/pull/4948#discussion_r695404180 (GitHub might have hidden this; open up all conversations on the PR). Most importantly, please consider merging the following two functions in ` pkg/odo/cli/component/list.go`:
* `HumanReadableOutputInPath`
* `HumanReadableOutput`

There's quite a bit of duplication in the code of these functions. Merging these could help avoid a situation where we missed making the necessary changes in https://github.com/openshift/odo/pull/4962/.

**Comment by kadel** [comment]
we won't fix this in v2, and for v3 this is not valid anymore as we don't have `--path` flag
