### ISSUE TITLE
We should be able to create a mount / storage without name being passed.

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#504]
Similar to functionality with `url create`, we should be able to pass in / use storage without specifying a name (by default, it'll use the name of the current component).

**Comment by cdrage** [comment]
This shouldn't error:
```
github.com/redhat-developer/odo  namespace ✔                                                                                                                                    23m
▶ ./odo storage create --path=/opt/app-root/src/storage/ --size=1Gi
Error: accepts 1 arg(s), received 0
Usage:
  odo storage create [flags]

Examples:
  # Create storage of size 1Gb to a component
  odo storage create mystorage --path=/opt/app-root/src/storage/ --size=1Gi


Flags:
      --component string   Component to add storage to. Defaults to active component.
  -h, --help               help for create
      --path string        Path to mount the storage on
      --size string        Size of storage to add

Global Flags:
  -v, --verbose   Verbose output

accepts 1 arg(s), received 0
```

**Comment by kadel** [comment]
Agreed, the name should be optional and we should generate some nice default storage name if it is not provided by a user.

Name was defined as an optional argument in original `storage create` issue #226, but somehow we missed that.

How about generating storage name as `<component name>-<4 random letters>`?
Of course, we would still need to check for collisions.

**Comment by cdrage** [comment]
@kadel Yeah, that works! We could work with the four random letters if no component name was passed in. Similar to how Kubernetes does it with automatic provisioning.

**Comment by kadel** [comment]
related to #216
