### ISSUE TITLE
odo push fails with idled components 

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/odo#5041]
/kind bug

## What versions of software are you using?

**Operating System:**
MacOS 

**Output of `odo version`:**
odo v2.3.0 (089b8ea26)

## How did you run odo exactly?
odo push

## Actual behavior
After creating a component and doing `odo push` scale the pod count to 0 on the deployment. 
do a second `odo push` it fails  with 

```
Failed to start component with name "java-quarkus-test-wrhd". Error: Failed to create the component: unable to get pod for component java-quarkus-test-wrhd: error while waiting for pod component=java-quarkus-test-wrhd: waited 4m0s but couldn't find running pod matching selector: 'component=java-quarkus-test-wrhd'
```

`odo delete` in the same situation fails with
```
 pod not found for the selector: app.kubernetes.io/part-of=app,app.kubernetes.io/instance=java-quarkus-test-wrhd
```

## Expected behavior

Either `odo push` succeeds and scales the deployment 
or `odo delete` cleans the deployment so that `odo push` can follow

**Comment by dharmit** [comment]
It _might_ be a good idea to switch from ephemeral `true` by default to `false`, that is, use PVC by default to store the code instead of `emptyDir`; but we still do need to have ephemeral preference. Basically, reverse what was done in #4360.

**Comment by feloy** [comment]
We get the same result when setting Ephemeral to `false`, it is still not possible to push again or delete the component

**Comment by dharmit** [comment]
@kadel @feloy I'm still trying to figure out how to address this issue.

* As far as SSA is concerned, is https://github.com/dharmit/odo/commit/b11f5465f1d842c5820e5bb625daa9a2f059738c the right way to track the number of Replicas for the Deployment under SSA? With that change, `f:replicas` shows up under fields managed by the manager "odo" when we do `kubectl get deploy -o yaml`.

  But, we still have `getPod` call at https://github.com/redhat-developer/odo/blob/9342ddc0e1fe12790ffd3f3ae6732d4ca812d6fe/pkg/devfile/adapters/kubernetes/component/adapter.go#L131-L138
  which leads to the error in issue description. We still have dependency on the `podName` fetched using the above call.
* > check for Deployment with matching selector instead of Pod
  But our further logic is dependent on the `podName` that we get using `getPod` call. I'm not sure if it's OK to base things on getting Deployment instead. I can explore this more if you think it should be the way to go.
* > odo updates the Deployment that has been modified by the user, to scale it to 1.
  Do you mean that if someone scales the pods down to 0, odo should just automatically scale it back to 1 on next `odo push`? This would again require getting rid of dependency on `podName` that we are getting above.

It seems to me like our logic's dependency on `podName` is maybe hurting us.

**Comment by feloy** [comment]
> @kadel @feloy I'm still trying to figure out how to address this issue.
> 
> * As far as SSA is concerned, is [dharmit@b11f546](https://github.com/dharmit/odo/commit/b11f5465f1d842c5820e5bb625daa9a2f059738c) the right way to track the number of Replicas for the Deployment under SSA? With that change, `f:replicas` shows up under fields managed by the manager "odo" when we do `kubectl get deploy -o yaml`.

odo has sometimes to work directly on the pod (syncing files, getting logs, etc) and the pod should be unique for odo to work correctly (what would happen with 2 replicas, on which one to sync files?), so it makes sense for me that odo fixes the replicas to 1.

When odo does this, I understand like you that it will be the manager of this field and will change it back to 1 at the next SSA if needed.

>   But, we still have `getPod` call at https://github.com/redhat-developer/odo/blob/9342ddc0e1fe12790ffd3f3ae6732d4ca812d6fe/pkg/devfile/adapters/kubernetes/component/adapter.go#L131-L138
>   
>   which leads to the error in issue description. We still have dependency on the `podName` fetched using the above call.
> * > check for Deployment with matching selector instead of Pod
>   

As said before, odo needs to know, in some circumstances, the existence of the pod, for example when syncing files, getting logs, etc. But, IMHO, it should be limited to these use cases. In general, when it does not need to do anything within the pod, it should work directly with the deployment, which is the resource it manages itself.

In this case (in the `Push` function), I have mixed feelings. At the beginning of the function, getting the pod is used to check if there has been a rollout of the deployment, and later it is used to sync files to the pod. For syncing, I agree that odo needs to know the pod, but for rollout, it should be able to do this only with the deployment status/watching on the deployment.

>   
>   But our further logic is dependent on the `podName` that we get using `getPod` call. I'm not sure if it's OK to base things on getting Deployment instead. I can explore this more if you think it should be the way to go.
> * > odo updates the Deployment that has been modified by the user, to scale it to 1.
>   

>   
>   Do you mean that if someone scales the pods down to 0, odo should just automatically scale it back to 1 on next `odo push`? This would again require getting rid of dependency on `podName` that we are getting above.
> 

IMHO, the `Push` function should be splitted in two independent parts:
- the first one that updates (with SSA) the deployment => this will have some side effects, one of them will be to recreate a pod if the template changes.
- once the state of the cluster is stable (the deployment has been rolled out), the second step is to work on the (stable) pod, to sync files to it, etc


> It seems to me like our logic's dependency on `podName` is maybe hurting us.

**Comment by kadel** [comment]
> IMHO, the `Push` function should be splitted in two independent parts:
> 
> * the first one that updates (with SSA) the deployment => this will have some side effects, one of them will be to recreate a pod if the template changes.
> * once the state of the cluster is stable (the deployment has been rolled out), the second step is to work on the (stable) pod, to sync files to it, etc

:+1: 

That was exactly what I was going to suggest as I was reading @dharmit's comment. 

Basically every time odo needs to do something with Pod or container, it needs to make sure that there is one by applying update to the Deployment. It is odo's insurance that everything is in the correct state as defined in Devfile.

**Comment by dharmit** [comment]
@feloy @kadel thanks for your inputs.

I have opened a PR to address this. I have _not_ broken the `Push` function into two yet, but delayed fetching the `podName` till it's actually required. As a result, the call to `err = a.createOrUpdateComponent(componentExists, parameters.EnvSpecificInfo)` happens before the pod name is fetched, and this leads to an update in the state of Deployment.

I couldn't find anything wrong with this solution, but would like to know if you guys think this would be a wrong approach.

**Comment by feloy** [comment]
@dharmit The `getPod` function has the side effect to wait for the Pod to be in running state. This can have some impact on the code between the place it were called and the place where you moved it. For example, some code can expect that the pod is running, and it won't be the case anymore.

**Comment by dharmit** [comment]
@feloy Based on my understanding, even if we were checking for the pod's existence way earlier, we were never performing any action that was dependent on whether the pod exists.

**Comment by dharmit** [comment]
> @dharmit The `getPod` function has the side effect to wait for the Pod to be in running state. This can have some impact on the code between the place it were called and the place where you moved it. For example, some code can expect that the pod is running, and it won't be the case anymore.

This has indeed come back to bite me on the PR. The integration tests are failing.
