### ISSUE TITLE
odo list output for 'State' does not match the output of create and describe for a K8s non-kubeadmin user

### ISSUE THREAD

**Issue by valaparthvi** [redhat-developer/odo#5042]
/kind bug

## What versions of software are you using?

**Operating System:**
Fedora 34
**Output of `odo version`:**
odo v2.3.0 (fd6ebb27f)

## How did you run odo exactly?
1. Start minikube server.
2. Setup a developer user on minikube with https://gist.github.com/valaparthvi/dbff58d41decdba4938318c91205ab03. This user does not have access to any OpenShift resource.
3. ```mkdir /tmp/comp && cd /tmp/comp```
4. `odo create nodejs -ojson`; check the state
5. `odo describe -ojson`; check the state
6. `odo list -ojson` or `odo list`; check the state

## Actual behavior
1.
2.
3.
4. The state is `Unknown`. For a kubeadmin user, it will be `Not Pushed`.
5. The state is `Unknown`. For a kubeadmin user, it will be `Not Pushed`.
6. The state is `Not Pushed`. It is the same for a kubeadmin user.

## Expected behavior
1.
2.
3.
4.
5.
6. The state should be `Unknown` same as that of create and describe.

## Any logs, error output, etc?
There should be a common function that decides the state of a component for create, describe and list. Create, and describe seems to be using [component.go:GetComponentState()](https://github.com/openshift/odo/blob/main/pkg/component/component.go#L1453) to decide on the state, while list uses its own logic.
Create : https://github.com/openshift/odo/blob/main/pkg/odo/cli/component/create.go#L1019
Describe :
    1. https://github.com/openshift/odo/blob/main/pkg/odo/cli/component/describe.go#L61
    2. https://github.com/openshift/odo/blob/main/pkg/component/component_full_description.go#L118

**Comment by dharmit** [comment]
I wonder what you're using to create GH issues because "Actual Behaviour" section has points 4, 5 and 6 while 1, 2 and 3 are empty, and for "Expected Behaviour" only point 6 has some info. Rest are empty. See the screenshot.

![image](https://user-images.githubusercontent.com/713521/132236333-bd8f3444-051e-44f9-890e-8023e86cd12a.png)

**Comment by valaparthvi** [comment]
> I wonder what you're using to create GH issues because "Actual Behaviour" section has points 4, 5 and 6 while 1, 2 and 3 are empty, and for "Expected Behaviour" only point 6 has some info. Rest are empty. See the screenshot.
> 
> ![image](https://user-images.githubusercontent.com/713521/132236333-bd8f3444-051e-44f9-890e-8023e86cd12a.png)

It means that the actual behaviour in step 4,5 is correct, while the expected behaviour in step 6 should change. It is a practice we used to follow in my previous teams while writing testSteps and expectedResults. For the steps, you don't have an expected result as such, you leave it empty, it kinda comes natural to me now, so that is how I wrote the issue description.

**Comment by dharmit** [comment]
> It means that the actual behaviour in step 4,5 is correct, while that of step 6 should change as mentioned in the expected behaviour section. It is a practice we used to follow in my previous teams while writing testSteps and expectedResults. For the steps, you don't have an expected result as such, you leave it empty, it kinda comes natural to me now, so that is how I wrote the issue description.

I would have never managed to figure that out. Thanks for explaining.
