### ISSUE TITLE
odo fails if it does not have access to openshift resources even while using the minikube cluster

### ISSUE THREAD

**Issue by valaparthvi** [redhat-developer/odo#5043]
odo fails if it does not have access to these openshift resources, even in minikube. It could be interesting to open an issue, to make odo ignore resources that it cannot access, instead of failing

_Originally posted by @feloy in https://github.com/openshift/odo/pull/5032#discussion_r702601525_

See #5042 for example.
/kind bug

**Comment by dharmit** [comment]
> odo fails if it does not have access to these openshift resources, even in minikube

Maybe it's because of the OLM? Operators might need access to some resources usually found in an OCP installation.

**Comment by valaparthvi** [comment]
> > odo fails if it does not have access to these openshift resources, even in minikube
> 
> Maybe it's because of the OLM? Operators might need access to some resources usually found in an OCP installation.

No, we are talking about the classic resources such as routes and deploymentconfigs.

**Comment by kadel** [comment]
I belive this is no longer an issue in v4
/close
