### ISSUE TITLE
How to convey more information to users when linking (`odo link`) without SBO?

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/odo#5053]
## What versions of software are you using?

**Operating System:** all

**Output of `odo version`:** `main`

## How did you run odo exactly?
`odo link` was executed by a non-admin user on a cluster that didn't have Service Binding Operator installed. `odo push` was executed after linking.

## Actual behavior
`odo push` displays the following message when it detects the user is not privileged to list CRDs (as they are cluster-wide resources not accessible to non-admin users):
```sh
Creating Kubernetes resources for component java-springboot
 ✓  Waiting for component to start [1ms]
 ⚠  Skipping the check for CRD, user does not have access
 ⚠  Skipping the check for CRD, user does not have access
```

## Expected behavior
What more should odo display on CLI vs. what could/should be covered in the documentation?

/kind bug
/area linking

**Comment by kadel** [comment]
Isn't this duplication of https://github.com/openshift/odo/issues/4570#issuecomment-906415195?


This is exactly the same problem. Showing that information in `odo link ` is hard, as the actual link is created later when you execute `odo push`.  Whatever the SBO is installed or not doesn't change this flow.

**Comment by kadel** [comment]
no `odo link` in v3
/close
