### ISSUE TITLE
Update operator document about mphealth version for Power

### ISSUE THREAD

**Issue by sjagadale** [redhat-developer/odo#5073]
/kind documentation

## What mistake did you find / what is missing in the documentation?

For JPA part In https://odo.dev/docs/tutorials/deploying-java-app-with-database, Power don’t support mphealth-3.0 version based their openliberty image, so in https://github.com/OpenLiberty/application-stack-samples.git, need to change to mphealth-2.0 for Power. We want doc the change here to replace the version by one command like sed.

**Comment by kandarpamalipeddi** [comment]
We can add a new point before this [line](https://odo.dev/docs/tutorials/deploying-java-app-with-database/#:~:text=Initialize%20the%20application%3A). (i.e., before - 3. Initialize the application: odo create java-openliberty mysboproj)

In case of IBM Z and Power architectures, replace mphealth version as 2.0, using below command:
sed -i "s/mpHealth-3.0/mpHealth-2.0/" src/main/liberty/config/server.xml

**Comment by sjagadale** [comment]
similar issue raised for Z platform as well - https://github.com/openshift/odo/issues/5071

**Comment by scottkurz** [comment]
There's a more fundamental issue here, which is that the https://odo.dev/docs/tutorials/deploying-java-app-with-database/  sample uses the java-openliberty devfile in the default devfile registry, which uses the **openliberty/application-stack** image that is amd64 only.   

We plan to publish multi-arch versions of this image for p/z but haven't yet.   

I'm confused because documenting the use of an alternative devfile with alt. image seems to be required before changing the Liberty config (server.xml) within the doc.

**Comment by kandarpamalipeddi** [comment]
As per the documentation mentioned at https://odo.dev/docs/tutorials/deploying-a-devfile-using-odo-on-IBM-Z-and-Power, CRW images are being used in case of IBM Z and Power.

As of now, we (IBM Z & P) are building our own devfile registry with CRW images and using it in ODO testing (Will have to do it till we get the multi-arch images). 

Who ever are going to use ODO on Z & P, they have to use the CRW images in the devfile registry for now.

Java-openliberty CRW image is not supporting mphealth-3.0, so we need this document entry for now.

**Comment by scottkurz** [comment]
> Java-openliberty CRW image is not supporting mphealth-3.0, so we need this document entry for now.

My guess is it's not the _image_ which isn't supporting mpHealth-3.0, but rather it's your devfile which is referencing an older version of Liberty.   You probably don't include Liberty in the image itself. 

Is your devfile source somewhere public?

**Comment by kandarpamalipeddi** [comment]
As of now, I am using the latest version of the openliberty images available on CRW i.e., `registry.redhat.io/codeready-workspaces/plugin-java11-openj9-rhel8:latest`
I tried it again yesterday and I am facing the same issue.

You can find the similar devfile at : https://github.com/kandarpamalipeddi/registry/blob/master/devfiles/java-openliberty/devfile.yaml

**Comment by scottkurz** [comment]
> 
> 
> As of now, I am using the latest version of the openliberty images available on CRW i.e., `registry.redhat.io/codeready-workspaces/plugin-java11-openj9-rhel8:latest`
> I tried deploying the openliberty app again yesterday and I am facing the same issue.
> 
> You can find the similar devfile at : https://github.com/kandarpamalipeddi/registry/blob/master/devfiles/java-openliberty/devfile.yaml

Try doing a find/replace 20.0.0.10 -> 21.0.0.6.   If you look at the latest java-openliberty devfile: https://github.com/devfile/registry/blob/main/stacks/java-openliberty/devfile.yaml   it uses this more recent version.

**Comment by kandarpamalipeddi** [comment]
@scottkurz 

Following are the logs with the liberty version 20.0.0.10.
```
[root@api.odo-ocp48-1.cp.fyre.ibm.com jpa]# odo push

Validation
 ✓  Validating the devfile [68648ns]

Creating Services for component mysboproj
 ✓  Services are in sync with the cluster, no changes are required

Creating Kubernetes resources for component mysboproj
 ✓  Waiting for component to start [13s]
 ✓  Links are in sync with the cluster, no changes are required
 ✓  Waiting for component to start [12ms]

Applying URL changes
 ✓  URL ep1: http://ep1-app-testservicebinding.apps.odo-ocp48-1.cp.fyre.ibm.com/ created

Syncing to component mysboproj
 ✓  Checking files for pushing [4ms]
 ✓  Syncing files to the component [2s]

Executing devfile commands for component mysboproj
 ✓  Executing build command "if [ -e /projects/.disable-bld-cmd ]; then echo \"found the disable file\" && echo \"devBuild command will not run\" && exit 0; else echo \"will run the devBuild command\" && mkdir -p /projects/target/liberty && if [ ! -d /projects/target/liberty/wlp ]; then echo \"...moving liberty\"; mv /opt/ol/wlp /projects/target/liberty; touch ./.liberty-mv; elif [[ -d /projects/target/liberty/wlp && ! -e /projects/.liberty-mv ]]; then echo \"STACK WARNING - LIBERTY RUNTIME WAS LOADED FROM HOST\"; fi && mvn -Dliberty.runtime.version=20.0.0.10 package && touch ./.disable-bld-cmd; fi" [1m]
 ✓  Executing run command "mvn -Dliberty.runtime.version=20.0.0.10 -Ddebug=false -DhotTests=true -DcompileWait=3 liberty:dev", if not running [2s]

Pushing devfile component "mysboproj"
 ✓  Changes successfully pushed to component


[root@api.odo-ocp48-1.cp.fyre.ibm.com jpa]# odo log -f
...
...
...
[INFO] Installing features: [jsf-2.3, cdi-2.0, jdbc-4.3, jpa-2.2, mphealth-3.0, jaxrs-2.1]
Downloading from central: https://repo.maven.apache.org/maven2/io/openliberty/features/repository-resolver/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/io/openliberty/features/repository-resolver/maven-metadata.xml (358 B at 3.1 kB/s)

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:01 min
[INFO] Finished at: 2021-09-22T07:32:45Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.openliberty.tools:liberty-maven-plugin:3.3.5-M2:dev (default-cli) on project jpa-starter-app: CWWKF1299E: The following features could not be obtained: mphealth-3.0. Ensure that the features are valid for Open Liberty. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
```

As per your suggestion, I tried replacing the version with 21.0.0.6 in the devfile and build is working fine.
Below is the log:
```
[root@api.odo-ocp48-1.cp.fyre.ibm.com jpa]# odo push

Validation
 ✓  Validating the devfile [51180ns]

Creating Services for component mysboproj
 ✓  Services are in sync with the cluster, no changes are required

Creating Kubernetes resources for component mysboproj
 ✓  Waiting for component to start [21s]
 ✓  Links are in sync with the cluster, no changes are required
 ✓  Waiting for component to start [32ms]

Applying URL changes
 ✓  URLs are synced with the cluster, no changes are required.

Syncing to component mysboproj
 ✓  Checking file changes for pushing [4ms]
 ✓  Syncing files to the component [1s]

Executing devfile commands for component mysboproj
 ✓  Executing build command "if [ -e /projects/.disable-bld-cmd ]; then echo \"found the disable file\" && echo \"devBuild command will not run\" && exit 0; else echo \"will run the devBuild command\" && mkdir -p /projects/target/liberty && if [ ! -d /projects/target/liberty/wlp ]; then echo \"...moving liberty\"; mv /opt/ol/wlp /projects/target/liberty; touch ./.liberty-mv; elif [[ -d /projects/target/liberty/wlp && ! -e /projects/.liberty-mv ]]; then echo \"STACK WARNING - LIBERTY RUNTIME WAS LOADED FROM HOST\"; fi && mvn -Dliberty.runtime.version=21.0.0.6 package && touch ./.disable-bld-cmd; fi" [1m]
 ✓  Executing run command "mvn -Dliberty.runtime.version=21.0.0.6 -Ddebug=false -DhotTests=true -DcompileWait=3 liberty:dev", if not running [2s]

Pushing devfile component "mysboproj"
 ✓  Changes successfully pushed to component

[root@api.odo-ocp48-1.cp.fyre.ibm.com jpa]# odo log -f
[INFO] Scanning for projects...
...
...
...
[INFO] Compiling 1 source file to /projects/target/test-classes
[INFO] Running liberty:create
[INFO] The liberty.runtime.version property value 21.0.0.6 is used for the runtimeArtifact version.
[INFO] CWWKM2102I: Using artifact based assembly archive : io.openliberty:openliberty-kernel:null:21.0.0.6:zip.
[INFO] CWWKM2102I: Using installDirectory : /projects/target/liberty/wlp.
[INFO] CWWKM2102I: Using serverName : defaultServer.
[INFO] CWWKM2102I: Using serverDirectory : /projects/target/liberty/wlp/usr/servers/defaultServer.
[INFO] Installing assembly...
[INFO] Expanding: /home/jboss/.m2/repository/io/openliberty/openliberty-kernel/21.0.0.6/openliberty-kernel-21.0.0.6.zip into /projects/target/liberty
[INFO] CWWKM2143I: Server defaultServer does not exist. Now creating...
[INFO] CWWKM2001I: Invoke command is [/projects/target/liberty/wlp/bin/server, create, defaultServer].
[INFO]
[INFO] Server defaultServer created.
[INFO] CWWKM2129I: Server defaultServer has been created at /projects/target/liberty/wlp/usr/servers/defaultServer.
...
...
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 4.185 s <<< FAILURE! - in org.example.app.it.DatabaseIT
[ERROR] testGetAllPeople  Time elapsed: 2.349 s  <<< ERROR!
java.lang.NullPointerException
        at org.example.app.it.DatabaseIT.testGetAllPeople(DatabaseIT.java:67)

[ERROR] testGetPerson  Time elapsed: 0.231 s  <<< ERROR!
java.lang.NullPointerException
        at org.example.app.it.DatabaseIT.testGetPerson(DatabaseIT.java:55)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   DatabaseIT.testGetAllPeople:67 NullPointer
[ERROR]   DatabaseIT.testGetPerson:55 NullPointer
[INFO]
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0
```

As application built successfully, we will made changes in the devfile and no documentation changes required.

Thanks for the clarification.

We are good to close this issue.
