### ISSUE TITLE
add flag to select which logs to see (all by default)

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#508]
When running "odo log" you get all logs concatenated. It would be good to be able to provide flags to select which logs to see, build or run, and all by default.

Name for these flags are not clear to me, but maybe `build` and `run` could fit. And possibly in the future, if needed, `deploy` although I don't think these would be interesting for the developer.

**Comment by kadel** [comment]
If I understand that correctly, by 'build' log you mean output from `assemble` script, and 'run' log would be output from running application (`run` script).

This might be bit tricky. Currently, we direct both outputs to stdout so it can be seen in OpenShift Web Console.
We might redirect `assemble` output to file to separete it, but that means that it won't be seen in Logs section in web console.

**Comment by jorgemoralespou** [comment]
@kadel hum...
We then would need to think this for a bit. As a developer I would like to be able to see both logs differentiated but also seeing the logs aggregated would make sense.

Adding @marekjelen and @gshipley to the conversation

**Comment by marekjelen** [comment]
Not sure I follow ... build logs (`assemble`) and runtime logs (`run`) are two different endpoints in the API that do not overlap.

**Comment by jorgemoralespou** [comment]
But in our scenario the build is run within a running pod, so it's the same
process and not 3 different processes.

**Comment by kadel** [comment]
The problem during build application is still running and producing logs. So you can end up with log like this:  
```
line from build phase
line form running app 
line from build phase
```

**Comment by jorgemoralespou** [comment]
We should explore what other options we have regarding to produce multiple
logs in a running container and properly labeling content coming from each
different log so that this can be done. Maybe @mfojtik and anyone on his
team might have an idea on how they would accomplish this.

Sadly, docker just logs stdout and stderr which are /proc/self/fd/1 and
/proc/self/fd/2. If any of the logging drivers could also take into account
any /proc/self/fd/* then we could smartly have outputs logging to different
files and then presenting it to clients in a seamless way. To me, this is a
flaw in docker logging. Maybe CRI-O could help in the future.
