### ISSUE TITLE
Allow user to perform outer loop build/deploy with CLI args, (without changing contents of devfile)

### ISSUE THREAD

**Issue by scottkurz** [redhat-developer/odo#5080]
/kind user-story

## User Story
As an application deployer (e.g. perhaps in writing a pipeline build task), I want to perform an image build and deploy (or possibly build only) with substitutions for devfile variables provided at build time.   (I don't want to necessarily have to express my customization as a devfile file, even using child/parent extension).    

This would be analogous to docker build-arg, e.g.: `docker build --build-arg abc=123`.

## Acceptance Criteria 
- [ ] odo should allow a CLI argument to be passed to override a devfile variable value, and to use this value in all aspects of outer loop build and/or deploy.

## Links 
- Related Epic (mandatory): ?

1. This would prereq and build on the support described here:  https://github.com/openshift/odo/issues/2756 , (now making its way into devfile library, e.g. here:  https://github.com/devfile/api/pull/580)
2. This might leverage https://github.com/openshift/odo/issues/4838, which could be a sort of "soft" prereq.

### NOTE:

This could also prompt the question "why not allow this on other commands?", e.g. "push" and "test".   This could get tricky because of pod state... e.g. 'push' may or may not start a new pod.. should it try to be smart about deciding whether to if the devfile variable values change?   OTOH, 'test' does not ever start a new pod.. so is it safer (if possibly wrong / user error) to allow new variable values?    Some things to think about...

/kind user-story

**Comment by yangcao77** [comment]
Devfile library release contains outerloop support: https://github.com/devfile/library/releases/tag/v1.2.0

**Comment by rm3l** [comment]
I think this has been addressed with the variable substitution feature we added in v3 to `odo dev` and `odo deploy` commands.
See https://odo.dev/docs/command-reference/dev#substituting-variables and https://odo.dev/docs/command-reference/deploy#substituting-variables

ref #5489

**Comment by rm3l** [comment]
Closing this issue as completed in [v3.0.0](https://github.com/redhat-developer/odo/releases/tag/v3.0.0) (https://github.com/redhat-developer/odo/issues/5489), but feel free to reopen if you think otherwise.

FYI, there is a separate issue for also supporting variable substitution when performing image builds: https://github.com/redhat-developer/odo/issues/6274

/close
