### ISSUE TITLE
`odo service create && odo push` should automatically link the service to component

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/odo#5085]
/kind feature

## Which functionality do you think we should add?
Earlier, services were not tied to the odo component the way they are now. In the sense, `odo service create` was possible to be executed from any location on user's system and not just from a valid component directory containing a `devfile.yaml`. However, now, `odo service create` fails if not executed from a valid component directory.

The flow to link such a service to a component looks like below:
```sh
$ odo service create <operator-name>/<cr-name> someName    # adds service's manifest to devfile.yaml
$ odo push    # creates the service on cluster

$ odo link <cr-name>/someName    # adds link information to devfile.yaml
$ odo push    # to actually setup a link between the service and component
```

It would be better if odo created a link by default for such service with a flag to opt-out.
1. Create a link by default
    ```sh
    $ odo service create <operator-name>/<cr-name> someName    # adds both the service's & link's manifest to devfile.yaml
    $ odo push    # creates the service on cluster and links it to the component as well
    ```

2. Flag to opt-out
    ```sh
    $ odo service create <operator-name>/<cr-name> someName --no-link
    $ odo push
    ```
    In this case, flow to link such a service to the component remains the same as it is presently.

## Why is this needed?
For better UX. Because if user didn't want to link such a service to a component, why would they have even created it?

/area linking
/area UX

**Comment by kadel** [comment]
> Earlier, services were not tied to the odo component the way they are now.

This is not ideal situation and it is something that we will need to address in the future. We need to decouple services and components.

> It would be better if odo created a link by default for such service with a flag to opt-out.

Adding link capability to `odo service create` is a good idea. But I would change it from opt-out to opt-in.
It will be safer. We can always change it later once we know how service and components should be structured.

```
odo service create <operator-name>/<cr-name> someName --link
```

/priority  medium

**Comment by valaparthvi** [comment]
/close
v3 `odo link` and `odo dev` implement this.
