### ISSUE TITLE
Start tracking how many people visit odo.dev

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5106]
We should start collecting some metrics for odo.dev website, to see if and how people use odo website and documentation.

We can start with simple metrics like how many people visit website and what pages.

/priority medium
/kind documentation

**Comment by dharmit** [comment]
Do you mean https://docs.netlify.com/monitor-sites/analytics/?

**Comment by kadel** [comment]
Orignaly I meant via Segment and Woopra like we have for telemetry, but if there is something form Netlify directly it should be ok.

**Comment by kadel** [comment]
It looks like Netlify Analytics is $9/month and it has only 30 days history. 

Let's go with Woopra and Segment, as we are already paying for that and it will give us longer history
