### ISSUE TITLE
Support `image` component and `deploy` devfile command / initial `odo deploy` implementation

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5109]
/kind user-story

## User Story
As a developer I want to be able to use devfile.yaml with outer loop support (using devfile's `image` component and `deploy` command)

## Acceptance Criteria 
- [x] #5145
- [x] #5151

## Links 
- Related Epic (mandatory):  https://github.com/openshift/odo/issues/2756

## Implementation notes
- `odo deploy` should use local machine to build the image
- autodetect and use container engine that is available on the local machine (we will start with podman or docker)
- interaction with container engine? Executing cli vs apis (https://docs.podman.io/en/latest/_static/api.html, https://docs.docker.com/engine/api/) Starting with simply executing cli might be easier, as both podman and docker have more or less same interface)
- there is no odo or devfile specific way to handle image registry credentials, it will reduce whatever is configured for local container engine (set by `docker login` or `podman login`)

## Open questions:
- how to make sure that application deployed using `odo push` doesn't collide  with `odo deploy`? 

/kind user-story

**Comment by scottkurz** [comment]
Just reacting to:
> there is no odo or devfile specific way to handle image registry credentials, it will reduce whatever is configured for local container engine 

There is [this example](https://github.com/devfile/api/blob/main/docs/proposals/devfile/outer-loop-build-and-deploy.md#example-using-a-dockerfile-with-registry-and-secret-for-the-image-push) in the outer loop proposal.   

Maybe that'd be good for a later issue/story.

**Comment by kadel** [comment]
> * add support for building images using podman _and_ docker in the first iteration (using `os.Exec`, no APIs)

created https://github.com/openshift/odo/issues/5145 to capture this


> * add support for composite commands (@kadel to provide an example other than a devfile that has deploy)

issue already exists https://github.com/openshift/odo/issues/5054

I'll add example to #5054

**Comment by serenamarie125** [comment]
@kadel is it fair to say that we will support devfile 2.2 with this?

**Comment by kadel** [comment]
> @kadel is it fair to say that we will support devfile 2.2 with this?

yes, this was only new thing added in 2.2, so after this is implemented we can say that odo supports devfile 2.2

**Comment by dharmit** [comment]
@kadel can you open an issue for `odo undeploy` or `odo deploy --delete` whatever it is that we would want to use to delete the resource deployed by `odo deploy`?

Also, should we have some command to show the user a list of resources (deployed by `odo deploy`) along with their state? I'm drawing parallels with `odo component list` command, which tells the user if the component is pushed. Similarly `odo url list`, `odo service list`. How would a user know the state of the resources created by `odo deploy`?

**Comment by kadel** [comment]
> @kadel can you open an issue for `odo undeploy` or `odo deploy --delete` whatever it is that we would want to use to delete the resource deployed by `odo deploy`?

https://github.com/openshift/odo/issues/5246




> Also, should we have some command to show the user a list of resources (deployed by `odo deploy`) along with their state? I'm drawing parallels with `odo component list` command, which tells the user if the component is pushed. Similarly `odo url list`, `odo service list`. How would a user know the state of the resources created by `odo deploy`?

feel free to create issue for that

**Comment by kadel** [comment]
implemented in #5228 
/close
