### ISSUE TITLE
use of existing Dockerfile

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5110]
## Prerequisite
- https://github.com/openshift/odo/issues/5109

## User Story

As a developer I want to be able to build image for my application using my **already existing** Dockerfile and deploy it to the cluster.

## Scenario
```
git clone myproject
# project already contains Dockerfile

odo push
# autodetect language
# build image
# push to cluster using devfile deploy command
```

## Acceptance Criteria

/kind user-story

**Comment by kadel** [comment]
/blocked
on #5109

**Comment by kadel** [comment]
> I think this will be taken care of by #5192. @kadel @feloy WDYT?

No, this is something bit different

**Comment by dharmit** [comment]
@kadel can you please help refine this one?

/triage needs-information

**Comment by kadel** [comment]
With `odo deploy` implemented and with outerloop support in devfile it is easy to create a devfile for this use case. I've created simple example https://github.com/kadel/devfile-nodejs-deploy/blob/2b7058af5cdac5a43ded2b6c44454add7cf82161/devfile.yaml#L56
