### ISSUE TITLE
Add documentation in Command Reference section

### ISSUE THREAD

**Issue by feloy** [redhat-developer/odo#5111]
/kind documentation

Document the different odo commands:

- [x] odo catalog (#5095)
- [x] odo create (@dimitraz - https://github.com/openshift/odo/pull/5173)
- [x] odo service (#5095)
- [ ] odo project
- [ ] odo component
- [ ] odo storage
- [ ] odo url
- [ ] odo debug
- [ ] odo registry (#5095)
- [ ] odo config
- [ ] odo env
- [ ] odo preference

If you are interested in participating to this issue, please:
- select a page from the list above
- write your GitHub ID on the selected line
- read the documentation https://github.com/openshift/odo/blob/main/website/docs/contributing/docs.md

When you have written the documentation for the page:
- create a new PR and commit the page you have written
- add the PR number on the selected line above

**Comment by dimitraz** [comment]
Hi 👋  I wouldn't mind documenting `odo create`, if you want to add my github username next to it

**Comment by feloy** [comment]
> Hi wave I wouldn't mind documenting `odo create`, if you want to add my github username next to it

Hi @dimitraz, I added your username. Thanks for your help :)

**Comment by mehabhalodiya** [comment]
Hi
I want to contribute but I am not familiar with any of the above `odo` commands.
Can someone please help me to get started?

**Comment by feloy** [comment]
> Hi I want to contribute but I am not familiar with any of the above `odo` commands. Can someone please help me to get started?

Hi @mehabhalodiya, welcome :)
You can have a look at this article to start using odo: https://dev.to/feloy/odo-a-tool-to-simplify-development-on-kubernetes-5c9a

**Comment by cdrage** [comment]
Closing this as this has been covered for `v2` and we are not working on `v3` documentation
