### ISSUE TITLE
odo / devfile library give non-intuitive behavior with parent uri set to relative path within local filesystem

### ISSUE THREAD

**Issue by scottkurz** [redhat-developer/odo#5115]
/kind bug

## What versions of software are you using?

**Operating System:** Win 10

**Output of `odo version`:** v2.3.1

### Start with two devfiles in local filesystem:

> ./child.yaml
> ./parent/devfile.yaml

Contents of **child.yaml** include

```yaml
parent:
  uri: "./parent/devfile.yaml"
```

### Run odo create 
> odo create comp --devfile ./child.yaml

## Actual behavior

Go panic stack trace, stack pasted below

## Expected behavior

I expect the relative URI to resolve to **./parent/devfile.yaml**

### NOTE 1

From reading the devfile library [code](https://github.com/devfile/library/blob/f858c8ef8ba970e6035787e089766fe714c9792e/pkg/devfile/parser/parse.go#L288-L304), it looks like it's only going to join/merge the relative URI in with the child path if the **absPath** is set on the context.   But there doesn't seem to be a path set on the devfile context, instead the devfile is streamed in as a string/bytes.  So ultimately we don't end up resolving the parent URI reference.

### DESIGN QUESTION?

A key design question: should the relative URI be calculated relative to the original location of the **child.yaml** devfile that was passed via `odo create --devfile child.yaml` ?  Or should it be calculated relative to the directory root (since that is where odo is going to write the devfile.yaml, copying it from its original location)?

## Any logs, error output, etc?

> github.com/devfile/library/pkg/devfile/parser/context.(*DevfileCtx).SetDevfileContent(0xc0007fb188, 0x2f, 0xc00042ae80)
>         /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/devfile/library/pkg/devfile/parser/context/content.go:62 +0xcd
> github.com/devfile/library/pkg/devfile/parser/context.(*DevfileCtx).Populate(0xc0007fb188, 0x0, 0x0)
>         /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/devfile/library/pkg/devfile/parser/context/context.go:94 +0xe6
> github.com/devfile/library/pkg/devfile/parser.populateAndParseDevfile(0x0, 0x0, 0xc0002d7180, 0x2f, 0x20ed4dd, 0xc, 0x0, 0x0, 0x0, 0x0, ...)
>         /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/devfile/library/pkg/devfile/parser/parse.go:140 +0x305
> github.com/devfile/library/pkg/devfile/parser.parseFromURI(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00064d660, ...)
>         /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/devfile/library/pkg/devfile/parser/parse.go:321 +0x345
> github.com/devfile/library/pkg/devfile/parser.parseParentAndPlugin(0xc00064d660, 0x5, 0x0, 0x0, 0x0, 0x0, 0xc000788d00, 0xc6, 0xd0, 0x21f2e5b, ...)
>         /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/devfile/library/pkg/devfile/parser/parse.go:195 +0x16d8
> github.com/devfile/library/pkg/devfile/parser.parseDevfile(0xc00064d660, 0x5, 0x0, 0x0, 0x0, 0x0, 0xc000788d00, 0xc6, 0xd0, 0x21f2e5b, ...)
>         /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/devfile/library/pkg/devfile/parser/parse.go:51 +0x2e5
> github.com/devfile/library/pkg/devfile/parser.populateAndParseDevfile(0xc00064d660, 0x5, 0x0, 0x0, 0x0, 0x0, 0xc000788d00, 0xc6, 0xd0, 0x21f2e5b, ...)
>         /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/devfile/library/pkg/devfile/parser/parse.go:146 +0x207
> github.com/devfile/library/pkg/devfile/parser.ParseDevfile(0x0, 0x0, 0x0, 0x0, 0xc00078a400, 0xc5, 0x200, 0x0, 0x0, 0x0, ...)
>         /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/devfile/library/pkg/devfile/parser/parse.go:113 +0x2e7
> github.com/devfile/library/pkg/devfile.ParseDevfileAndValidate(0x0, 0x0, 0x0, 0x0, 0xc00078a400, 0xc5, 0x200, 0x0, 0x0, 0x0, ...)
>         /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/devfile/library/pkg/devfile/parse.go:77 +0xd8
> github.com/openshift/odo/pkg/devfile.parseDevfile(0x0, 0x0, 0x0, 0x0, 0xc00078a400, 0xc5, 0x200, 0x0, 0x0, 0x0, ...)
>         /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/devfile/devfile.go:14 +0xd8
> github.com/openshift/odo/pkg/devfile.ParseFromData(...)
>         /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/devfile/devfile.go:51
> github.com/openshift/odo/pkg/odo/cli/component.(*CreateOptions).devfileRun(0xc00036e600, 0xc00055e000, 0x0, 0x0)
>         /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/create.go:860 +0x187
> github.com/openshift/odo/pkg/odo/cli/component.(*CreateOptions).Run(0xc00036e600, 0xc00055e000, 0x0, 0x0)
>         /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/create.go:959 +0xb05
> github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun(0x2438340, 0xc00036e600, 0xc00055e000, 0xc0007834e0, 0x1, 0x1)
>         /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:97 +0x459
> github.com/openshift/odo/pkg/odo/cli/component.NewCmdCreate.func1(0xc00055e000, 0xc0007834e0, 0x1, 0x1)
>         /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/create.go:1054 +0x65
> github.com/spf13/cobra.(*Command).execute(0xc00055e000, 0xc0007834c0, 0x1, 0x1, 0xc00055e000, 0xc0007834c0)
>         /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:856 +0x2c2
> github.com/spf13/cobra.(*Command).ExecuteC(0xc0002e0780, 0xc00004a118, 0x1e4c0a0, 0x3310a30)
>         /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:960 +0x375
> github.com/spf13/cobra.(*Command).Execute(...)
>         /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:897
> github.com/spf13/cobra.(*Command).ExecuteContext(...)
>         /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:890
> main.main()
>         /builddir/build/BUILD/gocode/src/github.com/openshift/odo/cmd/odo/odo.go:70 +0x430

**Comment by scottkurz** [comment]
Wondering if are there any examples of filesystem-based relative URI parents working in any devfile tooling?

**Comment by kadel** [comment]
> A key design question: should the relative URI be calculated relative to the original location of the **child.yaml** devfile that was passed via `odo create --devfile child.yaml` ? Or should it be calculated relative to the directory root (since that is where odo is going to write the devfile.yaml, copying it from its original location)?

It should be relative to the child devfile  location. This is defined in devfile specification:

> URI Reference of a parent devfile YAML file. It can be a full URL or a relative URI with the current devfile as the base URI.

**Comment by scottkurz** [comment]
> It should be relative to the child devfile location. This is defined in devfile specification:
> 
> > URI Reference of a parent devfile YAML file. It can be a full URL or a relative URI with the current devfile as the base URI.

So if I do:  `odo create --devfile .../somedir/child.yaml`, I understand :  `odo create --devfile ..`  will make a copy into the project root, (as **devfile.yaml**).

That seems to suggest either:
* odo should copy parents referred to via relative URI in the filesystem into the project root to preserve the validity
  OR
* users should not rely on relative URIs (since next time we validate the parent reference may become invalid).



#5112

**Comment by kadel** [comment]
This is getting a little complicated with how the parent is defined in devfile spec. 

I think that the best behavior for something like `odo create --devfile .../somedir/child.yaml` would be that odo checks if `parent` is referenced using relative path, and if it is, it will update path to be a correct one once the file is placed into the current directory.

But I'm also wondering if `--devfile` flag still makes sense. It was originally added for a different use case. And I'm starting to think that it is just adding more confusion.

**Comment by scottkurz** [comment]
> But I'm also wondering if `--devfile` flag still makes sense. It was originally added for a different use case. And I'm starting to think that it is just adding more confusion.

@kadel  - I think I lost the main thread here by mentioning the `--devfile` case.   I was hedging even in my description "...non-intuitive..." thinking maybe there's a path through the relative parent URI that works that I just hadn't found.

### Primary Problem

Even leaving aside the `--devfile` case, I can create the core problem with a devfile like:

```yaml
parent:
  uri: "./parent/devfile.yaml"
```

doing `odo create comp`.

### Secondary Problem

I thought the question:  "what is the base dir to resolve a relative URI against?" question was interesting for `odo create --devfile... `.

IMO, it would be fine to say that the base dir is the project root, and not bother having odo trying to adjust/rewrite relative path values in the process of copying to the project root.       But maybe this is a corner case anyway.

I'd hate to get rid of this altogether.  It is nice for referencing a devfile that's not part of a registry, e.g.: 

`odo create --devfile https://github.com/OpenLiberty/application-stack/releases/download/maven-0.7.0/devfile.yaml myc`

**Comment by mohammedzee1000** [comment]
I agree that updating the path is a risky maneuver. Relative paths have always had a high risk of breaking and any programmer of substance should be aware of this (symlinks, windows shortcuts anyone).

This would especially be true in the case of git repos or any remotes for that matter, as different people clone their repos differently (on different locations).

I think it would be safer to simply copy the  parent devfile with a random name into the context somewhere and update the relative link. The ony problem though is what if someone updates the original parent?

**Comment by mohammedzee1000** [comment]
Scope of this issue:
 - [ ] Fix library/odo code to consider relative paths for devfile (it currently only considers only absolute paths). I recommend making odo parse the relative urls to absolute before passing it on
 - [ ] Add tests to ensure that the logic works
 - [ ] Opetional: warn user when he uses relative paths that they can break under certain conditions

**Comment by valaparthvi** [comment]
I am unable to reproduce this panic with odo v2.4.0, but I do run into error while parsing the devfile. It seems that the `child.yaml` is not a valid devfile, you need to define a `schemaVersion` in order for it work, and on adding the `schemaVersion`, it seems that the devfile is properly parsed and an odo component is created.

Directory structure:
```sh
➜  tree
.
├── child.yaml
└── parent
    └── devfile.yaml

1 directory, 2 files
```
**child.yaml**
```yaml
schemaVersion: 2.2.0
parent:
    uri: ./parent/devfile.yaml
```

```sh
➜  odo create --devfile ./child.yaml
Devfile Object Creation
 ✓  Creating a devfile component from devfile path: /tmp/sess/child.yaml [51561ns]
Validation
 ✓  Validating if devfile name is correct [17359ns]
 ✓  Validating the devfile for odo [3ms]
 ✓  Updating the devfile with component name "sess-iads" [105873ns]

Please use `odo push` command to create the component with source deployed
```
And, `odo push` is successful as well.

**devfile.yaml**
```yaml
metadata:
  name: sess-iads
parent:
  uri: ./parent/devfile.yaml
schemaVersion: 2.2.0
```

I believe this issue is no longer an issue, but @scottkurz let me know if you think otherwise.

**Comment by valaparthvi** [comment]
@scottkurz Any update on this one?

**Comment by scottkurz** [comment]
@valaparthvi  - Thanks for looking into this.  I confirmed with odo v2.5.0 that the child/parent relationship works fine, with a local uri referring to the parent, when I include the schemaVersion in the child devfile.

It's certainly clear in the devfile doc this is required.
