### ISSUE TITLE
Configuration of multi-component devfiles

### ISSUE THREAD

**Issue by gnunn1** [redhat-developer/odo#5127]
/kind feature

## Which functionality do you think we should add?

odo config commands should have a switch to specify which, or all, components the change is impacting.

## Why is this needed?

By their nature devfiles are multi component, for example it is quite common to deploy an application in one container with it's dependencies (database for example) in one or more other containers. Currently `odo config` commands do not provide a way to target a specific component in the devfile.

**Comment by kadel** [comment]
`odo config` was removed from odo v3.

One of the reasons for this is that it is tough to provide good and, more importantly, friendly CLI for editing complex yaml structures like devfile.

Users will have much better experience edit devfile.yaml directly in their IDE. Especially with extensions like vscode yaml extension that has support for json schema editing devfile is really nice experience as you get suggestions in the editor

/close
