### ISSUE TITLE
support for cpuLimit, cpuRequest, memoryRequest

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5132]
Devfile 2.1.0 added additional fields to container component to allow defining additional resource limits

/kind feature
/area devfile
/priority high

**Comment by kadel** [comment]
> Devfile library currently doesn't parse additional resource settings
> [devfile/api#641](https://github.com/devfile/api/issues/641)

unblocked

**Comment by valaparthvi** [comment]
Might require a simple library update or look into how memoryLimit is implemented in odo.

**Comment by anandrkskd** [comment]
So for this issue there are two place we need to make changes 
- odo config command 
- update the devfile library

For this issue we require to implement 

We require
- [ ] Update Devfile library (vendor)
- [ ] odo config set/unset should suppport memmoryRequest,cpuRequest,cpuLimit

**Comment by veenarm** [comment]
We've hit this issue recently, our multi-tenants enforce these before container scheduling can occur, both init containers and pods must define both a request and limit for memory/cpu, I attempted devfile2.1.0 and it does nothing different.

**Comment by anandrkskd** [comment]
@dharmit we also want to add integration tests for this feature, Right?
And do we also want to add Documentation for this or as this is devfile related, Devfile documentation will be enough?

**Comment by dharmit** [comment]
> @dharmit we also want to add integration tests for this feature, Right? 

Yes. And unit tests wherever it makes sense.

> And do we also want to add Documentation for this or as this is devfile related, Devfile documentation will be enough?

How to use it from odo has to go into odo documentation. See if you can add docs for `odo config` under the Command Reference section of the website.

**Comment by anandrkskd** [comment]
> See if you can add docs for odo config under the Command Reference section of the website.

We are not going to update `odo config` as part of this PR. As discussed in the planning call, it will require changes in devfile Library.
