### ISSUE TITLE
Being able to choose what version of a component to deploy (wildfly version, nodejs version)

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#514]
When deploying a Wildfly application on OpenShift, I'm able to choose between: 10.1, 10, 9, and 8.1

When using `odo create wildfly` I'm only able to deploy the latest.

Should there be an option on being able to choose a version?

**Comment by kadel** [comment]
Let's start with investigation and decide how this can be solved

**Comment by cdrage** [comment]
@kadel 

So here are my thoughts.

 - Pretty easy to implement, you can easily grab all the tags to the imagestreams (even through CLI it's as simple as: `oc get is -n openshift`)
 - The code we have for `odo catalog list` can be re-used / re-implemented for 

Changes:

`odo catalog list`
 - We also show the versioning information from `odo catalog list`, we should add a new column that shows what tags are available. This is needed as when people implement their custom builders, they should be able to see what tags have been deployed

`odo create`
- We should add a `--version` parameter so we may pick the version of the image. OR, we can implement it like so: `odo create httpd:6.11` (for example) `odo create httpd:latest`

What do you think?

**Comment by kadel** [comment]
+1 for using `httpd:6.11` format.

+1 for adding a column to `catalog list`

**Comment by jorgemoralespou** [comment]
This one is really important as there are many imagestreams that don't have a "latest" tag, hence can not be used. I would love odo to have some logic so that if there is no latest tag cannot create the component and request the user to specify a version.

**Comment by jorgemoralespou** [comment]
Also, if no version is specified should default to latest, and not making mandatory to specify the version.

**Comment by cdrage** [comment]
@jorgemoralespou I've implemented these changes here: https://github.com/redhat-developer/odo/pull/565 and https://github.com/redhat-developer/odo/pull/558

Just going through testing, but these new features will be merged soon.

**Comment by cdrage** [comment]
This has now been implemented in #565 and #558 

You can now specify a version by using:

```
odo create nodejs:VERSION
```

and list all versions available to use:

```
odo catalog list
```
