### ISSUE TITLE
odo url list empty for not pushed component on Kubernetes

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/odo#5146]
/kind bug

## What versions of software are you using?

**Operating System:** Win1Pro

**Output of `odo version`:**
```
odo v2.3.1 (2ae31fb66)

Server: https://api.sandbox-m2.ll9k.p1.openshiftapps.com:6443
Kubernetes: v1.21.1+9807387
```

## How did you run odo exactly?
1. odo create java-springboot sbcomp
2. odo url list

## Actual behavior
On OpenShift:

```
Found the following URLs for component sbcomp                                          
NAME         STATE          URL                       PORT     SECURE     KIND         
8080-tcp     Not Pushed     <provided by cluster>     8080     false      route        
There are local changes. Please run 'odo push'.                                        
```

On Kubernetes (Minikube)

` X  no URLs found for component sbcomp. Refer `odo url create -h` to add one`

## Expected behavior

Should have the same output on OpenShift and Kubernetes

**Comment by valaparthvi** [comment]
/close
We are not likely to implement this feature in v3 and we are not actively working on v2.
