### ISSUE TITLE
Document how odo translates `container` component to Deployment

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5174]
/kind documentation

Some users want to understand how odo works, sadly we currently don't have any documentation around that. All this is in our heads or in code.

Things that should be documented that are not obvious
-  [ ] labels that odo automatically adds to deployments
-  [ ] ....... // TODO  add more)
 - [ ] ...... // TODO  add more

**Comment by cdrage** [comment]
@kadel updates on this / should we close this?

**Comment by cdrage** [comment]
I feel like I've covered this with the Devfile reference / how it works guide./

**Comment by kadel** [comment]
The https://odo.dev/docs/development/devfile#how-odo-creates-resources-from-devfile just says that odo create Deployment and Service, without any details.

We need to get to more details. We should at least document what labels and annotations are automatically added to resources created by odo. There should also be more information about how Service is generated based on the information from devfile endopint.
