### ISSUE TITLE
suggestion: make login command accept the same arguments as 'oc'

### ISSUE THREAD

**Issue by tmds** [redhat-developer/odo#5189]
This is a UX suggestion.

The OpenShift Web UI provides the option to 'Copy login command'.

This provides a user with something copy-pastable like:
```
oc login --token=deadbeef --server=https://myserver:6443
```

It would be nice if the `oc` command from the above line can be simply substituted by `odo`, so the that the following would log into the cluster:

```
odo login --token=deadbeef --server=https://myserver:6443
```

Currently, `odo` requires to rewrite these arguments as:
```
odo login https://myserver:6443 --token=deadbeef
```

cc @kadel

**Comment by kadel** [comment]
> It would be nice if the `oc` command from the above line can be simply substituted by `odo`, so the that the following would log into the cluster:

In previous OCP versions this used to work. But it looks like the `oc login` command changed.
We should update this
/kind bug
/priority medium
