### ISSUE TITLE
suggestion: remove starterProjects on `odo create`

### ISSUE THREAD

**Issue by tmds** [redhat-developer/odo#5190]
This is a UX suggestion.

When using the `odo create` command, the `starterProjects` should not be included in the generated `devfile.yaml` file.

The `starterProjects` provide information for the `odo create` command (specifically: the `--starter` arg). I don't think they have a purpose after that, so they clutter up the generated `devfile.yaml`.

cc @kadel

**Comment by kadel** [comment]
We definitely want to change the current behavior were `odo create` just downloads devfile.yaml from registry as it is.

But the goal is a bit different from just cleaning it up from starters or other unnecessary things. 

We want to get into the point where if you do something like `odo create dotnet50 awesome-app`, odo will generate simple devfile that will just reference the Devfile stack in registry. Than the devfile that odo will place in you directory will look something like this.
```yaml
schemaVersion: 2.1.0
metadata:
  name: awesome-app
parent:
    id: donet50
    registryUrl: https://registry.devfile.io
```

The idea is that the Devfile Stack (basicaly devfiles in registry) should be generic that suits most of the applications. And the local devfile should reference those and just add overrides that are specific for given application.

**Comment by tmds** [comment]
> The idea is that the Devfile Stack (basicaly devfiles in registry) should be generic that suits most of the applications. And the local devfile should reference those and just add overrides that are specific for given application.

My experience in practice which such setups is that it prevents upstream from making backwards-incompatible changes.

I like the current experience where the registry serves as a template repository. Once it is local, you can freely edit the file.

**Comment by kadel** [comment]
> My experience in practice which such setups is that it prevents upstream from making backwards-incompatible changes.

We would move to `parent` approach only once there is a safe way to pin the parent to a specific version.

> I like the current experience where the registry serves as a template repository. Once it is local, you can freely edit the file.

I agree that this has its benefits, but it has also its downsides. If the devfile in registry gets updated you won't know about it, and if you do you will have manually merge it with your devfile.

Now when I think about it odo should support both ways and let users decide what is better for them.

**Comment by tmds** [comment]
If you support this, I think you'll want to keep the changes to the repository devfiles backwards compatible. That ties your hands.

Also, if the user can override some commands locally, an update of the repository devfile can break how the commands interact.
