### ISSUE TITLE
suggestion: use a random AppName on 'odo create'

### ISSUE THREAD

**Issue by tmds** [redhat-developer/odo#5193]
`odo create` picks a random name for the component, but it uses a fixed name for the `AppName` of `app`.

Is there a reason the name doesn't get randomized?

I'm trying out `odo create` when I push a second unrelated component, I get an error because they are both using the same `AppName`:
```
Error: Failed to create the component: Failed to update config to component deployed.: url named "http-8080" already exists in the same app named "app"
```

cc @kadel

**Comment by kadel** [comment]
> Is there a reason the name doesn't get randomized?

We want to make sure that the URL names are somewhat predictable. When you do `odo create`, `odo push`, `odo delete` `odo push`, the second `odo push` should create the same resources as the first one. 


> ```
> Error: Failed to create the component: Failed to update config to component deployed.: url named "http-8080" already exists in the same app named "app"
> ```

This is a problem, odo needs to make sure that the url names don't collide

/kind bug
/priority medium

**Comment by valaparthvi** [comment]
Closing this since it's not relevant anymore.
/close
