### ISSUE TITLE
starter project with devfile

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5200]
In some situations the starter projects repo or zip can contain `devfile.yaml`
Currently, if starter project odo downloaded contains devfile odo will override it. 
If the downloaded starter project contains devfile, odo should keep it as it is, and don't try to place devfile into the directory.

## Acceptance Criteria 
- [ ] `odo create <stack-name> --starter <starter-name>` if the starter project repo contains devfile.yaml odo should keep it in the directory and don't override it with stack devfile
- [x] `odo create <stack-name> --starter <starter-name>` if the starter project repo doesn't have devfile.yaml odo use the stack devfile usually downloaded from registry and place it in the context directory (this is already implemented)
- [x] `odo create --devfile <devfile_path> --starter <starter-name>` if the starter project repo contains devfile.yaml odo should keep it in the directory and don't override it with --devfile devfile
- [x] `odo create --devfile <devfile_path> --starter <starter-name>`  if the starter project repo doesn't have devfile.yaml odo use the --devfile devfile and place it in the context directory
- [x] `odo create --starter <starter-name>` with user-created-devfile : if there is a devfile present in the context directory, odo should not allow using --starter flag.
- [x] Write integration tests covering all the cases.
- [x] Documentation - command reference for `odo create`

example of the repo with devfile.yaml https://github.com/nodeshift-starters/devfile-sample

/priority high

**Comment by dharmit** [comment]
> example of the repo with devfile.yaml https://github.com/nodeshift-starters/devfile-sample

Is there a registry that already has a nodejs component which considers this as a valid starter project? I'm asking because with the default devfile registry, I don't see it in the below output:
```sh
odo catalog describe component nodejs
Devfile Component(s):

* Registry: stage

Starter Projects:
---
name: nodejs-starter
attributes: {}
description: ""
subdir: ""
projectsource:
  sourcetype: ""
  git:
    gitlikeprojectsource:
      commonprojectsource: {}
      checkoutfrom: null
      remotes:
        origin: https://github.com/odo-devfiles/nodejs-ex.git
  zip: null
  custom: null

$ odo registry list
NAME      URL                                   SECURE
stage     https://registry.stage.devfile.io     No
```

**Comment by kadel** [comment]
> Is there a registry that already has a nodejs component which considers this as a valid starter project? I'm asking because with the default devfile registry, I don't see it in the below output:

No it doesn't. The reason for it that we could not add it to the registry because odo ignore it, and before it was even failing when there was a devfile in starter. So Elson and we were making sure that there is no devfile with starter in registry that would be doing that. 


@dharmit Is that a problem?

**Comment by mohammedzee1000** [comment]
So is there a registry available right now that has a starter project with a devfile in it

**Comment by dharmit** [comment]
> So there is no registry available right now with a starter having its own devfile :/. That will make testing cases 1 and 2 from acceptance criteria difficult

You'll have to use [devfile registry operator](https://github.com/devfile/registry-operator) to deploy your own registry on minikube/CRC to test this out. You will also need to create your own container image that has info about a stack like nodeshift-starters in it.
