### ISSUE TITLE
update link in OCP webconsole

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5203]
Download odo link in OCP web console still points to mirror.openshift.com (https://mirror.openshift.com/pub/openshift-v4/clients/odo/latest/). 
New release are no longer pushed to mirror.openshift.com.
The link should point to our new CDN location at https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/odo/latest

New ticked should be raised on OCP side to update the link

/priority high
/kind task

**Comment by rnapoles-rh** [comment]
Ticket https://github.com/openshift/console/issues/10415 was opened.

**Comment by rnapoles-rh** [comment]
openshift/console#10415 has been assigned but still open.

**Comment by rnapoles-rh** [comment]
Requested estimated time to be addressed.

**Comment by rnapoles-rh** [comment]
I escalated this today and a [bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=2036937) ticket and [PR](https://github.com/openshift/console-operator/pull/622) were created.

**Comment by rnapoles-rh** [comment]
[PR](https://github.com/openshift/console-operator/pull/622) was LGTMed and APPROVED, pending 2 reviews

**Comment by rnapoles-rh** [comment]
[PR](https://github.com/openshift/console-operator/pull/622) has merged
