### ISSUE TITLE
`odo service create -p` Missing details on how to set arrays 

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5215]
/priority high
/area service-operators

The `-p` flag is one of the most important flags for `odo service create` command.
The help message for command or for the flag should contain more information how to use it. 
The help message should explain users what is the system that it is using to specify parameters and how to set parameters that inside the arrays or other more complicated scenarios

Currently, it is just
`  -p, --parameters stringArray   Parameters of the plan where a parameter is expressed as <key>=<value`
and there are no examples.

**Comment by dharmit** [comment]
If creating most of the Operators from [this list on Service Binding Operator readme](https://github.com/redhat-developer/service-binding-operator#known-bindable-operators) is doable using `-p` flag, then we keep it. But if writing YAMLs is more convenient way, we consider removing `-p` from `odo service create`.

**Comment by dharmit** [comment]
/triage needs-information

maybe just need to point it based on https://github.com/openshift/odo/issues/5215#issuecomment-972877830.

**Comment by dharmit** [comment]
@kadel is this issue only about adding example to `odo service create -p`?

**Comment by dharmit** [comment]
For reference - https://github.com/openshift/odo/blob/16dd43ce196df0628918301ada4ec7a20247a44a/tests/integration/operatorhub/cmd_service_test.go#L138-L146.

**Comment by dharmit** [comment]
OK. But I still don't understand how we would want a user to specify these through CLI.

How would we specify individual instances in this case? Can you share a `odo service create` with parameters that you expect to work?

**Comment by dharmit** [comment]
@kadel @feloy do you folks think this issue is still relevant?

**Comment by kadel** [comment]
> @kadel @feloy do you folks think this issue is still relevant?

we can close this, it is only for v2.
In v3 we don' have this command and if we decide to add it, we will have to rethink it anyway. 
/close
