### ISSUE TITLE
start using SBO again

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5221]
new SBO  version hard codes binding definitions for some of the operators. This might make using SBO with odo much easier

- [ ] investigate if we can leverage this to fix https://github.com/openshift/odo/issues/5084 
- [ ] Investigate which Operators' annotations have been hard-coded by SBO and add tests for these in odo
  - [ ] Doesn't have to be all operators in a single sprint.
  - [ ] MVP would be to manually test it, but automate at least one in the first sprint

/triage needs-information

**Comment by kadel** [comment]
/priority high 
due to #5207

**Comment by dharmit** [comment]
For sprint 211, let's figure out how to move back to using SBO again. The code to be uncommented is at: https://github.com/redhat-developer/odo/blob/5f79c542a872ef7485b9b7a5a37c4dce0b6cb5d9/pkg/kclient/operators.go#L30-L35

Uncomment and test things.

**Comment by feloy** [comment]
The service binding operator v1.0 is setting default annotations to the Redis operator CRD, which are using non mandatory fields, and that causes problems with `odo` integration tests not using these fields (especially `redisSecret`).

**Comment by valaparthvi** [comment]
We are using SBO for tests and library when it's not available. I am going to close this issue. If anyone thinks it's still an issue, feel free to reopen it.
