### ISSUE TITLE
Git Shell not waiting for user input

### ISSUE THREAD

**Issue by mclhrn** [redhat-developer/odo#5222]
/kind bug

## What versions of software are you using?

**Operating System:**
```
Edition:     Windows 10 Enterprise
Version:    1909
```

**Output of `odo version`:**
```
odo v2.2.4 (f12e036b5)
```

## How did you run odo exactly?
* Using Git Shell on Windows...
* Cloned the registry and registry-support repos
* Customised the devfile samples to point at internal repos
* Deployed om Openshift
* Pointed `odo` at the new registry
* Run `odo create`
* Observe behaviour

## Actual behavior
Any command that requires user input is being run over by the next command in the chain... i.e. it is not waiting for user input.

## Expected behavior
Cli waits for desired user input

## Any logs, error output, etc?
Example output below is after simply running `odo create`

![Screenshot 2021-11-10 at 14 34 42](https://user-images.githubusercontent.com/1668635/141146989-d8cac130-ea36-4cb3-8fb5-3d69e275b36e.png)

**Comment by kadel** [comment]
i was not able to reproduce this with odo v3
/close
