### ISSUE TITLE
odo delete broken without local component

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/odo#5231]
## What versions of software are you using?

**Operating System:** Win10

**Output of `odo version`:**

```
odo v2.4.1 (dbf7ad592)

Server: https://api.crc.testing:6443
Kubernetes: v1.22.0-rc.0+a44d0f0
```

## How did you run odo exactly?

`odo delete -f -app app --project project mycomp`

## Actual behavior

Reports an error:
```
 X  error occurred while deleting component, cause: failed to read devfile from path 'C:\apps\odo\2.4.1\devfile.yaml': open C:\apps\odo\2.4.1\devfile.yaml: The system cannot find the file specified.
```

## Expected behavior

Component should be deleted on the cluster.

**Comment by rm3l** [comment]
This issue should be fixed in odo v3 (since #5511), with the `odo delete component --name <name>` command, which can be run from anywhere: https://odo.dev/docs/command-reference/delete-component#delete-without-access-to-devfile

see #5479, fixed by #5511
