### ISSUE TITLE
OLM not deployed on IBM Kubernetes cluster

### ISSUE THREAD

**Issue by feloy** [redhat-developer/odo#5232]
/kind documentation

Currently, OLM and operators are not deployed on IBM Kubernetes cluster. They should be deployed if we want to run operator-hub related tests on this cluster

### NOTE:

* Do not install SBO on the IBM k8s cluster
* We test `odo link` with Operator on OCP and with library on k8s.

**Comment by rnapoles-rh** [comment]
Installation of OLM stared in the Developer QE org: Failed with:
```
Waiting for deployment "olm-operator" rollout to finish: 0 of 1 updated replicas are available...

error: deployment "olm-operator" exceeded its progress deadline
```
Trying again.

**Comment by dharmit** [comment]
Things to consider:
* Automate installation of OLM on the IBM k8s cluster (k8s provided by the IBM Cloud service)
* Installation of Operator(s) that we want to test
