### ISSUE TITLE
darwin-arm64 binary build is missing from 2.4.2 release

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/odo#5239]
/kind bug

With the release of odo 2.4.2, the [artefacts for darwin-arm64 is build](https://github.com/openshift/odo/pull/5197), but the binary for `darwin-arm64` is not published on [developers.redhat.com](https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/odo/v2.4.2/).

The binary is missing from the release builds.

**Comment by dharmit** [comment]
I noticed this when the binaries were pushed to content-gateway on Friday. However, we don't know if something's amiss from odo side on this. I'm currently following up with Red Hat Release Engineering folks to understand what went wrong.

As far as making changes on odo side is concerned, the PR you linked should have sufficed.

**Comment by mohitsuman** [comment]
@dharmit let us know once the release-eng adds the binary to the content-gateway.

**Comment by kadel** [comment]
this has been fixed, binaries are there
