### ISSUE TITLE
using go-init as first process of component container

### ISSUE THREAD

**Issue by feloy** [redhat-developer/odo#5242]
/kind bug

When creating the Deployment for a component, the entrypoint of the container is `supervisord`. 

Because `supervisord` is not able to adopt zombie processes, in some circumstances, the container can have an important number of zombie processes not finished.

The `go-init` process is provided in the `odo-init-image` for this specific purpose. It was the entrypoint for components deployed by odo with `DeploymentConfig`, but is not used for components deployed with a `Deployment`.

odo should use `go-init` as the entrypoint for component containers started with a `Deployment`.

## Steps to reproduce

```
odo create nodejs 
odo watch

# update sources several times and let odo rebuild the app

odo exec -- ps
   PID TTY          TIME CMD
     1 ?        00:00:00 supervisord
   104 ?        00:00:13 node <defunct>
   130 ?        00:00:00 node <defunct>
   214 ?        00:00:00 npm <defunct>
   225 ?        00:00:13 node <defunct>
   251 ?        00:00:00 node <defunct>
   332 ?        00:00:00 devfile-command
   333 ?        00:00:00 npm
   344 ?        00:00:07 node
   368 ?        00:00:00 ps
```

**Comment by rm3l** [comment]
Closing this issue since we are no longer using Supervisord and the odo init image (https://github.com/redhat-developer/odo/pull/5768).

Feel free to reopen it if you think otherwise.

/close
