### ISSUE TITLE
delete outerloop resources

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5246]
## Acceptance criteria
- [ ] `odo delete -a` should delete everything that belongs to the current component and was created on the cluster (both outerloop (`odo deploy` and interllop `odo push` resources)
- [ ] `odo delete --deploy` should delete only outer loop resources created on the cluster (reverse of the `odo deploy`)
- [ ] `odo delete` should delete only intertroop resources created on the cluster (reverse of the `odo push`) (already present.)

/priorty high
/kind user-story
/area deploy

**Comment by dharmit** [comment]
`odo delete --deploy`
* Image shouldn't be deleted from the registry or local.
* Delete only stuff deployed by `odo deploy`, don't touch resources created by `odo push`.
* Tests
* Docs (CLI & odo.dev)

`odo delete -a`
* Everything in current `odo delete -a` plus `odo delete --deploy`

`odo delete`
* Tests to make sure that behaviour doesn't change for the case when a devfile has deploy related resources.
