### ISSUE TITLE
Having separate layers

### ISSUE THREAD

**Issue by feloy** [redhat-developer/odo#5247]
/kind bug

As described in the comment https://github.com/openshift/odo/issues/4057, the architecture of the code should use several layers (bottom to top):

- low-level layer that interacts with the cluster (using `k8s.io` packages)
- business layer that defines abstractions of the domain (app, component, project, storage, url, etc)
- cli layer that defines the UI

## Packages in layers

The low-level layer is composed of packages that access the underlying platforms:
- pkg/occlient
- pkg/kclient
- pkg/devfile (?)

The business layer is composed of packages that manage the `odo` objects:
- [x] pkg/application (#5293)
- [x] #5345
- [ ] pkg/catalog
- [ ] https://github.com/redhat-developer/odo/issues/5346  (#5329)
- [ ] pkg/config
- [ ] pkg/debug
- [x] pkg/preference (#5296)
- [x] pkg/project (#5293)
- [ ] pkg/service
- [ ] pkg/storage
- [ ] pkg/url
- [ ] pkg/version

The CLI layer is composed of packages in:
- [ ] cmd
- [ ] pkg/odo/cli

Other packages:
- [ ] pkg/segment

## Import of CLI layer

Packages of the CLI layer should not be imported from outside this CLI layer. These imports should be fixed:

```
$ grep -r github.com/openshift/odo/pkg/odo/cli pkg/ | grep -v ^pkg/odo/cli

pkg/odo/genericclioptions/runnable.go:			"github.com/openshift/odo/pkg/odo/cli/ui"
pkg/preference/preference.go:				"github.com/openshift/odo/pkg/odo/cli/ui"
pkg/catalog/catalog.go:			registryConsts	"github.com/openshift/odo/pkg/odo/cli/registry/consts"
pkg/catalog/catalog.go:			registryUtil	"github.com/openshift/odo/pkg/odo/cli/registry/util"
pkg/component/starter_project.go:	registryUtil	"github.com/openshift/odo/pkg/odo/cli/registry/util"
```

## Interactions with the console

Interactions with user (and especially console) should be done only from the CLI layer.

```
$ grep -r fmt.Print pkg/ | grep -v ^pkg/odo/cli | grep -v _test.go:

pkg/testingutil/httputils.go:	fmt.Println("running")
pkg/log/fidget/spinner.go:	fmt.Print("\r")
pkg/auth/login.go:		fmt.Println("Login failed (401 Unauthorized)")
pkg/auth/login.go:		fmt.Println("Verify you have provided correct credentials.")
pkg/auth/login.go:		fmt.Println(cause.Message)
```

## Interactions with the cluster

Interactions with the cluster should be done only from the low-level layer.

```
$ grep -r client-go pkg/ |grep -v ^pkg/kclient | grep -v ^pkg/occlient | grep -v _test.go:

pkg/testingutil/configs.go:	clientcmdapi 	"k8s.io/client-go/tools/clientcmd/api"
pkg/debug/portforward.go:			"k8s.io/client-go/rest"
pkg/debug/portforward.go:			"k8s.io/client-go/tools/portforward"
pkg/debug/portforward.go:			"k8s.io/client-go/transport/spdy"
pkg/auth/login.go:				"k8s.io/client-go/tools/clientcmd"
pkg/util/util.go:				"k8s.io/client-go/util/homedir"
```

## Import of low-level layer

Packages of the low-level layer should be imported from business layer only.

## Interfaces

Packages in the business layer and the low-level layer should declare an interface and a default Client implementing this interface so the upper layers use this interface and either use the default implementation, or create its own implementation for testing.

(to be continued)

**Comment by kadel** [comment]
This is great. Thank you, @feloy,  for writing this down :+1: 


> The low-level layer is composed of packages in:
> 
> * pkg/occlient
> * pkg/kclient

Another thing that I would to see is consolidation of `occlient` and `kclient` into one package. There is a lot of duplication between those tow, and with recent move to removing s2i related code from odo there are only 2 things that are specific to OpenShift that odo uses (Routes and Projects). Technically even those two are just another Kubernetes resources that are not different from any other Kubernetes CRs. Odo should treat all resources the same way.

**Comment by feloy** [comment]
> This is great. Thank you, @feloy, for writing this down +1
> 
> > The low-level layer is composed of packages in:
> > 
> > * pkg/occlient
> > * pkg/kclient
> 
> Another thing that I would to see is consolidation of `occlient` and `kclient` into one package. There is a lot of duplication between those tow, and with recent move to removing s2i related code from odo there are only 2 things that are specific to OpenShift that odo uses (Routes and Projects). Technically even those two are just another Kubernetes resources that are not different from any other Kubernetes CRs. Odo should treat all resources the same way.

Thanks :) 
I created another issue for merging occlient/kclient: #5249

**Comment by feloy** [comment]
Remaining packages will be deleted or worked on for v3
