### ISSUE TITLE
remove `odo component` subcommand.

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5253]
Every `component` subcomand (like `odo component push`, `odo component create` ...) has a shortcut as root `odo` command (`odo push`, `odo create`)
This can get quite confusing. As odo uses devfile for representation there are some weird stuff now. Like `odo service` is a separate command that is not under `odo component` but it adds stuff into devfile. But there is also `odo component link` that does almost the same thing to devfile (adds kubernetes component in form of ServiceBinding). The both do similar actions but one is `component` subcommand one  the other is not.

We should stop using `odo component` subcommands and have everything that is there as a normal odo command.

This should be gradual, first add deprication warning to  all `odo component *` commands and after at least 3 releases remove the commands in favor of the root command equivalents

**Comment by kadel** [comment]
Some data from telemetry:
In all our recorded data since April 2021 till today:

- 20331 commands were executed that are not starting with `odo component`
- 189 commands were executed that start with `odo component`

**Comment by rm3l** [comment]
There is no `component` subcommand in odo v3 (https://github.com/redhat-developer/odo/issues/5403).
@kadel Can we close this issue then?
