### ISSUE TITLE
odo link error message to an unpushed service is ambiguous

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/odo#5264]
/kind documentation

## What mistake did you find / what is missing in the documentation?

When trying to link to a service not pushed to the cluster, the error message is:

` X  couldn't find service named "Cluster/mypsql". Refer "odo service list" to see list of running services`

when `odo service list` reports:

```
NAME               MANAGED BY ODO     STATE          AGE
Cluster/mypsql     Yes (ncomp)        Not pushed

```

Based on odo 2.4.2

**Comment by dharmit** [comment]
odo doesn't support linking of a component to a service that hasn't been pushed to the cluster (a.k.a. the `Not pushed` services in `odo service list`).

It's being tracked in this user story https://github.com/openshift/odo/issues/4760.
