### ISSUE TITLE
`odo deploy`

### ISSUE THREAD

**Issue by serenamarie125** [redhat-developer/odo#5298]
description by @kadel:
# `odo deploy`

## User story
- As an odo user
- I want to be able to quickly deploy my application to the cluster in a similar manner how it will run in production
- So that I can properly test that everything will work correctly in prod

## Acceptance criteria
- [x] The result of the successful execution of `odo deploy` is Devfile component deployed in outer loop mode.
- [x] When there is no devfile in the current directory (and the directory is not empty) and no flags provided, command should run in interactive mode that is similar to `odo init`
- [x] If the current directory is empty it should error out
- [x] When devfile exists in the current directory, deploy the application in outer loop mode using the information from `devfile.yaml` in the current directory.

## example
```
$ odo deploy
There is no devfile.yaml in the current directory.
Based on the files in the current directory odo detected
Language: Java
Project type: SpringBoot
? Is this correct? Yes
Current component configuration:
Opened ports:
- 8080
- 8084
Environment variables:
- FOO = bar
- FOO1 = bar1
? What configuration do you want change?  [Use arrows to move, type to filter]
> NOTHING - configuration is correct
  Delete port "8080"
  Delete port "8084"
  Add new port
  Delete environment variable "FOO"
  Delete environment variable "FOO1"
  Add new environment variable
⠏ Downloading "java-quarkus". DONE
Deploying your component to cluster ...
⠏ Building container image locally ... DONE
⠏ Pushing image to container registry ... DONE
⠏ Waiting for Kubernetes resources ... DONE
Your component is running on cluster.
You can access it at https://example.com
```

If there is no devfile in the current directory `odo` should use ([Alizer](https://github.com/redhat-developer/alizer/pull/55/)) to get corresponding Devfile for code base in the current directory.
After the successful detection it will show  Language and Project Type information to users and ask for confirmation.
If user answers that the information is not correct, odo should ask "Select language" and "Select project type" questions (see: [`odo init`](odo-init.md) interactive mode).

The configuration part helps users to modify most common configurations done on Devfiles.
"? What configuration do you want change? " question is repeated over and over again until user confirms that the configuration is done and there is nothing else to change.

## remaining things to do 
- [x] integrate with #5423

**Comment by dharmit** [comment]
> * [ ]  When there is no devfile in the current directory and no flags provided, command should run in interactive mode that is similar to

Do we already have devfiles in the devfile registry that have outer loop resources baked into them? I did a quick search for `kind: deploy` on the [devfile registry repo](https://github.com/devfile/registry/search?q=kind%3A+deploy&type=code), but didn't find any.  I'm asking because without that, this part won't be of much use, and, in that case, we could prioritize on something else for alpha1.
