### ISSUE TITLE
PSI tests failing due to amqp server

### ISSUE THREAD

**Issue by anandrkskd** [redhat-developer/odo#5305]
/kind failing-test

Currently, tests using psi resources are failing due to amqp server(rabbitmq server) can not be reached.
The failing tests are marked as optional for now. 
Tests are currently affected due to these failures are
- ci/prow/psi-kubernetes-integration-e2e 
- ci/prow/psi-unit-test-mac 
- ci/prow/psi-unit-test-windows

Need more discussion if we want to resume these tests. If yes, then
- We need to setup a new amqp server and use the new server instead of old one to resume the tests.
Or else,
- Remove those tests as we have some tests running on IBMcloud.

Per discussion with Tomas, we will remove the tests .
Unit & Integration tests on both Mac & Windows. 
Budget approval is pending for Mac OS. Build by repo/project is a concern. Discussions in progress with Karel.

**Comment by dharmit** [comment]
Let's focus on #5232 and make the k8s tests on IBM Cloud mandatory by enabling OLM tests on it. We replace PSI k8s tests with that running on IBM Cloud.

Adding this to Sprint 213 so that we can revisit this then.

**Comment by anandrkskd** [comment]
Acceptance Criteria for this issue:
- [ ] Remove mac, windows unit test from prow
- [ ] remove minikube tests from prow
- [ ] configure enable windows tests with IBM cloud cluster (includes creation of new cluster for its test)
