### ISSUE TITLE
What's the purpose of the string `name` in `Complete` function in `Runnable` interface?

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/odo#5311]
Below is the definition of `Runnable` interface:
```go
type Runnable interface {
	Complete(name string, cmdline cmdline.Cmdline, args []string) error
	Validate() error
	Run() error
}
```

Most of the places in odo code don't make any use of the string `name`. Should we just remove it?

/kind discussion

**Comment by valaparthvi** [comment]
I see the only commands that require this arg are `odo link`, and `odo unlink`. We can change the method signature to remove the `name` arg, and use `cmdline.GetName()` instead wherever the need be.

**Comment by dharmit** [comment]
@valaparthvi do you want to open a PR for this?
