### ISSUE TITLE
`odo deploy`/`odo build-images` fails for docker backend

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/odo#5322]
/kind bug

## What versions of software are you using?

**Operating System:** Fedora 35

**Output of `odo version`:** `main`

## How did you run odo exactly?
```sh
$ git clone https://github.com/kadel/devfile-nodejs-deploy
$ cd devfile-nodejs-deploy
$ sed -i 's/kadel/<my-quay-username>/' devfile.yaml
$ odo project create nodejs-example
$ odo create
$ odo deploy
```

## Actual behavior
```sh
$ odo deploy

Building image quay.io/dharmit_rh/devfile-nodejs-deploy:latest
"docker build" requires exactly 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile
 ✗  command execution failed: error running docker command: exit status 1

$ odo build-images

Building image quay.io/dharmit_rh/devfile-nodejs-deploy:latest
"docker build" requires exactly 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile
 ✗  error running docker command: exit status 1
```

## Expected behavior
Both commands should pass

## Any logs, error output, etc?

* The `docker build` command that's generated by odo is: `docker build -t "quay.io/dharmit_rh/devfile-nodejs-deploy:latest" -f "/home/dshah/src/devfile-nodejs-deploy/Dockerfile" ${PROJECT_SOURCE}`

* Appending above command with a `.` (period) or path to the directory containing the devfile (`devfilePath`) in the function below solves the issue. https://github.com/redhat-developer/odo/blob/b20103c9f38b8291c92aa8bfdf048455e2d6d499/pkg/devfile/image/docker_compatible.go#L46

**Comment by feloy** [comment]
This is the role of `${PROJECT_SOURCE} to append the working directory. The problem is probably because this variable is empty or not expanded correctly

**Comment by dharmit** [comment]
Yes, the variable is surely not getting expanded. But where is this value `${PROJECT_SOURCE}` getting assigned to it? While tracing it to devfile library, I found it should be `${PROJECT_ROOT}` by default: https://github.com/redhat-developer/odo/blob/b20103c9f38b8291c92aa8bfdf048455e2d6d499/vendor/github.com/devfile/api/v2/pkg/apis/workspaces/v1alpha2/component_image_dockerfile.go#L45-L48

It says `Defaults to ${PROJECT_ROOT} in the container`, but `odo deploy` isn't being run inside a container, it's run on the user's host system where they are running odo commands. I'm not sure if I'm tracing this to the right place. 🤔

**Comment by feloy** [comment]
It comes from the `buildContext` field of the image to build in the devfile you are using:

```
  - name: prod-image
    image:
      imageName: "{{CONTAINER_IMAGE}}"
      dockerfile:
        uri: ./Dockerfile
        buildContext: ${PROJECT_SOURCE}
```

**Comment by dharmit** [comment]
Wow! That feels like an embarrassing question that I asked. 😆 

Shouldn't this variable be defined in the devfile at: https://github.com/kadel/devfile-nodejs-deploy/blob/2b7058af5cdac5a43ded2b6c44454add7cf82161/devfile.yaml#L6-L8

Is this devfile invalid/erroneous in that case?

**Comment by feloy** [comment]
> Wow! That feels like an embarrassing question that I asked. laughing
> 
> Shouldn't this variable be defined in the devfile at: https://github.com/kadel/devfile-nodejs-deploy/blob/2b7058af5cdac5a43ded2b6c44454add7cf82161/devfile.yaml#L6-L8
> 
> Is this devfile invalid/erroneous in that case?

I'm not sure. @kadel, where is this variable `${PROJECT_SOURCE}` coming from on your repo's Dockerfile?

**Comment by kadel** [comment]
> I'm not sure. @kadel, where is this variable `${PROJECT_SOURCE}` coming from on your repo's Dockerfile?

This is a predefined env variable. Odo is automatically adding it to containers.

From devfile spec:

> Special variables that can be used:
> 
> $PROJECTS_ROOT: A path where projects sources are mounted as defined by container component's sourceMapping.
> 
> $PROJECT_SOURCE: A path to a project source ($PROJECTS_ROOT/). If there are multiple projects, this will point to the directory of the first one.

**Comment by kadel** [comment]
before odo executes `docker`/`podman` command it should set `PROJECT_SOURCE` variable. value of this variable should be path to the directory with the devfile.yaml (current directory)
