### ISSUE TITLE
Odo push says warning cannot create ingress, add more details to output

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#5331]
/kind feature

## Which functionality do you think we should add?

When running `odo push` the output is as follows:

```sh
Creating Kubernetes resources for component nodejs-nodejs-ex-epmu
 ✓  Waiting for component to start [1m]
 ✓  Links are in sync with the cluster, no changes are required
 ✓  Waiting for component to start [7ms]
 ⚠  Unable to create ingress, missing host information for Endpoint http-3000, please check instructions on URL creation (refer `odo url create --help`)
```

Now... it says that you are unable to create ingress, but when looking at `odo push --help` there are no details on how to avoid that warning in the first place, maybe even an `odo push --hostname foo.bar.com` ? There are no instructions other than to look at `odo url create`.

But what if I wanted to avoid using `odo url create` in the first place and have it create an ingress via `odo push` like it's trying to do?

## Why is this needed?

For consistency. As of right now, when you run the example, it will always show a warning for a new user which is very unforgiving, especially since the warning is basically saying: "hey! now you have to learn how to use url create since you messed up pushing this component!" which doesn't equal a great experience.

**Comment by kadel** [comment]
> But what if I wanted to avoid using `odo url create` in the first place and have it create an ingress via `odo push` like it's trying to do?

That is technically not possible. In order to create Ingress user needs to provide a hostname. There is no way for odo to know the correct hostname.

**Comment by cdrage** [comment]
> > But what if I wanted to avoid using `odo url create` in the first place and have it create an ingress via `odo push` like it's trying to do?
> 
> That is technically not possible. In order to create Ingress user needs to provide a hostname. There is no way for odo to know the correct hostname.

Yeah, the problem is that when doing `odo push` with the current example, it will always say that warning and ask the user as to why there is no hostname. 

And then when you run `odo url create`, you'll run into this bug: https://github.com/redhat-developer/odo/issues/5387

**Comment by cdrage** [comment]
Ah, okay, that makes sense. I'll keep this issue open and instead refactor the output of the warning so it makes more sense / understandable.

**Comment by kadel** [comment]
this won't apply to v3 and we won't be changing this in v2
