### ISSUE TITLE
Google groups is no longer used.

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#5333]
/kind documentation

## What mistake did you find / what is missing in the documentation?

Within the GitHub issue template, we mention Google Groups.

Unfortunately, this has been seldom used, and there's only been 9 threads in the last 3 years.

We should remove all references to this, and instead simply point users to use Issues / Pull Requests instead.

## What is the relevance of it?

Google Groups seldom used, see issue templates here: https://github.com/redhat-developer/odo/tree/main/.github/ISSUE_TEMPLATE

**Comment by cdrage** [comment]
I've removed this from the GitHub issue and PR templates already when I sent in a PR #5003 

Should we still keep the mailing lists / remove the references to them in the wikipedia + site?

**Comment by kadel** [comment]
I would still keep it. Some people might prefer communicating over email, rather than slack

**Comment by cdrage** [comment]
> I would still keep it. Some people might prefer communicating over email, rather than slack

We've only had 9 threads in 3 years with absolutely no outside user base other than the core developers

**Comment by kadel** [comment]
google group was removed from PR template
