### ISSUE TITLE
odo describe [component name] does not work correctly / takes any parameter

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#5334]
/kind bug

## What versions of software are you using?

**Operating System:** Linux

**Output of `odo version`:** 
```sh
▶ odo version
odo v2.5.0 (724f16e68)
```

## How did you run odo exactly?
```sh
▶ odo describe klajsdfjklasdjkflasdf
Component Name: nodejs-nodejs-ex-epmu
Type: nodejs
URLs:
 · https://nodejs-nodejs-ex-epmu-3000.k8s.land exposed via 3000
```

## Actual behavior

Describes the current component.

## Expected behavior

Erroring out as I have passed an invalid component name. 

Or at least a warning saying "klajsdfjklasdjkflasdf" not found, but here is the current component instead.

## Any logs, error output, etc?

See above

**Comment by valaparthvi** [comment]
@cdrage, care to test #5370 ? It attempts to fix this sorta behavior.

**Comment by kadel** [comment]
this doesn't apply to v3 and we won't be fixing this in v2
