### ISSUE TITLE
odo url documentation command reference page on odo.dev

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#5335]
/kind documentation

## What mistake did you find / what is missing in the documentation?

When using `odo` for the first time in over a year, I found that there are some things that have changed that I cannot find documentation to. 

Specifically, I was looking for more detailed documentation on `odo url`. 

Unfortunately on the https://odo.dev site, there is only a short tutorial on how to use it and no references on the command reference https://odo.dev/docs/command-reference/build-images page

There are command references to other commonly used commands, but unfortunately not `url`.

Specifically, I'd like to figure out how to:
- Specify a custom ingress controller (I use nginx-ingress on a different default ingress backend, which I was unable to specify via `odo url create`)
- How to modify my kubernetes yaml files / propagate custom ingresses. Pushing a component is fine and pretty much standard, same as using PVC, but ingress scenarios and quite different in each deployment (cloud, baremetal, etc.)
- How to SPECIFICALLY set a hostname that may not be related to the service, for example, specifying: "--host foo.bar.com" and the ingress actually is created at foo.bar.com

## What is the relevance of it?

Teaching a noob how to use `odo url` again :)

**Comment by kadel** [comment]
/close
`odo url` is v2 command, odo v2 is on mantainace support
