### ISSUE TITLE
General odo.dev site improvements

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#5336]
/kind documentation

## What mistake did you find / what is missing in the documentation?

Few things I noticed when browsing the new https://odo.dev site which can be seen as general improvements:

General notes:
- [ ] More graphics :), it's kinda plain at the moment to be honest
- [ ] Better SEO, each page needs more `og` properties as well as `twitter:title`, etc. in the metadata
- [ ] No Favicon (it's just blank?)

**Comment by dharmit** [comment]
>  * [ ]  No Favicon (it's just blank?)

@valaparthvi did you get anything from the design team that was helping us have an icon for odo?

**Comment by valaparthvi** [comment]
> @valaparthvi did you get anything from the design team that was helping us have an icon for odo?

Well we have one that Tuomas created.

**Comment by cdrage** [comment]
Closing this issue as I've pushed the changes to the front page via PR: https://github.com/redhat-developer/odo/pull/5359

I've been in contact with Tuomas and we're going to update the logo next week to something higher resolution / slightly different
