### ISSUE TITLE
`odo describe service` should list the custom mappings usable with `odo link --map`

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/odo#5343]
/kind feature

## Which functionality do you think we should add?
`odo link --map <key>=<value>`  can help inject custom mappings into an odo component. It's not possible to find which custom mappings can be provided to this command without looking at the Kubernetes manifest of the Operator backed service. Instead of having to read and understand from a YAML, it would help if odo provided this information in a simpler way.

`odo describe service` could print this information.

## Why is this needed?
To make `odo link --map` more usable.

/area component
/area linking

**Comment by kadel** [comment]
It should not be `odo describe`. This command is for showing details about components.
This information is about service, so it should be in `odo service describe`.
Not that this command will probably be removed in v3. for odo v3 the equivalent should be `odo describe service` #5341

**Comment by dharmit** [comment]
Thanks for correcting. I changed the issue title and description accordingly.

**Comment by kadel** [comment]
command no longer exists in v3
/close
