### ISSUE TITLE
devfile/library add replicas to  `generator.DeploymentParams` structure

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5347]
It would be nice to have this field set when the Deployment is first created, by the devfile library. Could we propose a path to the library to add the Replicas to the `generator.DeploymentParams` structure?

_Originally posted by @feloy in https://github.com/redhat-developer/odo/pull/5315#r778793735_

**Comment by dharmit** [comment]
On the library side, I forked the repo and added the field, as can be seen on https://github.com/dharmit/library/commit/cd42e3f74d077a1bcebceced58761d0a4b1b0e5f.

On odo side, I made use of it, as can be seen on https://github.com/dharmit/odo/commit/ed0d244f99cec081df658464d7cee324c6901219.

@maysunfaisal can you help here? I have a couple of questions:
1. What are your thoughts about including an extra parameter for replica in the `generator.DeploymentParams` struct?
2. What tests would you recommend adding? A unit test that checks if a Deployment with specified number of replicas was created? Anything else?

**Comment by maysunfaisal** [comment]
@dharmit points 1 & 2 sounds good, feel free to open a PR
