### ISSUE TITLE
Have a list of compatible programming languages / application development somewhere

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#5358]
/kind documentation

## What mistake did you find / what is missing in the documentation?

It's hard to find what is supported / not supported on both the site as well as the documenation.

I'd like to be able to visit the site and know right away what application / programming language that odo supports and what I can do with it / version requirements.

## What is the relevance of it?

No documentation listed in the current docs / website

## TODO

- [ ] Add link to Devfile registry somewhere on the site
- [ ] Emphasize more in quick start / features / overview that you can list what's compatible and what's not with `odo catalog list components` and `odo catalog list services`, etc. As right now, it's not clearly emphasized

**Comment by kadel** [comment]
No we should not list compatible programming languages. It will be impossible to keep it up to date. The languages that odo supports are actually not in control of odo. It depends on devfile. So technically odo supports every language it is just a matter of creating the devfile for it.


If we want to have some list what is possible to do with odo we can link to upstream Devfile registry - https://registry.devfile.io/viewer

**Comment by cdrage** [comment]
> 

Thanks for the link! I didn't actually know that existed and that would immensely help with detailing to the user what's supported or not. I've updated my main question with a TODO list to hopefully complete this task.

**Comment by kadel** [comment]
the first item is covered in https://odo.dev/docs/overview/features
the second task is not valid anymore with odo v3
/close
