### ISSUE TITLE
macos: zsh: exec format error: odo

### ISSUE THREAD

**Issue by cmoulliard** [redhat-developer/odo#5362]
## Issue

Latest tar.gzip file fo macos machines do not work

```
sh -c 'curl -L https://mirror.openshift.com/pub/openshift-v4/clients/odo/latest/odo-darwin-amd64.tar.gz | gzip -d > /usr/local/bin/odo'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15.1M  100 15.1M    0     0  2277k      0  0:00:06  0:00:06 --:--:-- 2254k
chmod +x /usr/local/bin/odo
odo version
zsh: exec format error: odo
```
Question: IS there a distribution working for macos users ?

**Comment by kadel** [comment]
@cmoulliard, Sorry about this. 
I guess you have the command form  docs.openshift.com, right? 


Sadly it is out of date. It has two problems, it uses `mirror.opensift.com which is no longer updated. odo artifacts are now hosted on https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/odo/. The second problem is that the command that we have there only "ungzips" the archive, but it doesn't "untar" it :-( 

There already is a PR that should update OCP documentation. (https://github.com/openshift/openshift-docs/pull/40570)


The correct  one-liner to get binary is:
```
sudo sh -c 'curl -L https://developers.redhat.com/content-gateway/file/pub/openshift-v4/clients/odo/v2.5.0/odo-darwin-arm64.tar.gz | tar -Oxz > /usr/local/bin/odo'
```


To be honest odo section in docs.openshift.com is in a horrible state :-/ We are working on updating it, but meanwhile, it is better to use our upstream documentation at https://odo.dev.


Sorry for the complications.

**Comment by cmoulliard** [comment]
> I guess you have the command form docs.openshift.com, right?

Yes. I used the repo part of the openshift [documentation](https://docs.openshift.com/container-platform/4.9/cli_reference/developer_cli_odo/installing-odo.html).

**Comment by cmoulliard** [comment]
> We are working on updating it,

Saw the email and announce concerning doc re-org ;-)

**Comment by cmoulliard** [comment]
I suggest to close this ticket as this problem affects the OpenShift ODO doc. What do you think @kadel ?
