### ISSUE TITLE
Move examples / quick start guides to github.com/ododev rather than personal usernames

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#5375]
/kind documentation

## What mistake did you find / what is missing in the documentation?

In our current guide we reference personal usernames with regards to downloading the quick example:

```sh
git clone https://github.com/dharmit/odo-quickstart
cd odo-quickstart
```

## What is the relevance of it?

In order to make the guides more professional, I propose that we change the example links to an organization that has a neutral name such as https://github.com/ododev/quickstart instead of https://github.com/dharmit/odo-quickstart

To increase professionalism as well as indicate that it's maintained by a team rather than owned by a single user.

**Comment by dharmit** [comment]
Moved to https://github.com/odo-devfiles/odo-quickstart

/close

**Comment by cdrage** [comment]
Reopening it as we haven't updated documentation yet to reflect the change.

The redirection works, but none of the docs have been updated it.
