### ISSUE TITLE
Using a devfile variable substitution at the beginning of a commandLine in devfile results in error

### ISSUE THREAD

**Issue by ajm01** [redhat-developer/odo#5376]
/kind bug

## What versions of software are you using?

**Operating System:**
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"

**Output of `odo version`:**
odo v2.5.0 (724f16e68)

## How did you run odo exactly?
odo create <comp>

## Actual behavior
added a devfile variable and used variable as the first entry on a commandLine later in the devfile. When creating the component, odo reports a problem with the commandLine in the devfile.yaml and exits with error.

## Expected behavior
The devfile variable substitution should occur with no error or failure.

## Any logs, error output, etc?
added the following devfile variable:

`mvn-cmd: 'mvn'`

used the variable later in the following commandLine:

```commands:
  - id: run
    exec:
      component: dev
      commandLine:  {{mvn-cmd}} -DinstallDirectory=/opt/ol/wlp -Ddebug=false -DhotTests=true -DcompileWait=3 io.openliberty.tools:liberty-maven-plugin:{{liberty-plugin-version}}:dev
      workingDir: /projects
      hotReloadCapable: true
      group:
        kind: run
        isDefault: true
```

odo flags the commandLine as follows:

```$ odo create mycomp
Devfile Object Creation
 ✓  odo will create a devfile component from the existing devfile: /home/ajmauer/REPOS/javaOpenLibertyStackRepo/devfile-stack/inner-loop-test-dir/devfile-stack-intro/devfile.yaml [459700ns]
 ✗  yaml: line 56: did not find expected key
```

I found if I added any kind of prepended string to the beginning of the commandLine, such as:

`commandLine:  echo "CommandLine"; {{mvn-cmd}} -DinstallDirectory=/opt/ol/wlp -Ddebug=false -DhotTests=true -DcompileWait=3 io.openliberty.tools:liberty-maven-plugin:{{liberty-plugin-version}}:dev`

the substitution works fine. It seems like the '{{' at the outset causes an issue?

**Comment by kadel** [comment]
@ajm01 If your string is starting with `{` you need to use quotes.
```yaml
      commandLine:  "{{mvn-cmd}} -DinstallDirectory=/opt/ol/wlp -Ddebug=false -DhotTests=true -DcompileWait=3 io.openliberty.tools:liberty-maven-plugin:{{liberty-plugin-version}}:dev"
```

This is a YAML "feature". `{` is used to define mappings. You will face the same problem if you start your string with `[` or `&`, and many other characters.
It is usually good to quote strings if they start with something other than an alphanumeric character.

**Comment by rm3l** [comment]
Closing as a solution has been provided.

/triage support
/close
