### ISSUE TITLE
Make --hostname a shortcut to --host for url create

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#5379]
/kind feature

## Which functionality do you think we should add?

Switching between multiple CLI tools I find myself using `--hostname` a lot in odo by mistake, which results in an error.

## Why is this needed?

I think we should add a simple shortcut that when you use --hostname it's a shortcut to --host as well, since the names are often mixed / used in other similar tools.

**Comment by kadel** [comment]
`--host` used because the field that this roughly corresponds to in `ingress` and `route` is also called `host`. I think that it is worth having an alias for it.

**Comment by cdrage** [comment]
oc uses `--hostname` for creating a route:

```sh
▶ oc create route edge --help
Create a route that uses edge TLS termination 

Specify the service (either just its name or using type/name syntax) that the generated route should expose via the
--service flag.

Usage:
  oc create route edge [NAME] --service=SERVICE [flags]

Examples:
  # Create an edge route named "my-route" that exposes frontend service.
  oc create route edge my-route --service=frontend
  
  # Create an edge route that exposes the frontend service and specify a path.
  # If the route name is omitted, the service name will be re-used.
  oc create route edge --service=frontend --path /assets

Options:
      --allow-missing-template-keys=true: If true, ignore any errors in templates when a field or map key is missing in
the template. Only applies to golang and jsonpath output formats.
      --ca-cert='': Path to a CA certificate file.
      --cert='': Path to a certificate file.
      --dry-run=false: If true, only print the object that would be sent, without sending it.
      --hostname='': Set a hostname for the new route
```

I think we should have the same for `odo` as an alias just so when you're swapping between tools you don't make the mistake of forgetting it's `--host` not `--hostname`.
