### ISSUE TITLE
If spinner / loading icon is less than 1ms we shouldn't output it

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#5380]
/kind feature

## Which functionality do you think we should add?

If spinner / loading icon has been implementing on part of the CLI, and it's faster than 1ms, we shouldn't output how many nanoseconds it took to complete, for example:

```sh
Validation
 ✓  Validating the devfile [80853ns]
```

Is useless, and should just output:

```sh
Validation
 ✓  Validating the devfile
```

## Why is this needed?

No good output for the user..

**Comment by kadel** [comment]
I would also add that the duration should be in more user-friendly units. nano-seconds are pointless for human understanding. Seconds and minutes would be much better.
