### ISSUE TITLE
Unable to create a root domain / non-subdomain.

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#5383]
/kind feature

## Which functionality do you think we should add?

There is no applicable command to create a url at the root location. For example...

```sh
odo url create . --port 3000 --host example.com
# or
odo url create "" --port 3000 --host example.com
# or
odo url create / --port 3000 --host example.com
````

## Why is this needed?

So I can deploy an application on the default example.com port rather than a subdomain like foo.example.com

**Comment by kadel** [comment]
Creating and odo url for 2nd level domain is more an edge case. We should figure out how to support it, but it is not a high priority.
`odo url create` is mainly for innerloop. That mean that the url that you create with this command are supposed to serve primarily or development, not for real production deployment. I don't expect that someone would host application that they are actively developing on a 2nd level domain.

**Comment by cdrage** [comment]
Closing this as `url create` we are no longer using for `odo dev`, and for `odo deploy` you can specify your own route / ingress.
