### ISSUE TITLE
'odo create nodejs-angular' creates component with two the same named 'dist' storage items 

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/odo#5397]
/kind bug

## What versions of software are you using?

**Operating System:** Linux

**Output of `odo version`:** v2.5.0

## How did you run odo exactly?

```odo create nodejs-angular --starter=nodejs-angular-starter```

## Actual behavior

Creates component with two storage items with the same name `dist`. There is no way to delete one of the items using `odo storage delete dist`, because it deletes both of the storage items.

## Expected behavior

Storage items have unique names and odo delete storage lets delete specific storage item.

**Comment by kadel** [comment]
> Creates component with two storage items with the same name `dist`. There is no way to delete one of the items using `odo storage delete dist`, because it deletes both of the storage items.

This behavior is actually correct. There is only one storage. The devfile defines only one storage (volume) that is shared across into two containers. 

But we will probably need to revisit the `odo storage list` output, as it might not clearly communicate what is going on. 

```
$ odo storage list
The component 'nodejs-angular-angular-qafh' has the following storage attached:
NAME     SIZE     PATH                             CONTAINER     STATE
dist     4Gi      /project/dist/nodejs-angular     builder       Pushed
dist     4Gi      /usr/share/nginx/html            server        Pushed
```

/kind ux

**Comment by dgolovin** [comment]
@kadel basically you are saying that IDE should show one 'dist' even though it is two reported in json. Will fix that.

**Comment by kadel** [comment]
> @kadel basically you are saying that IDE should show one 'dist' even though it is two reported in json. Will fix that.

yes that is correct. Just the way how odo shows this is not intuitive :-/

**Comment by dgolovin** [comment]
I have couple other questions:

* How do I list containers for component?
* Can I delete build container or it should not be allowed, because it breaks 'odo push'?
* How do I create component with multiple containers?
* How do I control what source goes to what container?

**Comment by kadel** [comment]
> * How do I list containers for component?

No way to do that using odo cli, you would have to check `devfile.yaml`



> * Can I delete build container or it should not be allowed, because it breaks 'odo push'?

You can't do that from odo cli, but you can edit `devfile.yaml` directly and remove it. If you are thinking about doing this in [nodejs-angular](https://registry.devfile.io/viewer/devfiles/Community+nodejs-angular) devfile than it will definitely break that devfile. 



> * How do I create component with multiple containers?

You write `devfile.yaml` with multiple containers. Odo is not creating new devfiles, it is just downloading devfiles that are present in Devile registry.

**Comment by valaparthvi** [comment]
/close
Closing this in favor of v3. odo does not handle storage as of now, so this issue isn't really relevant.

Feel free to open it if you think otherwise.
