### ISSUE TITLE
`odo delete component`

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5409]
/kind user-story

## User Story
- As an odo user 
- I want to be able to delete all resources that odo created on the cluster 
- So that 
  - I can start over fresh (because something went wrong)
  - I'm not wasting cluster resources when I'm not using/developing component 
  - I can delete them when I don't need them

## Acceptance Criteria 
- [x] #5478
- [x] #5479

## Related Epic:
#5312

**Comment by dharmit** [comment]
* If no flags are specified and the command is executed from component directory, it deletes the component referred by the devfile.
  * It deletes stuff from the cluster. Doesn't delete anything from local file system
* To delete a component without local devfile.yaml, two flags will be there:
  *  `--name` - for the name of the component
  * `--namespace` - for the namespace in which the component exists.
* Discussion about deleting local files (`devfile.yaml` & `.odo`) to happen with PMs before we decide anything
