### ISSUE TITLE
Remove CSB Jenkins instance

### ISSUE THREAD

**Issue by rnapoles-rh** [redhat-developer/odo#5418]
## Why is this needed?
Currently, we are not using Jenkins for any kind of operation and leaving it as it is, will become another infra to manage for QE.
As we are using IBM Pipelines and don't have plans for using Jenkins, we want to remove the jenkins instance.

**Comment by anandrkskd** [comment]
I have created a ticket for this issue on CSB jenkins side.
Will close this issue once the ticket is closed.

**Comment by anandrkskd** [comment]
Closing this issue as the associated ticket is not resolved and closed.

/close
