### ISSUE TITLE
Version reminders considered disruptive

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#542]
I find it a bit obtrusive that it's 6 lines of output:

```sh
---
A newer version of odo (version: v0.0.7) is available.
Update using your package manager, or run
curl https://raw.githubusercontent.com/redhat-developer/odo/master/scripts/install.sh | sh
to update manually, or visit https://github.com/redhat-developer/odo/releases
---
```

Could we reduce it to..  1?

```sh

A newer version of Odo (0.0.7) is available. See https://github.com/redhat-developer/odo/releases for more detail.
```

Another note, is that we should be adding installation instructions on each release (within the release pages: https://github.com/redhat-developer/odo/releases)

**Comment by surajnarwade** [comment]
Totally agreed, perhaps can we add interactive question here, `do you want update? [y/N]` ?
if yes new binary gets downloaded and replaced with existing one.

(Just a thought)

**Comment by kadel** [comment]
+1
I would also like to add an option to permanently disable version checks.
see https://github.com/redhat-developer/odo/issues/122

**Comment by cdrage** [comment]
This has been improved as well as an option added to permanently disable version checks #122
