### ISSUE TITLE
Select and pull a devfile using Alizer

### ISSUE THREAD

**Issue by feloy** [redhat-developer/odo#5422]
/kind feature

Create a package to select a devfile and pull it, using Alizer to auto-detect the devfile
Given:
- a directory containing source files
- a destination directory to store devfile

```
Based on the files in the current directory odo detected
Language: Java
Project type: SpringBoot

? Is this correct? Yes
```

**Comment by cdrage** [comment]
Charlie's notes:

1. Fetch from devfile registry
2. Get the files
3. Analyze with alizer for checking results / what is being used

**Comment by feloy** [comment]
The package `pkg/odo/cli/init/params` defines Backends to select a devfile using diffetent methods:
- `interactive` backend selects a devfile with the help of the user, interactively
- `flags` backend selects a devfile with the help of a list of flags

You can add an `alizer` backend that will select a devfile with the help of sources in a specific directory.

You will need to modify the signature of the `IsAdequate` method to add a directory path, so the `alizer` backend can return true when the directory contains files.
