### ISSUE TITLE
Cache devfile pulls

### ISSUE THREAD

**Issue by feloy** [redhat-developer/odo#5424]
/kind feature

## Which functionality do you think we should add?

- [ ] Create a package that caches in memory the pulls of devfiles from registry, during the execution of only one odo session (no need to persist the cache or to try to refresh it).
- [ ] Use this package for `odo init`, `odo dev`, `odo deploy`
- [ ] Remove the preference about caching devfile

## Why is this needed?

An odo session can download several times a devfile, either to save the devfile for the user, or to get access to information inside the devfile (get the list of starter projects, etc). At the end, the odo session can download the devfile several times, which can tamper the statistics of devfile registries.

**Comment by valaparthvi** [comment]
I am new to this caching business, and I am wondering where to start with this issue. Do we have a caching mechanism in place or some example that I should be looking at?

**Comment by feloy** [comment]
If you think the cache needs to be thread-safe (do we want to download several devfiles in paralell from different go routines?), you can use or get inspiration from this library: https://github.com/patrickmn/go-cache

**Comment by dharmit** [comment]
@feloy 

>  * [ ]  Use this package for `odo init`, `odo dev`, `odo deploy`

My understanding is that interactive modes for `odo dev` and `odo deploy` shall resort to using the functionality from `pkg/init` when it can't find a `devfile.yaml` in `pwd`. So at the end of the day, we need to implement this in `pkg/init`. Is my understanding correct?

Other than the case of absence of a `devfile.yaml`, is there any other place outside `odo init` where we should be caching devfile(s)?

> * [ ]  Remove the preference about caching devfile

What does this mean? 🤔

**Comment by valaparthvi** [comment]
> > * [ ]  Remove the preference about caching devfile
>
>What does this mean? 🤔 

We have a `RegistryCacheTime` preference setting, IIUC this is about removing the usage of that setting.
