### ISSUE TITLE
`getComponent` should handle the error

### ISSUE THREAD

**Issue by surajnarwade** [redhat-developer/odo#544]
`getComponent` function should handle error if there is no component set.
Reference: https://github.com/redhat-developer/odo/blob/master/cmd/utils.go#L44

**Comment by cdrage** [comment]
@surajnarwade Can we close this? I see that it errors out now if no component has been set.

https://github.com/redhat-developer/odo/blob/7965a83cadd5bf1f1daaf477efb98a8928a344a3/cmd/cmdutils.go#L51

**Comment by surajnarwade** [comment]
yeah we can close this :)
Closing ====>
