### ISSUE TITLE
Refactoring error messages / wrapping output more / consistent UX / UI

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#5445]
/kind feature

## Which functionality do you think we should add?

There are some issues with logging that is not consistent throughout `odo` at the moment, see below:

- [ ] Logging does not have consistent output and we do not  necessarily use `log.Errorf` everywhere: https://github.com/redhat-developer/odo/blob/main/pkg/log/status.go#L285
- [ ] Error output messages are not very clear and are not wrapped correctly at times, some error outputs do not offer solutions on what to do / fix the problem, or links to how to fix it.
- [ ] We should categorize common issues or bugs which offer solutions via the forms of links / troubleshooting steps
- [ ] Possibly categorize each issue (kubernetes issue, devfile issue, etc.)

## Why is this needed?

Improving  logging output for the developer.

**Comment by kadel** [comment]
/close
v3 improved a lot of things in logging and UX
