### ISSUE TITLE
Odo GH actions mirror site needs to be updated to the latest

### ISSUE THREAD

**Issue by josephca** [redhat-developer/odo#5461]
/kind feature

## Which functionality do you think we should add?
Odo GH actions' mirror site seems not been updated after v2.3.1 even later releases are published. 

https://github.com/redhat-actions/openshift-tools-installer
https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/odo/

## Why is this needed?
Devfile integration tests are depending on Odo GH actions.

**Comment by kadel** [comment]
I already mentioned this in https://github.com/redhat-actions/openshift-tools-installer/issues/66

Odo is no longer using mirror.openshift.com for hosting new binary versions. 
The primary location for downloading new odo releases is https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/odo/
