### ISSUE TITLE
Use go 1.17.x to build odo

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/odo#5463]
The build system used by odo to build and publish binaries on [Red Hat Developer content gateway](https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/odo/) has been upgraded to use go 1.17.5. We should build odo using that at the time of making v3alpha1 release.

## remaining
- [ ] #5707
- [x] update IBM cloud build pipeline to use go 1.17
- [x] test in build in Brew using **scratch** build

/kind feature
/area release-eng

**Comment by kadel** [comment]
> The build system used by odo to build and publish binaries o

What is the build system used to build odo binaries?

**Comment by dharmit** [comment]
> What is the build system used to build odo binaries?

Red Hat internal build system, no?

**Comment by anandrkskd** [comment]
> What is the build system used to build odo binaries?

IFAIR we use brew to build our binaries.

**Comment by dharmit** [comment]
> What is the build system used to build odo binaries?

Is that some sort of a quiz you are taking or does this question have some relevance?

**Comment by anandrkskd** [comment]
We are currently using UBI image `registry.access.redhat.com/ubi8/go-toolset:1.16.7` in odo-init-image, but latest version available in that [registry](https://catalog.redhat.com/software/containers/ubi8/go-toolset/5ce8713aac3db925c03774d1?container-tabs=gti) is `1.16.12`. Either, we can use new image to build odo-init-image, or update the version when it is available in `registry.access.redhat.com`.

**Comment by kadel** [comment]
> We are currently using UBI image `registry.access.redhat.com/ubi8/go-toolset:1.16.7` in odo-init-image, but latest version available in that [registry](https://catalog.redhat.com/software/containers/ubi8/go-toolset/5ce8713aac3db925c03774d1?container-tabs=gti) is `1.16.12`. Either, we can use new image to build odo-init-image, or update the version when it is available in `registry.access.redhat.com`.

OpenShift is definitely using at least 1.17 what image they are using?

**Comment by anandrkskd** [comment]
> OpenShift is definitely using at least 1.17 what image they are using?

By OpenShift are you asking about the [Openshift/origin](https://github.com/openshift/origin)?

**Comment by anandrkskd** [comment]
@kadel do we want to use `registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.17-openshift-4.10` in odo-init-image?

**Comment by kadel** [comment]
> @kadel do we want to use `registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.17-openshift-4.10` in odo-init-image?

yes and no :-) For upstream (what is in Dockerfile in repo) we should use something that is based on UBI not RHEL. Then for actual official releases, we can use this RHEL image. 
Image gets replaces during our release process https://gitlab.cee.redhat.com/openshiftdo/release/-/blob/master/manual-release/sync-build-init-image.sh#L77

**Comment by anandrkskd** [comment]
>  For upstream (what is in Dockerfile in repo) we should use something that is based on UBI not RHEL.

But we currently don't have ubi image available for go 1.17.

**Comment by anandrkskd** [comment]
Currently, the build target for 4.10/4.11 doesn't have go 1.17 support, the latest available for the build target 4.10 is go 1.16.
We may need to ask EXD team to add support for go 1.17 on 4.10.
/status blocked

**Comment by anandrkskd** [comment]
@kadel as per our last discussion about the `odo-init-image`, we are not going to update the base image as the latest version(go 1.17) image is not available in the ubi registry. Correct me if I am wrong!

**Comment by anandrkskd** [comment]
Scratch build with go 1.17.7 was successful.

**Comment by anandrkskd** [comment]
Closing this issue as we have another [issue](https://github.com/redhat-developer/odo/issues/5707) for tracking   odo-init-image with go 1.17 
/close
