### ISSUE TITLE
Latest odo Version in mirror.openshift.com gives error "unknown shorthand flag: n in -n"

### ISSUE THREAD

**Issue by edwin** [redhat-developer/odo#5473]
/kind documentation

## What mistake did you find / what is missing in the documentation?
im installing the latest version of odo by following this doco
```
https://odo.dev/docs/getting-started/installation/
```

running odo version will give below result
```
$ odo version
odo v2.3.1 (2ae31fb66)

Server: https://api.cluster.local6443
Kubernetes: v1.22.1+d8c4430
```

trying to follow this doco 
```
https://odo.dev/docs/using-odo/create-component)
```

but running below command would gives an error
```
$ odo create java-springboot snowdrop -n project01

Error: unknown shorthand flag: 'n' in -n
Usage:
  odo create <component_type> [component_name] [flags]
```

i there something i missed?

## What is the relevance of it?

it seems that odo binaries in `https://mirror.openshift.com/pub/openshift-v4/clients/odo/latest/` is still in `odo v2.3.1 (2ae31fb66)` yet the latest odo release in github is `2.5.0`
is it possible that `mirror.openshift.com/` is not syncing?

thanks

**Comment by kadel** [comment]
> is it possible that mirror.openshift.com/ is not syncing? 


new odo versions are no longer published on mirror.openshift.com

As documented in https://odo.dev/docs/getting-started/installation/ The primary location for downloading new odo version is shttps://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/odo

**Comment by kadel** [comment]
I've opened #5474 to better handle the change of the odo download location.


As for
```
$ odo create java-springboot snowdrop -n project01

Error: unknown shorthand flag: 'n' in -n
Usage:
  odo create <component_type> [component_name] [flags]
```

This is outdated documentation that we need to fix.

**Comment by edwin** [comment]
fyi, im downloading `odo` from `https://developers.redhat.com/products/odo/overview`
that link still refer to `mirror.openshift.com/ ` instead of `developers.redhat.com/`

**Comment by valaparthvi** [comment]
The latest still points to 2.5.1, but our docs have been updated to point to the latest v3 releases, I am closing this issue. Edwin, please feel free to reopen this if the need be.
