### ISSUE TITLE
Add warning or redirect mirror.openshift.com to content-gatway

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5474]
/kind user-story

## Background
Multiple users reported that mirror.openshift.com has outdated version because they were not aware that the primary location for odo moved to https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/odo/

## User Story
As an odo user I want to know that I'm accessing an outdated location (https://mirror.openshift.com/pub/openshift-v4/clients/odo/) for downloading odo.

## Acceptance Criteria 
- [x] Update link on https://developers.redhat.com/products/odo/overview to point to content-gateway
- [x] https://mirror.openshift.com/pub/openshift-v4/clients/odo/ should redirect to https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/odo/
  - [x] it needs to work for versions directories `https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/odo/<version>` -> `https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/odo/<version>`
  - [x] as well as for direct binary link `https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/odo/<version>/odo-linux-amd64` -> `https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/odo/<version>/odo-linux-amd64`
- [ ] In case the redirect is not possible, there should be a directory in `https://mirror.openshift.com/pub/openshift-v4/clients/odo/` called `!!!README!!!` (displayed first) with text file explaining that the location moved to `https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/odo/`

## Links 
#5473 
#5461

/kind user-story

**Comment by mohammedzee1000** [comment]
I have reached out to art to figure out if we can have redirect or a readme with new location of latest artifacts posted.

As a secondary objective, I have also reached out to docs team to figure out who owns the web page that contains old links.

**Comment by mohammedzee1000** [comment]
https://issues.redhat.com/browse/ART-3856
https://issues.redhat.com/browse/RHDUXD-1480

**Comment by mohammedzee1000** [comment]
Link on https://developers.redhat.com/products/odo/overview has been updated successfully. Now all that remains is redirect/readme on mirror.openshift.

**Comment by mohammedzee1000** [comment]
It also appears the openshift installer action was closed

**Comment by mohammedzee1000** [comment]
The last thing remaining here is pretty much outside of our control. All we can do it chase after the ART team. We do not know when they will take it up

**Comment by mohammedzee1000** [comment]
The redirect issue has been closed. WE can now see the latest odo even if you access mirror.openshift.com. The fact that this redirect is invisible (no url change is noticed) could confuse people but at eod they will get the latest artifacts even if they go to mirror.openshift 

After the next release, if we do not see the newer artifacts then we can complain but as far as now, this task is pretty much done

**Comment by mohammedzee1000** [comment]
@kadel ptal as well

**Comment by kadel** [comment]
> The redirect issue has been closed. WE can now see the latest odo even if you access mirror.openshift.com. The fact that this redirect is invisible (no url change is noticed) could confuse people but at eod they will get the latest artifacts even if they go to mirror.openshift

It looks like the way they set this up is redirects on a file level. So you need to go all the way to file downloads to see that it redirects. Not ideal, but at least it all points to one location.


The way how this is set up is documented at https://github.com/openshift/aos-cd-jobs/tree/master/hacks/s3_art-srv-enterprise#proxying-to-red-hat-content-gateway-cgw


/close
