### ISSUE TITLE
`odo delete component` -  in the directory with `devfile.yaml`

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5478]
/kind task

## Acceptance Criteria 
- [ ] If `odo delete component` is executed in a directory with `devile.yaml` it should delete all cluster resources related to that devfile (both inner loop and outer loop)
- [ ] Command to delete component should print what will be deleted first and ask the user to confirm.
- [ ] Command should have a flag to "force" deletion without confirmation
- [ ] No local files are deleted or modified.

**Comment by valaparthvi** [comment]
> No local files are deleted or modified.
Does this mean, we do not delete devfile.yaml, and .odo as well?

**Comment by feloy** [comment]
> > No local files are deleted or modified.
> 
> To reiterate, does this mean, we do not delete `devfile.yaml`, and `.odo` as well?

Yes right, we do not delete `devfile.yaml`, and `.odo`

**Comment by valaparthvi** [comment]
> Command to delete component should print what will be deleted first and ask the user to confirm.

Does this mean we ask the user to confirm every resource that they want to delete?
So for the inner loop, it will just be the component itself, and for outerloop, whatever resources are mentioned in the devfile, correct?
This behavior is same as v2 (with the difference that no configuration files will be deleted), correct?

**Comment by feloy** [comment]
I think it is to first display the list of resources that will be deleted, then ask if we want to delete all these resources.

I don't think there is a sense to delete only some resources.

I think it would be important to display the deleted resources when `--force` is used: this way, this output can serve as log if the command is executed from a script.

**Comment by dharmit** [comment]
> Yes right, we do not delete `devfile.yaml`, and `.odo`

If we don't delete `devfile.yaml`, doesn't it pollute the user's git repo if it didn't have a `devfile.yaml` already? For example, a user did `odo init` which creates `devfile.yaml`, why should `odo delete component` not delete this `devfile.yaml`?

Why not the `.odo` directory? It contains `odo-file-index.json`, which IMO should be deleted. Also, the same git repo thing that I mentioned for `devfile.yaml`. IMO, the command should delete all traces of odo ever having run in that directory. Which means it should delete both `.odo` and `.odoignore` files.

**Comment by kadel** [comment]
> If we don't delete `devfile.yaml`, doesn't it pollute the user's git repo if it didn't have a `devfile.yaml` already? For example, a user did `odo init` which creates `devfile.yaml`, why should `odo delete component` not delete this `devfile.yaml`?

we can revisit this later if needed. For now, odo will not delete devfile.yaml


> Why not the `.odo` directory? It contains `odo-file-index.json`, which IMO should be deleted. Also, the same git repo thing that I mentioned for `devfile.yaml`. IMO, the command should delete all traces of odo ever having run in that directory. Which means it should delete both `.odo` and `.odoignore` files.

This is a good point. deleting `.odo` make quite a lot of sense. I think that this will be the next thing that we will have to add into `odo delete component`. but for now, let's make it simple, stick to the original plan and delete just stuff from the cluster. We can easily add this later. 


If recall correctly odo doesn't create `.odoignore` users are required to do it manually. Odo should not delete it if it was not by odo.
