### ISSUE TITLE
`odo delete component` - delete components without devfile.yml

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5479]
- [ ] component is specified using `--name` and `--namespace` flags. `--namespace` is optional and if not used, it assumes default Namespace as defined in `KUBECONFIG`
   - [ ] deletion will be based on label selector `app.kuberentes.io/instance` or `app.kuberentes.io/instance`
- [ ] Deletion should not make any assumption about Kubernetes Kinds. It needs to be able to delete any resource like custom CRs...
- [ ] For now, the deletion should be allowed only on components managed by odo. 
- [ ] Command to delete component should print what will be deleted first and ask the user to confirm.
- [ ] Command should have a flag to "force" deletion without confirmation
- [ ] No local files are deleted or modified.
- [ ] `odo deploy` needs to be updated to add `app.kuberentes.io/instance`

**Comment by feloy** [comment]
When we are looking at the resources with specific labels, we will sometimes find resources that are owned by another resource with same labels. For example, if we find a deployment with labels, we will also find associated replicaset and pod.

1. Do we want to remove all these resources ourselves, or just the parent ones, and let the Kubernetes garbage collector do its work
2. If we remove only the parent, do we display only the resources we will effectively delete, or also the resources that will be deleted by the cluster, for example:

```
The following resources will be deleted: 
	Deployment: my-go-app-app
	Endpoints: my-go-app-app
The following resources will be handled by garbage collector:
	Replicaset: my-go-app-app-57955d5d8c
	Pod: my-go-app-app-57955d5d8c-w2p9k
```

**Comment by kadel** [comment]
> 1. Do we want to remove all these resources ourselves, or just the parent ones, and let the Kubernetes garbage collector do its work
> 2. If we remove only the parent, do we display only the resources we will effectively delete, or also the resources that will be deleted by the cluster, for example:

I would go with just removing the parent resources and displaying just the parents as well. 
The idea is that we should show those resources that odo will be deleting. the "child" resources will be deleted by k8s garbage collector, not by odo.

**Comment by dharmit** [comment]
> I cannot find a way to test the `odo delete component --name aname` command when we have deployed a component on the dev mode. Actually, we could use the v2 `odo push` command to push a component, but this command will be, as far as I understand, removed in a near future. Or we could use the command `odo dev` to push it, as it is not removing the component on exit, but this cleanup will be done in a near future.

IMO, till `odo dev` doesn't start handling the cleanup, we could use this lack of feature in `odo dev` to test `odo delete component --name name` here.

> So finally, do we want to consider the case when a component is pushed in Dev mode?

I think yes because at some point (maybe in alpha2), we want to extend `odo dev` to respect the flag `--no-cleanup`.
