### ISSUE TITLE
Improve file structure of /tests directory

### ISSUE THREAD

**Issue by anandrkskd** [redhat-developer/odo#5482]
/area testing
Currently, we only have devfile tests, we should re-structure the way we store the test and simplify the structure.

Areas getting affected:
- Makefile
 - [ ] make test-unit
 - [ ] make test-integration
 - [ ] make test-interactive
 - [ ] make test (interactive, unit, integration)
 - [ ] removing other test-*
- Test scripts(ibm/openshift-ci)

**Comment by rnapoles-rh** [comment]
Proposal is to move tests assets as follows:
odo
    tests
        devfile
        interactive
        integration
            loginlogout
            odoinit
            odopreference
            odolist
            odo delete
            odoversion
            odoutils
        e2e
