### ISSUE TITLE
Have a way to re-run failed tests

### ISSUE THREAD

**Issue by rnapoles-rh** [redhat-developer/odo#5487]
/kind feature
## Which functionality do you think we should add?

- [ ] have a way to re-run failed tests

## Why is this needed?
The only way we have to rerun tests is to commit a change (adding a comment, or a new blank line)

**Comment by rnapoles-rh** [comment]
We can use the ibmcloud cli to run pipelines by using `ibmcloud dev pipeline-run <PIPELINE_ID>`
We need to run that command if the toolchain returns FAIL to github
There might be race conditions if there are pending jobs or if one or multiple PR commits at the time the pipeline is about to fail.

**Comment by rnapoles-rh** [comment]
We might be able to trigger the pipeline manually directly from GitHub by using [](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow#configuring-a-workflow-to-run-manually)Configuring a workflow to run manually

**Comment by rnapoles-rh** [comment]
Tomas found:
[Redeliver a delivery for a repository webhook](https://docs.github.com/en/enterprise-cloud@latest/rest/reference/webhooks#redeliver-a-delivery-for-a-repository-webhook)

**Comment by rm3l** [comment]
To check again

**Comment by rnapoles-rh** [comment]
the `ibmcloud dev pipeline-run` command does not access commit ID as parameter, so we can not re-run tests for a specific PR:

```
-> % ibmcloud dev pipeline-run help
Name:
   pipeline-run - [Beta] Run a pipeline

Usage:
   ibmcloud dev pipeline-run PIPELINE_ID [options]

   PIPELINE_ID - the ID that defines the pipeline to run

Options:
   --stage-id value  Specify the Stage ID
   --output value    Optional: Specify output format, only JSON is supported now.
   --trace           Display more detailed messages
```

With regards to the latest IBM Cloud modules for Ansible, it provides a resource for cd_toolchain_tool_pipeline. This allows cd_toolchain_tool_pipeline to be created, updated and deleted, but not to trigger the pipeline. 

The current workaround to redeliver with a comment or minor change continues to be our option.

**Comment by rm3l** [comment]
Thanks for the update.

The current workaround that we are all using is closing and then reopening the PR, which would also trigger the IBM Cloud Pipeline for that PR. 

Closing this issue for now until we find a better option, in which case we could consider reopening it.

/close
