### ISSUE TITLE
Have the ability to make IBM tests mandatory/optional for PR merging

### ISSUE THREAD

**Issue by rnapoles-rh** [redhat-developer/odo#5488]
/kind feature
## Which functionality do you think we should add?

- [ ] Have the ability to make tests mandatory/optional for PR merging

## notes
It would be nice to first have #5487 before making test required

https://docs.ci.openshift.org/docs/

**Comment by anandrkskd** [comment]
Closing this issue as we have made IBM cloud mandatory for PRs.
/close
