### ISSUE TITLE
`odo url create` permanently expands devfile variables

### ISSUE THREAD

**Issue by arthurbarr** [redhat-developer/odo#5496]
/kind bug

## What versions of software are you using?

odo 2.5 on macOS:

```
odo v2.5.0 (724f16e68)

Server: https://api.arthur3.cp.fyre.ibm.com:6443
Kubernetes: v1.22.3+e790d7f
```

## How did you run odo exactly?

`odo url create --port 9443 --secure --container dev`

## Actual behavior

My `devfile.yaml` was completely re-written:

1. The order of all the YAML was changed to be alphabetical, which is ugly2. 
2. More importantly, all the devfile variables were permanently expanded.  e.g. instead of `{{liberty-version}}`, every occurrence was expanded out to be the value of that variable.3. 

## Expected behavior

Don't do that.  Ideally, leave the whole file alone, except the bit you're adding to.  I can maybe manage with everything getting re-ordered, but expanding the variables makes things much harder to maintain.

## Any logs, error output, etc?

No.

**Comment by kadel** [comment]
sadly, this is a "feature" of the Go yaml parser that odo uses. 

Currently, there is no way to prevent re-writing the yaml file :-( 
We would have to write our own yaml parser from scratch.

**Comment by valaparthvi** [comment]
Not relevant for v3. Closing it.
/close

**Comment by valaparthvi** [comment]
However, this is still relevant for any commands that try to edit the Devfile and we'll be tracking it in #5789.
