### ISSUE TITLE
Using `go generate` to generate mocks and automating it

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/odo#5503]
/kind discussion

Currently, we generate mocks by running `sh scripts/mockgen.sh` script.

Instead, we could use `go generate` which is meant to generate code or run commands written within existing `.go` files.

**Approach 1**: single `gen.go` file like the current `mockgen.sh` script
```go
package scripts

//go:generate mockgen -source=../pkg/localConfigProvider/localConfigProvider.go -package localConfigProvider -destination ../pkg/localConfigProvider/mock_localConfigProvider.go

//go:generate mockgen -source=../pkg/storage/storage.go -package storage -destination ../pkg/storage/mock_Client.go
```
Running `go generate ./...` generates the mocks.

**Approach 2**: `//go:generate` statement in each file containing interface declaration (provided we want to mock that interface):
```go
package kclient

import ...

//go:generate mockgen -source=interface.go -package kclient -destination=mock_Client.go
type ClientInterface interface {
```
Running `go generate ./...` generates the mocks.

**Automation**: Irrespective of using shell script or `go generate`, we should modify the default build target in the `Makefile` to run the step each time someone does `make`/`make install`. This way, a dev doesn't have to remember to run the command in case the interface changes.
```Makefile
.PHONY: bin
bin: ## build the odo binary
	go generate ./...
	go build ${BUILD_FLAGS} cmd/odo/odo.go
```

**Comment by feloy** [comment]
I find the approach 2 would be more readable.

For the automation, as a developer, I would find strange to see changed files appear, as it is not straightforward to see the link between a `make bin` and a regeneration of code.

Instead, I would force the developer to run `go generate` and push the associated changes for the CI tests to pass. There is an example of such a test in devfile/api: https://github.com/devfile/api/blob/main/.github/workflows/ci.yaml#L29
