### ISSUE TITLE
remove `odo url` command

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5504]
/kind task
/priority high

for alpha1 there will be no `odo url` command.
The command should be removed from odo.

## Acceptance criteria
- [ ] `odo -h` doesn't show anything about url command
- [ ] `odo url` errors out as nonexisting command.
- [ ] code handling `odo url`  command should be removed.

**Comment by dharmit** [comment]
@kadel did you close this one by error?

**Comment by kadel** [comment]
> @kadel did you close this one by error?

no, this now part of the larger issue https://github.com/redhat-developer/odo/issues/5521
as disused we don't know if breaking that big issues by commands is a good approach
