### ISSUE TITLE
remove `--context` flag from cli

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5517]
/kind task
/priority high

in v3 there will be no `--context` flag in any of the odo commands.
The flag should be removed from odo.

## Acceptance criteria
- [x] check all commands and remove `--context` flag

## links
parent task https://github.com/redhat-developer/odo/issues/5403

**Comment by kadel** [comment]
`--context` flag is there for commands that will be removed in #5521

**Comment by feloy** [comment]
The `build-image` command still accepts the `--context` flag

**Comment by feloy** [comment]
Fixed #6202 
/close
