### ISSUE TITLE
Add option to allows user to specify port when component is created

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#552]
## Problem statement
Currently when `odo create ` odo inspect builder image and checks what ports are exposed.
This is just a metadata in the container image. 

User can configure its application to listen on a different port, or different port can be used as default in some frameworks. Then the component will not work properly as we create Service that points only to the ports that are specified in the image.

Example of this happening is #468 

## Solution
Add new optional flag to `odo create`. `--port` this flag could be specified multiple times.

Example:
```
odo create nodejs frontend --port 3000 --port 3030
```
The above command should create a component as we do right now, but the Service that is generated will be for ports 3000 and 3030, and there will be no port detection from an image.

If there is no `--port` flag, then the behavior remains the same. Odo will detect ports from the image.
The only thing that should change here, is that we should display a message saying what ports are going to be used.

This should solve #468

**Comment by mik-dass** [comment]
closing #596
