### ISSUE TITLE
Cleanup commands to align with alpha1

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5521]
odo output should look like this.

```
$ odo -h


Usage:
  odo [flags]
  odo [command]

Examples:
  # Creating and deploying a Node.js project
  git clone https://github.com/odo-devfiles/nodejs-ex
  cd nodejs-ex
  odo init
  odo dev

Available Commands:
  build       Build components defined in the devfile (images)
  delete      Delete resources (component)
  deploy      Deploy devfile
  dev         Deploy component in a development mode
  init        Bootstrap a new project
  login       Log in to an OpenShift cluster
  logout      Log out of the current OpenShift session
  preference  Modify odo settings (registry, set, unset, view)

Utility Commands:
  utils       Utilities for terminal commands and modifying odo configurations (terminal)
  version     Print the client version information
````

## Acceptance criteria 
- [x] every command that is not listed in the example output above should be removed together with its code
- [x] test cases for the removed command should be removed, tests cases use removed commands should be updated
- [x] odo -h doesn't show anything else than command in the above example
- [x] commands that are going to be removed need to be removed together with their implementation and test cases
- [x] all help messages and error messages need to be reviewed and updated to make sure that it doesn't contain reference to commands that no longer exist

## Commands for removal
- [x] #5560
  - [x] #5549
- [x] #5561
- [x] #5562
- [x] #5563
- [x] #5564
- [x] #5559

## Commands to hide
Some commands are not in alpha1, but they will be added in alpha2 and are used in a lot of test scenarios. Instead of completely removing those commands and updating almost all of the tests we can just hide the commands for now.
- [x] hide `odo project` command (https://github.com/redhat-developer/odo/pull/5578)

/priority high
/kind task

**Comment by kadel** [comment]
@feloy @anandrkskd to do research mainly what it will take to update tests that use `odo push` and `odo url`

/assign @feloy 
/assign @anandrkskd

**Comment by xkwangcn** [comment]
hello, have one question, the basic commands seems has big change in next version, could you share me the reason remove those commands and add new command to replace them? I want to know the background or user demand about this. Thanks.

**Comment by kadel** [comment]
hi @xkwangcn, This is driven mainly by user feedback and telemetry.

One of the things that we see in our telemetry data is that we are getting a consistent stream of new odo users, but they don't usually stick around, it looks like they try it, play with it for a few days, and then never go back. 
For me this suggests that the idea and odo's promise is valid, but the execution of that idea needs to change a little bit. 
We want to make odo's cli structure a bit cleaner and in general, streamline the whole experience.
