### ISSUE TITLE
Verify telemetry in v3

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5566]
/kind task

# acceptance criteria
- [x] telemetry should capture the name of each command that is executed, and if it was successful or not
- [x] if there is an error it should be captured in telemetry
- [x] `odo init` should send following additional properties
   - [ ] `interactive` if the command entered interactive mode or not
   - [ ] `devfileLanguage` - corresponding to `metadata.language` field in devfile
   - [ ] `devfileProjectType` - corresponding to `metadata.projectType` field in devfile
   - [ ] `devfileName` - corresponding to `metadata.name`
- [x] `odo dev` and `odo deploy` should send following additional properties
   - [ ] `interactive` if the command entered interactive mode or not
   - [ ] `devfileLanguage` - corresponding to `metadata.language` field in devfile
   - [ ] `devfileProjectType` - corresponding to `metadata.projectType` field in devfile
   - [ ] `devfileName` - corresponding to `metadata.name`
   - [ ] `clusterType` - if the odo is connected to `openshift3` `openshift4` or `kubernetes`

--- 
bonus:
- [x] if ~`ODO_DEBUG_TELEMETRY=true`~ `ODO_DEBUG_TELEMETRY_FILE=somepath` odo telemetry` will save telemetry data to file instead of sending it to segment.io
- [x] tests can keep telemetry enabled and use debug instead to allow writing tests cases for telemetry data

**Comment by valaparthvi** [comment]
Why do we want to know what name the user sets in the devfile(`metadata.name`)? IMO, it could be a potential PII data.

**Comment by kadel** [comment]
> Why do we want to know what name the user sets in the devfile(`metadata.name`)? IMO, it could be a potential PII data.

Yes, we do. I think that we can reasonably expect that this won't be a PII.
