### ISSUE TITLE
Remove support for github based devfile registries

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5579]
Deprecation message was added almost a year ago https://github.com/redhat-developer/odo/pull/4707
v3 is a good time to completely remove this from odo. 
Only devfile registries that odo should support is those using official https://github.com/devfile/registry-support

**Comment by valaparthvi** [comment]
`odo init` does not seem to support GitHub based registries. This is what I tried.
```
➜  odo preference registry add RGH2 https://github.com/devfile/registry
 ⚠  Git based registries Deprecated  Please see https://github.com/redhat-developer/odo/tree/main/docs/public/git-registry-deprecation.adoc
New registry successfully added
➜  mkcd /tmp/101    
➜   odo init --name aname --devfile nodejs --devfile-registry RGH2      
 ✗  Downloading devfile "nodejs" from registry "RGH2" [448ms]
 ✗  unable to download devfile: invalid character '<' looking for beginning of value
the command failed, the devfile has been removed from current directory
```

**Comment by kadel** [comment]
`odo init` is going to be removed.
There are still parts of the code with special logic to handle github registries like https://github.com/redhat-developer/odo/blob/f298389667d65ad633d521f8dc85909ffe88b3ca/pkg/catalog/catalog.go#L188-L230 this should be removed together with tests handling this
