### ISSUE TITLE
`odo deploy` and `odo build-images` is not working on windows

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5588]
It is not possible to build images on Windows

/kind bug
/priority high
/area windows
/area deploy

```
-  Building image locally  ...
/bin/bash: line 1: podman: command not found
 X  Building image locally [376ms]
 X  error running podman command: exit status 127
```

Problem is that odo is trying to execute it inside bash
https://github.com/redhat-developer/odo/blob/7618e8f3e4385bdca620e934c0b27d8fcc878099/pkg/devfile/image/docker_compatible.go#L39

**Comment by mohammedzee1000** [comment]
Ok I did some digging and figured out some stuff
The reason we use bash -c is to ensure shell expansion of environment variables which does not happen by default in exec.Cmd

**Comment by mohammedzee1000** [comment]
@kadel

**Comment by kadel** [comment]
> we either set the envs using `os.Setenv`

to me, using `os.Setenv` looks like the best and cleanest option.
