### ISSUE TITLE
Add pre-commit hook to odo

### ISSUE THREAD

**Issue by valaparthvi** [redhat-developer/odo#5593]
/kind feature

## Which functionality do you think we should add?
Add a pre-commit hook to run go-fmt, go-lint, etc validations before committing to avoid validation failures post commit.

## Why is this needed?
We have validations in [scripts/openshiftci-presubmit-unittests.sh](https://github.com/redhat-developer/odo/blob/main/scripts/openshiftci-presubmit-unittests.sh) that run once a commit is pushed to GH. Some of these validations can be added to the pre-commit hook if not all.
What validations can be added remains to be found, but I would like to propose this idea of adding pre-commit hooks to odo.

I think it would make the PR review and merge process a little faster wherein we don't wait for validation jobs to be run, but run and fix them locally by default before committing and pushing the changes.

References:
https://pre-commit.com/#intro
https://github.com/TekWizely/pre-commit-golang

**Comment by dharmit** [comment]
How's this different from using "File Watchers" or "Actions on Save" in GoLand (I think you use GoLand)?

**Comment by valaparthvi** [comment]
This issue seemed relevant when I opened, but I think we can live without it.
