### ISSUE TITLE
Stop catching `os.Interrupt` signal for Telemetry in case of `odo dev`

### ISSUE THREAD

**Issue by valaparthvi** [redhat-developer/odo#5595]
In the case of `odo dev`, interrupt is not really interrupt that we want to catch as an error. Perhaps you can add a check for `odo dev` before the signal watcher starts.
https://github.com/redhat-developer/odo/blob/main/pkg/odo/genericclioptions/runnable.go#L73

Check if `cmd.Name() == "dev"`, and if it is, don't add the `os.Interrupt` signal to the list. @feloy what do you think?

_Originally posted by @valaparthvi in https://github.com/redhat-developer/odo/pull/5576#discussion_r836294874_

**Comment by mohammedzee1000** [comment]
/kind bug

This seems to be a much more complicated issue than it appears.
The interrupt being an error could entirely depend on where the interrupt happened as well like before the command to wait for something to change for eg

Do we want to consider the intricacies or not

**Comment by dharmit** [comment]
https://github.com/redhat-developer/odo/pull/5596/commits/e8cf3e289e9cbc98fabbd0ee6df27b3e8ae4fc1d will fix this.
