### ISSUE TITLE
Add tests for binaries

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#560]
We should be adding tests for deploying a binary application.

For example:
```sh
  wget -O example.war 'https://github.com/appuio/hello-world-war/blob/master/repo/ch/appuio/hello-world-war/1.0.0/hello-world-war-1.0.0.war?raw=true'
  odo create wildfly --binary example.war
```

**Comment by kadel** [comment]
there is one simple tests for `--binary` in https://github.com/redhat-developer/odo/blob/master/tests/e2e/demo_test.go

**Comment by cdrage** [comment]
Ah, I didn't see it since it was in demo. Thanks!
