### ISSUE TITLE
Error messages should never start capitalize or end with punctuation

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#5611]
/kind documentation

## What mistake did you find / what is missing in the documentation?

See: https://github.com/golang/go/wiki/CodeReviewComments#error-strings

All error messages should not be capitalize or end with punctuation. 

Unless it's the most *top* level error message. 

## What is the relevance of it?

A lot of our error output is inconsistent throughout `odo`

**Comment by kadel** [comment]
We already use https://golangci-lint.run/ as part of our `make validate` check. It should be possible to configure check that will automatically flag any capitalized errors
