### ISSUE TITLE
Image pull secrets

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/odo#5616]
/kind feature

## Which functionality do you think we should add?
I want to be able to pass image pull secrets that should be used by odo when generating deployments as a result of commands such as odo push or deploy. 

## Why is this needed?
Images from a devfile can come from a private registry, or the deployment may need a secret to overcome the rate limits on the image registry like docker.io imposes.

**Comment by kadel** [comment]
Odo should use the same approach as DevWorkspace operator. https://github.com/devfile/devworkspace-operator/blob/main/docs/additional-configuration.adoc#adding-image-pull-secrets-to-workspaces

**Comment by feloy** [comment]
This is possible with odo v3, as documented here: https://odo.dev/docs/user-guides/advanced/container-based-application-development-air-gapped-environment/#pulling-the-container-image
