### ISSUE TITLE
followup on "odo dev part 2 (cleanup) #5485"

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5621]
- [ ] at least one test with devfile that creates storage, k8s. networking/Service (endpoint), k8s component. 
- [ ] verify that this work on Windows

**Comment by dharmit** [comment]
@feloy IIUC, your PR addressed the first part (`at least one test with devfile that creates storage, k8s. networking/Service (endpoint), k8s component.`) of this issue, right?
