### ISSUE TITLE
`odo logs` part 1

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5622]
Part of the https://github.com/redhat-developer/odo/issues/5533 user story

## users should be able to use odo logs command to display stdout and stderr logs of components deployed in dev and deploy mode

- [x] `odo logs` show ALL logs (both dev mode and deploy mode, from all containers)
- [x] `odo logs --dev` shows logs of all containers running in dev mode
- [x] `odo logs --deploy` show logs of all containers from deploy mode
- [x] each log line should be prefixed with name of the container
- [x] command need to be able to handle multiple deployments, pods, and containers (For example devfile can contain multiple Deployments in outer-loop or there can be multiple containers in inner loop etc... )
- [x] Documentation

**Comment by dharmit** [comment]
@kadel this might have been discussed on some call, but it's not noted on this or the parent issue - do we want to follow the logs by default or do we want to print the logs available at the time of running the command? This might have been taken into consideration when pointing the issue as well, but I was probably not around on that call (this Monday.)

**Comment by dharmit** [comment]
In #5760, I have worked upon displaying logs for pods created by odo during the inner loop, a.k.a. Dev mode. It doesn't have follow/tail ability yet. Deploy mode, flags for `--dev` and `--deploy` will follow in a separate PR later. However, from the acceptance criteria, I am ensuring that below two items are covered (IMO, they need to be covered for all scenarios):
* each log line should be prefixed with name of the container
* command need to be able to handle multiple deployments, pods, and containers

**Comment by kadel** [comment]
remaining at least 5 points of work

**Comment by feloy** [comment]
I'm reopening this issue as an integration test covering this feature is failing from time to time:

```
• Failure [2.493 seconds]
odo logs command tests
/home/phmartin/Documents/gits/odo/tests/integration/devfile/cmd_logs_test.go:11
  when component is created and odo logs is executed
  /home/phmartin/Documents/gits/odo/tests/integration/devfile/cmd_logs_test.go:38
    when running in Deploy mode
    /home/phmartin/Documents/gits/odo/tests/integration/devfile/cmd_logs_test.go:71
      should successfully show logs of the running component [It]
      /home/phmartin/Documents/gits/odo/tests/integration/devfile/cmd_logs_test.go:78

      No future change is possible.  Bailing out early after 1.058s.
      Running odo with args [odo logs]
      Expected
          <int>: 1
      to match exit code:
          <int>: 0

```

```
[odo]  ✗  container "main" in pod "devfile-nodejs-deploy-2-6c7c86c779-gdx2g" is waiting to start: ContainerCreating
```

**Comment by dharmit** [comment]
> `[odo] ✗ container "main" in pod "devfile-nodejs-deploy-2-6c7c86c779-gdx2g" is waiting to start: ContainerCreating`

It was for this specific reason (I faced this while testing against minikbue) that in the integration tests I added: https://github.com/redhat-developer/odo/blob/7493e973a598148bf777fec78b21127aac503bf9/tests/integration/devfile/cmd_logs_test.go#L74-L76
and https://github.com/redhat-developer/odo/blob/7493e973a598148bf777fec78b21127aac503bf9/tests/integration/devfile/cmd_logs_test.go#L100-L102

What else should we be doing here?

**Comment by dharmit** [comment]
By any chance, does the environment where these tests are running have Docker installed but not podman? I'm wondering if changing the line from:
```go
helper.Cmd("odo", "deploy").AddEnv("PODMAN_CMD=echo").ShouldPass()
```
to:
```go
helper.Cmd("odo", "deploy").AddEnv("PODMAN_CMD=echo DOCKER_CMD=echo").ShouldPass()
```
would do the trick.

**Comment by feloy** [comment]
> > `[odo] ✗ container "main" in pod "devfile-nodejs-deploy-2-6c7c86c779-gdx2g" is waiting to start: ContainerCreating`
> 
> It was for this specific reason (I faced this while testing against minikbue) that in the integration tests I added:
> 
> https://github.com/redhat-developer/odo/blob/7493e973a598148bf777fec78b21127aac503bf9/tests/integration/devfile/cmd_logs_test.go#L74-L76
> 
> 
> and
> https://github.com/redhat-developer/odo/blob/7493e973a598148bf777fec78b21127aac503bf9/tests/integration/devfile/cmd_logs_test.go#L100-L102
> 
> What else should we be doing here?

IMO, the status could be something else than Running or ContainerCreating. You should instead test that the status is Running

**Comment by feloy** [comment]
> By any chance, does the environment where these tests are running have Docker installed but not podman? I'm wondering if changing the line from:
> 
> ```go
> helper.Cmd("odo", "deploy").AddEnv("PODMAN_CMD=echo").ShouldPass()
> ```
> 
> to:
> 
> ```go
> helper.Cmd("odo", "deploy").AddEnv("PODMAN_CMD=echo DOCKER_CMD=echo").ShouldPass()
> ```
> 
> would do the trick.

No, odo first test for the presence of the podman program. As you declare it as `echo`, it will find it, and odo won't try and test for Docker presence.

**Comment by dharmit** [comment]
> IMO, the status could be something else than Running or ContainerCreating. You should instead test that the status is Running

Tests start three pods. If even one of the pods is in `Running` state and others are in `ContainerCreating` state, the condition would be satisfied and, IMO, we would hit the test failures more often than we do now.

**Comment by feloy** [comment]
> > IMO, the status could be something else than Running or ContainerCreating. You should instead test that the status is Running
> 
> Tests start three pods. If even one of the pods is in `Running` state and others are in `ContainerCreating` state, the condition would be satisfied and, IMO, we would hit the test failures more often than we do now.

You will need to test them independently (or check that Running appears three times)

**Comment by dharmit** [comment]
> You will need to test them independently (or check that Running appears three times)

But what's wrong with the current approach? I've ran these tests many times locally and never faced the problem you mention in https://github.com/redhat-developer/odo/issues/5622#issuecomment-1160550743.

I'm not saying you are wrong. But I'm failing to understand why we hit this issue in spite of all containers being in `Running` state. Or maybe, some Pod has failed to start for whatever reasons, and it's status is netiher `ContainerCreating` nor `Running`.

In which case, what you said makes sense to explicitly check that all Pods are in `Running` state.

**Comment by dharmit** [comment]
I have opened #5851 which should address this. PTAL.
