### ISSUE TITLE
odo with Developer Sandbox shows `use workspace.devfile.io/v1alpha2 DevWorkspace` warnings

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/odo#5625]
When running the current `main` branch of odo against Developer Sandbox, `odo dev` reports a bunch of warnings like:

```sh
$ odo dev
....
....
↪ Deploying to the cluster in developer mode
 ◓  Waiting for Kubernetes resourcesW0405 15:33:59.291310   17558 warnings.go:70] workspace.devfile.io/v1alpha1 DevWorkspace is deprecated; use workspace.devfile.io/v1alpha2 DevWorkspace
 ◒  Waiting for Kubernetes resourcesW0405 15:33:59.803485   17558 warnings.go:70] workspace.devfile.io/v1alpha1 DevWorkspaceTemplate is deprecated; use workspace.devfile.io/v1alpha2 DevWorkspaceTemplate
 ◐  Waiting for Kubernetes resourcesW0405 15:34:33.494855   17558 warnings.go:70] workspace.devfile.io/v1alpha1 DevWorkspace is deprecated; use workspace.devfile.io/v1alpha2 DevWorkspace
 ◑  Waiting for Kubernetes resourcesW0405 15:34:34.008092   17558 warnings.go:70] workspace.devfile.io/v1alpha1 DevWorkspaceTemplate is deprecated; use workspace.devfile.io/v1alpha2 DevWorkspaceTemplate
 ✓  Waiting for Kubernetes resources [46s]
 ✓  Syncing files into the container [4s]
```

/area dev
/triage needs-information
/kind bug

(I'm not sure if this should be classified as bug, but I can't think of anything else either.)

**Comment by feloy** [comment]
This happens when calling the `kclient.GetAllResourcesFromSelector` method.

I can see a related message whn running on a Kubernetes v1.21 cluster:

```
W0405 11:35:26.588174  279766 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
```

I can think of 2 solutions for this:
- either skip the known deprecated GVRs, but we will need to maintain this list, which could be different for the different clusters versions
- or try to hide these warning messages

**Comment by kadel** [comment]
> * or try to hide these warning messages (https://kubernetes.io/blog/2020/09/03/warnings/#customize-client-handling)

if possible i would prefer this solution
