### ISSUE TITLE
Provide an `odo alizer -o json` command

### ISSUE THREAD

**Issue by feloy** [redhat-developer/odo#5642]
`odo` should provide an `alizer` command with `-o json` flag, that will return the result of the `alizer` tool on the current directory.

```
$ odo alizer -o json
{
  "devfile": "go",
  "devfileRegistry": "StagingRegistry"
}
```

The caller will use the exit status of the command to get the error status. 0=> OK and (not 0) => Error

In case of error, the json output will be present in the stderr with the content:

```
{
  message: "..."
}
```

TODO:
- [ ] #5806

**Comment by kadel** [comment]
As we discussed with people working on IDE plugins, this command should return all matches together with the score

**Comment by kadel** [comment]
/status blocked
We need alizer to support returning multiple results sorted by confidence

**Comment by rm3l** [comment]
BTW, I remember one comment from the past sprint demo was that `alizer` as a command did not seem obvious or self-descriptive. I think they suggested using something like `odo identify` or `odo analyze`. Shouldn't we rename this command as part of this issue? @kadel @feloy

**Comment by kadel** [comment]
> Shouldn't we rename this command as part of this issue? @kadel @feloy

+1 for `odo analyze`
