### ISSUE TITLE
Provide an `odo list -o json` command

### ISSUE THREAD

**Issue by feloy** [redhat-developer/odo#5643]
`odo list` command should provide a `-o json` flag to return the list of components in json format.

The list should be prepared to contain several kind of objects: components,  bindings, etc.

```
$ odo list -o json
{
  componentInDevfile: "a-component",
  components: [ 
  {
    "name": "a-component",
    "projectType": "nodejs",
    "runningIn": {
        "Dev": true, 
        "Deploy": true
    },
    "managedBy": "odo"
  }
  ]
}
```

The caller will use the exit status of the command to get the error status. 0=> OK and  (not 0) => Error

In case of error, the json output will be:
```
{
  message: "..."
}
```

**Comment by kadel** [comment]
> components: [ { ... } ]

What will the `components` structure look like?
