### ISSUE TITLE
Provide an `odo init -o json` command

### ISSUE THREAD

**Issue by feloy** [redhat-developer/odo#5645]
`odo init` command should provide a `-o json` flag for non interactive mode, to return details about the downloaded devfile. The output should contain the path of the devfile, its content (the Data part of the devfileObj structure), some high level information (supportedOdoFeatures) and the state of the component (port forwards, running in). ManagedBy must indicate `odo`

```
{
  "devfilePath": "/path/to/new/devfile.yaml",
  "devfileData": {
    "devfile": <devfile content>,
    "supportedOdoFeatures": {
      "dev": true,
      "deploy": false,
      "debug": true,
    }
  },
  "forwardedPorts": [],
  "runningIn": [],
  "managedBy": "odo"
}
```

## Acceptance criteria 

- [ ] If `-o json` flag is used but no other one flag is passed, the command should fail
- [ ] The caller will use the exit status of the command to get the error status. 0=> OK and (not 0) => Error
- [ ] In case of error, the json output will be: `{  "message": "..." }`

**Comment by kadel** [comment]
> "devfile-data": { [... ] }

Could we use `component` instead of `devfile-data` and make the structure match the structure of the `component` field in `odo list -o json`?

**Comment by kadel** [comment]
the devfile data should haev the same format as the output of `odo registry --detail --devfile -o json` (see https://github.com/redhat-developer/odo/issues/5644)
