### ISSUE TITLE
`odo version` never displays the cluster version for a Kubernetes cluster

### ISSUE THREAD

**Issue by feloy** [redhat-developer/odo#5650]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**

odo v2.5.0 (13bbc37df)

## How did you run odo exactly?

```
$ odo version
```

## Actual behavior

```
$ kubectl cluster-info 
Kubernetes control plane is running at https://192.168.1.194:6443
CoreDNS is running at https://192.168.1.194:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

$ odo version
odo v2.5.0 (13bbc37df)
```

## Expected behavior

I expect that the command outputs the version of the cluster.

```
$ odo version
odo v2.5.0 (13bbc37df)

Server: https://192.168.1.194:6443
Kubernetes: v1.21.0
```

**Comment by valaparthvi** [comment]
@feloy Do you think this can be a good first issue? I know people who are interested in contributing to odo and this could be a good start.

**Comment by feloy** [comment]
@valaparthvi 
The error comes from this "fail fast":
```
// fail fast if user is not connected (same logic as `oc whoami`)
	_, err = c.userClient.Users().Get(context.TODO(), "~", metav1.GetOptions{})
	if err != nil {
		return nil, err
	}
```
But this should be done only on an OpenShift cluster, or we should detect that the error is an error about Connection, not about not found resource (we don't care if this fails on a Kubernetes cluster)

**Comment by valaparthvi** [comment]
@feloy Like we discussed yday about picking some issues from your plate, I am interested in picking this one if you haven't started working on it yet and if you're okay with it.

**Comment by feloy** [comment]
> @feloy Like we discussed yday about picking some issues from your plate, I am interested in picking this one if you haven't started working on it yet and if you're okay with it.

OK, you can get it, I didn't start working on it.
Thanks
