### ISSUE TITLE
Use image builders from your namespace when listing the catalog

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#566]
`odo catalog list` should show items in my local namespace as well, so if I define a builder in OpenShift Online I can use it.

**Comment by kadel** [comment]
related to https://github.com/redhat-developer/odo/issues/500

**Comment by kadel** [comment]
Currently, we are deciding whatever the image is builder image or not based on annotations in the ImageStream Tags list - https://github.com/redhat-developer/odo/blob/master/pkg/catalog/catalog.go#L84

Currently, are querying images only in OpenShift project.
We should also query images in the current project. Let's use the same logic, for now, to determine if the image is a builder or not. Later we can also add some custom label, that will make it easier for the user to import builder images. 


This will also require changes to functions that are creating components as currently, they are expecting builderImage to be  only in openshift project
