### ISSUE TITLE
`odo describe component -o json`

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5660]
- [ ] without any additional flags, it describes the current component (devfile in the current directory)
- [ ] can be used with `--name` to describe other components existing on the cluster
- [ ]  `--namespace` is optional and can be used only with `--name` flag

non-json output is part of https://github.com/redhat-developer/odo/issues/5661

```
$ odo describe component -o json
```
```json
{
  "devfilePath": "/path/to/devfile.yaml",
  "devfileData": {
    "devfile": <content of devfile>
  },
  "supportedOdoFeatures": {
      "dev": true,
      "debug": true,
      "deploy": true
  },
  "devForwardedPorts": [
  { 
    "containerName": "cont1",
    "localPort": 40001,
    "containerPort": 8080,
    "address": "localhost",
  }
  ],
  "runningIn": ["Dev", "Deploy"], # or just "Dev", "Deploy", "Unknown", or []
  "managedBy": "odo"  
}
```

**Comment by valaparthvi** [comment]
Why does the output without access to devfile not include data such component type, component name, and namespace? Wouldn't it be helpful?
