### ISSUE TITLE
`odo describe component`

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5661]
/kind user-story

## User Story
- As an odo user
- I want to be able to get detailed information about my component
- So that 
   - I know what commands/odo features are supported by given devfile 
   - I know what are the parts that my application  (devfile) is composed of 

## Acceptance Criteria
- [ ] when user executes the `odo describe component` it should display detailed information about the devfile.yaml in the current directory
- [ ] when user executed the `odo describe component` with `--name` flag it should display detailed information about the component existing on the cluster. Note that in this case the information is not extracted from devfile, but rather from Kubernetes resources. Some information might not be available (like supported odo features), in this case it should show `unknown`
- [ ] `--namespace` is optional and can be used only with `--name` flag
- [ ] forwarded ports are displayed only when `odo dev` is currently running. the format is `<local-address>:<local-port> -> <container-name>:<container-port>` this request to implement https://github.com/redhat-developer/odo/issues/5676 first

/kind user-story

Json output for this command is part of https://github.com/redhat-developer/odo/issues/5660

## example 
```
$ odo describe component

Name: python
Display name: Python
Project Type: python
Language: python
Version: 1.0.0
Description: Python Stack with Python 3.7
Tags: Python, pip

Running in: Dev,Deploy

Forwarded ports:
   - localhost:40001 -> py-web:8080 

Supported odo features:
  - dev: true
  - deploy: false
  - debug: true

Container components:
 - py-web

Kubernetes components:
  - binding-mysql
```

```
$ odo describe component --name myspring

Name: myspring
Display name: 
Project Type: springboot
Language: java
Version: 1.0.0
Description: unknown
Tags: unknown

Supported odo features:
  - dev: unknown
  - deploy: unknown
  - debug: unknown

Running in: Dev,Deploy

Container components: unknown

Kubernetes components: unknown
```

**Comment by feloy** [comment]
On both situtation (with or without name), where are "Container components" and "Kubernetes components" coming from?

For the command without name (and with devfile), this info can come from the devfile content. 

But for the command with name (and without devfile), we cannot get this info from devfile. In think that we could gather this information from the cluster, but in this case, where do we want to store this information in the JSON output?
