### ISSUE TITLE
IBM Cloud tests are failing when the PR title contains a quote

### ISSUE THREAD

**Issue by feloy** [redhat-developer/odo#5663]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**

## Actual behavior

When a PR title contains a quote `'`, the IBM Cloud tests fail with the message:

```
/tmp/run: 96: ./_env: Syntax error: Unterminated quoted string
```

**Comment by anandrkskd** [comment]
@feloy I think this is something which is handled by ibmcloud CI, do you think It's still relevant ? or should we close it

**Comment by rm3l** [comment]
Needs investigation

**Comment by ritudes** [comment]
I check the PR's with quotes ' as well as backquotes ` ,and they passed all the IBM cloud tests.

**Comment by rm3l** [comment]
I faced this issue again on https://github.com/redhat-developer/odo/pull/6833. PR title was: `Fix flaky 'odo dev' test on Podman by randomizing component names`:

```
Preparing to start the job...
Running on public worker: eu-depublicworker04-3
Pulling image quay.io/odo-dev/ibmcloudtest-image:v1.19-1 ...
Job execution started at Mon May 22 16:16:51 UTC 2023
Custom image
Cloning the 'main' branch from repo 'https://github.com/redhat-developer/odo.git'
2023/05/22 16:17:21 Skipping step because a previous step failed
/tmp/run: 18: export: dev test on Podman by randomizing component names: bad variable name
Repository successfully cloned
Performing Pull Request Checkout
From https://github.com/redhat-developer/odo
 * [new ref]             refs/pull/6833/head -> ids-pipeline-temp-branch-for-pr
Switched to branch 'ids-pipeline-temp-branch-for-pr'

Finished: FAILED
```
