### ISSUE TITLE
Catalog items should allow to specify tag

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#567]
`odo catalog list`in OpenShift Online shows redhat-openjdk18-openshift which don't have a latest version, only 1.0, 1.1 and 1.2. If I want to create a component with version 1:2 I can't, as `odo component create redhat-openjdk18-openshift:1.2 myapp`gives an error

**Comment by jorgemoralespou** [comment]
When doing in OpenShift Online:

```
$ odo create redhat-openjdk18-openshift myapp
Service "myapp" is invalid: spec.ports: Required value
```

Odo is trying to use latest image which don't exist.

**Comment by kadel** [comment]
Isn't this the same problem as described in  #514?

**Comment by jorgemoralespou** [comment]
@kadel I guess it's the same. WIll close this in favor of that one.

Closing as duplicate of #514
