### ISSUE TITLE
Add tutorial / details on how to use odo with VSCode / IDE's

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#5674]
/kind documentation

## What mistake did you find / what is missing in the documentation?

We are lacking tutorials / pictures / images on how to use odo with VSCode and a straight forward tutorial.

~Also consider re-adding instructions for installing the VSCode Plugin (removed in https://github.com/redhat-developer/odo/pull/6086#discussion_r963843455 and #6214) once the VSCode Plugin has migrated to v3.~

## What is the relevance of it?

No docs available.

**Comment by kadel** [comment]
- [ ] add (embed) openshift connector demo on odo.dev https://www.youtube.com/watch?v=HEsYgDqD1rM 
  - [ ] on installation page https://odo.dev/docs/getting-started/installation#ide-installation
  - [ ] on homepage alongside the CLI demo

**Comment by cdrage** [comment]
> * [ ]  add (embed) openshift connector demo on odo.dev https://www.youtube.com/watch?v=HEsYgDqD1rM
>   
>   * [ ]  on installation page https://odo.dev/docs/getting-started/installation#ide-installation
>   * [ ]  on homepage alongside the CLI demo

Do you know of any other videos which are much shorter (less than 3 minutes?) rather than the 20 minute demo?

**Comment by rm3l** [comment]
To be considered after VSCode / IDEs have completed their migration to v3, likely after v3 GA.

For the record, this was estimated to 3 story points.
