### ISSUE TITLE
When running `odo dev` and `odo deploy` and prompting for initializing, should have better info

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#5679]
/kind documentation

## What mistake did you find / what is missing in the documentation?

When running `odo dev`, if there is no Devfile, it will try to initialize:

```sh
admin@DESKTOP-DCBL4DB C:\Users\admin>odo dev
The current directory already contains source code. odo will try to autodetect the language and project type in order to select the best suited Devfile for your project.
Based on the files in the current directory odo detected
Language: javascript
Project type: nodejs
The devfile "nodejs" from the registry "DefaultDevfileRegistry" will be downloaded.
? Is this correct? (Y/n)
 X  interrupt

admin@DESKTOP-DCBL4DB C:\Users\admin>odo init
  __
 /  \__     Initializing new component
 \__/  \    Files: Source code detected, a Devfile will be determined based upon source code autodetection
 /  \__/    odo version: v3.0.0-alpha1
 \__/

Interactive mode enabled, please answer the following questions:
Based on the files in the current directory odo detected
Language: javascript
Project type: nodejs
The devfile "nodejs" from the registry "DefaultDevfileRegistry" will be downloaded.
? Is this correct? (Y/n)
 X  interrupt
the command failed, the devfile has been removed from current directory
```

However, there is not much information, as compared to running `odo init`.

When we try to initialize via `odo dev`, we should output to the user that we are going to initialize the directory / use better output. Make it clear to the user that we are creating a new project rather than saying: `The current directory already contains source code. odo will try to autodetect the language and project type in order to select the best suited Devfile for your project.`

## What is the relevance of it?

More information needed to be outputted to the user for clarifying on what `odo` is doing.

**Comment by kadel** [comment]
> When we try to initialize via `odo dev`, we should output to the user that we are going to 
initialize the directory / use better output


Maybe something like this?:

There is no devfile.yaml in the current directory.
odo will try to autodetect the language and project type in order to select the best-suited Devfile for your project.

@cdrage, or do you have something else in mind?

**Comment by valaparthvi** [comment]
@cdrage Can you address Tomas's question? And if this does not seem like an issue anymore then close it?
