### ISSUE TITLE
implement `autoBuild` and  `deployByDefault`

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5694]
devfile 2.2.0 added two new fiels we need to make sure that odo has a proper support for it

https://github.com/devfile/api/pull/709

**Comment by feloy** [comment]
https://github.com/devfile/api/issues/852

**Comment by dharmit** [comment]
Should require making changes into https://github.com/redhat-developer/odo/blob/main/pkg/devfile/components.go#L12 as pointed by @feloy.

**Comment by feloy** [comment]
Make research on this issue

**Comment by rm3l** [comment]
I did some research on this issue to better understand the impact on `odo`, based on the final proposal at https://github.com/devfile/api/issues/852#issuecomment-1211928487:
- `odo dev`
- `odo deploy`
- `odo build-images`: currently, we are building all Image Components, regardless of whether they are referenced or not. So `autoBuild` won't change that behavior. We can continue to build all Images, regardless of `autoBuild`.
- Binding and `odo deploy`: currently, `odo add binding` adds a Kubernetes component to the Devfile with `deployByDefault` not set and which is not referenced by any `apply` command. Per https://github.com/devfile/api/issues/852#issuecomment-1211928487, it will need to be automatically created on startup. So `odo dev` will auto-create it (as before). But I assume `odo deploy` would also do the same, which changes the behavior of `odo deploy` regarding ServiceBinding resources. I understand that this clarifies things, but would that be ok to change this behavior, @kadel?

I have started implementing the required changes in https://github.com/redhat-developer/odo/pull/6654, using [this Devfile](https://github.com/rm3l/odo/blob/5694-implement-autobuild-and-deploybydefault/tests/examples/source/devfiles/nodejs/devfile-autobuild-deploybydefault.yaml) for the test cases.
And the Devfile Parser seems to currently return the default value (`false`) for `deployByDefault` and `autoBuild`, making it quite impossible to handle cases where those fields are not set, and the component is not referenced by any apply command. I'll need to investigate further..

**Comment by rm3l** [comment]
> I have started implementing the required changes in #6654, using [this Devfile](https://github.com/rm3l/odo/blob/5694-implement-autobuild-and-deploybydefault/tests/examples/source/devfiles/nodejs/devfile-autobuild-deploybydefault.yaml?rgh-link-date=2023-03-10T16%3A19%3A09Z) for the test cases. And the Devfile Parser seems to currently return the default value (`false`) for `deployByDefault` and `autoBuild` if not set, making it quite hard to handle cases where those fields are not set, and the component is not referenced by any apply command. I'll need to investigate further..

Ok, I've narrowed down the issue to a boolean passed to the Devfile parser arguments: `FlattenedDevfile`. If this is set to `true` (default value), the Parser sets all unset fields to their default values, making it hard to determine when they are not set:
https://github.com/devfile/library/blob/bd4a12f272573de1ab254f3e138a9b55904af620/pkg/devfile/parser/parse.go#L147-L153
Setting it to `false` ([`055f71a` (#6654)](https://github.com/redhat-developer/odo/pull/6654/commits/055f71ac98d4235e778b8751ad2ddcb14660efcc)) works fine in the scope of this issue, but creates other issues when parsing Devfiles with Parents..

**Comment by rm3l** [comment]
Blocked by https://github.com/devfile/api/issues/1067
