### ISSUE TITLE
Support exec command for deploy

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5701]
## User Story
- As an odo user
- I want to be able to use `exec` command as a `deploy` command (or as part of the `composite` command that is defined as `deploy` command as it is allowed by devfile spec
- So that I can use for example helm or kustomize commands in my deploy flow (see example)

## Acceptance Criteria
- [ ] 
- [x] Make sure to also enable the use of ImageStreams by adding the relevant annotation. See https://github.com/redhat-developer/odo/issues/6376

/kind user-story

```
 ✗  Exec command is not implemented for Deploy
```

## Example
devfile example with `exec` command in deploy

https://github.com/kadel/demo-odo-springboot/blob/d5956f5a8af41ae28dc4d97e0d9c03c9250c1e27/devfile.yaml#L114

/area devfile-spec

**Comment by dharmit** [comment]
Try to have similar reusable code for `exec` command for various group kinds like `deploy`, `build`, etc. instead of having separate implementation of `exec` all over odo code.

**Comment by dharmit** [comment]
> devfile example with `exec` command in deploy
> 
> https://github.com/kadel/demo-odo-springboot/blob/d5956f5a8af41ae28dc4d97e0d9c03c9250c1e27/devfile.yaml#L114

The example devfile uses a container component to execute the exec command. In odo, we spin up such a container in the inner loop only. So for an `odo deploy` with an `exec` command for deploy would succeed only if the component is already running in inner loop.

How do we want to handle this situation? @kadel

**Comment by kadel** [comment]
> The example devfile uses a container component to execute the exec command. In odo, we spin up such a container in the inner loop only. So for an `odo deploy` with an `exec` command for deploy would succeed only if the component is already running in inner loop.
> 
> How do we want to handle this situation? @kadel

Good questions.
I would say that the container should be automatically created, and then when the command is finished, it should be deleted. 
But this is interesting discussion that we should probably bring on the Devfile level.

**Comment by dharmit** [comment]
> I would say that the container should be automatically created, and then when the command is finished, it should be deleted.

That would mean creating a k8s job with the spec of the specified container. Sounds doable at first glance. But certain attributes of a Devfile container component like `endpoints`, `sourceMapping`, `dedicatedPod` would be unnecessary/useless in this context. Of course, we could just ignore them and focus on the required attributes.

> But this is interesting discussion that we should probably bring on the Devfile level.

OK.

**Comment by valaparthvi** [comment]
Should the container continue to run even after the task is done? If we use k8s jobs to run exec command, the pod running the job will terminate as soon as the task is done?

**Comment by valaparthvi** [comment]
https://docs.google.com/document/d/1wbFZLf51FVFDFUHLoVddycbldK23RSHWxDuUexWVy8g/edit#
