### ISSUE TITLE
Error / warn user when trying to push to other source defined in BuildConfig

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#571]
Scenario:
I deploy an image using git
I then try to update that image with local
Since I originally deployed using git, Odo should error out and tell me that I need to update using git and not local or even binary (in Java's case).

@syamgk @kadel

**Comment by cdrage** [comment]
@kadel 

Let me re-phrase!

If I deploy with Git and I choose to update / push changes using **local**, Odo should error out / tell the user to push / update using the originally method (git).

**Comment by mik-dass** [comment]
@cdrage Currently if the build source is git in the buildConfig and we try to push changes using local then this error is shown
```unable to push local directory to component that uses git repository as source```
Should we improve this message?

**Comment by cdrage** [comment]
@mik-dass Yeah, maybe describe what the original source actually is as well. "Unable to push local directory /foo/bar to component FOOBAR that uses Git repository: https://github.com/foo/bar" ?

**Comment by kadel** [comment]
> If I deploy with Git and I choose to update / push changes using local, Odo should error out / tell the user to push / update using the originally method (git).

I agree about push, we should improve our message to add more info. 

But what still confuses me is what update has to do with this.

**Comment by kadel** [comment]
@mik-dass wasn't this solved in #573?

**Comment by mik-dass** [comment]
@kadel yes
