### ISSUE TITLE
Add our deploy examples upstream to Devfile registry (2.2.0 schema)

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#5742]
/kind feature

## Which functionality do you think we should add?

As a user, I want to have my deploy devfiles maintained by the devfile registry for examples such as node.js, dotnet, java, etc.

## Why is this needed?

- [ ] It should have our `odo` deploy examples pushed upstream to the Devfile registry

**Comment by kadel** [comment]
Thís is going to be addressed in https://github.com/devfile/api/issues/757
