### ISSUE TITLE
Missing link to Apple M1 (darwin-arm64) binaries in OpenShift docs

### ISSUE THREAD

**Issue by rofrano** [redhat-developer/odo#5753]
/kind feature

## Which functionality do you think we should add?

As a Software Engineer, I need a native arm64 compiled version of `odo,` So that I can work in Docker containers with VSCode Remote Containers on Apple M1 Silicon which is arm based.

## Why is this needed?

My teams and students do all of their work in Docker containers using Visual Studio Code and the Remote Container extension. Many teams members have new Apple M1 Silicon Macs that are arm based and this number continues to grow. All of our containers are Linux based and so we need a version of `odo` that runs in a  linux container on arm64 architecture.

For more information on why we do this, read my article: [Developing on Apple M1 Silicon with Virtual Environments](https://johnrofrano.medium.com/developing-on-apple-m1-silicon-with-virtual-environments-4f5f0765fd2f) for a similar solution using Vagrant which also requires an arm64 version of `odo`.

**Comment by cdrage** [comment]
Hey @rofrano 

We have releases of `odo` for Mac M1 which I've been personally using it.

https://odo.dev/docs/getting-started/installation#macos

**Comment by rofrano** [comment]
@cdrage Awesome! You might want to tell the Red Hat OpenShift team about this because their docs make no mention of an arm64 version: https://docs.openshift.com/container-platform/4.6/cli_reference/developer_cli_odo/installing-odo.html

Thanks for pointing this out. I'm going to try and incorporate this into my DevOps course this semester. You can close this issue.

**Comment by rofrano** [comment]
@cdrage Do you know why none of the commands in the `odo` [Quick Start Guide](https://odo.dev/docs/getting-started/quickstart) work? I tried:

```bash
odo catalog list components
odo create nodejs frontend
odo url create ...
```

And all I get is:

```
Invalid command - see available commands/subcommands above
```

That `catalog`, `create` and `url` are invalid commands? Are there 2 versions of `odo`?

**Comment by rofrano** [comment]
@cdrage It appears that the [installation page](https://odo.dev/docs/getting-started/installation#cli-binary-installation) points to `v3.0.0~alpha1` which is missing MOST of the `odo` functions!

You might want to relink `latest` to `v2.5.1` which is the last working version and not to an alpha version that is not ready for public consumption yet. I switched my download to `v2.5.1` and all is working again.

**Comment by kadel** [comment]
Hi @rofrano, thanks for raising this. I'll keep this issue open and only rename it. As you discovered we need to mention M1 binaries on openshift docs.


/title Missing link to Apple M1 (darwin-arm64) binaries in OpenShift docs

**Comment by valaparthvi** [comment]
This is addressed by Gabriel's PR https://github.com/openshift/openshift-docs/pull/51827.

**Comment by valaparthvi** [comment]
I believe we can close this since downstream docs will point to upstream.
/close
