### ISSUE TITLE
Registry DefaultDevfileRegistry error :  x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by mafalarz** [redhat-developer/odo#5759]
/kind bug

## What versions of software are you using?

**Operating System:**
Windows 10 Pro 21H2 19044.1645

**Output of `odo version`:**
odo v2.5.1 (ae0c55309)

## How did you run odo exactly?
odo create nodejs

## Actual behavior
 !  Registry DefaultDevfileRegistry is not set up properly with error: Get "https://registry.devfile.io/index": x509: certificate signed by unknown authority, please check the registry URL and credential (refer `odo registry update --help`)

 X  Checking if the devfile for "nodejs" exists on available registries [0ns]
 X  devfile component type "nodejs" is not supported, please run `odo catalog list components` for a list of supported devfile component types

## Expected behavior
That it works

**Comment by kadel** [comment]
/close
closing this as there was no response, and it did not looked like odo issue.
@mafalarz if you still have this issue feel free to comment and reopen this
