### ISSUE TITLE
Cleanup and reorganise e2e test

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#576]
We need to clean up our e2e tests a bit.

- broke it down into multiple test cases
- rename demo_test.go to something better
- write helper functions for common tasks in e2e tests to make it easier to add new test cases

**Comment by ashetty1** [comment]
Here's how I will go about this issue to start with:

- Move helper functions to a separate file: e2e.go
- Create helper functions to project/application creation and deletion 
- Move detailed tests into separate test files
- e2e_test.go will contain a bare minimal set of cases which could be easily run locally too
- Investigate issues with running tests on minishift

**Comment by ashetty1** [comment]
PR fixing minishift issues #606

**Comment by kadel** [comment]
Hi @ashetty1, how is this going?

**Comment by surajnarwade** [comment]
Closing this issue, since #625 is merged.
