### ISSUE TITLE
Haphazard ordering of docs under "Command Reference" for v3.0.0-alpha1

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/odo#5766]
/kind documentation

## What mistake did you find / what is missing in the documentation?
Under the "Command Reference" section on the sidebar on https://odo.dev/docs/3.0.0/overview/intro, I noticed that the ordering of the docs is haphazard. Multiple docs have the same value for `sidebard_position` in the front matter, which makes no sense.

## What is the relevance of it?
Haphazard ordering is of no help to the users. We should have them in some order. We initially started with alphabetical order so that it's simpler for users to quickly find what they are looking for. However, that ordering is no longer adhered to.

**Comment by cdrage** [comment]
Agreed, let's reorder the Command Reference so it's alphabetical.

**Comment by dharmit** [comment]
> The ordering seemed to be the order of usage of the odo commands

So initially there was this idea that we do "order of usage of the odo commands" in the "User Guides" section. This section would be about conveying a story to the user. As for the "Command Reference" section, the idea was to keep things alphabetical.

Now that @cdrage is back, I don't have a strong opinion about it. But, personally, it makes sense to me to follow the above approach.
