### ISSUE TITLE
Research TDD (Test Driven Development)

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#577]
We have some issues regarding our code quality and testing.
It might be interesting to try follow TDD process.

- Research TDD process. 
- Make a short introduction for the rest of the team, explaining basic principles of TDD process

**Comment by kadel** [comment]
@ashetty1 Please convert your google doc to the markdown document and link and add info to development.md for everyone to see.

**Comment by kadel** [comment]
Or to a wiki page, whatever you think is better.

**Comment by ashetty1** [comment]
Added the workflow doc here: #607

**Comment by ashetty1** [comment]
PR #607 with the workflow document has been merged.
