### ISSUE TITLE
odo dev fails when using an image running as root for dev container

### ISSUE THREAD

**Issue by feloy** [redhat-developer/odo#5782]
/kind bug

## What versions of software are you using?

**Operating System:**

Linux Fedora 35

Kubernetes cluster only

**Output of `odo version`:**

odo v3.0.0-alpha2 (25dfab4b4)

## How did you run odo exactly?

```
$ odo init --name my-go-app --devfile go --starter go-starter
$ odo dev
[...]
 ◐  Syncing files into the container ✗  Command 'tar xf - -C /projects' in container failed.

 ✗  stdout: 

 ✗  stderr: tar: devfile.yaml: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: go.mod: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: main.go: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: .gitignore: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: README.md: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
tar: Exiting with failure status due to previous errors


 ✗  err: error while streaming command: command terminated with exit code 2

 ✗  Syncing files into the container [267ms]
Cleaning resources, please wait
 ✗  failed to create the component: failed to sync to component with name my-go-app: failed to sync to component with name my-go-app: unable push files to pod: error while streaming command: command terminated with exit code 2
```

## Any logs, error output, etc?

This is due to tar extracting user with original owner, which is the default for root user.

A solution would be to run tar with `--no-same-owner` option

**Comment by rm3l** [comment]
@feloy I couldn't reproduce the issue using the steps you provided and using the latest commit on main: [f3cd3e9](https://github.com/redhat-developer/odo/commit/f3cd3e9fc3f9167883bdac5121743ad3aa714ecc). Did you do something special?
(Just trying to see if and how adding an integration test to your PR #5783 could be helpful to prevent future regressions)

Here is an excerpt of the logs, to make sure the `tar` command has been executed without the `--no-same-owner` option.
```
I0602 09:24:15.447047  412214 file_indexer.go:464] last modified date changed: /home/asoro/work/tmp/5783-review--tar-no-same-owner-image-running-as-root/main.go                                                                                                                 
I0602 09:24:15.447074  412214 adapter.go:133] List of files to be deleted: +[]                                                                                                                                                                                                   
I0602 09:24:15.447079  412214 adapter.go:135] List of files changed: +[/home/asoro/work/tmp/5783-review--tar-no-same-owner-image-running-as-root/main.go]                                                                                                                        
I0602 09:24:15.447085  412214 adapter.go:169] Push: componentName: my-go-app, path: /home/asoro/work/tmp/5783-review--tar-no-same-owner-image-running-as-root, files: [/home/asoro/work/tmp/5783-review--tar-no-same-owner-image-running-as-root/main.go], delFiles: [], isForceP
ush: false                                                                                                                                                                                                                                                                       
I0602 09:24:15.447109  412214 adapter.go:209] Copying files /home/asoro/work/tmp/5783-review--tar-no-same-owner-image-running-as-root/main.go to pod
I0602 09:24:15.447116  412214 sync.go:38] CopyFile arguments: localPath /home/asoro/work/tmp/5783-review--tar-no-same-owner-image-running-as-root, dest /projects/5783-review--tar-no-same-owner-image-running-as-root, targetPath /projects, copyFiles [/home/asoro/work/tmp/5783-review--tar-no-same-owner-image-running-as-root/main.go], globalExps [.git .odo/env .odo/odo-file-index.json main]
I0602 09:24:15.447130  412214 pods.go:174] Executing command tar xf - -C /projects
I0602 09:24:15.447206  412214 sync.go:79] makeTar arguments: srcPath: /home/asoro/work/tmp/5783-review--tar-no-same-owner-image-running-as-root, destPath: /projects/5783-review--tar-no-same-owner-image-running-as-root, files: [/home/asoro/work/tmp/5783-review--tar-no-same-owner-image-running-as-root/main.go]
I0602 09:24:15.447448  412214 sync.go:110] Got abs path: /home/asoro/work/tmp/5783-review--tar-no-same-owner-image-running-as-root/main.go
I0602 09:24:15.447458  412214 sync.go:111] Making /home/asoro/work/tmp/5783-review--tar-no-same-owner-image-running-as-root relative to /home/asoro/work/tmp/5783-review--tar-no-same-owner-image-running-as-root/main.go
I0602 09:24:15.447468  412214 sync.go:127] makeTar srcFile: 5783-review--tar-no-same-owner-image-running-as-root/main.go
I0602 09:24:15.447475  412214 sync.go:128] makeTar destFile: main.go 
I0602 09:24:15.447480  412214 sync.go:148] recursiveTar arguments: srcBase: /home/asoro/work/tmp, srcFile: 5783-review--tar-no-same-owner-image-running-as-root/main.go, destBase: /projects, destFile: main.go
I0602 09:24:15.447486  412214 sync.go:154] Corrected destinations: base: /projects file: main.go
 ✓  Syncing files into the container [41ms]
I0602 09:24:15.487331  412214 exec.go:26] Executing command [/opt/odo/bin/supervisord ctl status] for pod: my-go-app-app-5cbb5fc948-ssp97 in container: runtime
debugrun                         STOPPED   
devrun                           RUNNING   pid 203, uptime 0:00:35
I0602 09:24:15.529238  412214 pods.go:29] Waiting for component=my-go-app pod
I0602 09:24:15.530732  412214 pods.go:59] Status of my-go-app-app-5cbb5fc948-ssp97 pod is Running

```

**Comment by feloy** [comment]
I forgot to mention the problem occurs on Kubernetes clusters only (as OpenShift seems to force the use of non-root containers). Are you testing on OpenShift?

**Comment by rm3l** [comment]
> @rm3l I forgot to mention the problem occurs on Kubernetes clusters only (as OpenShift seems to force the use of non-root containers). Are you testing on OpenShift?

🤔 I've tested this only on Kubernetes (local Kind cluster).

**Comment by feloy** [comment]
> > @rm3l I forgot to mention the problem occurs on Kubernetes clusters only (as OpenShift seems to force the use of non-root containers). Are you testing on OpenShift?
> 
> thinking I've tested this only on Kubernetes (local Kind cluster).

Can you connect to the container to see if you are root, and if so, try to create a tar and untar it?

**Comment by rm3l** [comment]
> > > @rm3l I forgot to mention the problem occurs on Kubernetes clusters only (as OpenShift seems to force the use of non-root containers). Are you testing on OpenShift?
> > 
> > 
> > thinking I've tested this only on Kubernetes (local Kind cluster).
> 
> Can you connect to the container to see if you are root, and if so, try to create a tar and untar it?

The container is running as root:

```
❯ kubectl exec -it my-go-app-app-5cbb5fc948-7xlc9 -- sh
Defaulted container "runtime" out of: runtime, copy-supervisord (init)
# id
uid=0(root) gid=0(root) groups=0(root)

# cd /projects
# ls
README.md  devfile.yaml  go.mod  main  main.go

# tar cvf /projects/test.tar *
README.md
devfile.yaml
go.mod
main
main.go

# ls -l
total 12312
-rw-r--r-- 1 1000 1000      45 Jun  2 07:11 README.md
-rw-r--r-- 1 1000 1000     968 Jun  2 07:11 devfile.yaml
-rw-r--r-- 1 1000 1000      68 Jun  2 07:11 go.mod
-rwxr-xr-x 1 root root 6289614 Jun  2 08:03 main
-rw-r--r-- 1 1000 1000     245 Jun  2 07:24 main.go
-rw-r--r-- 1 root root 6297600 Jun  2 08:10 test.tar

# tar xf test.tar -C /projects
# echo $?
0

```

**Comment by feloy** [comment]
@rm3l What is the Kubernetes version you are using?

I can see it fail on 1.23, not on 1.22

**Comment by rm3l** [comment]
> @rm3l What is the Kubernetes version you are using?
> 
> I can see it fail on 1.23, not on 1.22

Using 1.23 as well:
```
❯ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.1
Kustomize Version: v4.5.4
Server Version: v1.23.5
```

This is weird, because I also just tried to create a tar on the host, then untar it on the fly inside the container (as it seems to be done by odo, per my understanding from the logs), and no issue either.

```
asoro in work-laptop in ☸ kind-local-k8s-cluster in ~/work/tmp/5783-review--tar-no-same-owner-image-running-as-root via 🐹 v1.18.1 on ☁️   
✦ ❯ tar cf test.tar *

asoro in work-laptop in ☸ kind-local-k8s-cluster in ~/work/tmp/5783-review--tar-no-same-owner-image-running-as-root via 🐹 v1.18.1 on ☁️   
✦ ❯ ls -l
Alias tip: ll
total 28
-rw-r--r-- 1 asoro asoro    45 Jun  2 09:11 README.md
-rw-r--r-- 1 asoro asoro   968 Jun  2 09:11 devfile.yaml
-rw-r--r-- 1 asoro asoro    68 Jun  2 09:11 go.mod
-rw-r--r-- 1 asoro asoro   245 Jun  2 09:24 main.go
-rw-r--r-- 1 asoro asoro 10240 Jun  2 10:23 test.tar

asoro in work-laptop in ☸ kind-local-k8s-cluster in ~/work/tmp/5783-review--tar-no-same-owner-image-running-as-root via 🐹 v1.18.1 on ☁️   
✦ ❯ kubectl exec -it my-go-app-app-5cbb5fc948-7xlc9 -- sh -c 'rm -rf /projects/* && ls -l /projects'
Defaulted container "runtime" out of: runtime, copy-supervisord (init)
total 0

asoro in work-laptop in ☸ kind-local-k8s-cluster in ~/work/tmp/5783-review--tar-no-same-owner-image-running-as-root via 🐹 v1.18.1 on ☁️   
✦ ❯ cat test.tar | kubectl exec --stdin my-go-app-app-5cbb5fc948-7xlc9 -- tar xf - -C /projects     
Defaulted container "runtime" out of: runtime, copy-supervisord (init)

asoro in work-laptop in ☸ kind-local-k8s-cluster in ~/work/tmp/5783-review--tar-no-same-owner-image-running-as-root via 🐹 v1.18.1 on ☁️   
✦ ❯ kubectl exec -it my-go-app-app-5cbb5fc948-7xlc9 -- ls -l /projects
Defaulted container "runtime" out of: runtime, copy-supervisord (init)
total 16
-rw-r--r-- 1 1000 1000  45 Jun  2 07:11 README.md
-rw-r--r-- 1 1000 1000 968 Jun  2 07:11 devfile.yaml
-rw-r--r-- 1 1000 1000  68 Jun  2 07:11 go.mod
-rw-r--r-- 1 1000 1000 245 Jun  2 07:24 main.go

```

**Comment by feloy** [comment]
I think the volume used for the /projects directory is the main limitation.

It works for me with an NFS volume with the no_root_squash flag (which enables root client of NFS to act as root on NFS volume), but not with an NFS without this flag (which is more secure)

**Comment by rm3l** [comment]
> I think the volume used for the /projects directory is the main limitation.
> 
> It works for me with an NFS volume with the no_root_squash flag (which enables root client of NFS to act as root on NFS volume), but not with an NFS without this flag (which is more secure).
> 
Okay, I see. Good point about the volume. I didn't configure anything on Kind about volumes.
Using your branch, I can see the owner is `root`:

```
root@my-go-app-app-77965987c6-pwcjn:/go# ls /projects/ -l
total 6172
-rw-r--r-- 1 root root      45 Jun  2 07:11 README.md
-rw-r--r-- 1 root root     968 Jun  2 07:11 devfile.yaml
-rw-r--r-- 1 root root      68 Jun  2 07:11 go.mod
-rwxr-xr-x 1 root root 6289614 Jun  2 09:04 main
-rw-r--r-- 1 root root     245 Jun  2 07:24 main.go
```

>
> The Kubernetes cluster used for test is using NFS volumes without no_root_squash, the error is reproducible there. But it could be interesting to test with other kind of volumes
>
But out of curiosity, all our tests (at least the ones running `odo dev` with `Ephemeral` set to `false`) should have been failing then, no?

**Comment by feloy** [comment]
> > I think the volume used for the /projects directory is the main limitation.
> > It works for me with an NFS volume with the no_root_squash flag (which enables root client of NFS to act as root on NFS volume), but not with an NFS without this flag (which is more secure).
> 
> Okay, I see. Good point about the volume. I didn't configure anything on Kind about volumes. Using your branch, I can see the owner is `root`:
> 
> ```
> root@my-go-app-app-77965987c6-pwcjn:/go# ls /projects/ -l
> total 6172
> -rw-r--r-- 1 root root      45 Jun  2 07:11 README.md
> -rw-r--r-- 1 root root     968 Jun  2 07:11 devfile.yaml
> -rw-r--r-- 1 root root      68 Jun  2 07:11 go.mod
> -rwxr-xr-x 1 root root 6289614 Jun  2 09:04 main
> -rw-r--r-- 1 root root     245 Jun  2 07:24 main.go
> ```
> 
> > The Kubernetes cluster used for test is using NFS volumes without no_root_squash, the error is reproducible there. But it could be interesting to test with other kind of volumes
> 
> But out of curiosity, all our tests (at least the ones running `odo dev` with `Ephemeral` set to `false`) should have been failing without your changes then, no?

Yes, on the IBM Kubernetes cluster, it should fail, but we don't have tests with the go devfile used with `odo dev` (we are running most of the  `odo dev` tests with nodejs devffile)
