### ISSUE TITLE
failed to delete the ServiceBinding resource

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5797]
/kind bug
/priority high

When using `odo dev`, the ServiceBinding is being created, and when we control+c the process, the ServiceBinding is deleted, but the logs say "Failed to delete the "ServiceBinding" resource"

**Comment by valaparthvi** [comment]
I am unable to reproduce this issue on main. Tomas, can you test again?

**Comment by valaparthvi** [comment]
@rm3l  could not reproduce this either, I am going to close this issue.
