### ISSUE TITLE
`odo dev` automaticaly refresh oidc token before it expires

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5819]
## User Story
- As an odo usser
- I don't want `odo dev` command to be interrupted because auth token expired.
- So that I can keep working without `odo dev` failing on me due to an expired session. 

## Acceptance Criteria
- [ ] when `odo dev` is running, it should periodically check the validity of the authentication token. The first check should be right after start-up. If the token is going to expire in the next 10 minutes odo should refresh the token. If it will be valid in the next 10 mins, do nothing and wait for 10 minutes to check the token again.

/kind user-story

**Comment by rm3l** [comment]
To clarify: which auth mechanism is used to connect to OpenShift?

**Comment by feloy** [comment]
As I understand, OpenShift does not use OIDC by default, but an OpenID connect Identity provider can be specified, using these steps: https://docs.openshift.com/container-platform/4.10/authentication/identity_providers/configuring-oidc-identity-provider.html

**Comment by feloy** [comment]
https://developers.redhat.com/openshift/keep-logining-in#:~:text=In%20a%20typical%20OpenShift%20environment,will%20need%20to%20login%20again.

**Comment by cdrage** [comment]
Needs more information: Unable to find solution for implementation / feature at the moment

**Comment by valaparthvi** [comment]
There isn't a way to automatically refresh a token with oc. Closing it.
