### ISSUE TITLE
[Epic] Improve devfile spec support in odo

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5834]
odo, currently has only limited coverage of devfile specification.
We have identified a few areas where we should improve devfile coverage in odo.
Most of the requested improvements are based on real scenarios where a lack of support for particular odo features made it hard or impossible to use odo with project.

- https://github.com/redhat-developer/odo/issues/6565
- https://github.com/redhat-developer/odo/issues/5694
- https://github.com/redhat-developer/odo/issues/6274 
- ~https://github.com/redhat-developer/odo/issues/5706~ (we decided to move this issue out of this epic - see https://github.com/redhat-developer/odo/issues/5706#issuecomment-1568325682) 
- ~https://github.com/redhat-developer/odo/issues/6786~ (priority reduced => issue moved out of this epic)

**Comment by rm3l** [comment]
/close

All items completed. https://github.com/redhat-developer/odo/issues/5706 and https://github.com/redhat-developer/odo/issues/6786 moved out of this Epic.
