### ISSUE TITLE
OpenShift integration tests are started with different command then Kubernetes one

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5839]
/kind bug
/area testing
/priority high

I've just noticed that OpenShift and Kubernetes tests on IBM cloud are executing different test commands.

OpenShift tests are started with
```
GOFLAGS='-mod=vendor' go run -mod=vendor github.com/onsi/ginkgo/ginkgo  -randomizeAllSpecs -slowSpecThreshold=120 -timeout 14400s -nodes=32 tests/integration/
```
Kubernetes tests with
```
GOFLAGS='-mod=vendor' go run -mod=vendor github.com/onsi/ginkgo/ginkgo  -randomizeAllSpecs -slowSpecThreshold=120 -timeout 14400s -nodes=32 tests/integration/devfile/
```

This looks suspicious to me. Especially as I've seen PR where one of the tests fails and the other is successful.

**Comment by anandrkskd** [comment]
This is now fixed by https://github.com/redhat-developer/odo/pull/5931 
/close
