### ISSUE TITLE
Document how odo works with projects/namespaces

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5860]
/area Documentation

There is some confusion on how odo works with namespaces. 
For example, users are wondering why the `odo project set` doesn't change the project that the component is in.

**Comment by valaparthvi** [comment]
I don't have anything else to work on this sprint, so I'm going to pick this up.
/assign valaparthvi

**Comment by valaparthvi** [comment]
I think @rm3l has done a pretty good job at the clarifying this in [the help section](https://github.com/redhat-developer/odo/blob/main/pkg/odo/cli/set/namespace/namespace.go#L33) and in [the docs](https://odo.dev/docs/command-reference/set-namespace), I have raised a PR highlighting what he's written. I am not sure if we can get more specific than that.
