### ISSUE TITLE
`odo init` interactive mode: Automatic port detection based on Alizer detection

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5863]
/kind user-story

## User Story
As an odo user, I want odo to automatically detect the port that my application is using So that I don't have to type it again if it is already defined in my project source code.

## Acceptance Criteria 
- [ ]  `odo init` should automatically detect all ports that the application listens to

## Notes
The detection logic should be in Alizer, odo should just use Alizer library for this.

/kind user-story

**Comment by kadel** [comment]
/status blocked
Currentl, Alizer can't do this, but it is work in progress

**Comment by ryanj** [comment]
I would love to see support for manually providing a port value via `odo init --port PORTNUMBER`.  

If more than one port is detected, we may need the user to specify which port to use anyway.

**Comment by rm3l** [comment]
> I would love to see support for manually providing a port value via `odo init --port PORTNUMBER`.
> 
> If more than one port is detected, we may need the user to specify which port to use anyway.

Thanks for your input, @ryanj !

As I understand it, if there are multiple ports detected in the application and returned by Alizer (when running `odo init`), the resulting Devfile would list them all, and `odo dev` would expose and port-forward each one of them. It would then be up to users to call the application on the right port forwarded.
But as you suggested, giving users the ability to explicitly specify the port (and optionally a debug port too) (at least when running `odo init` non-interactively) would be great.

@kadel Any comment on that?

**Comment by valaparthvi** [comment]
- If alizer detects single port, override the port defined in Devfile.
- If alizer detects no port, use the port defined in Devfile.
- Warn the user about it in both the cases.
- If there are multiple container components, error out, for now.
