### ISSUE TITLE
Do not setup cluster for the integration tests that do not require it

### ISSUE THREAD

**Issue by valaparthvi** [redhat-developer/odo#5868]
## User Story
As a developer I want to use a different setup for integration tests that do not require cluster setup such as namespace creation which tends to slow things down, so that we can make our test suite a little bit faster.

## Acceptance Criteria 
It should not setup cluster for the test cases of the following command:
- [ ] `odo preference`
- [ ] `odo registry`
- [ ] `odo init`
- [ ] `odo analyze`

## Links 
- Related Epic (mandatory): 

/kind user-story

**Comment by rm3l** [comment]
+1. Same thing for `odo init` tests, I think.
