### ISSUE TITLE
odo test statistics are broken

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5874]
/kind bug
/area testing
/priority high

Last update almost 5 months ago (2022-02-04)

https://gist.github.com/anandrkskd/102d08389c61e7f7293570bf38205d3b#file-test-stats-md

**Comment by anandrkskd** [comment]
We have moved to a new location for stats, i.e. [odo-tools/flake-stats.md](https://github.com/anandrkskd/odo-tools/blob/master/output/flake-stats.md)

**Comment by anandrkskd** [comment]
Test stats are broken again, https://github.com/redhat-developer/odo/pull/5809 broke the statistics.

**Comment by anandrkskd** [comment]
This is partially fixed, It will completely fix once a new version of ginkgo is released as mentioned [here](https://github.com/onsi/ginkgo/issues/973#issuecomment-1227705364).
