### ISSUE TITLE
failing periodic test

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5875]
All periodic tests are failing for more than a week :-/ 

- tests on 4.8 last success June 13th  
https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/job-history/gs/origin-ci-test/logs/periodic-ci-redhat-developer-odo-main-v4.8-integration-e2e-periodic
- tests on 4.9 last success June 14th
https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/job-history/gs/origin-ci-test/logs/periodic-ci-redhat-developer-odo-main-v4.9-integration-e2e-periodic
- tests on 4.10 last success June 15th
https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/job-history/gs/origin-ci-test/logs/periodic-ci-redhat-developer-odo-main-v4.10-integration-e2e-periodic
- tests on 4.11 last success June 14th
https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/job-history/gs/origin-ci-test/logs/periodic-ci-redhat-developer-odo-main-v4.11-integration-e2e-periodic
- tests on ??? last success June 15th
https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/job-history/gs/origin-ci-test/logs/periodic-ci-redhat-developer-odo-v2-integration-e2e-periodic

What is the last tests? The name is not saying much about what it is testing. 

**Why do we have periodic tests if no one is paying attention to them?**

**Comment by kadel** [comment]
> I've passed many time during this week checking the responsability of this issue for these failing tests:
> 
> [redhat-developer/service-binding-operator#1172](https://github.com/redhat-developer/service-binding-operator/issues/1172)
> 
> I'm waiting for the 1.1.1 release to validate there won't be more issue after the fix, but the tests ran locally are succesful with the fix.


Did you notice this problem thanks to the falling periodic tests? 

There is also another problem. The test that was supposed to start failing first and alert us about this problem is [periodic-ci-redhat-developer-odo-v2-operatorhub-integration-nightly](https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/job-history/gs/origin-ci-test/logs/periodic-ci-redhat-developer-odo-v2-operatorhub-integration-nightly?buildId=), but this is the only test that is not constantly failing :-(

**Comment by feloy** [comment]
> > I've passed many time during this week checking the responsability of this issue for these failing tests:
> > [redhat-developer/service-binding-operator#1172](https://github.com/redhat-developer/service-binding-operator/issues/1172)
> > I'm waiting for the 1.1.1 release to validate there won't be more issue after the fix, but the tests ran locally are succesful with the fix.
> 
> Did you notice this problem thanks to the falling periodic tests?
> 

The quantity of failing periodic tests alerted me, and I used the PR ones to try and catch the problem

**Comment by anandrkskd** [comment]
> There is also another problem. The test that was supposed to start failing first and alert us about this problem is [periodic-ci-redhat-developer-odo-v2-operatorhub-integration-nightly](https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/job-history/gs/origin-ci-test/logs/periodic-ci-redhat-developer-odo-v2-operatorhub-integration-nightly?buildId=), but this is the only test that is not constantly failing :-(

I think this should be fixed ASAP to avoid such issues. I have created an [issue](https://github.com/redhat-developer/odo/issues/5880) to track this.

**Comment by anandrkskd** [comment]
There are two major failures that we are still experiencing on periodic jobs, 
failure in test case `[It] should verify developer workflow from non-empty Directory` 
and openshift 4.11 periodic tests are also failing for binding commands.
