### ISSUE TITLE
Use secure communication channels when communicating with external services

### ISSUE THREAD

**Issue by rnapoles-rh** [redhat-developer/odo#5888]
/kind feature
## Which functionality do you think we should add?
Ensure we use secure communication channels / use of encryption when communicating with any external services:

- devfile registry
- kubernetes API servers
- starter projects
- any URL in the devfile

## Why is this needed?
Avoid possible man-in-the-middle tampering attacks. This was discussed during threat model review.
(Ensure we use the secure flag set to true. Overall, we should not make clients bypass security checks like server certificate validation)

**Comment by kadel** [comment]
> Ensure we use secure communication channels / use of encryption when communicating with any external services

Is this about using this inside our CI/CD infrastructure?
