### ISSUE TITLE
Integration tests - verify secrets are not written into log files

### ISSUE THREAD

**Issue by rnapoles-rh** [redhat-developer/odo#5889]
/kind feature
## Which functionality do you think we should add?
Write integration test to verify secrets are not written into the logs.

## Why is this needed?
Discussed during threat model review. Required to prevent generic information disclosure (API keys, secrets) threat

**Comment by kadel** [comment]
Not sure I understand how this should look like.
Odo would handle Secrets only if someone writes them in devfile. If someone does that, than it doesn't relly matter if odo shows in logs or not; the fact that the secret is exposed in Devfile is a much bigger problem.

There is a documentation issue that aims explaining this on devfile docs (https://github.com/devfile/api/issues/1033)

/close
