### ISSUE TITLE
Update documentation to urge the user to use binding as files insted of env variables

### ISSUE THREAD

**Issue by rnapoles-rh** [redhat-developer/odo#5890]
/kind documentation
## What mistake did you find / what is missing in the documentation?
To avoid generic information disclosure threat, we need to update documentation to urge the user to use binding as files instead of env variables

**Comment by feloy** [comment]
Arguments can be found in "Kubernetes Security" book from Liz Rice, Michael Hausenblas (page 61 of the book, page 71 of the PDF), "Passing Secrets as Environment Variables"

ebook downloadable from https://info.aquasec.com/kubernetes-security-sem
