### ISSUE TITLE
Integration tests should error out immediately if the operator is not installed

### ISSUE THREAD

**Issue by valaparthvi** [redhat-developer/odo#5926]
/kind user-story

## User Story
As an odo dev
I want, the integration tests related to binding error out immediately if the OLM is not installed on the cluster, or if there are situations we know for sure the operator does not exist on the cluster,
So that, tests can fail quickly. 

## Acceptance Criteria 
- [ ] It should error out immediately if OLM is not installed (perhaps by checking the `csv` resource)
- [ ] It should error out immediately if `subscriptions` resource returns nothing within a few seconds, because a `csv` might take some time, but `subscriptions` is quick to appear once the operator installation script is applied.

## Links 
- Related Epic (mandatory): 

/kind user-story

cc: @cdrage

**Comment by kadel** [comment]
If OLM or SBO is not present on the cluster, odo should still try to create binding using SBO integrated SBO library.

- #5938 




/close
