### ISSUE TITLE
`odo add binding` without SBO on the cluster

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5938]
/kind user-story

## User Story
As an odo user, I want to be able to create binding using odo without requiring SBO on my cluster So that I can use odo binding even on the clusters where I can't install operators.

## Acceptance Criteria 
- [ ] It should be possible to run `odo add binding` and see bindable services on clusters without SBO installed (ref #6125)
- [ ] update vendored SBO to the latest stable version
- [ ] It should be possible to create ServiceBinding using  `odo create binding` on a cluster without SBO installed
- [ ] `odo list binding` should list bindings created by odo on clusters without SBO
- [ ] `odo delete binding` should delete bindings created by odo on clusters without SBO
- [ ] `odo describe binding` should show information (including binding information) about binding on clusters without SBO

/kind user-story

**Comment by valaparthvi** [comment]
Is the information exposed by BindableKinds available if SBO is not installed? Can Service Binding Library do that?
/triage needs-information

**Comment by dharmit** [comment]
Are we sure about adding this feature for good? I'm asking because in v2 we added this feature, then in v3 we removed it initially, and now we are planning to add it again.

**Comment by kadel** [comment]
> Is the information exposed by BindableKinds available if SBO is not installed? Can Service Binding Library do that?

The Service Binding Library should be able to do that.



> Are we sure about adding this feature for good? I'm asking because in v2 we added this feature, then in v3 we removed it initially, and now we are planning to add it again.

Yes, we are. In v2 the problem was the implementation that was not stable because the library itself was not stable. We need to work with SBO team to come up with better and more stable approach.

**Comment by dharmit** [comment]
> We need to work with SBO team to come up with better and more stable approach.

Do you mean to do this after implementing this feature or before?

**Comment by valaparthvi** [comment]
@rm3l It's safe to close this issue, no? I assume binding is not a priority at the moment.

**Comment by rm3l** [comment]
> @rm3l It's safe to close this issue, no? I assume binding is not a priority at the moment.

I agree.
Reducing the priority to Low and closing it. Will reopen if needed.

/priority Low
/close not-planned
