### ISSUE TITLE
odo dev cannot delete from cluster servicebindings from group servicebinding.io

### ISSUE THREAD

**Issue by feloy** [redhat-developer/odo#5943]
/kind bug

 When a Devfile contains a Kubernetes resource declaring a servicebinding from group the servicebinding.io

and when removing the Kubernetes resource from the Devfile

`odo  dev` is unable to delete the servicebinding from the cluster, as it tries to remove a servicebinding from the group binding.operators.coreos.com and not servicebinding.io.

**Comment by rm3l** [comment]
Initial story point estimation: 1

**Comment by valaparthvi** [comment]
Running this without SBO is not a problem because when it is not installed, the ServiceBinding resource is not created, hence there is no need of deleting it.

**Comment by feloy** [comment]
But what about the secret created by odo using the SBO library, and the reference of this secret into the Deployment?

**Comment by valaparthvi** [comment]
You're right, the secret does not get deleted, at least not for binding.operators.coreos.com group. For servicebinding.io, the secrets are not created at all, which might be another bug.
