### ISSUE TITLE
odo create deletes pre-existing content in current directory

### ISSUE THREAD

**Issue by puravida-marco** [redhat-developer/odo#5948]
/kind bug

## What versions of software are you using?

**Operating System:** Fedora Linux 36.20220709.0 (Silverblue)

**Output of `odo version`:** odo v2.5.1 (ae0c55309)

## How did you run odo exactly?

Followed the starter doc: https://devfile.io/docs/devfile/2.1.0/user-guide/developing-with-devfiles/

Command run: `odo create nodejs my-first-odo-project --starter nodejs-starter` in my project folder assuming a new directory `my-first-odo-project` would be created

## Actual behavior

As part of the create command the current directory gets "cleaned" meaning everything gets deleted except .git folders.
This was unexpected and affected numerous files which were not meant to be deleted / are lost now. Nothing too crazy lost but still... could have been worse.

## Expected behavior

At very least a warning that the command is potentially destructive on command line and in the (starter) docs. 
Ideally already existing content gets retained or some confirmation needs to be given that its fine to delete.

## Any logs, error output, etc?

Procedure to reproduce
```
mkdir -p odo-reproduce-delete/valuable-directory
touch odo-reproduce-delete/valuable-directory/valuable-file.md
cd odo-reproduce-delete
odo create nodejs my-first-odo-project --starter nodejs-starter
ls valuable-directory
# output: "valuable-directory": No such file or directory (os error 2)
# sadness starts
```

**Comment by valaparthvi** [comment]
Hey @puravida-marco, while your issue is valid, can you try the latest odo v3, and see if that works for you?

```sh
mkdir -p odo-reproduce-delete/valuable-directory
touch odo-reproduce-delete/valuable-directory/valuable-file.md
cd odo-reproduce-delete
odo init --devfile nodejs --name my-first-odo-project --starter nodejs-starter
# output: `odo init` will now allow you to use --starter flag if the directory is not empty
ls valuable-directory
# output: "valuable-directory" still exists
# hopefully you're still happy
```

odo detects that the current directory is not empty, and will not allow you to download the starter project.

**Comment by puravida-marco** [comment]
Hey @valaparthvi,
Yes can confirm that v3 (beta) does refuse to use a starter if the directory is not empty - hence nothing gets deleted :+1: 
That works for me, will switch to the v3 beta for my tests and will be on the lookout for the GA release :eyes: 
Thanks!

**Comment by valaparthvi** [comment]
> Hey @valaparthvi, Yes can confirm that v3 (beta) does refuse to use a starter if the directory is not empty - hence nothing gets deleted +1 That works for me, will switch to the v3 beta for my tests and will be on the lookout for the GA release eyes Thanks!

That's great! :rocket:
