### ISSUE TITLE
Create service binding guide for main odo.dev site

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#5959]
/area documentation
/kind bug

## What mistake did you find / what is missing in the documentation?

We have the blog: https://odo.dev/blog/binding-external-service-with-odo-v3/

But there's no "full" example (shows all the devfile.yaml), 

We need to create some documentation that follows the similar format to the quickstart on https://odo.dev

**Comment by valaparthvi** [comment]
#6077 addresses this.
/close
