### ISSUE TITLE
Unhelpful error with odo add binding

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#5960]
/area documentation
/kind bug

## What mistake did you find / what is missing in the documentation?

With the error output:

```sh
k8s/devfiles/portforward  master ✗                                                                            139d2h ◒
▶ odo add binding
 ✗  No bindable service instances found
```

It's not telling me what I should do.

It should tell the user *how* to create a bindable service instance, or what steps to make it appear?

## What is the relevance of it?

Not a helpful error message / should explain how to create a service / fix.

**Comment by kadel** [comment]
What should be the more helpful message?

**Comment by rkratky** [comment]
@cdrage, why is this a docs bug? Do you mean there should be a docs section explaining error messages?

**Comment by valaparthvi** [comment]
@cdrage is this still relevant?

**Comment by cdrage** [comment]
> @cdrage is this still relevant?

Nope! I'll close this issue.
