### ISSUE TITLE
odo list output inconsistent

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/odo#5974]
/kind bug

## What versions of software are you using?

**Operating System:**
Win10Pro

**Output of `odo version`:**

```
odo v3.0.0-beta2 (c8e4458f4)

Server: https://api.sandbox-m2.ll9k.p1.openshiftapps.com:6443
Kubernetes: v1.23.5+9ce5071
```
## How did you run odo exactly?

- `odo init`
- `odo list` <- report a single component
- `odo dev`
- `odo list` <- report 2 components

## Actual behavior

Report 2 components

## Expected behavior

A single component should be reported

**Comment by valaparthvi** [comment]
I am unable to reproduce this issue. I still see a single component after `odo dev`. Unless you change the `.metadata.name` in devfile.yaml in the middle of `odo dev`, I think `odo list` works as expected.

**Comment by jeffmaury** [comment]
No I did not but I set my own component name and did not use the default while in `odo init`

**Comment by kadel** [comment]
@jeffmaury If you are still able to reproduce this can you please share the content of 
 `devfile.yaml` and `.odo/env/env.yaml`  ?

**Comment by jeffmaury** [comment]
Closing as I was running the second `odo list` command from a wrong folder
