### ISSUE TITLE
Indicate OLM / operators / SBO is resource hungry / may not run on small clusters

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#5982]
/area documentation
/kind bug

## What mistake did you find / what is missing in the documentation?

TLDR; Operators have issues running on clusters with low resources / running on HDD architecture / 1 or 2 node clusters.

We need to indicate in documentation that the user may have issues / link to how to troubleshoot a CrashLoopBackoff image via operators.

This is due to timing out issues with leader election loss: https://github.com/operator-framework/operator-sdk/issues/1813

TODO: ADD MORE INFO.

**Comment by kadel** [comment]
Isn't this more of a problem on an operator's side than on odo's?

**Comment by valaparthvi** [comment]
no longer relevant since we do not mention cluster setup in the docs.
