### ISSUE TITLE
odo delete incomplete

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/odo#5983]
/kind bug

## What versions of software are you using?

**Operating System:**
Win10Pro

**Output of `odo version`:**
```
odo v3.0.0-beta2 (c8e4458f4)

Server: https://api.sandbox-m2.ll9k.p1.openshiftapps.com:6443
Kubernetes: v1.23.5+9ce5071

```
## How did you run odo exactly?

- `odo init`
- `odo delete component -f`

## Actual behavior

`devfile.yaml` is still there and `.odo` has files

## Expected behavior

Cleanup should be done

**Comment by kadel** [comment]
The `-f` (`--force`) is not intented to delete `devfile.yaml` or `.odo`.
There currently is no option to delete local files using odo cli.

This is not a bug but an intended feature.
/close 

I've opened this as a new feature request https://github.com/redhat-developer/odo/issues/5997
Please note that there is no way for odo to know if, `devfile.yaml` was generated by another tool or was downloaded by the user manually. The new proposed command will simply delete all odo-related files and directories even if they were not created by odo. This needs to be used with care.
