### ISSUE TITLE
Strange message when deleting a non existent component

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/odo#5987]
/kind bug

## What versions of software are you using?

**Operating System:**
Win10Pro

**Output of `odo version`:**

```
odo v3.0.0-beta2 (c8e4458f4)

Server: https://api.sandbox-m2.ll9k.p1.openshiftapps.com:6443
Kubernetes: v1.23.5+9ce5071
```

## How did you run odo exactly?

`odo delete component -f `

in a folder with no `.odo` and no `devfile.yaml`

## Actual behavior

```
C:\work\src\tmp\quarkus\maven\rest>odo delete component -f
 X  The current directory does not represent an odo component.
To start editing your component, use "odo dev" and open this folder in your favorite IDE. Changes will be directly reflected on the cluster.
To deploy your component to a cluster use "odo deploy".
Or switch to directory with a component.
```

## Expected behavior

We should have the error message that there is no component in this folder and maybe some info how to create it

**Comment by valaparthvi** [comment]
I think the message is good enough. It tells you why the command failed, "The current directory does not represent an odo component.", and it tells you how to proceed further, by running `odo dev`, or `odo deploy`, or move to a directory that has a component.

**Comment by jeffmaury** [comment]
No reference ever to `odo init`, `odo dev` or `odo deploy` have absolutely no sense here.

**Comment by valaparthvi** [comment]
> No reference ever to `odo init`, `odo dev` or `odo deploy` have absolutely no sense here.

You don't always need `odo init` as an entrypoint to odo. You can run `odo dev`, or `odo deploy`, which will guide you to download a devfile by analyzing your directory.
But I think it prints the same message if the directory is empty, in which case, you're right, it should talk about `odo init`.

**Comment by jeffmaury** [comment]
No you're right I did not know you can start with `odo dev` or `odo deploy`

**Comment by valaparthvi** [comment]
Oh no, but what you say makes sense for an empty directory. I am going to keep this open.
