### ISSUE TITLE
YAML syntax highlighting in dark mode is partially broken

### ISSUE THREAD

**Issue by dogsbay** [redhat-developer/odo#6002]
/area documentation
/kind bug

## What mistake did you find / what is missing in the documentation?

YAML syntax highlighting in dark mode is partially broken, due to a problem with the specific prism renderer.

https://odo.dev/docs/user-guides/advanced/pushing-specific-files

We could fix this by using a different dark theme, for example, 

```
  darkTheme: require('prism-react-renderer/themes/oceanicNext')
```

Or by adding a temporary CSS fix in src/css/custom.css:

```
.token.atrule {
	color: #c792ea;
}
```

## What is the relevance of it?

Dark mode is probably the preferred reading mode, and better syntax highlighting would improve the user experience

**Comment by valaparthvi** [comment]
Thanks for opening this issue up @dogsbay.
@cdrage What do you think?

**Comment by valaparthvi** [comment]
I've gone ahead and created a PR, I see no harm in changing the theme. Oh, and @dogsbay is really Gabriel McGoldrick :smile:

**Comment by gabriel-rh** [comment]
https://deploy-preview-6005--odo-docusaurus-preview.netlify.app/docs/user-guides/advanced/pushing-specific-files

Highlighting now works for atrule tokens
