### ISSUE TITLE
odo describe component should show information about available debug ports

### ISSUE THREAD

**Issue by valaparthvi** [redhat-developer/odo#6036]
`odo describe component` will have a separate section(human readable, and JSON) for debug ports.

Debug endpoints can be identified with the [following naming convention](https://github.com/redhat-developer/odo/issues/5988#issuecomment-1239497488):
- either a single endpoint named `debug`
- or any endpoint with a name starting with `debug-`

Also, make sure to make `odo describe component` display endpoint exposure.

_Originally posted by @valaparthvi in https://github.com/redhat-developer/odo/issues/5988#issuecomment-1219452690_

/status blocked
Until #5988 is merged.

/kind feature

**Comment by rm3l** [comment]
Unblocking this as https://github.com/redhat-developer/odo/issues/5988 is done (see https://github.com/redhat-developer/odo/issues/5988#issuecomment-1307478264)

**Comment by valaparthvi** [comment]
Add a new `PortName` field to `api.component.go:ForwardedPort`.
