### ISSUE TITLE
odo init: download project before asking for name

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#6039]
/kind feature

## Which functionality do you think we should add?

As per @valaparthvi 's comment in https://github.com/redhat-developer/odo/pull/5989

When we use `odo init` on an empty project:

We should ask the name of the project *AFTER* a project has has been downloaded, so analyzer may detect the correct project name.

## Why is this needed?

Better intuitive decision making for `odo init`

**Comment by kadel** [comment]
this has been already implemented
/close
