### ISSUE TITLE
Support `--no-cleanup` for `odo dev`

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/odo#6042]
/kind user-story

## User Story
As a user, I want `odo dev` to not perform cleanup each time `Ctrl+C` is hit, so that:
* I can use the same terminal session to start a microservice application with multiple odo components.
* Each execution of `odo dev` doesn't have to wait to download updates required to start the application

## Acceptance Criteria 
- [ ] `odo dev --no-cleanup` should disable deletion of resources created by `odo dev`. Such resources should be deleted when `odo delete component`/`odo delete namespace` is executed (same as current beahviour)
- [ ] Hitting `Ctrl+C` when `--no-cleanup` flag is provided should only stop `odo dev` process. It should keep the Kubernetes resources like Deployment, Pod, Service Bindings intact.
- [ ] After making any changes to source files in the component directory, when `odo dev` is executed again (with or without `--no-cleanup` flag), odo should synchronize the code and files with the previously started `odo dev --no-cleanup` process.

## Links 
- Related Epic (mandatory): N/A

/kind user-story
/area dev

**Comment by kadel** [comment]
So far, there was no interest in this feature from users.

We can reconsider this once we have a real use-case for it. 

/close
