### ISSUE TITLE
add `app.openshift.io/runtime` label to resources created by odo

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#6044]
/kind user-story

## User Story
As an odo and ODC user, I want to see language/framework icons in ODC topology view So that I can quickly recognize what is running and so that I have a consistent view with components created by ODC.

<img width="573" alt="Screenshot 2022-08-22 at 17 12 39" src="https://user-images.githubusercontent.com/57206/185956224-eeba324e-6057-422a-9675-9c1de05738ef.png">

The left is the component with the correct labels deployed with ODC, the right is nodejs component deployed using `odo dev`

## Acceptance Criteria 
- [ ] `odo dev` should add `app.openshift.io/runtime` label  to all resources created with value of `metadata.language` field in devfile.yaml
- [ ] `odo deploy` should add `app.openshift.io/runtime` label  to all resources created with value of `metadata.language` field in devfile.yaml

/kind user-story
/priority medium

**Comment by valaparthvi** [comment]
What value should be assigned to the label? Language? Project Type? Some devfiles have icon matching language, some with project type.
