### ISSUE TITLE
Reorganize the quickstart guide / separate into dev and deploy guides

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#6051]
- make less confusing / less options for user

**Comment by valaparthvi** [comment]
- [ ] Split the quickstart into multiple parts with the main one being about `odo dev`.
    - [ ] `odo init` and `odo dev`
    - [ ] Advanced usage: `odo deploy`
    - [ ] Advanced usage: connecting to a service
- [ ] Decrease the confusion between OC and K8s.
- [ ] Different quickstart guide for different languages.
- [ ] Define configurator before the quickstart guide begins in the main guide(?).

**Comment by kadel** [comment]
cleanup:
 -  remove "Cluster Setup" section. It is not necessary odo should work out-of-the-box in most of the cluster setups. And most of the developers won't be dealing with the cluster setup. I don't expect that someone would be setting up minikube or oc just to use odo.  Alternatively, we could move it into some advanced section.
 - The install section for MacOS has weird tabs. Intel/AppleSilicon/Homebrew Homebrew shouldn't be on the same level as Intel/AppleSilicon. The recommended/default installation method should be homebrew
 - group "installing from source", "using Maven" under umbrella section "Alternative installation methods"
