### ISSUE TITLE
odo preference remove registry change the shell color after execution

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/odo#6052]
/kind bug

## What versions of software are you using?

**Operating System:**

Win10Pro

**Output of `odo version`:**

```
odo v3.0.0-beta3 (f4e96a4e3)             
                                         
Server: https://api.crc.testing:6443     
Kubernetes: v1.24.0+9546431              
```

## How did you run odo exactly?

`odo preference remove registry my`

## Actual behavior

![image](https://user-images.githubusercontent.com/695993/186424915-782ce9aa-9f40-40ea-a7ba-303909b261f3.png)

## Expected behavior

Shell should not have color modified

**Comment by cdrage** [comment]
@jeffmaury What terminal and theme are you using? I'm trying to reproduce this in powershell and cmd and I'm unable.

**Comment by jeffmaury** [comment]
> @jeffmaury What terminal and theme are you using? I'm trying to reproduce this in powershell and cmd and I'm unable.

I'm using cmd.exe embedded into ConEmu https://conemu.github.io

If using cmd.exe then I don't have the issue

**Comment by cdrage** [comment]
No matter what I do I'm still unable to reproduce this.

We could always detect if an environment variable is being used by ConEmu: https://conemu.github.io/en/ConEmuEnvironment.html and then disable colouring manually.

I believe that may be the only option @jeffmaury

**Comment by kadel** [comment]
It looks like this has been fixed. I was not able to reproduce this.

<img width="535" alt="Screenshot 2023-02-23 at 11 34 29" src="https://user-images.githubusercontent.com/57206/220882877-04150834-1040-480f-80d5-6475c4149932.png">


/close
