### ISSUE TITLE
odo delete project checks if project exists after asking the confirmation question

### ISSUE THREAD

**Issue by valaparthvi** [redhat-developer/odo#6053]
/kind bug

## What versions of software are you using?

**Operating System:** Fedora 31

**Output of `odo version`:** odo v3.0.0-beta3 (61e81ffef)

## How did you run odo exactly?
1. odo delete namespace non-existent-ns

## Actual behavior
```sh
$ odo delete namespace cmd-delete-test174rx 
? Are you sure you want to delete namespace "cmd-delete-test174rx"? Yes
 ✗  unable to delete project "cmd-delete-test174rx": unable to delete Namespace cmd-delete-test174rx: namespaces "cmd-delete-test174rx" not found
``` 

## Expected behavior
```sh
odo delete namespace cmd-delete-test174rx 
 ✗  namespaces "cmd-delete-test174rx" not found
```

**Comment by MahendraBishnoi29** [comment]
hello again 😃@valaparthvi can I take this issue, if yes then where to make your suggested changes?

**Comment by valaparthvi** [comment]
> hello again smiley@valaparthvi can I take this issue, if yes then where to make your suggested changes?

I'm glad you're coming back! https://github.com/redhat-developer/odo/blob/main/pkg/odo/cli/delete/namespace/namespace.go#L85 is where you need to check if the project exists, before asking the question.

**Comment by kevydotvinu** [comment]
Hello @valaparthvi, are we participating in Hacktoberfest 2022?

**Comment by valaparthvi** [comment]
@kevydotvinu odo is not participating in Hacktoberfest this year, but feel free to work on this if you want to, we'll be more than happy to review it.

**Comment by kevydotvinu** [comment]
Thank you for your update, @valaparthvi. Please review [this](https://github.com/redhat-developer/odo/pull/6233) and let me know if any change is required.

**Comment by SD-13** [comment]
Hey @kevydotvinu, are you still working on this issue?

**Comment by kevydotvinu** [comment]
> Hey @kevydotvinu, are you still working on this issue?

I am on it, @SD-13.
