### ISSUE TITLE
`odo list`: Empty parentheses for odo version if component is not running yet in the cluster

### ISSUE THREAD

**Issue by rm3l** [redhat-developer/odo#6061]
/kind bug

## What versions of software are you using?

**Operating System:**
Fedora 36

**Output of `odo version`:**
odo v3.0.0-beta3 (644d94cde)

## How did you run odo exactly?
```shell
❯ # From a new empty directory, but you can skip the "odo init" step if you already have a component.
❯ # The important point is that the component must not be running yet in the cluster.
❯ odo init --name my-sample-go --devfile go --starter go-starter
❯ odo list
```

## Actual behavior

```
❯ odo list
 ✓  Listing components from namespace 'default' [175ms]
 NAME                              PROJECT TYPE  RUNNING IN  MANAGED            
 * my-sample-go                    go            None        odo ()             
 my-nodesjs-with-k8s-uri-with-var  nodejs        Deploy      odo (v3.0.0-beta3) 
```

## Expected behavior
The `odo ()` cell seems odd to me, at first sight. We could either report the current version of `odo`, or just "odo" if we are unable to determine the version?

## Any logs, error output, etc?

_Originally posted by @rm3l in https://github.com/redhat-developer/odo/pull/6028#discussion_r955968706_

**Comment by valaparthvi** [comment]
> just "odo" if we are unable to determine the version?

I think this makes more sense considering it is not yet running on the cluster and we do not know who it'll be managed by.
