### ISSUE TITLE
odo dev consumes a lot of cpu if cluster is stopped

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/odo#6062]
/kind bug

## What versions of software are you using?

**Operating System:**
Win10Pro

**Output of `odo version`:**

`odo v3.0.0-beta3 (f4e96a4e3)`

## How did you run odo exactly?

- `odo dev`
- `stop cluster (crc stop)`

Saw the odo process consuming about 10% of CPU on my 8 pro system

**Comment by valaparthvi** [comment]
/triage needs-information
We need to replicate this from our end.

**Comment by kadel** [comment]
I've tried to reproduce this but no luck.
If this is still an issue feel free to reopen this.

/close
