### ISSUE TITLE
Clean up documentation before GA

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#6068]
Clean up documentation before GA.

- [x] #6076
- [x] #6077
- [x] #6080
- [x] #6082
- [x] #6083
- [x] #6084
- [x] #6085
- [x] #6152

**Comment by valaparthvi** [comment]
I'm going to unassign myself from this issue since Charlie has already done most of the work on this.

/unassign valaparthvi

**Comment by rm3l** [comment]
Closing this issue as all tasks listed have been done.

/close
