### ISSUE TITLE
Decrease usage of OC and K8s in advanced guide

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#6084]
Decrease the confusion between OC and K8s in advance usage guide (odo deploy and connecting to services) the cluster type switcher should be on top of the page

**Comment by cdrage** [comment]
I feel like we've cleaned this up via: https://github.com/redhat-developer/odo/pull/6071/files#diff-7ff4b0af2abcdaed633145873082748dd56b844ed91f7b760acb1a18b260571a by making sure that all instances of Openshift vs Kubernetes cluster setup is done via tabs / type switcher

**Comment by valaparthvi** [comment]
/close
With #6071 in, I guess this issue can be closed. Feel free to reopen if the need be.
