### ISSUE TITLE
v3.0.0 Release preparation: Create release readiness doc

### ISSUE THREAD

**Issue by rm3l** [redhat-developer/odo#6139]
Example of doc for v2: https://docs.google.com/document/d/1Do-mwKMq9wLQb1oxh5KvwLqEli4PtXKO8Z4irwdffPU/edit

**Comment by anandrkskd** [comment]
Creation of [Release Readiness Doc](https://docs.google.com/document/d/1ZIbZ4d7HxyrLYi47_5r4mdLdEyGu-DG8A1xtjB698bs/edit#heading=h.bnmzu07kyat5) is now completed. Closing this issue.
/close
