### ISSUE TITLE
Create dropdown menus for examples for user guides / other documentation.

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#6143]
/area documentation
/kind bug

## What mistake did you find / what is missing in the documentation?

See: https://github.com/redhat-developer/odo/pull/6126

We should make the example output as dropdown menus as well on all the tutorial guides / etc.

## What is the relevance of it?

Cleaner and looks better! :)

**Comment by SD-13** [comment]
Hi @cdrage, Can I take this one?

**Comment by cdrage** [comment]
Go ahead, but just check with @valaparthvi as she may have updated the site already with this :)

**Comment by valaparthvi** [comment]
Hi @SD-13, you can start by working on the [Quickstart guides](https://odo.dev/docs/user-guides/quickstart/).
For reference, you can take a look at https://odo.dev/docs/overview/configure.

**Comment by SD-13** [comment]
> Hi @SD-13, you can start by working on the [Quickstart guides](https://odo.dev/docs/user-guides/quickstart/).
> For reference, you can take a look at https://odo.dev/docs/overview/configure.
> 

Sure, I will look into it and will reach out to you if I have any query. Thanks,

**Comment by SD-13** [comment]
Hi @valaparthvi, I have added `examples` in the Quickstart docs. Please have a look and let me know if I missed anything. Also, please help me to find the other docs that need to be updated in this issue. Thanks,

**Comment by valaparthvi** [comment]
Add a sample output for the following pages:
1. https://odo.dev/docs/user-guides/advanced/connecting-a-service#step-5-exit-and-cleanup: `odo remove binding --name my-go-app-mongodb-instance`
2. https://odo.dev/docs/user-guides/advanced/experimental-mode#enabling-the-experimental-mode
3. https://odo.dev/docs/command-reference/list-services
4. https://odo.dev/docs/command-reference/set-namespace: Replace `odo set namespace mynamespace` with `odo set namespace <namespace>` and same for the project command.

@SD-13 These are the remaining pages that needs an update. You can assign the issue to yourself if you would like to fix them.
