### ISSUE TITLE
odo dev with podman pod (create pod and sync files)

### ISSUE THREAD

**Issue by feloy** [redhat-developer/odo#6151]
/kind user-story

## User Story
As a user I want to run odo dev with --run-on=podman/cluster flag So that I can choose to execute the component pod on Podman or on Kubernetes

## Acceptance Criteria 
- [x] `odo dev` should accept a `--run-on` flag, with accepted values cluster (default) and podman
- [x] `--run-on` flag should be experimental (see #6150)
- [x] `odo dev` in cluster mode should behave as `odo dev`

`odo dev --run-on=podman`
- [x] should work without any Kubernetes config
- [ ] should support devfiles from Registry (https://github.com/redhat-developer/odo/issues/6330)
- [x] should deploy a Pod using podman CLI
- [ ] #6333
- [x] should sync the local files to the Pod
- [x] should execute the build then run commands
- [x] should cleanup resources then exit when Ctrl-C is pressed
- [x] should *not* watch for files changes nor devfile changes

## Links 
- Related Epic (mandatory): #5865 

/kind user-story

**Comment by elsony** [comment]
Exposing as part of the --run-on flag is useful if someone wants to switch between the two modes. Have we considered also putting it as part of the preference so that the user doesn't have to specify that on every odo dev or odo deploy command?

**Comment by kadel** [comment]
> Exposing as part of the --run-on flag is useful if someone wants to switch between the two modes. Have we considered also putting it as part of the preference so that the user doesn't have to specify that on every odo dev or odo deploy command?

That makes sense. We can add this. But it is something that we should consider only after we have a more solid implementation and it is ready to be moved out of experimental mode.

**Comment by feloy** [comment]
Reopening as some Devfiles (the ones declaring volumes) are not supported

Also, ports should be tested before to be used, to be able to deploy several components at the same time

**Comment by rm3l** [comment]
As discussed during standup, I'm closing this issue as complete (so it can be visible as such in the [v3.3.0 milestone](https://github.com/redhat-developer/odo/milestone/25)).
Newly added items will be tracked as separate issues:
- https://github.com/redhat-developer/odo/issues/6330 (so as to support Devfiles from default registry)
- https://github.com/redhat-developer/odo/issues/6333

/close
