### ISSUE TITLE
Adjust sidebars on odo.dev by making some sections expanded by default and others collapsed

### ISSUE THREAD

**Issue by rm3l** [redhat-developer/odo#6152]
/area documentation
/kind documentation

## What mistake did you find / what is missing in the documentation?
`Command Reference` should be the last section in the left sidebar.

## What is the relevance of it?
As the largest section, it hides other sections below it, like "Developer Reference".

**Comment by valaparthvi** [comment]
Do you think now would be a good time to switch back to collapsible sidebar?

**Comment by rm3l** [comment]
> Do you think now would be a good time to switch back to collapsible sidebar?

It could be a solution too.

TBH, I like the sidebar on the [Docusaurus website](https://docusaurus.io/docs/next), where not all sections are collapsed. The "Getting Started" section is expanded by default, and the other sections are collapsed.

I am not sure how complex it is, but I was wondering if we couldn't have something similar (some sections expanded by default, while others like Command Reference are collapsed).

@cdrage What do you think?

**Comment by valaparthvi** [comment]
> TBH, I like the sidebar on the [Docusaurus website](https://docusaurus.io/docs/next), where not all sections are collapsed. The "Getting Started" section is expanded by default, and the other sections are collapsed.

I agree. Having that would be nice.

**Comment by rm3l** [comment]
Changing the issue title to better reflect what has been done in the #6156 

/retitle Adjust sidebars on odo.dev by making some sections expanded by default and others collapsed
