### ISSUE TITLE
make timeout time configurable

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#617]
When running odo, if the connection to the cluster is slow, it will fail with an `are you authenticated error?`

Timeout time needs to be configurable on:
- global odo config file. @kadel Is this global odo config file something we should consider?
- per command flag, as global configuration and not command specific flag

We should also revisit which commands need to check that you're connected to the cluster, as a `odo app create xxx` command failed on me and it shouldn't really check it.

**Comment by syamgk** [comment]
we are implementing `odo config` command as per issue https://github.com/redhat-developer/odo/issues/122 so after PR https://github.com/redhat-developer/odo/pull/589 gets merged we can extend odo config for specifying the time-out

this is how we are implementing it now
```
odo config --help
Modifies Odo specific configuration settings within the config file.

Usage:
  odo config [flags]
  odo config [command]

Aliases:
  config, configuration


Examples:
  # Get the current configuration
   odo config get
 
  # Set a configuration value
   odo config set UpdateNotification false
```

**Comment by syamgk** [comment]
I've sent a PR https://github.com/redhat-developer/odo/pull/757 for this, which will allow the user to modify the default timeout value by explicitly configuring it on `~/.kube/odo` file using `odo utils config` command
```sh
./odo utils config 
Modifies Odo specific configuration settings within the config file.

Available Parameters:
UpdateNotification - Controls if an update notification is shown or not (true or false),
Timeout            - timeout(in seconds) for openshift server connection check(1 to 99)

```
so, for example, the user can modify the timeout by 
```sh
$ odo utils config set timeout 5
```

**Comment by jorgemoralespou** [comment]
@kadel We need to look into the format of this file the sooner the better
