### ISSUE TITLE
If build fails, seems retrying indefinitively and hard to stop

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/odo#6173]
/kind bug

## What versions of software are you using?

**Operating System:**
Win10Pro

**Output of `odo version`:**

```
odo v3.0.0-rc2 (39a9a2874)

Server: https://api.sandbox-m2.ll9k.p1.openshiftapps.com:6443
Kubernetes: v1.23.5+012e945
```

## How did you run odo exactly?

`odo dev`

## Actual behavior

Tried to do odo dev on several components on Red Hat Developer Sandbox and the Maven build fails because of OutOfMemory errror but then seems Maven build is retried and it's very hard to stop the loop

## Expected behavior

Loop should be limited at least (3 to 5 retries by default ?)

**Comment by kadel** [comment]
Agreed, odo should have a limit on retries. It should try 3 times and then stop trying until it detects some changes.
