### ISSUE TITLE
🎉 Release v3.1.0 🎉 

### ISSUE THREAD

**Issue by rm3l** [redhat-developer/odo#6179]
Issue to track work for publishing a new release of `odo` at the end of the Sprint.

- Target release process start date: **Oct 18, 2022**
- Errata date (when we expect the binaries to be published): **Nov 20, 2022**
- Version: **v3.1.0**.
  - Since this is not a pre-release, make sure to update the [`build/VERSION`](https://github.com/redhat-developer/odo/blob/main/build/VERSION) file
- Once release is done, make sure link to download `latest` points to v3.1.0: https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/odo/latest/

Note: Write an announcement blog post once the release is done.

/kind task
/area release-eng

**Comment by valaparthvi** [comment]
/close
No need to write blog post.
