### ISSUE TITLE
`odo dev` does not recreate K8s resources created by apply commands in case they're deleted

### ISSUE THREAD

**Issue by valaparthvi** [redhat-developer/odo#6193]
/kind bug

## What versions of software are you using?

**Operating System:**
Fedora 35
**Output of `odo version`:**
odo v3.0.0-rc2 (3d2bf3470)

## How did you run odo exactly?
1. Use devfile-composite-apply-commands.yaml to create a component.
2. Run `odo dev`.
3. Delete the K8s resource created by the apply command
```sh
kubectl delete deploy my-component
```
4. Wait for `odo dev`
## Actual behavior
`odo dev` does not recreate the deployment resource.

## Expected behavior
`odo dev` should recreate the deployment resource and ensure that the Devfile state is always maintained.

**Comment by rm3l** [comment]
/remove-lifecycle rotten
/remove-lifecycle stale
/reopen

Still relevant.
