### ISSUE TITLE
Tests with Podman platform

### ISSUE THREAD

**Issue by feloy** [redhat-developer/odo#6236]
/kind user-story

## User Story
As a developer I want the test platform to support podman tests So that I can test podman deployment

## Sub-Stories
- [x] Running Podman tests manually: https://github.com/redhat-developer/odo/pull/6332
- [x] Setup CI infra for testing odo on Podman: https://github.com/redhat-developer/odo/issues/6340

## Links 
- Related Epic (mandatory): https://github.com/redhat-developer/odo/issues/5871

/kind user-story

**Comment by rm3l** [comment]
Closing this issue as complete as the 2 sub-stories it contains have been completed.

/close
