### ISSUE TITLE
Update Homebrew main formula to install v3

### ISSUE THREAD

**Issue by rm3l** [redhat-developer/odo#6239]
Per the discussion in https://kubernetes.slack.com/archives/C01D6L2NUAG/p1662055367333189, we need to update the main formulae to install v3, now that v3 is available.
We also need to create separate formulae in case someone still wants to install v2.

**EDIT**: As mentioned below, we need to update [this formula in homebrew-core repo](https://github.com/Homebrew/homebrew-core/blob/master/Formula/odo-dev.rb?rgh-link-date=2022-10-21T06%3A58%3A02Z).

**Comment by kadel** [comment]
the odo homberew tab from https://github.com/kadel/homebrew-odo/ is deprecated (I forgot to mention it in repo) and our official documentation no longer refers to it.


There is odo-dev formulae in official homebrew-core   https://github.com/Homebrew/homebrew-core/blob/master/Formula/odo-dev.rb This is the one that should be updated

**Comment by rm3l** [comment]
Ok, thanks for the information.
I saw the deprecated repo mentioned in our wiki page for releasing a new version: https://github.com/redhat-developer/odo/wiki/Release:-New-version-of-odo
I'll update this page.

And yes, that would be great if you could mention it in repo (and maybe archive it if no longer relevant, so we are not tempted to create issues or PRs there).

**Comment by kadel** [comment]
- ⏳ opened PR to update odo-dev formluae https://github.com/Homebrew/homebrew-core/pull/113682
- ✅  https://github.com/kadel/homebrew-odo/ archived

**Comment by rm3l** [comment]
Awesome - thanks @kadel!
