### ISSUE TITLE
'-o json' support for 'odo list namespace'

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/odo#6257]
/kind feature

## Which functionality do you think we should add?

$subj

## Why is this needed?

For IDEs integration.

**Comment by valaparthvi** [comment]
`odo project list` in v2 had JSON output, that can be used for this command as well.

**Comment by kadel** [comment]
```json
[
 { name: "project1",
   active: false
 },
 { name: "project2",
   active: true
 }
]
```
