### ISSUE TITLE
Add "-w" flag to create component action

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#628]
This -w flag (watch/wait) would block the shell until the component is ready to use, so it'll monitor that the component deployment is active and prevent the user to take any action before. If the flag is not specified, the command should exit as soon as possible, and potentially we can add a status action to tell us if the component is ready to push.

**Comment by kadel** [comment]
prerequisite: #556

**Comment by cdrage** [comment]
Blocked on #556

**Comment by syamgk** [comment]
Unblocked after merging #622

**Comment by kadel** [comment]
This should be implemented  similarly to https://github.com/redhat-developer/odo/issues/846

**Comment by syamgk** [comment]
so this means If `-w` flag is present then show the logs and block the shell. on 
`odo create python --git https://github.com/openshift/django-ex.git`
other wise exit the command without showing the msg `Component 'xxxxxx' was created and port xxxx/TCP was opened` ?
@kadel @jorgemoralespou

**Comment by kadel** [comment]
> so this means If `-w` flag is present then show the build logs and block the shell. on
> `odo create python --git https://github.com/openshift/django-ex.git`
> other wise exit the command without showing build logs and the msg `Component 'xxxxxx' was created and port xxxx/TCP was opened` ?

yes




> also what does it mean by ` status action to tell us if the component is ready to push.`?

I think that this is realted to #830.  That is something that we will add later.
