### ISSUE TITLE
`odo describe component` should show information about components running on podman

### ISSUE THREAD

**Issue by rm3l** [redhat-developer/odo#6298]
Acceptance Criteria:
- [ ] Default behavior: describe component if running from all accessible platforms
- [ ] If `platform` is specified, limit listing to that platform
- [ ] Do not fail if K8s cluster or podman are not available

NOTES:
- Depends on https://github.com/redhat-developer/odo/issues/6317
- Implications on the output (human-readable or JSON) when listing from all accessible platforms
  - Need a column (or field in JSON) indicating the platform
  - Occurrences to namespace in output and CLI flag
- Should support both cases: running with and without a Devfile

**Comment by feloy** [comment]
Research:
Test when podman is not running any instance.
`podman system connection list`

**Comment by feloy** [comment]
```
"devForwardedPorts": [
        {
            "platform": "podman",  <-- added
            "containerName": "runtime",
            "localAddress": "127.0.0.1",
            "localPort": 40001,
            "containerPort": 3000
        {
            "platform": "cluster",  <-- added
            "containerName": "runtime",
            "localAddress": "127.0.0.1",
            "localPort": 40002,
            "containerPort": 3000
        },
        },
    ],
```
