### ISSUE TITLE
[odo on Podman] Ignore and show warning when handling Kubernetes components

### ISSUE THREAD

**Issue by rm3l** [redhat-developer/odo#6299]
See https://github.com/redhat-developer/odo/issues/6299#issuecomment-1317187243

**Comment by kadel** [comment]
For now, let's just ignore them and show a warning to the user.

```
▶ odo dev --run-on podman
  __
 /  \__     Developing using the "nodejs-starter" Devfile
 \__/  \    Platform: podman
 /  \__/    odo version: v3.2.0
 \__/

↪ Deploying to podman in developer mode
WARNING!!: skipping kubernetes component "component-name". Kubernetes components are not supported on Podman.
 ✓  Deploying pod [3s]
 ✓  Building your application in container (command: install) [3s]
 •  Executing the application (command: run)  ...
...
...
...

``

**Comment by rm3l** [comment]
Makes sense for now - thanks.

Not sure if it is worth a separate issue then :)
Anyways, I'll retitle it.

/retitle [odo on Podman] Show warning when handling Kubernetes components

**Comment by valaparthvi** [comment]
The current behavior as I see it is complete ignorance for the k8s component when `odo dev` is run on podman. Can someone confirm it?

**Comment by rm3l** [comment]
> The current behavior as I see it is complete ignorance for the k8s component when `odo dev` is run on podman. Can someone confirm it?

Yes, that's the point.
