### ISSUE TITLE
`odo project list` failing on travis

### ISSUE THREAD

**Issue by ashetty1** [redhat-developer/odo#630]
The command `odo project list` seems to be consistently failing on travis. Works perfectly fine locally.

https://travis-ci.org/redhat-developer/odo/jobs/415951402#L658
```
odoe2e odo project 
  should create a new project
  /home/travis/gopath/src/github.com/redhat-developer/odo/tests/e2e/e2e_test.go:48
Running command: odo project create odo-1534258217
New project created and now using project : odo-1534258217
•
------------------------------
odoe2e odo project 
  should get the project
  /home/travis/gopath/src/github.com/redhat-developer/odo/tests/e2e/e2e_test.go:53
Running command: odo project get --short
odo-1534258217
•
------------------------------
odoe2e odo project 
  should list the project
  /home/travis/gopath/src/github.com/redhat-developer/odo/tests/e2e/e2e_test.go:58
Running command: odo project list
ACTIVE   NAME
         myproject
• Failure [0.126 seconds]
/home/travis/gopath/src/github.com/redhat-developer/odo/tests/e2e/e2e_test.go:36
  odo project
  /home/travis/gopath/src/github.com/redhat-developer/odo/tests/e2e/e2e_test.go:47
    should list the project [It]
    /home/travis/gopath/src/github.com/redhat-developer/odo/tests/e2e/e2e_test.go:58
    Expected
        <string>: ACTIVE   NAME
                 myproject
        
    to contain substring
        <string>: odo-1534258217
```

This is related to PR #625. Commenting out the test relating to `odo project list` in the PR and adding a reference to this issue there.

**Comment by kadel** [comment]
Shouldn't we fix it rather than commenting out the test?

**Comment by ashetty1** [comment]
@kadel looks like a problem in the API itself: https://github.com/redhat-developer/odo/blob/master/pkg/occlient/occlient.go#L260 isn't returning the active project

**Comment by syamgk** [comment]
I've build the master branch and ran `make test-e2e` on my local machine and it was passing. 
used Minishift for bringing up the cluster

**Comment by syamgk** [comment]
@ashetty1 I noticed it take a few seconds for the project to be created. so if we add a sleep of 2 seconds before running `odo project list` then everything works as expected. 
same with `oc create project` and `oc delete project` as well. It takes few seconds to completly create, delete the project.

**Comment by ashetty1** [comment]
@syamgk do you know why `odo project get` works but not `odo project list` then?

**Comment by syamgk** [comment]
when doing `odo project get`it's coming from the config file whereas while doing `odo project list` its making an API call to the openshift cluster

**Comment by ashetty1** [comment]
The `sleep` workaround seems to be working for now.

**Comment by syamgk** [comment]
@ashetty1  let's close this since we got #625 merged and have the test on master https://github.com/redhat-developer/odo/blob/master/tests/e2e/e2e_test.go#L60
