### ISSUE TITLE
Allow fetching a specific Devfile Stack version

### ISSUE THREAD

**Issue by rm3l** [redhat-developer/odo#6315]
/kind user-story

## User Story
As an odo user, I want to be able to specify a Stack version when initializing a new component, So that I can have better control over the Devfile I'm requesting.

## Acceptance Criteria 

- [x] If no version is specified, it should download the default version
- [x] If version is `latest`, it should download the latest version
- [x] Otherwise, it should download the requested version
- [x] It should work everywhere Devfile can be initialized and personalized: `odo init`, `odo dev` and `odo deploy` 
- [ ] [TBD] It should fallback to /index if /v2index is not available.
### `odo init`
- [x] Interactive mode should allow users to pick a Stack version (default is the version marked as default)
- [x] Non-interactive mode: add a new `--devfile-version` flag
- [x] Interactive mode should also include `devfile-version` flag in message displayed as hint for automation

### `odo dev` and `odo deploy`
When there is source code, but no Devfile, we run the interactive init mode. So this should allow users to pick a Stack version (default is the version marked as default)

## Links 
- Related Epic (mandatory): https://github.com/redhat-developer/odo/issues/6294

**NOTES**:
- It looks like there is a `v2index`  API that lists all versions for each Stack, e.g.: https://registry.stage.devfile.io/v2index

/kind user-story

**Comment by feloy** [comment]
springboot at least has two versions in result of https://registry.stage.devfile.io/v2index

**Comment by feloy** [comment]
- Test using integration and unit tests,
  - integration mostly to test flag recognition
  - unit test to test odo features (getting latest, specific version, ...) using fake data
- check if it is possible to download latest version of stack using a specifc (supported) devfile version
