### ISSUE TITLE
Setup CI infra for testing odo on Podman

### ISSUE THREAD

**Issue by rm3l** [redhat-developer/odo#6340]
@## User Story
As an odo developer, I want to set up CI infra So that I can reliably run `odo` tests using Podman as backend and be confident with my code changes.

## Acceptance Criteria
- [ ] It should not keep a long-running VM; instead, it should spin up VMs (with Podman) on the fly and destroy them once the tests are done
- [ ] It should pass all tests added in https://github.com/redhat-developer/odo/pull/6332, using the `test-integration-podman` Make target
- [ ] Add a script to reproduce the env.

## Links 
- Related Epic (mandatory): [#6332 ](https://github.com/redhat-developer/odo/issues/5871)
- Parent user story: https://github.com/redhat-developer/odo/issues/6236

**Comment by anandrkskd** [comment]
Just to be sure, we don't want a long-running VM for this test, 
- we want to create and delete VMs on the fly, for each test run.

cc_ @rm3l, @kadel

**Comment by rm3l** [comment]
> Just to be sure, we don't want a long-running VM for this test,
> 
> * we want to create and delete VMs on the fly, for each test run.
> 
Yes, ideally. That's what we concluded in the Cabal call on Nov-8.
You can start with on-demand VMs for now, and we'll see how long it takes to start a VM on IBM Cloud.

**Comment by feloy** [comment]
It would be interesting to try to run the tests with a GitHub action, using a ubuntu system (`runs-on: ubuntu-latest`), as this image contains podman

**Comment by rm3l** [comment]
For reference, here is the link to all software installed in the default runner images provided/maintained by GitHub: https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#tools
