### ISSUE TITLE
`odo url create` creates a route without target port

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/odo#636]
![image](https://user-images.githubusercontent.com/620330/44121061-529bcd3c-9fd3-11e8-9247-4b148a446143.png)

Environment:
Windows 10 Pro + Hyperv
```
>odo version
odo v0.0.9 (8b7a724)

Server: https://10.0.0.48:8443
OpenShift: v3.9.31
Kubernetes: v1.9.1+a0ce1bc657
```
```
>minishift version
minishift v1.20.0+1bd6d5c
CDK v3.5.0-rc.2-1
```
Steps to replicate:

``` 
>odo app create a1
Creating application: a2
Switched to application: a2

>>odo create httpd httpd-test --git https://github.com/openshift/httpd-ex.git
Component 'httpd-test' was created.
Triggering build from https://github.com/openshift/httpd-ex.git.

Cloning "https://github.com/openshift/httpd-ex.git" ...
        Commit: 0ac6da93a1f65fe9175cb1b7838cfca7b23d5fbe (Merge pull request #15 from adambkaplan/sclorg-rename)
        Author: Honza Horak <hhorak@redhat.com>
        Date:   Fri Aug 3 13:08:12 2018 +0200
---> Enabling s2i support in httpd24 image
AllowOverride All
---> Installing application source
=> sourcing 20-copy-config.sh ...
=> sourcing 40-ssl-certs.sh ...
Pushing image 172.30.1.1:5000/myproject/httpd-test-a1:latest ...
Push successful

Component 'httpd-test' is now set as active component.

c:\Temp\odo-test\httpd>odo url create
Adding URL to component: httpd-test
URL created for component: httpd-test

httpd-test - http://httpd-test-a1-myproject.10.0.0.48.nip.io
```
open OpenShift Web Console and check Routes page.

**Comment by mik-dass** [comment]
@dgolovin There is already an issue for this https://github.com/redhat-developer/odo/issues/553 and a PR for https://github.com/redhat-developer/odo/pull/615

**Comment by dgolovin** [comment]
@mik-dass thanks for the links! Surprisingly if I use nodejs-ex project with the same scenario it works without problems.

**Comment by dgolovin** [comment]
I have no external link available, because it is local OpenShift cluster, but I can tell you are right about nodejs-ex exposes only one port 8080/TCP.

**Comment by mik-dass** [comment]
@dgolovin yeah that will be really helpful thanks :+1:

**Comment by surajnarwade** [comment]
@dgolovin , since #615 is merged, can we close this ? can you please check once ?

**Comment by dgolovin** [comment]
@surajnarwade verified on local master build. Works for me. Closing.
