### ISSUE TITLE
By default enable ImageStream resolving 

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#6376]
/kind user-story

## User Story
As an odo user, I want to be able to use ImageStreams on OpenShift So that I can use my images hosted on the internal OpenShift registry.

## Acceptance Criteria 
- [ ] odo should add `alpha.image.policy.openshift.io/resolve-names: '*'` annotation to all Deployments generated from `container` component 
- [ ] Update the documentation about annotations added by `odo`: https://odo.dev/docs/development/architecture/how-odo-works#annotations

/kind user-story

**Comment by feloy** [comment]
It should also be done for Deployment created for a Component in Deploy mode

**Comment by feloy** [comment]
> It should also be done for Deployment created for a Component in Deploy mode

It seems this is not possible for the moment:
- ` ✗  exec command is not implemented for Deploy`
- when creating an Apply command for Deploy with a `container` component, nothing happens

**Comment by rm3l** [comment]
> > It should also be done for Deployment created for a Component in Deploy mode
> 
> It seems this is not possible for the moment to deploy a `container` component in Deploy mode :
> 
> * ` ✗  exec command is not implemented for Deploy`
>
I updated the description of https://github.com/redhat-developer/odo/issues/5701 to make sure we do not forget to also add this annotation when this is implemented.
> * when creating an Apply command for Deploy pointing to a `container` component, nothing happens
>
I guess that's a different issue, but it's not clear to me what is supposed to be the behavior here. 
@kadel ?
When looking at the [Devfile spec](https://devfile.io/docs/2.2.0/devfile-schema#commands), I can see that:

> Use the the apply command to apply a given component definition, usually a kubernetes, openshift or an image component. Apply commands are also typically bound to preStart and postStop events.
> For example, when an apply command is bound to a preStart event, and references a container component, it will start the container as a K8S initContainer in the devworkspace POD, unless the component has its dedicatedPod field set to true.
>
