### ISSUE TITLE
display environment variables in `odo describe component`

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#6419]
/kind user-story

## User Story
As an IDE plugin developer, I want to know where the source code in the container is located So that I can specify the mapping between source files on the local machine and the remote container. 

## Acceptance Criteria 
- [ ] `odo describe component` should display all environment variables for each container container
- [ ] `odo describe component -o json` should display all environment variables for each container container
- [ ] If the application is created on cluster (in dev or deploy mode) the variable list should also contain all extra variables that are automatically injected by odo like `PROJECTS_ROOT` and `PROJECT_SOURCE` or any additional variables. In other words, if it is created on a cluster, it should display all variables defined in the container spec.

## Notes
- Case of environment variables referencing a Secret or ConfigMap ? We could just display the keys in the first place

## example

```
▶ odo describe component
Name: nodejs-starter
Display Name: Node.js Runtime
Project Type: Node.js
Language: JavaScript
Version: 2.1.1
Description: Stack with Node.js 16
Tags: Node.js, Express, ubi8

Running in: Dev

Forwarded ports:
 •  127.0.0.1:40001 -> runtime:3000
 •  127.0.0.1:40002 -> runtime:5858

Supported odo features:
 •  Dev: true
 •  Deploy: true
 •  Debug: false

Container components:
 •  runtime
    Environment variables:
     • FOO: bar
     • DEBUG_PORT: 5858
     • PROJECT_SOURCE: /project
     • PROJECTS_ROOT: /project
 •  build
    Environment variables:
     • FOO1: bar1
     • PROJECT_SOURCE: /project
     • PROJECTS_ROOT: /project

```

```
▶ odo describe component -o json
{
	"devfilePath": "/Users/tkral/Code/odo-examples/nodejs-starter/devfile.yaml",
	"devfileData": {
		"devfile": {
			"schemaVersion": "2.2.0",
			"metadata": {
				"name": "nodejs-starter",
				"version": "2.1.1",
				"displayName": "Node.js Runtime",
				"description": "Stack with Node.js 16",
				"tags": [
					"Node.js",
					"Express",
					"ubi8"
				],
				"icon": "https://nodejs.org/static/images/logos/nodejs-new-pantone-black.svg",
				"projectType": "Node.js",
				"language": "JavaScript"
			},
			"components": [
				{
					"name": "runtime",
					"container": {
						"image": "registry.access.redhat.com/ubi8/nodejs-16:latest",
						"env": [
							{
								"name": "DEBUG_PORT",
								"value": "5858"
							},
							{
								"name": "FOO",
								"value": "bar"
							},
							{
								"name": "PROJECT_SOURCE",
								"value": "/projects"
							},
							{
								"name": "PROJECTS_ROOT",
								"value": "/projects"
							}
                                                 ]
```

## Links 

/kind user-story

**Comment by rm3l** [comment]
/priority Medium

Reducing the priority of this issue, since https://github.com/redhat-developer/odo/issues/6453 has been specifically created to address the original need described here (knowing where the source code in the container is located).
