### ISSUE TITLE
Allow passing extra build flags to podman/docker

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#6421]
/kind user-story

## User Story
As an odo user running Mac with AppleSilicon, I want to be able to build images for different platforms (amd64) So that I can run them on my cluster is amd64

## Acceptance Criteria 
- [x] `odo deploy` and `odo build-images` should check for `ODO_IMAGE_BUILD_ARGS` env variable and use it as additional arguments for `podman/docker build`
- [x] `odo run` should check for `ODO_CONTAINER_RUN_ARGS` env variable and use it as additional arguments for `podman/docker run`
- [ ] Tests
- [ ] Documentation
 
`ODO_IMAGE_BUILD_ARGS` we should come up with a better name for this variable. As in the future, we will have in-cluster build where this variable won't make sense. 

`ODO_CONTAINER_RUN_ARGS` come up with better name ;-)

## example:
`ODO_IMAGE_BUILD_ARGS="--platform linux/amd64" odo deploy` should run `podman build  --platform linux/amd64 ... `

**for discussion:**
Or this could also be a cli flag for `odo build-images` and `odo deploy` 

/kind user-story

**Comment by rm3l** [comment]
This seems related to https://github.com/redhat-developer/odo/issues/6178

**Comment by rm3l** [comment]
To better separate global options from those that are specific to a Podman/Docker sub-command, I have introduced an additional env var (`ODO_CONTAINER_BACKEND_GLOBAL_ARGS`), which will be passed as global flags to any Podman/Docker command executed by `odo`.

This will be needed for example if we want to pass global options like `--root` and `--runroot` to better isolate our integration tests on Podman.

`ODO_IMAGE_BUILD_ARGS` will be passed as flags specific to the `podman build` and `docker build` commands.

`ODO_CONTAINER_RUN_ARGS` will be passed as flags specific to the commands creating resources, like `podman play kube` when running `odo` against Podman.

So for example, running this:
```
$ ODO_IMAGE_BUILD_ARGS='--platform=linux/amd64;--build-arg=MY_ARG=my_value' \
  ODO_CONTAINER_BACKEND_GLOBAL_ARGS='--root=/tmp/podman/root;--storage-driver=overlay' \
  ODO_CONTAINER_RUN_ARGS='--configmap=cm-foo.yml;--quiet' \
  odo dev --platform=podman
```

will result in running the following commands:
```shell
podman \
  --root=/tmp/podman/root --storage-driver=overlay \
  build \
  --platform=linux/amd64 --build-arg=MY_ARG=my_value \
  ...

...
podman \
  --root=/tmp/podman/root --storage-driver=overlay \
  play kube \
  --configmap=cm-foo.yml --quiet
  ...

...
# Any other podman commands executed by odo under the hood
# will use the global args, e.g.:
podman \
  --root=/tmp/podman/root --storage-driver=overlay \
  pod list --format {{.Name}} --noheading

podman \
  --root=/tmp/podman/root --storage-driver=overlay \
  pod stop $podName

```
