### ISSUE TITLE
Support Devspaces devfile registry

### ISSUE THREAD

**Issue by feloy** [redhat-developer/odo#6435]
/kind feature

When trying to fetch a versioned devfile from a Devfile Registry not supporting versions, odo should not fail, but download the default devfile.

This needs some research to check if it is natively supported by the Devfile Reegistry (by simply ignoring the version field), or if odo needs to make a specific fallback call.

**Comment by valaparthvi** [comment]
Devspaces registries might not support versioned stack and we want make Devfiles that work on Devspace should also work with odo.
