### ISSUE TITLE
Documentation for `odo app list` should say 'List all the applications in current project'

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/odo#644]
https://github.com/redhat-developer/odo/blob/e67cb82387437b2729a56c581951e5610c4f519f/cmd/application.go#L134

To follow the same pattern used in `odo list' https://github.com/redhat-developer/odo/blob/e67cb82387437b2729a56c581951e5610c4f519f/cmd/list.go#L17

**Comment by cdrage** [comment]
PR here: https://github.com/redhat-developer/odo/pull/696
