### ISSUE TITLE
Flakes analysis on IBM cloud tests

### ISSUE THREAD

**Issue by anandrkskd** [redhat-developer/odo#6451]
/kind tests

we need some way to analyse the flakes observed as IBM Clouds tests to make tests more reliable  

https://github.com/kadel/odo-tools fetches logs from https://search.ci.openshift.org, but since we stopped using Prow, this tool can be modified to fetch logs from IBM cloud.

**Comment by rm3l** [comment]
To be worked on during DevTools week (June 2023).
