### ISSUE TITLE
`odo describe component` with Devfile: display remote source code location for each container component

### ISSUE THREAD

**Issue by rm3l** [redhat-developer/odo#6453]
/kind user-story

## User Story
As an IDE plugin developer or user, I want to know where the source code in the container is located, So that I can specify the mapping between source files on the local machine and the remote container. 

## Acceptance Criteria 
- [ ] `odo describe component` should display the source code location for each container container
- [ ] `odo describe component -o json` should display the source code location for each container container
- [ ] If the component is not running, it should get the information from the local Devfile. This depends on the values of the following container components fields :
  - `mountSources` (default value if not set is `true`)
  - `sourceMapping` (default value if not set is `/projects`)
- [ ] It should not report that information if `mountSources` is `false` 
- [ ] #6498
- [ ] It should also work with components running on Podman

## Examples

```
▶ odo describe component
Name: nodejs-starter
Display Name: Node.js Runtime
Project Type: Node.js
Language: JavaScript
Version: 2.1.1
Description: Stack with Node.js 16
Tags: Node.js, Express, ubi8

Running in: Dev

Forwarded ports:
 •  127.0.0.1:40001 -> runtime:3000
 •  127.0.0.1:40002 -> runtime:5858

Supported odo features:
 •  Dev: true
 •  Deploy: true
 •  Debug: false

Container components:
 •  runtime
    Project Source: /projects
 •  build
    Project Source: /project

```

```
▶ odo describe component -o json
{
	"devfilePath": "/Users/tkral/Code/odo-examples/nodejs-starter/devfile.yaml",
	"devfileData": {
		"devfile": {
			"schemaVersion": "2.2.0",
			"metadata": {
				"name": "nodejs-starter",
				"version": "2.1.1",
				"displayName": "Node.js Runtime",
				"description": "Stack with Node.js 16",
				"tags": [
					"Node.js",
					"Express",
					"ubi8"
				],
				"icon": "https://nodejs.org/static/images/logos/nodejs-new-pantone-black.svg",
				"projectType": "Node.js",
				"language": "JavaScript"
			},
			"components": [
				{
					"name": "runtime",
					"container": {
						"image": "registry.access.redhat.com/ubi8/nodejs-16:latest",
						"projectSource": "/projects"
...
```

## Links 
Related to https://github.com/redhat-developer/odo/issues/6419

/kind user-story

**Comment by valaparthvi** [comment]
I am not sure how this will work for named components in a simple way. One way it can work out is if I exec inside the component's pod and get the value of $PROJECT_SOURCE, but then we'll need to discuss how it would look in the both the output.
