### ISSUE TITLE
Restart pod on Podman when related information is changed in Devfile

### ISSUE THREAD

**Issue by rm3l** [redhat-developer/odo#6458]
/kind user-story

## User Story
As a user running `odo` against Podman, I want changes to my Devfile to be detected and applied, So that I can continuously iterate on my project without having to restart `odo dev` manually. 

Restarting `odo dev` manually every time I edit something in the Devfile can be annoying and time-consuming.

Currently, it detects any changes to the Devfile and warns users that `odo dev` needs to be restarted (see https://github.com/redhat-developer/odo/issues/6336). Even changes that would not affect the running Pod (like changes to the `build` or `run` commands) are ignored.

## Acceptance Criteria 
- ~[ ] It should recreate the Pod on Podman if there are changes in the Devfile that would modify the Pod spec (e.g., changes in the container component, ...)~
- ~[ ] It should not recreate the Pod on Podman if there are changes in the Devfile that would **not** modify the Pod spec (e.g., changes to the `run` command only)~
- ~[ ] Similarly to how `odo dev` works against a cluster, it should notify users of the current Pod state~
- ~[ ] Similarly to how `odo dev` works against a cluster, external factors that might affect the running Pod should also be handled by recreating the Pod if needed (but that can be a separate issue)~
- [ ] For now, it should just recreate the Pod on Podman if there any changes in the Devfile
- [ ] Update documentation: remove this point from the ["Podman Support limitations"](https://odo.dev/docs/development/architecture/podman-support-limitations#pod-not-updated-when-devfile-changes) page

## Links 
- Related Epic (mandatory): https://github.com/redhat-developer/odo/issues/6578
- Related Issue: https://github.com/redhat-developer/odo/issues/5728

/kind user-story

**Comment by valaparthvi** [comment]
@rm3l To add more information on this.

**Comment by rm3l** [comment]
/unassign
/remove-triage needs-information

Description and acceptance criteria updated. We can discuss and review this in the grooming call.

**Comment by rm3l** [comment]
@valaparthvi  I'm also removing this from the current Sprint (236) as it is not pointed yet, and so that it shows up in the [Grooming view](https://github.com/orgs/redhat-developer/projects/16/views/21) in the Project.

**Comment by valaparthvi** [comment]
**Grooming Call [April 20 '23]:**
Current scope of the issue:
1. For now, delete and recreate the pod no matter where the change occurs.
2. Volumes can be used to maintain persistent data.
3. Port forwarding needs to be restarted.

Look into other ACs after we decide on a new design to separate resources and commands.

**Comment by valaparthvi** [comment]
Should be fixed by refactoring done in #6771.
