### ISSUE TITLE
Allow users define custom port-mappings for port forwarding

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#6479]
/kind user-story

## User Story
As an odo user, I want to be able to define a mapping for port-forwarding So that I can have predictable port numbers; this is useful when developing multi-component applications.

example:

`cd frontend`
`odo dev`

`cd ../backend`
`odo dev`

configure the `frontend` to use port 20002 (`odo dev` for backed was started second)

I stop everything, next day I want to continue working but this time I start `odo dev` session for `backend` before `frontend`. Now I have to keep in mind to reconfigure the frontend to use a different port.

A slightly better experience would be to have 

`cd frontend`
`odo dev`

`cd ../backend`
`odo dev --port-forward 8888:8000`

Now no matter what order I run commands, I will get backed on localhost:8888.

An even better experience would be for odo to remember custom port mappings so next time I can just do `odo dev`. This is something that we can look into as second stage. 

## Acceptance Criteria 
- [x] Users should be able to define custom port mapping using flags provided to `odo dev` command using `--port-forward` flag. Flag accepts argument in `<localPort>:<containerPort>`
- [x] `port-forward` can be defined as multiple times (for multiple ports)
- [x] if multiple containers have the same port and the command should fail and guide the user to specify container name `--port-forward <localPort>:<containerName>:<containerPort>`
- [ ] `--address <ipaddress>` flag should allow specifying on which local address the port will be listening 
- [x] Validate if the containerPort is a valid endpoint(?)
- [ ] Handle `dedicatedPod` (is it handled currently?)
- [x] Cannot use `--random-port` and `--port-forward` together.
- [x] Validate that a local port is not defined more than once

allowed formats for `--port-forward`

`8080:80` - local port 8080 listening only on `localhost`, container port 80
`8080:mycontainer:80` - local port 8080 listening only on `localhost`, container port 80 on container called mycontainer

/kind user-story

**Comment by rm3l** [comment]
- Separate flag for listening host

**Comment by valaparthvi** [comment]
This issue will be fixed in 2 parts to avoid larger PR size:
- Implement for Kubernetes (#6704)
- Implement for Podman (TBD)

**Comment by valaparthvi** [comment]
What port range should we accept? Currently it accepts any value between 1 to 65535. Should we increase the lower limit to 1024?

**Comment by rm3l** [comment]
> What port range should we accept? Currently it accepts any value between 1 to 65535. Should we increase the lower limit to 1024?

I think we should not prevent that. 
A user might want to run `odo dev` as root to expose an application via a privileged port.. And it is even possible to grant a binary like `odo` the system capability to open privileged ports while still running with the privileges of a regular user.
I think we should make sure an appropriate error is returned when setting up port forwarding if the user does not have the privileges to open privileged ports.
