### ISSUE TITLE
Add app.openshift.io/vcs-uri annotation on Podman resources

### ISSUE THREAD

**Issue by rm3l** [redhat-developer/odo#6493]
/kind feature
/area odo-on-podman

## Which functionality do you think we should add?
Came across this while pair-programming on https://github.com/redhat-developer/odo/issues/6447

Related test: [`should create vcs-uri annotation for the deployment when running odo dev`](https://github.com/redhat-developer/odo/blob/main/tests/integration/cmd_dev_test.go#L2053)

## Why is this needed?
To be consistent with the way we manage labels and annotations on both Kubernetes and Podman (https://github.com/redhat-developer/odo/issues/6317)

**Comment by valaparthvi** [comment]
vcs-uri annotation is helpful in determining the source of the container.
Ref: https://github.com/redhat-developer/app-labels/blob/master/labels-annotation-for-openshift.adoc#annotations

**Comment by valaparthvi** [comment]
The value for this annotation should be same as is implemented for cluster.
