### ISSUE TITLE
odo dev on podman and cluster cannot run simultaneously

### ISSUE THREAD

**Issue by valaparthvi** [redhat-developer/odo#6494]
/kind bug

## What versions of software are you using?

**Operating System:**
Fedora 35
**Output of `odo version`:**
odo v3.5.0 (da9a9efb8f)
## How did you run odo exactly?
1. `odo init --devfile go --name my-go-app --starter go-starter`
2. `ODO_EXPERIMENTAL_MODE=true odo dev --platform podman` wait for it to finish
3. In another tab `odo dev`.

## Actual behavior
Once `odo dev` starts, both the dev sessions continue to sync because of the changes in .odo/devstate.json and never reach a stable state.

## Expected behavior
Both sessions should be able to run and reach a stable state.

## Any logs, error output, etc?
I am not sure if this is a valid use case and if something like this is an ideal workflow but it still a nuisance as an odo developer when I want to build and test new features for both podman and cluster.

## Acceptance criteria

- [x] PID is added to the content of the devstate file
- [x] Platform is added to the content of the devstate file
- [x] Forwarded Ports are added to the content of the devstate file
- [x] each `odo dev` session creates its own devstate.$PID.json file
- [x] the first `odo dev` session also creates a `devstate.json` file, for compatibility.
- [x] each `odo dev` session should check if `devstate.json` file exists and references a PID not existing, it deletes it; this helps in cleaning any file lying around when the previous process was kill(9)-ed. Same for all `odo` commands reading this file (`odo describe component`, ...)
- [x] `odo describe component` displays forwarded ports from all devstate.$PID.json files
- [x] `odo describe component --platform <platform>` displays forwarded ports from  devstate.$PID.json file with platform=&lt;platform>
- [x] `odo dev` can run only once per platform, exit if a devstate.$PID.json file with the platform already exists.

**Comment by feloy** [comment]
https://github.com/redhat-developer/odo/issues/6362 should fix the problem

**Comment by rm3l** [comment]
**Grooming (2023-03-30)**
- Have one devstate.json file per Dev session PID

**Comment by valaparthvi** [comment]
/status blocked
https://github.com/redhat-developer/odo/issues/6719

**Comment by feloy** [comment]
The implementation for checking if a PID exists is different on Windows and Unix, and needs some attention (do we want to run tests on Windows with Podman + Kubernetes?)
