### ISSUE TITLE
send `platform` and `experimental mode` as properties to telemetry

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#6508]
/kind user-story

## User Story
As a ... I want to ... So that ...

## Acceptance Criteria 
- [ ] It should ....
- [ ] It should ....

## Links 
- Related Epic (mandatory): 

/kind user-story

**Comment by rm3l** [comment]
**Grooming (2023-01-19)**
- Should be implemented outside of the experimental mode
- 2 new fields:
  - platform: podman, kubernetes, openshift
  - platform version: whole version, not just major
- Send only for `odo dev` and `odo deploy` commands
- Get rid of cluster type in code

**Comment by feloy** [comment]
cluster type is still sent to telemetry for commands odo create/delete/set namespace/project.

@kadel do we want to remove this telemetry info (cluster type) for these commands? Note that we did not plan to add platform and platform version for these commands.

**Comment by kadel** [comment]
If it is possible, let's keep it for `odo create/delete/set namespace/project` as it is. If it is complicated code too much than we can remove cluster type from those commands. Currently there are no reports that use that data

**Comment by valaparthvi** [comment]
/close
Required work is done.
