### ISSUE TITLE
ctrl-c `odo dev` reported as an error in telemetry 

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#6514]
/kind bug

When user ctrl-c `odo dev` it is reported as an error in the telemetry data

this is send to the telemetry
```
error: Dev mode interrupted by user
error-type: *errors.errorString
```

user interrupting `odo dev` is expected behavior and should not be reported as an error

**Comment by rm3l** [comment]
**Grooming (2023-06-01)**

- Interrupting the process should return 0 as exit code (separate issue)
- For `odo dev`:
  - If an error occurs in cleanup, exit code should not be 0. If no error, exit code should be 0

- Do not explicitly exit in odo context. Leverage the cancelable context. Returning an error should propagate as an exit code.
