### ISSUE TITLE
Test failure: `odo dev` interactive tests

### ISSUE THREAD

**Issue by valaparthvi** [redhat-developer/odo#6530]
Summarizing 1 Failure:
  [FAIL] odo dev interactive command tests directory is not empty when Alizer cannot determine a Devfile based on the current source code [It] should not fail but fallback to the interactive mode
  C:/Users/Administrator.ANSIBLE-TEST-VS/3097/tests/helper/helper_interactive.go:111

Refer:
https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-6522-windows-tests-3097.txt

https://github.com/redhat-developer/odo/pull/6522

cc: @anandrkskd

**Comment by anandrkskd** [comment]
Closing this issue for #6594 
/close
