### ISSUE TITLE
Files are created during unit tests

### ISSUE THREAD

**Issue by feloy** [redhat-developer/odo#6539]
/kind bug

After the update of the devfile library (commit [19f8e0ebd](https://github.com/redhat-developer/odo/commit/19f8e0ebdbdce780e946d07d2ea9067344b782ac)), running the unit tests create files in `pkg/libdevfile/testdata/`

```
$ make test
[...]
$ git status
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	pkg/libdevfile/testdata/parent-devfile-commands-only.yaml
	pkg/libdevfile/testdata/parent-devfile-components-only.yaml
	pkg/libdevfile/testdata/parent-devfile-empty.yaml
	pkg/libdevfile/testdata/parent-devfile.yaml
```

**Comment by rm3l** [comment]
Came across this issue earlier today. Might be caused by https://github.com/devfile/library/pull/139

**Comment by rm3l** [comment]
Issue reported in the Devfile library: https://github.com/devfile/api/issues/1118

/status blocked

Meanwhile, (I know this kinda hides the issue for now), but locally, I have added the paths to these files to my local `.git/info/exclude` to avoid accidentally pushing them..

**Comment by feloy** [comment]
> 
> Meanwhile, (I know this kinda hides the issue for now), but locally, I have added the paths to these files to my local `.git/info/exclude` to avoid accidentally pushing them..


  Thanks for the tip, I'll stop pushing these files accidentally :)

**Comment by rm3l** [comment]
Issue still relevant.

/reopen
/remove-lifecycle stale
/remove-lifecycle rotten
/remove-status blocked
