### ISSUE TITLE
Document potential pitfalls with air-gapped environments

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#6542]
/area documentation

We should document what problems users in a restricted network environment could face when using odo and defiles.

Notes:

- `odo init` requires a Devfile registry. By default, it uses an upstream registry that is most likely not going to work in such environments; users should deploy their own 
- link to Devfile documentation explaining how to install off-line registry (https://devfile.io/docs/2.2.0/installation-of-in-cluster-offline-devfile-registry) 
- document what parts of devfile users need to change (images, configure npm/maven, etc...). to make sure that Devfiles  can work (**This should most like by part of devfile documentation, not odo docs** and odo docs should link to it)

**Comment by dgolovin** [comment]
@kadel please also mention proxy settings, it seems to fit into documentation about 'restricted network environment'.
