### ISSUE TITLE
Odo don't work well in online

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#658]
Because online uses block storage redeployments with rolling strategy don't work, but they should be created with recreate strategy.
IMHO this should probably need to be the default in development mode, since it'll be more resource (cpu, mem) friendly to what developers should probably have and might not have a big impact in the inner loop.

Maybe worth adding this as an odo utils config option and `odo create` flag as well.

**Comment by surajnarwade** [comment]
is our user aware of things like `recreate` strategy ?

**Comment by kadel** [comment]
It makes sense.
Let's change default DeploymentStrategy to Recreate.

And make this configurable.

```
odo utils config set DeploymentStrategy RollingUpdate

odo utils config set DeploymentStrategy Recreate
```

**Comment by kadel** [comment]
probably fixed in #1223 
TODO: 
 - verify this on online

**Comment by kadel** [comment]
tested this on OpenShift free online.
It works,  it is just a little bit slower, but that is expected.

For example, if you add storage to the component, it will trigger redeployment.
Recreate first shuts down the old pod and then it starts creating a new one, if you are unlucky and the new pod is scheduled on a different node, it has to pull the image again. This can take a minute.

**Comment by kadel** [comment]
I'm a little bit lost :-(

> @kadel this can also happen with "Recreate" that the pod will be created on a new node.

Do you mean with RollingUpdate? Yes, the pod can be scheduled to a different node, but with RollingUpdate scheduler waits for the new pod to be "online" before taking down the old one.
From a users perspective, it looks better as there is no downtime (time it takes to pull image the old pod is still running)

I'm not trying to say that this is a huge deal. I'm just pointing out that there is also a small downside to it.

> Also, liveness and readiness probes makes the process faster. Without them a pod will take the default time to shut down, which is 30 seconds.

Isn't this more about how application inside container handles signals?
The container gets `SIGTERM` signal when Kubernets wants to shut it down. If the application behaves properly, it should shut itself down. When this is not done after default timeout 30s, it will be killed with `SIGKILL` signal.

> We could improve the time it takes for shutdown if we configure a probe in the supervisor. But yet again, this would require a custom supervisor process that would know when to answer OK and when KO. This would make redeployments almost instantaneous.

Even if you have the liveness my comment about signals is true. If liveliness probe fails, Kubernetes  will try to terminate the pod, if the application doesn't react to SIGTERM the default 30s timeout will take places before it gets "shot down" with `SIGKILL`

**Comment by jorgemoralespou** [comment]
Yes, you're right. I was thinking about something else, and got mixed in my head.

**Comment by kadel** [comment]
I'm closing this issue. Odo now created DeploymentConfigs with Recreate strategy (added in #1223).

There is one more issue related to odo and OpenShift online, but that one is related to storage. and not that easy to fix -  https://github.com/redhat-developer/odo/issues/755
