### ISSUE TITLE
Use Go 1.20 (or 1.19)

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#6581]
1.20 was released on Feb 1st. This means that our current version (1.18) is no longer supported.

- [ ] Update all our CI jobs to use 1.20 (or at least 1.19 if 1.20 is not available)
- [ ] Update release jobs to use 1.20 (or at least 1.19 if 1.20 is not available)

/priority high

**Comment by rm3l** [comment]
```
$ podman image pull registry.ci.openshift.org/openshift/release:golang-1.20
Trying to pull registry.ci.openshift.org/openshift/release:golang-1.20...
Error: initializing source docker://registry.ci.openshift.org/openshift/release:golang-1.20: reading manifest golang-1.20 in registry.ci.openshift.org/openshift/release: manifest unknown: manifest unknown
```

I'm updating to Go 1.19, as 1.20 does not seem to be available yet.
