### ISSUE TITLE
`odo describe component` fails when trying to get info about "non-odo" component

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#6584]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**
odo v3.6.0 (a03576435)

## How did you run odo exactly?
- created a new component using OpenShift Dev Console (+Add -> Samples -> Basic Node.js)
- run odo list
  ```
  ▶ odo list
   ✓  Listing resources from the namespace "tkral-dev" [9s]
  
  Components:
   NAME                       PROJECT TYPE  RUNNING IN  MANAGED
   * java-springboot-starter  springboot    None        Unknown
   nodejs-basic               Unknown       None        Unknown
   devfile-sample-git         Unknown       None        Unknown
   modelmesh-controller       Unknown       None        modelmesh-controller
  ```
- run odo describe component 
  ```
  ▶ odo describe component --name nodejs-basic
   ✗  no component found with name "nodejs-basic" in the namespace "tkral-dev"
  ```

## Actual behavior
`odo describe component ` complains that the component nodejs-basic doesn't exists, but `odo list` sees it.  This is confusing behaviour. One odo commands sees that compoent, but other doesn't

## Expected behavior
It need to be possible to run `describe` command on every item listed in the `list` output.

## Any logs, error output, etc?
Odo won't be albe to get all the information from the compoentn that is not managed by odo. This is ok. THe output can be limited to only information that odo can obtain. 

/kind bug
/priority high

**Comment by feloy** [comment]
Floows the case "Describe"
Rely on best-practices labels to determine information

Ingresses / Routes should be displayed it such resources exist with best-practices labels
