### ISSUE TITLE
Add scaffolding command to generate code for runtimes such: SpringBoot, Vert.x, Thorntail

### ISSUE THREAD

**Issue by cmoulliard** [redhat-developer/odo#659]
I would like to propose the idea to have a `scaffolding` command able to generate within the current folder a maven project for the java runtimes such as Spring boot, Vert.x, Thorntail or Spring Boot for Camel, ...

The command is a HTTP Client calling a HTTP REST endpoint and passing as parameters information needed to generate a zipped file

Most of the parameters are generic and could be apply no matter if we generate a project for SpringBoot, Vert.x, ...

Parameter :  

```
url : address of the REST Service generating the project
GroupId : maven group of the gav
ArtifactId  : maven artifact of the gav
Version : maven version of the gav
Java PackageName: name of the package = path of the folders containing the java classes
Dependencies: List of starters, modules, .... (web, security, jpa, ...)
BomVersion : Version of the BOM file containing the GAVs
Runtime version : Version of the framework to be used (it could also be equal to BOM version)
Template: template name to be used (= booster) to populate the project using the code
```

We could imagine to use an interface within the scaffold command and generate method but where the implementation of the content of the method is provided by the runtime golang package. That will need to import such go packages during odo build or dynamically via a golang plugin

**Comment by jorgemoralespou** [comment]
If this requires some server-side components to work I would think that should not be in the scope of `odo` for now, but deferred.
Having a command that will work in some clusters but not on others depending on whether this HTTP rest endpoint is available is not desired.
If what you propose is that this HTTP rest endpoint is in a public well know URL, then we need to work and define how to make this URL stable enough throughout time and provide versioning semantics to allow for evolution.

**Comment by cmoulliard** [comment]
> public well know URL

That will be a public URL that of course we will make it stable enough, versioned to support to be used/called by odo or `curl/httpie` tool also like the `f8 launcher`

**Comment by cmoulliard** [comment]
> some clusters

The command to be used will be cluster's agnostic as it will call by example `start.vertx.io`, `start.snowdrop.me`, ...

**Comment by girishramnani** [comment]
is this issue still relevant?

**Comment by kadel** [comment]
> is this issue still relevant?

yes

**Comment by cmoulliard** [comment]
If you are interested, here is what @metacosm developed to support such a scaffolding feature - https://github.com/halkyonio/kreate/blob/master/pkg/kreate/cli/project/project.go#L26. Ideally the launcher should be the API that odo or another Dev CLI tool could call to scaffold for a runtime a project
