### ISSUE TITLE
Move podman out of Experimental Mode

### ISSUE THREAD

**Issue by valaparthvi** [redhat-developer/odo#6592]
/kind user-story

## User Story
As an odo dev, I want to move podman out of experimental mode. With all the required issues of epic #5871 done, we can now move out of the experimental mode.

## Acceptance Criteria 
- [x] It should work without enabling Experimental Mode.
- [ ] update documentation
  - [x] remove all mentions of experimental mode
  - [x] document `--platform` flag for all commands: odo dev, odo list, odo describe, odo delete, odo logs
  - [ ] add documentation explaining the limitations of podman implementations (see https://odo.dev/docs/development/architecture/how-odo-works)
    - [ ] Apply command are not supported
    - [ ] Component listening on localhost
## Links 
- Related Epic (mandatory): #5871, #6578 

/kind user-story

**Comment by feloy** [comment]
Try to change extension of experimental mode page to hide it

**Comment by feloy** [comment]
> Try to change extension of experimental mode page to hide it


The "Experimental mode" page is referenced from blog posts, and removing the page breaks the build of the website.

**Comment by valaparthvi** [comment]
@feloy What remains on this issue?

**Comment by feloy** [comment]
> * add documentation explaining the limitations of podman implementations

add documentation explaining the limitations of podman implementations
