### ISSUE TITLE
Cannot start 2 different Dev sessions on Podman due to conflicting host ports

### ISSUE THREAD

**Issue by rm3l** [redhat-developer/odo#6612]
/kind bug

## What versions of software are you using?

**Operating System:**
Fedora 37, kernel 6.1.12-200.fc37.x86_64
MacOS Ventura 13, Darwin Kernel Version 22.3.0

**Output of `odo version`:**
odo v3.7.0 (e32024f87)

**Output of `podman version`:**
```
Client:       Podman Engine
Version:      4.4.1
API Version:  4.4.1
Go Version:   go1.19.5
Built:        Thu Feb  9 11:58:53 2023
OS/Arch:      linux/amd64
```

## How did you run odo exactly?

In one terminal:
```
$ mkdir /tmp/nodejs1 && cd /tmp/nodejs1
$ odo init --name my-nodejs --devfile nodejs --starter nodejs-starter
$ ODO_EXPERIMENTAL_MODE=t odo dev --debug --platform=podman
```

Wait until the Dev session is started.

In a separate terminal:
```
$ mkdir /tmp/nodejs2 && cd /tmp/nodejs2
$ odo init --name my-nodejs-2 --devfile nodejs --starter nodejs-starter
$ ODO_EXPERIMENTAL_MODE=t odo dev --debug --platform=podman
```

## Actual behavior

The dev session for `my-nodejs-2` (second terminal) wouldn't start, because we are trying to bind to port 20001, which is already used by the dev session started by `my-nodejs` (first terminal).
The error is explicit: `[... rootlessport listen tcp 0.0.0.0:20001: bind: address already in use]`

```
$ ODO_EXPERIMENTAL_MODE=t odo dev --debug --platform=podman
============================================================================
⚠ Experimental mode enabled. Use at your own risk.
More details on https://odo.dev/docs/user-guides/advanced/experimental-mode
============================================================================

  __
 /  \__     Developing using the "my-nodejs-2" Devfile
 \__/  \    Platform: podman
 /  \__/    odo version: v3.7.0
 \__/

↪ Running on podman in Dev mode
 ✗  Deploying pod [6s]
Cleaning up resources
 ✗  exit status 125: 
Complete Podman output:
Trying to pull registry.access.redhat.com/ubi8/nodejs-16:latest...
Getting image source signatures
Checking if image destination supports signatures
Copying blob sha256:f6020ef1f0c813cb6e68b95ffe2ba1eb76a61b5083e624cb8a72a51626191bf7
Copying blob sha256:1eb1cc491a1bd8e2827ef1c90d2253d5aca4348cc5642ec2206c85dfd20a22e1
Copying blob sha256:ea0a20a2c44861ba5e4cd80a32868b6f8265cd3ee81310d4d493a1b50d1c0d8c
Copying config sha256:bfc987a83b9e6ffa90480235b015d1eb969bb78adec0e78714140787b091efaf
Writing manifest to image destination
Storing signatures
[starting container c2b8f4c5cef80875ea6e4987bbb81e21cdceaf3894a382c5f1178a1fc2c0c337: rootlessport listen tcp 0.0.0.0:20001: bind: address already in use]
[starting container c2b8f4c5cef80875ea6e4987bbb81e21cdceaf3894a382c5f1178a1fc2c0c337: rootlessport listen tcp 0.0.0.0:20001: bind: address already in use starting container 5c71090911cb59380f68223bf1ef033b5edbff0543d53b5c4a736e3c86465810: a dependency of container 5c71090911cb59380f68223bf1ef033b5edbff0543d53b5c4a736e3c86465810 failed to start: container state improper]
Pod:
f673cb2681aa98a0f976f50f4acb6e08f89342f698004654d45bda5742270f84
Container:
5c71090911cb59380f68223bf1ef033b5edbff0543d53b5c4a736e3c86465810

starting container c2b8f4c5cef80875ea6e4987bbb81e21cdceaf3894a382c5f1178a1fc2c0c337: rootlessport listen tcp 0.0.0.0:20001: bind: address already in use
starting container 5c71090911cb59380f68223bf1ef033b5edbff0543d53b5c4a736e3c86465810: a dependency of container 5c71090911cb59380f68223bf1ef033b5edbff0543d53b5c4a736e3c86465810 failed to start: container state improper

Error: failed to start 2 containers
```

## Expected behavior
The dev session started in the second tab should listen on different ports not being used. So it looks like there is an issue with the way we detect if a port is used or not ([`util.IsPortFree(int)`](https://github.com/redhat-developer/odo/blob/main/pkg/util/util.go#L786-L796)).

## Any logs, error output, etc?

Initially, I suspected the [kernel issue](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/7VPNMC77YC3SI5LFYKUA4B5MTFPLTLVB/) we already hit a few weeks ago. But running https://go.dev/play/p/ijrIFcB3ayo?v=goprev works as expected. And this is reportedly fixed in recent kernels. So this is not a kernel issue to me.

**Comment by rm3l** [comment]
**NOTE**: I quickly checked if it works with Kubernetes, since both Kubernetes and Podman implementations of `odo dev` use the same [`util.IsPortFree(int)`](https://github.com/redhat-developer/odo/blob/main/pkg/util/util.go#L786-L796) function to determine if a port is available. And port-forwarding on Kubernetes works as expected by binding to non-conflicting ports. So maybe there is something different in how Podman handles `hostPort`?

**Comment by valaparthvi** [comment]
This works on podman 3.4.7 and Kernel version 6.0.12-100.
```sh
$ uname -a 
Linux fedora 6.0.12-100.fc35.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Dec 8 16:53:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by feloy** [comment]
If a port is open by `podman`, it is not detected (by either `odo dev` on podman or cluster)

**Comment by feloy** [comment]
Need research

**Comment by rm3l** [comment]
I reported this issue to the Podman folks: https://github.com/containers/podman/issues/17719

And the conclusion is that this issue is (again) a regression in the kernel that allows binding twice on the same port under some circumstances.
It has been reported to the kernel [1], and a patch [2] is underway.

Meanwhile, I think a workaround for us could be to explicitly set `hostIP` in the Pod spec to `127.0.0.1`, or, better, try to detect used ports bound to `0.0.0.0` (and not only `127.0.0.1`).

[1] https://lore.kernel.org/netdev/e21bf153-80b0-9ec0-15ba-e04a4ad42c34@redhat.com/
[2] https://lore.kernel.org/netdev/533d3c1a-db7e-6ff2-1fdf-fb8bbbb7a14c@leemhuis.info/T/
