### ISSUE TITLE
[Nightly failure] DevfileRegistriesList tests failing on prow

### ISSUE THREAD

**Issue by anandrkskd** [redhat-developer/odo#6637]
/priority critical-urgent
/area testing

Recently added tests failing on prow nightly jobs due to permission issues for developer user (used for testing)
 
```
  [FAIL] odo devfile init command tests when DevfileRegistriesList CRD is installed on cluster [BeforeEach] when CR for devfileregistrieslists is installed in namespace should be able to download devfile from the in-cluster registry
  /go/src/github.com/redhat-developer/odo/tests/helper/helper_oc.go:34
  [FAIL] odo init interactive command tests when DevfileRegistriesList CRD is installed on cluster [BeforeEach] when CR for devfileregistrieslists is installed in namespace should download correct devfile from the first in-cluster registry
  /go/src/github.com/redhat-developer/odo/tests/helper/helper_oc.go:34
  [FAIL] odo preference and config command tests when DevfileRegistriesList CRD is installed on cluster [BeforeEach] when CR for devfileregistrieslists is installed in namespace registry list should return registry listed in CR
  /go/src/github.com/redhat-developer/odo/tests/helper/helper_oc.go:34
  [FAIL] odo devfile registry command tests when DevfileRegistriesList CRD is installed on cluster [BeforeEach] when CR for devfileregistrieslists is installed in namespace should list detailed information regarding nodejs when using an in-cluster registry
  /go/src/github.com/redhat-developer/odo/tests/helper/helper_oc.go:34
  [FAIL] odo preference and config command tests when DevfileRegistriesList CRD is installed on cluster [BeforeEach] when CR for devfileregistrieslists is installed in namespace should fail to delete the in-cluster registry
  /go/src/github.com/redhat-developer/odo/tests/helper/helper_oc.go:34
  ```
  
  
  > ___Note:___ This will effect interOp tests as well, so we need to make sure its fixed ASAP

Links to failed jobs:
- https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-redhat-developer-odo-main-v4.10-integration-e2e-periodic/1632894058881880064
- https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-redhat-developer-odo-main-v4.11-sbo-nightly-odo-tests/1632894061771755520
- https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-redhat-developer-odo-main-v4.12-integration-e2e-periodic/1632894062153437184
- https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-redhat-developer-odo-main-v4.11-integration-e2e-periodic/1632894060073062400
- https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-redhat-developer-odo-main-v4.9-integration-e2e-periodic/1632894062996492288

**Comment by anandrkskd** [comment]
To resolve this, I think either 
- we can give user developer access to created CRD/CR, or
- skip this test from prow as we have unit tests testing this part extensively (cc @rm3l, @feloy)

**Comment by rm3l** [comment]
> To resolve this, I think either
> 
> * we can give user developer access to created CRD/CR, or
> * skip this test from prow as we have unit tests testing this part extensively (cc @rm3l, @feloy)

🤔 I remember we thought about this Forbidden or Unauthorized case in the code and handled it gracefully.. But we didn't think about the test cases where the user might not have permission to apply such manifests.
I also think we can run those tests only on Kubernetes and skip OpenShift/Prow.

**Comment by rm3l** [comment]
@anandrkskd @ritudes Will you be able to look into this issue today? Otherwise, we'll take a look. It would be great if the next nightly tests run with the fix for this issue (to unblock the v3.8.0 release).

**Comment by anandrkskd** [comment]
I will create a PR for it ASAP

**Comment by rm3l** [comment]
> I will create a PR for it ASAP

I created https://github.com/redhat-developer/odo/pull/6640, to fix this as soon as possible. Please take a look when you get a chance.
