### ISSUE TITLE
Flaky `remove binding` test: `should have led odo dev to delete ServiceBinding from the cluster`

### ISSUE THREAD

**Issue by anandrkskd** [redhat-developer/odo#6651]
/area testing 
/kind flake

link to failed tests:
https://storage.googleapis.com/origin-ci-test/36206/rehearse-36206-periodic-ci-redhat-developer-odo-main-v4.13-integration-e2e-periodic/1631544866049626112/build-log.txt
https://storage.googleapis.com/origin-ci-test/logs/periodic-ci-redhat-developer-odo-main-v4.10-integration-e2e-periodic/1630357454946570240/build-log.txt

**Comment by rm3l** [comment]
Issue was not reproduced recently in the past few weeks. Closing it for now. We'll reopen it if it occurs again.
