### ISSUE TITLE
Documentation(Advanced Usage): Tutorial to debug an application (Go, Python, Dotnet, Java)

### ISSUE THREAD

**Issue by valaparthvi** [redhat-developer/odo#6663]
There is no tutorial on debugging an application. It will help to have a quickstart like guides for all the common languages on this topic.

**Comment by rm3l** [comment]
Good point. This should even be part of the documentation, IMO, for example under "Advanced Usage > Debugging application", no?

**Comment by valaparthvi** [comment]
> Good point. This should even be part of the documentation, IMO, for example under "Advanced Usage > Debugging application", no?

I believe that is what I meant, I'll change the title.

/title Documentation(Advanced Usage): Tutorial to debug an application (Go, Python, Dotnet, Java)

**Comment by valaparthvi** [comment]
@rm3l I am interested in working on this, and I think I remember you mentioned an interest as well. Would you like to work on this together?
