### ISSUE TITLE
`odo dev` should exit if the build command fails

### ISSUE THREAD

**Issue by adambkaplan** [redhat-developer/odo#6671]
/kind user-story

## User Story
As an odo user, I want `odo` to log the build command output only once if it fails and indicate which command in the Devfile should be fixed, so that I can understand why my devfile/source code is not working and fix it without having to scroll through a lot of logs.

See the "Original issue" section below for the original user request.

## Acceptance Criteria 
- [ ] Similar to how the `run`/`debug` commands are handled, if the `build` command fails, `odo dev` should not retry until there is a manual sync triggered (by pressing `p`) or until there are new changes in the local source code or the devfile
- [ ] `odo dev --no watch` should also behave the same way, the only difference being that it should retry only if there is manual sync triggered (by pressing `p`)
- [ ] Make sure it behaves the same way on both cluster and Podman

## Links 
- Related Epic (mandatory): https://github.com/redhat-developer/odo/issues/5848
- Related issues:
  - https://github.com/redhat-developer/odo/issues/6173

---

# Original issue

/kind feature

## Which functionality do you think we should add?

If the build command as defined in the devfile fails, `odo dev` should exit and indicate which command in the devfile should be be fixed/investigated

## Why is this needed?

When bootstrapping a project via `odo init`, it may be the case that the build command needs to be modified so that the application can be compiled.

This is particularly true for go-based projects. The stacks currently available on https://github.com/devfile/registry/blob/main/stacks/go assume there is a `main.go` at the project root. This is not universally true - there is no firm consensus in the go community that this pattern should be adopted, and many teams/projects have their own idioms around "main" files. Example - putting command line invocations in the `cmd` package is common.

Stopping the sync loop and printing the last lines of the log (current behavior) followed by a helpful action statement would improve the developer flow.

**Comment by valaparthvi** [comment]
Thank you for raising this, Adam. We'll be sure to groom this soon.

**Comment by feloy** [comment]
The PR #6762 mkes some refactoring on the Dev code, to simplify the legacy code:
- getting the values passed into the context
- Move Devfile param to WatchParams insted of being part of the Adapter structure,  and build adapter only once
