### ISSUE TITLE
`odo analyze` returns error if current directory contains an invalid Devfile

### ISSUE THREAD

**Issue by rm3l** [redhat-developer/odo#6683]
/kind bug

## What versions of software are you using?

**Output of `odo version`:**
odo v3.8.0 (987d6f6fc)

## How did you run odo exactly?

```
mkdir /tmp/issue-odo-analyze
cd /tmp/issue-odo-analyze

cat << EOF > main.go
package main

import "fmt"

func main() {
        fmt.Println("Hello World")
}
EOF

touch devfile.yaml

odo analyze -o json
```

## Actual behavior

Output of `odo analyze`:
```json
{
        "message": "failed to parse the devfile /tmp/bug-odo-analyze/devfile.yaml: failed to populateAndParseDevfile: schemaVersion not present in devfile: /tmp/bug-odo-analyze/devfile.yaml"
}
```

## Expected behavior

The goal of `odo analyze` is to analyze the current directory and return things it has detected (like best Devfile, name, port, ...). Even if there is already a Devfile, I think we should not try to validate it at this point.

**Comment by valaparthvi** [comment]
- This error might be coming from where the Devfile obj is built into the context, we should be able to ignore this error for `odo analyze`.
