### ISSUE TITLE
On cluster, when run is hotReloadCapable, the Build command is not called after source sync

### ISSUE THREAD

**Issue by feloy** [redhat-developer/odo#6695]
/kind bug

On cluster, when Run command is hotReloadCapable, the Build command is not executed after source sync.

On Podman, the Build command is executed after each source sync.

## Acceptance Criteria
- [ ] Behavior should be consistent on both podman and cluster; build command should be called after source sync if it is not hotReloadCapable.
- [ ] Document the behavior in how `odo dev` works.
- [ ] Make sure all tests pass

## What versions of software are you using?

odo v3.8.0

**Comment by rm3l** [comment]
Link to PR in devfile/api : https://github.com/devfile/api/pull/1091

**Comment by valaparthvi** [comment]
Should not be merged before https://github.com/redhat-developer/odo/issues/6747 is closed/validated.
