### ISSUE TITLE
hotReloadCapable support

### ISSUE THREAD

**Issue by feloy** [redhat-developer/odo#6697]
/kind bug

There exists some misunderstandings around the hotReloadCapable meaning.

On Odo:
- on cluster: When Run command is hoteloadCapable, Build **and** Run commands are executed only once
- on Podman, when Run command is hotReloadCapable, Run command **only** is executed only once. 
- on both podman and cluster, the hotReloadCapable'ity of the Build command is not considered

On Devfile stacks:
- on Angular devfile (and similar), the Run command is marked as hotReloadCapable, but not the Build command. This is compatible with the behaviour of odo on cluster, but not on Podman (as the Build command should be executed only once).

After discussion with @tkral, we propose to disambiguate this by:

- [x] Updating description of hotReloadCapable on devfile/api to:
  - [x] specify on which command it is supported: build, run, debug
  - [x] specify what is the behaviour for Build command vs Run/Debug commands
  - [x] clarify that it is a synonym of (must be ran only once)
- [x] #6747
- [x] Fixing Odo on Cluster and Podman to run the Build command after source changes only when hotReloadCapable (of the Build command itself, not of the Run command) is false.

Related issues: 
- [x] https://github.com/redhat-developer/odo/issues/6657
- [x] https://github.com/redhat-developer/odo/issues/6695

**Comment by valaparthvi** [comment]
Track this issue for the hotReloadCapable support.
https://github.com/devfile/api/pull/1091
