### ISSUE TITLE
`odo run <devfile-command>` when `odo dev` is NOT running

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#6714]
/kind user-story

## User Story
As an odo user, I want to be able to start commands defined in the devfile when I need to So that I can run actions defined in the devfile, like, for example running commands that test things, or nondefault build commands that do some optional extra work.

## Acceptance Criteria 
- [ ] `odo run` can be run without running `odo dev` first
- [ ] if the component has `mountSources:true` odo run needs to sync source code into the container before executing the command
TODO @kadel

## Links 
- Related Epic (mandatory): 

/kind user-story

**Comment by feloy** [comment]
From a plugin user point of view, if the plugin runs "odo dev --no-commands", if would be transparent for the user.
For a CLI user, they still need to run "odo dev --no-commands" at the beginning of the session.

**Comment by feloy** [comment]
Closing as not planned due to complexity to run without an "odo dev" process
