### ISSUE TITLE
[Research] Allow testing odo on both podman and cluster simultaneously in integration tests

### ISSUE THREAD

**Issue by valaparthvi** [redhat-developer/odo#6719]
- Setup a handful of integration tests to cover changes done by #6494, more specifically devstate.$PID.json file changes, that will test odo simultaneously on both podman and cluster.
- It is possible to setup a GH action that will install podman and a local K8s cluster(minikube, kind, etc).
- minikube/kind to run on podman or docker? Podman support for both the clusters is experimental and might not as stable as docker.
- Investigate GH actions to setup local k8s cluster (minikube, kind). jkube, devfile seems to have one.
- Tests can also include `odo list`, and `odo describe components.

**Comment by valaparthvi** [comment]
Pointing the issue from a research point of view.

**Comment by rm3l** [comment]
Reopening as it still makes sense, and this issue was already scoped to research only.

/reopen
/remove-lifecycle stale
/remove-lifecycle rotten
/remove-triage needs-information
/retitle [Research] Allow testing odo on both podman and cluster simultaneously in integration tests
