### ISSUE TITLE
Fix outdated release verification script

### ISSUE THREAD

**Issue by rm3l** [redhat-developer/odo#6730]
/kind user-story
/area release-eng
/area testing

## User Story
As an odo developer or QE, I want to test `odo` binaries candidates for release, So that I can be confident to mark the corresponding Errata as `REL_PREP`.

The [release-bit-verification](https://github.com/redhat-developer/odo/blob/main/scripts/release-bit-verification.sh) script is mentioned in the QE release checklist, as part of the QE process to test `odo` release candidates attached as RPMs to the Errata. But it is currently outdated; for example, it is running Make targets that no longer exist.

From my quick analysis of the script, it currently:
- checks the checksums from the RPM
- checks that the version reported by `odo version` is the same as the one recorded in the passed RPM file
-  checks out the `odo` repository at the specified version tag and runs integration and E2E tests using the appropriate `odo` binary (extracted from the passed RPM file)

## Acceptance Criteria
- [ ] Make sure the script errors out immediately if there is an error
- [ ] The release verification script should only run E2E tests
- [ ] To avoid manual (and tedious) work, it should ideally work on all supported Operating Systems (Linux, Windows, Mac)

## Links 
- Related Epic (mandatory): 

/kind user-story

**Comment by valaparthvi** [comment]
@ritudes will you be interested in this issue?

**Comment by ritudes** [comment]
Yeah sure..Thank you for this suggestion @valaparthvi

**Comment by ritudes** [comment]
Current update:
As per my discussion with @rm3l , I am going through the scripts and other sources, trying to understand how to meet the criteria's.
