### ISSUE TITLE
`odo dev --debug --platform=podman --forward-localhost` does not work on arm64 macOS

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/odo#6732]
/kind bug

## What versions of software are you using?

**Operating System: macOS arm64**

**Output of `odo version`: 3.9.0**

## How did you run odo exactly?

```
odo-darwin-amd64 dev --platform=podman --debug --forward-localhost
```

## Actual behavior

Command fails with error

```
 __
 /  \__     Developing using the "new-com1" Devfile
 \__/  \    Platform: podman
 /  \__/    odo version: v3.9.0
 \__/

↪ Running on podman in Dev mode
 ✗  Deploying pod [4s]
Cleaning up resources
 ✗  exit status 125: 
Complete Podman output:
Error: playing YAML file: choosing an image from manifest list docker://quay.io/devfile/base-developer-image@sha256:27d5ce66a259decb84770ea0d1ce8058a806f39dfcfeed8387f9cf2f29e76480: no image found in image index for architecture arm64, variant "v8", OS linux
```

## Expected behavior

Dev started without errors

## Any logs, error output, etc?

M/A

**Comment by kadel** [comment]
We need something to do about this on odo side, expect maybe trying to detect this situation and fail early with nicer error message.

The devfile you are using uses an image not was built for amd64.

I've opened issue to request build of this image for amd64 https://github.com/devfile/api/issues/1102

**Comment by msivasubramaniaan** [comment]
Issue with Windows as well
![image (3)](https://user-images.githubusercontent.com/93245779/234061226-c65b77dc-4c34-4ead-92c9-b9e72e969fcd.png)

**Comment by rm3l** [comment]
> Issue with Windows as well ![image (3)](https://user-images.githubusercontent.com/93245779/234061226-c65b77dc-4c34-4ead-92c9-b9e72e969fcd.png)

@msivasubramaniaan I think your error is different. Can you try again by running `odo dev --debug --platform podman --forward-localhost`?
As depicted in the error message, Podman cannot forward ports to container apps listening on the loopback interface, and this seems to be the case with the debug port (5858) in your "test-podman" project.

**Comment by msivasubramaniaan** [comment]
> > Issue with Windows as well ![image (3)](https://user-images.githubusercontent.com/93245779/234061226-c65b77dc-4c34-4ead-92c9-b9e72e969fcd.png)
> 
> @msivasubramaniaan I think your error is different. Can you try again by running `odo dev --debug --platform podman --forward-localhost`? As depicted in the error message, Podman cannot forward ports to container apps listening on the loopback interface, and this seems to be the case with the debug port (5858) in your "test-podman" project.

Thanks @rm3l post added `--forward-localhost` param, now I can able to run on the Windows

**Comment by rm3l** [comment]
/status blocked
/remove-lifecycle stale

Blocked by https://github.com/devfile/api/issues/1102

**Comment by carlosonunez-redhat** [comment]
This is still an issue in 2026, and how to work around this (especially from Visual Studio Code) isn't clear.
