### ISSUE TITLE
wrong intrepretation of .gitignore file

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#6734]
/kind bug

## What versions of software are you using?

**Operating System:**
MacOS

**Output of `odo version`:**

odo v3.9.0 (431725543)

## How did you run odo exactly?
using pet clinic example
`git clone https://github.com/spring-projects/spring-petclinic`
`cd spring-petclinic`
`odo dev`
open http://localhost:20001/

## Actual behavior
the webpage has no CSS (missing petclinic.css file)

## Expected behavior
not missing CSS styles :-)

## Any logs, error output, etc?

odo ignores petclinic.css, but based on the .gitignore rules in 
https://github.com/spring-projects/spring-petclinic/blob/0962ed7e8f5df8cf287c79975f9894f3189aebab/.gitignore#L17
`petclinic.css` should not be ignored, because of `!petclinic.css` rule which should make `petclinic.css` included even if the previous patter (`*.css`) excluded it (https://git-scm.com/docs/gitignore)

`odo dev -v 4`
```
I0413 09:59:29.893440   87045 util.go:635] ignoring path /Users/tkral/Code/odo-examples/spring-petclinic/src/main/resources/static/resources/css/petclinic.css because of glob rule /Users/tkral/Code/odo-examples/spring-petclinic/*.css
```

It looks like odo has a naive implementation where it treats everything in  .gitignore as a glob pattern

**Comment by feloy** [comment]
The library works correctly, but the check was done in 2 different places on odo side, and the library was used in 1 place only.

The PR #6760 should fix the issue, by using the library in the second place too
