### ISSUE TITLE
Short vs long flags

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#674]
Should we support short, long or both type of flags?

e.g:
- `-p` or `--port`
- `-e` or `--env`

Does it make sense to have equivalents to most of the flags, to the ones most used to all, to none?
Depending on the resolution, we should open issues here to track adding these.

@kadel

**Comment by dgolovin** [comment]
The same idea applies to #683:
* -c or --component 
* -a or --application
* -p or --project

**Comment by surajnarwade** [comment]
short flags might be confusing for the user, 
for example, `-p` is project in some case and port in some case

**Comment by jorgemoralespou** [comment]
@surajnarwade we need to select a list of flags that will be shortified, and stick to these. Not all flags need to have a short version, but for sure the most common ones, as it will improve the user experience, and that is, ultimately the goal for this project.

As an example, we can look into `oc new-app -h` output:
```
 -e, --env=[]: Specify a key-value pair for an environment variable to set into each container.
      --env-file=[]: File containing key-value pairs of environment variables to set into each container.
  -f, --file=[]: Path to a template file to use for the app.
      --grant-install-rights=false: If true, a component that requires access to your account may use your token to
install software into your project. Only grant images you trust the right to run with your token.
      --group=[]: Indicate components that should be grouped together as <comp1>+<comp2>.
      --ignore-unknown-parameters=false: If true, will not stop processing if a provided parameter does not exist in the
template.
      --image=[]: Name of an image stream to use in the app. (deprecated)
  -i, --image-stream=[]: Name of an image stream to use in the app.
      --insecure-registry=false: If true, indicates that the referenced Docker images are on insecure registries and
should bypass certificate checking
  -l, --labels='': Label to set in all resources for this application.
  -L, --list=false: List all local templates and image streams that can be used to create.
      --name='': Set name to use for generated application artifacts
      --no-install=false: Do not attempt to run images that describe themselves as being installable
  -o, --output='': Output results as yaml or json instead of executing, or use name for succint output (resource/name).
```

**Comment by dgolovin** [comment]
@jorgemoralespou @surajnarwade short flags for most often used long ones. In competition between --port and --project, I would say project wins.

**Comment by syamgk** [comment]
it would be nice to implement short flags for most commonly used flags
