### ISSUE TITLE
Add e2e tests on podman

### ISSUE THREAD

**Issue by valaparthvi** [redhat-developer/odo#6742]
/kind user-story

## User Story
As an odo developer I want to add e2e tests for podman So that we can test e2e cases on podman. Now that podman support is stable, it  makes sense to test e2e tests on podman if we don't do it already.

## Acceptance Criteria 
- [ ] It should run all e2e tests against podman
- [ ] Setup these tests for periodic jobs since we do this for cluster (?)
- [ ] Add a Makefile target

## Links 
- Related Epic (mandatory): 

/kind user-story

**Comment by valaparthvi** [comment]
@rm3l This issue still seems relevant. Please reopen if you agree.

**Comment by rm3l** [comment]
> This issue still seems relevant. Please reopen if you agree.

I agree, but not sure we'll have the bandwidth to work on that issue. Anyway, let's keep it open.

/reopen
/remove-lifecycle rotten
/remove-lifecycle stale
