### ISSUE TITLE
Test infra - Develop script / documentation to deploy air-gap cluster on demand

### ISSUE THREAD

**Issue by rnapoles-rh** [redhat-developer/odo#6749]
/kind user-story

## User Story
As a developer or QE I want to deploy air-gap clusters on demand So that I can easily deploy and have them available only when needed 
Can follow the [documented process available for the QE GitOps team](https://spaces.redhat.com/pages/viewpage.action?pageId=124849245). Requires to be adapted for our needs.

## Acceptance Criteria 
- [ ] It should allow to deploy the air-gap in an automated fashion
- [ ] It should have documentation available, describing limitations if any.

/kind user-story

**Comment by rm3l** [comment]
@ritudes to request help from @anandrkskd.

**Comment by ritudes** [comment]
@rnapoles-rh currently working on resolving the issues related to service request.
