### ISSUE TITLE
Keep devfiles in tests/examples/ up-to-date

### ISSUE THREAD

**Issue by feloy** [redhat-developer/odo#6755]
/kind user-story

## User Story
As a test developer I want to have a script that keeps devfiles in the local repository up-to-date So that I can run tests with latest devfiles

## Acceptance Criteria 
- [ ] It should get devfile-registry.yaml from registry
- [ ] It should create derive devfiles by editing the devfile-registry.yaml with some patching tool (yq, etc)

Example: 

```
$ wget https://registry.devfile.io/devfiles/java-springboot/1.2.0 \
  -O tests/examples/source/devfiles/springboot/devfile-registry.yaml

$ yq 'del(.metadata.projectType)' \
  tests/examples/source/devfiles/springboot/devfile-registry.yaml \
  > tests/examples/source/devfiles/springboot/devfile-with-missing-projectType-metadata.yaml
```

## Links 
- Related Epic (mandatory): 

/kind user-story

**Comment by rm3l** [comment]
**Grooming**

- Idea to use the parent-child hierarchy.
  - Use a local parent
