### ISSUE TITLE
`odo deploy` fails with 401 while pushing to container registry

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/odo#6778]
/kind bug

## What versions of software are you using?

**Operating System:**

RHEL 8.7

**Output of `odo version`:**

```
odo v3.9.0 (8cb53c2a0)

Server: https://api.crc.testing:6443
Kubernetes: v1.24.0+3882f8f
```

## How did you run odo exactly?

```
crc start # I made sure that crc started properly
odo login -u developer -p developer
git clone https://github.com/devfile-samples/devfile-sample-go-basic
cd devfile-sample-go-basic
odo deploy
```

You can also reproduce this bug with version 3.0.0 of the python+flask devfile and starter code

## Actual behavior

The component is not deployed to OpenShift, and `odo` displays the following output:

```
❯ odo deploy
  __
 /  \__     Running the application in Deploy mode using go Devfile
 \__/  \    Namespace: my-test-project-1
 /  \__/    odo version: v3.9.0
 \__/

↪ Building & Pushing Image: go-image:latest
 •  Building image locally  ...
STEP 1/7: FROM registry.access.redhat.com/ubi9/go-toolset:1.18.9-14
STEP 2/7: COPY . .
--> 6b04abfcc74
STEP 3/7: RUN go mod download
go: no module dependencies to download
--> 4394cddaeaf
STEP 4/7: RUN go build -o ./main
--> 415d97bde34
STEP 5/7: ENV PORT 8081
--> ff5f1bf845f
STEP 6/7: EXPOSE 8081
--> cb6bf788651
STEP 7/7: CMD [ "./main" ]
COMMIT go-image:latest
--> 62cbfab7488
Successfully tagged localhost/go-image:latest
62cbfab7488bcb420404a7be564bb9a41dd2550c027e00fc9ca7037ae98cd193
 ✓  Building image locally [4s]
 •  Pushing image to container registry  ...
Getting image source signatures
Error: trying to reuse blob sha256:314640f419c581ddcac8f3618af39342a4571d5dc7a4e1f5b64d60f37e630b49 at destination: checking whether a blob sha256:314640f419c581ddcac8f3618af39342a4571d5dc7a4e1f5b64d60f37e630b49 exists in docker.io/library/go-image: errors:
denied: requested access to the resource is denied
error parsing HTTP 401 response body: unexpected end of JSON input: ""

 ✗  Pushing image to container registry [507ms]
 ✗  error running podman command: exit status 125
```

## Expected behavior

The component is deployed to OpenShift and `odo` reports no errors

**Comment by rm3l** [comment]
Hi @datho7561, thanks for reporting this issue!

Indeed, `odo` currently tries to build and push image names as they are defined in the Devfile.

But we are working on #6565, with the end goal of handling image names as selectors by dynamically pushing images to user-defined registries without changing the Devfile.
We have a work-in-progress PR (#6768) implementing this feature.

I think this is the exact problem that could be addressed with this.

Can you please try using `odo` from this PR (#6768) and let us know your thoughts? Once you build `odo` from this PR, you'll need to first set an image registry in the `odo` settings to use this feature, e.g.: `odo preference set ImageRegistry "registry.example.com/$USER"`

Thanks.

**Comment by rm3l** [comment]
The troubleshooting guide on [odo.dev](https://odo.dev/) now contains a dedicated section about that kind of issues: https://odo.dev/docs/troubleshooting#odo-deploy-is-failing-to-push-container-image-components-due-to-401-errors

So closing this issue as done.

/close
