### ISSUE TITLE
`odo preference set ConsentTelemetry false` event not send to telemetry

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#6790]
/kind bug

## How did you run odo exactly?

with enabled telemetry 
```
▶ odo preference view
Preference parameters:
 PARAMETER           VALUE
 ConsentTelemetry    true
 Ephemeral
 PushTimeout
 RegistryCacheTime
 Timeout
 UpdateNotification

Devfile registries:
 NAME                    URL                          SECURE
 DefaultDevfileRegistry  https://registry.devfile.io  No
```

I've executed
```
▶ odo preference set ConsentTelemetry false
? consenttelemetry is already set. Do you want to override it in the config Yes
 ✓  Value of 'consenttelemetry' preference was set to 'false'
```

but I don't see `odo preference set` event in the telemetry

## Expected behavior
At the time of executing `odo preference set` command the telemetry was enabled so I should see that even being recorded

**Comment by feloy** [comment]
The other way, when telemetry is not active, and user executes `odo preference set ConsentTelemetry true`, telemetry must be sent.

To sum up, telemetry must be sent every time user changes the telemetry preference.
