### ISSUE TITLE
Filtering devfile stacks based on the architecture field in metadata when running odo init

### ISSUE THREAD

**Issue by feloy** [redhat-developer/odo#6803]
## User Story
- As an odo user using a cluster running on IBM Z
- I want `odo init` Stack selection to list only stacks supporting IBM Z
- So that I don't create a component that uses devfile that won't work on my cluster.

Parent user-story: #6669

## Acceptance Criteria
- [ ] Stacks without any architectures in the index are compatible with **all** of them
- [ ] odo init interactive mode should ask for architectures (multi-choice) before to ask to select a Devfile stack
- [ ] x86 architecture is checked by default
- [ ] make it work with `index` and `v2index`
- [ ] Possibly add human readable architecture names for the user selection
- [ ] On flag mode, add a flag --architecture=x64 --architecture=ppc64le. Default value: amd64 (to be sure it works for amd64 users)
Get available values at https://github.com/devfile/api/blob/main/pkg/devfile/header.go#L24-L29 to display it on help/output mesg, and error out if passed value not in the list

- No automatic 
- In Alizer mode, display the architectures supported by the chosen Devfile, so the user can reply No and select manually a new one 
- 
registry-library documentation on how to filter based on architecture https://github.com/devfile/registry-support/tree/main/registry-library#specify-registry-options

/kind user-story
/priority high

**Comment by rm3l** [comment]
**Grooming (Jul 6, 2023)**

- List of architectures built using constants from the library
- Unit tests only
