### ISSUE TITLE
Infra ansible scripts

### ISSUE THREAD

**Issue by feloy** [redhat-developer/odo#6813]
/kind bug

Issues I have noticed after ansible scripts to deploy test Infra have been merged:

- the `infra-test.yaml` workflow runs for every PR. It should run only if files into `scripts/ansible` are modified
- the `infra-apply.yaml` workflow is not running when a PR is merged into main.

**Comment by rm3l** [comment]
> the infra-test.yaml workflow runs for every PR. It should run only if files into scripts/ansible are modified

There is also one thing I noticed while quickly creating #6823 : the workflow in `infra-test.yaml` makes use of GitHub Repository Secrets. For security reasons, GitHub will not inject secrets to PRs created from forks. So this workflow will actually never pass if a PR is created from a fork with changes in `scripts/ansible`.
