### ISSUE TITLE
Clarify whether Java is a supported language

### ISSUE THREAD

**Issue by gunnarmorling** [redhat-developer/odo#686]
From the README.md:

> Multiple languages: Odo supports Node.JS, Ruby, .Net Core, Perl, PHP and Python.

Is it true, that Java isn't supported by odo? If it actually is, it should be added to the list of supported languages, given our huge portfolio of Java-based middleware software (WildFly/EAP, Vert.x, ...).

**Comment by cdrage** [comment]
@gunnarmorling You're right. We should add Java but in quotations / brackets add that it supports Wildfly,EAP, etc.)

**Comment by cmoulliard** [comment]
Why is the commit not yet merged on master ?
