### ISSUE TITLE
Support templates workflow in odo

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/odo#6867]
/kind feature

## Which functionality do you think we should add?

 Odo should provide a template-based workflow for users to get started with application development on OpenShift.

## Why is this needed?

Odo templates are sample repositories created using the Odo Developer CLI conventions so that you can use Odo. The odo templates extend beyond simple "Hello World!" to provision OpenShift resources, configure environment variables, define outer loop workflows and more. These templates serve as the foundation from which users can build and customize their own solutions. Each template includes:

- Application code
- Defined `devfile.yaml` needed to provision the OpenShift/K8s resources
- `devfile.yaml` file that describes the application configuration

Users have the flexibility to extend and customize these templates according to their specific requirements.

Sample Templates:
- Front End app with a MongoDB database connected
- Python app with MySQL db running on OpenShift
- React App with nodejs backend and database connected

Links:
- RHDP-646

**Comment by rm3l** [comment]
**Team discussion (Jun 20, 2023)**

- is this targeting only OpenShift users? If yes, we'll need to look into how to provision services via OpenShift Catalog for example..
- There seems to be no consensus yet as to how Devfile should be used with more complex applications. First starting point to clarify this: what are the recommended/best practices for structuring projects with Devfiles (projects, dependentProjects as proposed in https://github.com/devfile/api/issues/1082, ...)? Especially when the application is made up of several microservices. => Issue to raise in the Devfile community calls.
