### ISSUE TITLE
Why do we suggest/propose to be logged ?

### ISSUE THREAD

**Issue by cmoulliard** [redhat-developer/odo#690]
Why the command `odo version` suggest/propose to be logged ? 
Is it because you would like ti display additional info ? If this is not the case, then remove the message `Please log in to the cluster`

```
odo v0.0.10 (1e7221f4)
Please log in to the cluster
```

**Comment by cdrage** [comment]
Yeah, this is an error. If you use --skip-connection-check it won't show it, but we should *not* be checking / doing anything with the cluster with simply using `odo version`.

**Comment by syamgk** [comment]
while running `odo version --skip-connection-check` without internet connection it is returning the below pasted log  instead it should output `Unable to connect to openshift cluster` i guess
```sh
$ odo version --skip-connection-check
odo v0.0.12 (HEAD)
Get https://devtools-dev.ext.devshift.net:8443/version/openshift: dial tcp: lookup devtools-dev.ext.devshift.net on [::1]:53: read udp [::1]:57695->[::1]:53: read: connection refused
```
