### ISSUE TITLE
`odo init` non-interactive mode: Allow specifying ports when Devfile has at most one container component

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#6919]
/kind user-story

## User Story
As an odo user, I want to be able to set the ports when calling `odo init` non-interactively So that I can have my Devfile initialized right away with the right ports without having to edit it later on.

#5863 added the ability to automatically detect my application ports from the source code and use that as ports when initializing a Devfile interactively, but as a user, I also want to be able to specify such port(s) non-interactively.
This is useful to support the port detection feature in the IDE extensions as well (https://github.com/redhat-developer/vscode-openshift-tools/issues/2781).

As discussed in https://github.com/redhat-developer/odo/issues/6211#issuecomment-1293075852, there might be issues with Devfiles that have more than one container components, but this issue will be addressed in https://github.com/redhat-developer/odo/issues/6264.

The goal of this issue is to handle the case where the Devfile has only one container component, which should cover most of the Devfile stacks in the default registry.

## Acceptance Criteria 
- ~[ ] odo init shoudl have paramersts to allow overriding ports in the devfile~
- ~[ ] to know in which container the port shoudl be added odo init should take an optional argument `command-name`~
- [ ] It should expose a **repeatable** `--port` flag, which would allow users to specify several ports
- [ ] It should error out if the Devfile has more than one container components
- [ ] It should ignore the ports definition if the Devfile does not have any container component
- [ ] It should overwrite the endpoints definition with the ones coming from the `--port` flag
  - **[Q] what to do with any `debug` or `debug-*` ports?** 

## Links 
- Related Epic (mandatory): 
- Feature request: #4448
- Related issue: https://github.com/redhat-developer/odo/issues/6264

/kind user-story

**Comment by kadel** [comment]
/duplicate
https://github.com/redhat-developer/odo/issues/4448

**Comment by rm3l** [comment]
After a discussion with Tomas, re-opened the issue and scoped it to handling only the single container component scenario.
The multi-container components scenario will be addressed in https://github.com/redhat-developer/odo/issues/6264

**Comment by rm3l** [comment]
**Grooming (2023-06-22)**

Closed in favor of https://github.com/redhat-developer/odo/issues/6925
