### ISSUE TITLE
[Epic] Provide api endpoints for odo (Phase 2)

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#6990]
- [ ] #7083
- [x] https://github.com/redhat-developer/odo/issues/6984

**Comment by datho7561** [comment]
Here is a list of all the `odo` commands we use in vscode-openshift-tools:
- `odo deploy`
- `odo delete component`
- `odo dev`
- `odo dev --debug`
- `odo dev --debug --platform podman --forward localhost`
- `odo list project -o json`
- `odo delete namespace -f -w`
- `odo create namespace -w`
- `odo preference view -o json`
- `odo preference add registry $NAME $URL`
- `odo registry -o json`
- `odo list service --namespace $NAMESPACE -o json`
- `odo version`
- `odo version -o json`
- `odo logout`
- `odo describe component`
- `odo describe component -o json`
- `odo registry --details --devfile $DEVFILE_NAME --devfile-registry $DEVFILE_REGISTRY-NAME -o json`
- `odo logs --dev`
- `odo logs --dev --platform podman`
- `odo logs --dev --follow`
- `odo logs --dev --follow --platform podman`
- `odo analyze -o json`
- `odo set namespace $NAMESPACE`
- `odo delete component --files -f`
- `odo add binding --service-namespace $SERVICE_NAMESPACE --service $SERVICE_NAME --name $BINDING_NAME`
- `odo init --name $NAME --devfile $DEVFILE_NAME --devfile-registry $DEVFILE_REGISTRY --starter $STARTER_PROJECT`

**Comment by kadel** [comment]
closing this in favor of https://github.com/redhat-developer/odo/issues/7083 that will be used to track extensions portion of this task

/close
