### ISSUE TITLE
`.odo/devstate.*` files with a non-odo pid should not block running `odo dev`

### ISSUE THREAD

**Issue by rm3l** [redhat-developer/odo#6994]
If `odo dev` did not get the chance to reset its state files (e.g., it was abruptly killed or not stopped properly) and the OS assigned the previous PID (stored in `.odo/devstate.*`) to another process, `odo dev` will never be able to start again on the same platform (unless the user manually deletes those state files). As discussed in https://github.com/redhat-developer/odo/discussions/6958, this happened sporadically on Windows.

The goal of this issue is to make `odo delete component` also remove those state files. This would be provided as an option to users for starting over when facing similar issues.
And this would also fix https://github.com/redhat-developer/odo/issues/6534

`odo dev` should also ignore a devstate file pointing to a non-odo process.

We already have a `--files` flag for `odo delete component` which deletes the `.odo` folder, but might also delete the Devfile if it was originally created by `odo`.

## Acceptance Criteria
- [ ] `odo dev` should ignore a devstate file when its pid is not an odo process
- [ ] `odo delete component` and `odo delete component --running-in dev` should remove the state files
- [ ] `odo delete component --running-in deploy` should not remove the state files
- [ ] Add this to the Troubleshooting page: https://odo.dev/docs/troubleshooting

---
### Discussed in https://github.com/redhat-developer/odo/discussions/6958

<div type='discussions-op-text'>

<sup>Originally posted by **jochenr** July  7, 2023</sup>
Hello, 

using odo (from vscode's openshift tooling) I sporadically/very often get this error:

Starting odo dev --debug
  __
 /  \__     Developing using the "quarkus-camel-xxx" Devfile
 \__/  \    Namespace: xxx-dev
 /  \__/    odo version: v3.11.0
 \__/

- Running on the cluster in Dev mode
 X  unable to save state file: a session with PID 25992 is already running on platform "cluster"

Press any key to close this terminal

Environment is
  Openshift local 
  CRC version: 2.20.0+f3a947
  OpenShift version: 4.13.0

running on Windows 10

I am not able to finde the cause of the problem.

I'd appreciate some help.

Thank you,
Jochen</div>

/kind task
/area dev

**Comment by feloy** [comment]
When a session is running, do we want:
- to stop the session and delete the devstate file?
- to skip the deletion of the associated devstate file?

**Comment by michael-valdron** [comment]
More information needed, waiting for next cabal call

**Comment by feloy** [comment]
> 

Stop it, to be sure we are restarting from scratch

We need to find a way to be sure a process with a given pid is really an odo process
