### ISSUE TITLE
Link to Inner Loop Document in Introduction section seems to be broken

### ISSUE THREAD

**Issue by yash2189** [redhat-developer/odo#7026]
/area documentation

Add one of the following kinds:
/kind bug

## What mistake did you find / what is missing in the documentation?
The introduction section has a description containing 'what is odo?' wherein there is a reference for **[inner loop](https://odo.dev/docs/introduction/#:~:text=odo%20is%20focused%20on%20inner%20loop%20development%20as%20well%20as%20tooling%20that%20would%20help%20users%20transition%20to%20the%20outer%20loop.)** development which seems to have a broken link

## What is the relevance of it?
Please refer the screenshot: 
![image](https://github.com/redhat-developer/odo/assets/31548778/40fc619b-1fcd-4305-bebd-19bbc9cafde3)

**Comment by feloy** [comment]
Thanks for raising the issue.

Note for devs: Absolute paths should be used for links, to avoid this kind of error.

**Comment by yash2189** [comment]
hello @feloy I would like to contribute to this issue if it is up for grabs?

**Comment by rm3l** [comment]
> I would like to contribute to this issue if it is up for grabs?

Hi @yash2189,
Sure, contributions are more than welcome.
Thanks.

/assign @yash2189

**Comment by rm3l** [comment]
Fixed with https://github.com/redhat-developer/odo/commit/97adb91567cc324a8b966bfb725576ad08b54f35
