### ISSUE TITLE
Test_getLatestReleaseTage fails on Travis

### ISSUE THREAD

**Issue by mik-dass** [redhat-developer/odo#704]
It seems to occur quite frequently
```
--- FAIL: Test_getLatestReleaseTag (1.36s)
	notify_test.go:18: error getting latest release TagName via API
```

**Comment by surajnarwade** [comment]
@syamgk , you didn't handle error here:
https://github.com/redhat-developer/odo/blob/master/pkg/notify/notify_test.go#L34

**Comment by surajnarwade** [comment]
problem: you are using `"github.com/google/go-github/github"` in unit test and travis environment don't have that.
Ideally we should get rid of `go-github` :smiling_imp:

**Comment by mik-dass** [comment]
This is the problem 
```
--- FAIL: Test_getLatestReleaseTag (0.76s)
	notify_test.go:18: error getting latest release TagName via API, error: GET https://api.github.com/repos/redhat-developer/odo/releases/latest: 403 API rate limit exceeded for 35.184.96.71. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 19m23s]
```
We need to remove the GitHub call

**Comment by mik-dass** [comment]
@ashetty1 Please have a look

**Comment by syamgk** [comment]
the problem is limits as mrinal said, i think Its better to hardcode the releaseTag

**Comment by cdrage** [comment]
@syamgk @mik-dass @surajnarwade 

I've removed the unit test since it's hitting the API limit, we will have to re-work this. PR was here: https://github.com/redhat-developer/odo/pull/710
