### ISSUE TITLE
Recognise `devfile.yml` and `.devfile.yml` as Devfiles

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/odo#7060]
/kind bug

## What versions of software are you using?

**Operating System:**
Fedora Linux 38

**Output of `odo version`:**
```
odo v3.14.0 (471928fea)

Server: https://api.crc.testing:6443
Kubernetes: v1.26.6+73ac561
Podman Client: 4.6.1
```

## How did you run odo exactly?
1. Clone https://github.com/eclipse/lemminx.
2. Add the recommended Devfile, which was the Maven one.
3. Rename the Devfile to `devfile.yml`
4. `odo dev`

## Actual behavior
odo starts initializing a new component in interactive mode

## Expected behavior
Dev mode starts, using `devfile.yml` as the Devfile.

## Any logs, error output, etc?

See https://github.com/redhat-developer/vscode-openshift-tools/issues/3124

**Comment by rm3l** [comment]
/status blocked

Blocked on https://github.com/devfile/api/issues/1035, to clarify the acceptable filenames for devfile.
https://github.com/devfile/api/issues/1035#issuecomment-1433139995 suggested supporting `.yaml` only, based on the [YAML spec FAQ](https://yaml.org/faq.html).
We'll need to confirm the decision on this..

**Comment by rm3l** [comment]
/remove-status blocked

Unblocked now that https://github.com/devfile/api/issues/1265 and https://github.com/devfile/api/issues/744 have been fixed on the Devfile parser library side.
The changes in the Devfile library have been pulled in https://github.com/redhat-developer/odo/pull/7130.
