### ISSUE TITLE
API: collect requirements from OpenShift VSCode extension

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#7083]
Work with OpenShift VSCode extension team and create a list of API endpoints that would help extension, sorted by how much it would help extension steam lighting code or speeding up operations

list of commands used by extension - https://github.com/redhat-developer/odo/issues/6990#issuecomment-1660601740

**Comment by feloy** [comment]
We are waiting for input from plugin developers to know which endpoint to start with, first

**Comment by datho7561** [comment]
Just tested stopping `odo dev` on Windows. It works fine. If this was the main motivation for exposing a Web API, then I don't think this is needed anymore.

**Comment by rm3l** [comment]
> Just tested stopping `odo dev` on Windows. It works fine. If this was the main motivation for exposing a Web API, then I don't think this is needed anymore.

Thanks! I guess this issue can be closed then. Feel free to reopen if you think otherwise.

/close
