### ISSUE TITLE
License headers

### ISSUE THREAD

**Issue by feloy** [redhat-developer/odo#7085]
/kind user-story

To follow the discussion initiated during Devtools Week, do we want to include license headers in source files?

@kadel @rm3l

**Comment by rm3l** [comment]
> /kind user-story
> 
> To follow the discussion initiated during Devtools Week, do we want to include license headers in source files?
> 

Seems like this is something recommended by Red Hat Legal team. I just searched and found an article title `Copyright Notices for Open Source Projects` on The Source:

**"We now recommend that all original source files in Red Hat-maintained open source projects have a header comment containing a copyright notice followed by a license notice."**

So yes, to me, we should include those headers; and I guess a way to enforce their presence in CI.
Also, I guess we will need to ignore generated code.

**Comment by rm3l** [comment]
Not needed, per the Legal team.
