### ISSUE TITLE
Port the frontend to React, so it can be used as a Backstage plugin, and integrated into other React-based frontends

### ISSUE THREAD

**Issue by feloy** [redhat-developer/odo#7106]
A port of the Devfile Builder is available at:
https://github.com/feloy/devfile-builder-react

- It is compatible with te API served by `odo dev`, and can be used to replace the UI served by `odo dev`.

- It is compatible with the React version used by Backstage, and can be integrated into a Backstage plugin, using the backend from `odo dev` for now (see demo - TODO)

- It should be possible to integrate it in any other frontend using React (to be tested)

**Comment by rm3l** [comment]
/close

Most of the work done in https://github.com/feloy/devfile-builder-react and a demo of it integrated into Backstage has been presented.

The remaining work will be addressed in a separate issue if needed to continue this:
- [ ] Save action
- [ ] Simpler integration with Backstage: need to publish and consume a proper Backstage frontend plugin
