### ISSUE TITLE
Documentation and testing .jar Java files

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#711]
From: https://gist.github.com/cmoulliard/46b5651eb23ae831f74307be5df2ca9c#gistcomment-2699876

As well as PR #622 

@cmoulliard and I discovered that not only do we NOT test for `.jar` files, but we do not have any sort of documentation either for it.

**Comment by cmoulliard** [comment]
Test case can be designed using this project : https://github.com/snowdrop/ocp-odo-build-install

Remark : This project uses git as source and don't push binary uber jar file !

**Comment by cdrage** [comment]
@kadel Yeah, let's close this.
