### ISSUE TITLE
Symlinks to latest odo binary on mirror.openshift are pointing to older version

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/odo#7120]
/kind bug

## Actual behavior

Symlinks to Odo binary on the [mirror.openshift latest](https://mirror.openshift.com/pub/openshift-v4/clients/odo/latest/) point to older version 3.10.0.

E.g. https://developers.redhat.com/content-gateway/file/pub/openshift-v4/clients/odo/v3.10.0/odo-darwin-arm64.tar.gz.sha256

## Expected behavior

These links should point to the latest odo release 3.15.0

**Comment by rm3l** [comment]
/area release-eng

Issue reported to the release team - waiting for a response..

**Comment by rm3l** [comment]
/status blocked

Issue reported internally: CLOUDDST-20681

**Comment by rm3l** [comment]
Issue fixed on the Content Gateway side.

/close
