### ISSUE TITLE
odo telemetry prompt can interfere with bash commands

### ISSUE THREAD

**Issue by amisevsk** [redhat-developer/odo#7145]
/kind bug

## What versions of software are you using?

**Operating System:** Linux

**Output of `odo version`:** `odo v3.15.0 (10b5e8a8f)`

## How did you run odo exactly?
With the goal of getting the current `odo` version:
```
odo version --client | grep -Eo 'v?[0-9]+\.[0-9]+\.[0-9]+'
```
(on first run, before seeing telemetry prompt)

## Actual behavior
The command hangs indefinitely and cannot be cancelled (i.e. ctrl+c does not work).

## Expected behavior
Either `odo` should prompt for telemetry on stderr (instead of stdout) so that users see the prompt in these cases, or it should avoid prompting when output is redirected to a file/pipe. 

## Any logs, error output, etc?
Can be reproduced with the following Dockerfile
```Dockerfile
FROM registry.access.redhat.com/ubi8-minimal:8.8-860

RUN microdnf install -y curl \
    && curl -L https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/odo/v3.15.0/odo-linux-amd64 -o /usr/local/bin/odo \
    && chmod a+x /usr/local/bin/odo \
    && microdnf -y clean all

RUN echo -e '#!/bin/bash \n\
             odo version --client | grep -Eo "v?[0-9]+\.[0-9]+\.[0-9]+" \n\
             exec "$@"' > /entrypoint.sh \
    && chmod a+x /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]
```
If I build an image from this Dockerfile, then
* If I run `podman run <image>` it prints `odo`'s version
* If I run `podman run -it --rm <image> /bin/bash`, it hangs indefinitely and must be `podman kill`ed

## More background
The [Web Terminal Operator](https://github.com/redhat-developer/web-terminal-operator/) includes `odo` as part of its built-in tooling. In order to be able to list the software and versions installed, the web-terminal-tooling container generates a "installed-versions.txt" file at startup using the above command, which can hang if e.g. it is run from an interactive prompt.

As a workaround, we just close `stdin` before calling the script, which avoids the issue.

**Comment by rm3l** [comment]
/area telemetry
/remove-status needs-triage

Hi @amisevsk,

Thanks for reporting this issue.

While I agree it makes sense for `odo` to avoid prompting when the output is piped or redirected to a file, I'd like to suggest two more things:
- It is possible to disable the consent prompt via the `ODO_TRACKING_CONSENT` environment variable. See https://odo.dev/docs/overview/configure#environment-variables-controlling-odo-behavior
- Most of the `odo` commands expose a JSON output to make it easier for other programs to consume the output; so I think using [`odo version --client -o json`](https://odo.dev/docs/command-reference/json-output#odo-version--o-json) might be simpler to use. However, I guess that would still prompt for telemetry consent. So using the `ODO_TRACKING_CONSENT` would still be needed.

Would that work for you?
