### ISSUE TITLE
Add instructions on how to use monkey unit testing in unit testing doc

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#717]
See: https://github.com/redhat-developer/odo/pull/648#discussion_r216370162

We should add instructions on how to also use monkey within unit testing / occlient.go tests!

Ping @anmolbabu

**Comment by surajnarwade** [comment]
we should close this issue since license of monkey :monkey:  don't allow us to use it.

**Comment by anmolbabu** [comment]
Closing this due to licensing compatibility issues with monkey library
