### ISSUE TITLE
Make ocdev version also get OpenShift version

### ISSUE THREAD

**Issue by containscafeine** [redhat-developer/odo#72]
When we run `ocdev version`, it should also get the version of OpenShift client and server.
Will help in troubleshooting and determining if it's being used with the compatible versions or not.

**Comment by kadel** [comment]
Does this issue still make sense if we are moving away from using `oc` binary?

**Comment by containscafeine** [comment]
I think adding the server version makes sense, the client version does not. Instead of the client version, we can print the client's API version which client-go can(should) provide us. But yes, this should be implemented using client-go and not `oc` binary

**Comment by kadel** [comment]
closed in #366
