### ISSUE TITLE
Add the possibility to indicate the devfile `odo dev -f devfile-redis.yaml`

### ISSUE THREAD

**Issue by batleforc** [redhat-developer/odo#7212]
/kind feature

## Which functionality do you think we should add?

The possibility to indicate in the CLI which DevFile to use with a cli like `odo dev -f devfile-redis.yaml`

## Why is this needed?

I would like to have multiple DevFile depending on which case I'm working with. ATM I'm working with Eclipse Che and ODO depending if I work with my own computer or if I need to work on the go. Due to this, I tend to have multiple DevFile (like 5 or 6) that are cut for different use case. I would like to have an arg that let me select the DevFile to use like `odo dev -f devfile-redis.yaml`. That would allow me to launch my env with a redis cluster and not my default DevFile who only include a single redis node and a huge container including all I need to work.

**Comment by rm3l** [comment]
Thanks for this request, @batleforc. This seems quite similar to the user story depicted in https://github.com/redhat-developer/odo/issues/6600

/triage duplicate

**Comment by batleforc** [comment]
Thak's @rm3l, do I close my issue ? i will watch closely the other issue

**Comment by rm3l** [comment]
> Thank @rm3l, do I close my issue ? i will watch closely the other issue

Closing in favor of https://github.com/redhat-developer/odo/issues/6600

/close not-planned
/triage duplicate
