### ISSUE TITLE
ODO Nightly Build binary archive content changes due to repeated builds?

### ISSUE THREAD

**Issue by vrubezhny** [redhat-developer/odo#7256]
/kind bug

Due to the repeatedly executed Nightly Build GH Action for the same commit ID the resulting nightly build archive content for a given platform and arch might be different from one day to another. 

For instance, the ODO binary downloaded from `https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-nightly-builds/odo-linux-amd64-082e3071d.tar.gz` 
- on 29 June 2024 had `28ce2f28a1932290677f2646202d120c5b67cc5f822ee0c10a07ef6cdf33fa32` sha256 checksum 
- on 1 July 2024 (now) it has `cdca2480315c14ce383d2d91533c944886edd2897e5af1fe16d47f6ee7a33bdd` sha256 checksum.
UPD:
- on 2nd July 2024, the same archive has `b02ca3fab8fadc111cf14becc1718468d42a56c094225c543988b061454686ca` sha256 checksum.

This prevents us from possibility to verify the authenticity of the nightly build archive when it's used to install the ODO binary a day after the first nightly build created for the latest commit ID.  

## What versions of software are you using?

**Operating System:**

ANY of included to the build matrix

**Output of `odo version`:**

```
odo v3.16.1 (082e3071d-nightly)

Server: https://127.0.0.1:42801
Kubernetes: v1.27.3
Podman Client: 5.1.1
```

## How did you run odo exactly?

```
./odo-linux-amd64-082e3071d version
```

## Actual behavior

The same version of archives built for the latest commit ID and loaded to https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-nightly-builds/ might have different sha256 checksum due to the repeated run of Nightly Build GH Action for the same commit ID.

## Expected behavior

A nightly build archive build for the same commit ID for a specific platform/arch has the same sha256  whenever we try downloading the archive.
  
## Any logs, error output, etc?

None.

**Comment by rm3l** [comment]
@vrubezhny Thanks for reporting this issue. https://github.com/redhat-developer/odo/commit/230d4377202ffd00f9e27362eb63ddc5316aa462 should help here, by not building a new binary for the latest commit if there is a binary uploaded for that commit.
You can see 2 consecutive runs of the Nightly jobs here on the latest commit:
- https://github.com/redhat-developer/odo/actions/runs/9779092583 would upload all the binaries
- https://github.com/redhat-developer/odo/actions/runs/9779142460 would not overwrite the binaries for that commit

Hope that helps.
