### ISSUE TITLE
e2e tests are failing in CI because of an issue in  `bootstrap-supervisored-s2i`

### ISSUE THREAD

**Issue by syamgk** [redhat-developer/odo#731]
`odo create php testcmp` is failing on CI due to the unavailability of [https://bootstrap.pypa.io/get-pip.py](https://bootstrap.pypa.io/get-pip.py) which is needed by a script in `bootstrap-supervisored-s2i`
here: https://github.com/kadel/bootstrap-supervisored-s2i/blob/master/.s2i/bin/assemble#L21

https://travis-ci.org/redhat-developer/odo/jobs/427997408#L724

**Comment by syamgk** [comment]
upstream issue: https://github.com/pypa/get-pip/issues/34

**Comment by piyush1594** [comment]
@syamgk The upstream issue has been closed, I think we are good to close this.

**Comment by syamgk** [comment]
@piyush1594 yes this got resolved, so closing the issue
