### ISSUE TITLE
odo fails when `~/.kube/` directory doesn't exist

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#738]
```
▶ odo version
unable to fetch configuration from Odo config file.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1c30b54]

goroutine 1 [running]:
github.com/redhat-developer/odo/pkg/config.(*ConfigInfo).GetUpdateNotification(...)
	/Users/tomas/Code/goenv/odo/src/github.com/redhat-developer/odo/pkg/config/config.go:142
github.com/redhat-developer/odo/cmd.Execute()
	/Users/tomas/Code/goenv/odo/src/github.com/redhat-developer/odo/cmd/root.go:109 +0x44
main.main()
	/Users/tomas/Code/goenv/odo/src/github.com/redhat-developer/odo/main.go:6 +0x20
```

The same happens when you set `ODOCONFIG` to a path where there is a non-existing directory
```
ODOCONFIG=/tmp/nonexisting/config odo version
```

We should make sure that odo creates non-existing directories for config.

While I was debugging this error I found out that if [config.New() in config.go](https://github.com/redhat-developer/odo/blob/0764b574d496419bf0f48b2cfde01d345078c42a/cmd/root.go#L105) fails we just print error and continue after that like nothing happened :-(  [checkErrror](https://github.com/redhat-developer/odo/blob/0764b574d496419bf0f48b2cfde01d345078c42a/cmd/root.go#L170) should be used there checkError

**Comment by mik-dass** [comment]
@kadel I think we can close this
