### ISSUE TITLE
Watch command fails for component created using local source

### ISSUE THREAD

**Issue by anmolbabu** [redhat-developer/odo#746]
User should be able to watch component created using local source and binary.
However, due to a regression [here](https://github.com/redhat-developer/odo/pull/713/files#r218104675), watch for local source is not working and errors out as under

```
▶ odo watch
Watch is supported by binary and local components only and source type of component nodejs is local
```

**Comment by kadel** [comment]
@anmolbabu When you are reporting an issue like this please add a bit more info, like an error message that you are getting etc...
It makes it easier to find etc..

**Comment by kadel** [comment]
You get the following error even if the component is local

```
▶ odo watch
Watch is supported by binary and local components only and source type of component nodejs is local
```


Watch command is not working because of this
https://github.com/redhat-developer/odo/pull/713/files#r218104675

**Comment by anmolbabu** [comment]
> @anmolbabu When you are reporting an issue like this please add a bit more info, like an error message that you are getting etc...
> It makes it easier to find etc..

Ack .. will follow this hereafter
