### ISSUE TITLE
add proper documentation

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#75]
Documentation
We should be providing documentation for installing ocdev to cover:

- [x] Pre-requisities
- [x] Download and Installing: MacOS, Windows, Linux
- [ ] Verify your installation
- [x] Getting started - @containscafeine
- [ ] Update ocdevcli
- [ ] Troubleshooting
- [ ] Uninstallation

parent issue: #70

**Comment by kadel** [comment]
Pre-requisites and Installation docs in https://github.com/redhat-developer/ocdev/pull/93

**Comment by containscafeine** [comment]
I'm getting started with the getting started doc :P

**Comment by cdrage** [comment]
I'm 99% sure we have all the relevant docs now for someone to bring up a cluster as well as use Odo on it :) I'm closing this for now and if we need anything else let's revisit this in the future!
