### ISSUE TITLE
Watch is not working!!

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#751]
You get the following error even if the component is local

```
▶ odo watch
Watch is supported by binary and local components only and source type of component nodejs is local
```

Watch command is not working because of this
https://github.com/redhat-developer/odo/pull/713/files#r218104675

**Comment by anmolbabu** [comment]
@kadel I think this is duplicate of https://github.com/redhat-developer/odo/issues/746

**Comment by kadel** [comment]
Closing as duplicate of #746
