### ISSUE TITLE
What do we want to express with the link command

### ISSUE THREAD

**Issue by cmoulliard** [redhat-developer/odo#760]
What do we want to express with the link command ? 

As k8s already injects into a pod created, the service's information of the services available in a namespace as ENV var

```
sh-4.2$ env | grep ROUTER_SERVICE
ROUTER_SERVICE_PORT_1936_TCP=1936
ROUTER_SERVICE_PORT_80_TCP=80
ROUTER_SERVICE_PORT=80
ROUTER_SERVICE_HOST=172.30.147.81
ROUTER_SERVICE_PORT_443_TCP=443
```

what could be then the added value to add [new ENV vars ](https://goo.gl/j2x76j) ? 

1) To standardize the naming to access the different services part of a namespace and belonging to an odo's project
2) To standardize but also facilitate service's search (query/filter,....) as they will start by convention with `COMPONENT_` prefix followed by the `NAME_OF_THE_COMPONENT` and `PORT/HOST`

Question : 

As the Service IP address can change when we restart the Openshift Cluster, will then the ENV vars of the links been recalculated and updated ? As I don't think that Service IP changes between node restart, then this question is irrelevant

**Comment by kadel** [comment]
> As k8s already injects into a pod created, the service's information of the services available in a namespace as ENV var

problem with this is that it works is Service was created before Pod.

If you create Service first, and then Pod you won't get those env vars.

> As the Service IP address can change when we restart the Openshift Cluster, will then the ENV vars of the links been recalculated and updated ? As I don't think that Service IP changes between node restart, then this question is irrelevant

The link should point to the Service name using internal dns name not ip

**Comment by jorgemoralespou** [comment]
This should come from the primitive that Service Catalog needs to provide for service injection. This is a problem already in OpenShift that most likely they are trying to solve.

@sspeiche Can you hook anyone working on service catalog for them to update us on what's the state of the art around linking?

**Comment by cmoulliard** [comment]
> service injection

Even if a service injection is offered, env var should be added to the Deployment or DeploymentConfig in order to let the application to consume them when it will start the pod's container....

**Comment by jorgemoralespou** [comment]
@cmoulliard that is "service injection" in the context of service catalog. Too many things named service ;-D 
I could call it "binding injection". https://github.com/kubernetes-incubator/service-catalog/issues/165

**Comment by cmoulliard** [comment]
The binding is just creating a Secret for the moment using the ServiceInstance parameters AND will not at all inject it to a selected pod, deployment | deploymentconfig unfortunately

**Comment by jorgemoralespou** [comment]
@cmoulliard That is the scope of tha issue :-D which I guess you've read.
This is something that the service catalog SIG group is working on, hence I asked @sspeiche to get someone involved with us, to understand their timing.

The same way we are leveraging many parts of openshift, this is something we could do (and would not be standard, or we could rely on, and be standard). What we can do and when depends on their timing.

Maybe @pmorie can help us know what's their timings/priorities.

**Comment by cdrage** [comment]
With @cmoulliard and @geoand 's implementation here: https://github.com/redhat-developer/odo/pull/723 could we close this issue?

**Comment by geoand** [comment]
I propose we close it. I have also opened PR #856 as a follow up
