### ISSUE TITLE
Add component/application/service autocompletion

### ISSUE THREAD

**Issue by slemeur** [redhat-developer/odo#77]
### Description
When using the commands pointing to a particular component or application, like `ocdev application delete <application_name>`, it would be handy to provide autocompletion.
This way the developer can:
- get the list of all applications / components, in case he does not have them in mind
- fasten the interaction with the commands

**Comment by cdrage** [comment]
Linking this here: https://github.com/spf13/cobra/blob/master/bash_completions.md which was can use in order to generate the autocompletion / use the autocompletion for the list of components / applications. In particular, we'll be using `odo list`

**Comment by cdrage** [comment]
We've gone ahead and implemented this (well, *half*). Autocompletion is complete, however, automatically grabbing the next component / list of components from using tab is not.
