### ISSUE TITLE
Add unit tests and e2e tests for watch

### ISSUE THREAD

**Issue by anmolbabu** [redhat-developer/odo#770]
Watch is a continous process so e2e tests for this can be tricky

@kadel recommends the following steps for watch e2e tests
1. Start watch in a separate process
2. Make some code change on the watched source
3. Grep for filesystem events from watch logs
4. Terminate the process

The UTs can also be tricky as it involves :
1. files and folders
2. filesystemnotifier

**Comment by ashetty1** [comment]
You could refer to tests written for `TestWaitForBuildToFinish` for writing unit tests for watch: https://github.com/redhat-developer/odo/blob/master/pkg/occlient/occlient_test.go#L2334
