### ISSUE TITLE
Create Java example and use it in our test suite

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#777]
- Java is our main target and we need to use Java components in our tests.
- We will probably need two examples one that compiles to jar, and other that compiles to war.

**Comment by cmoulliard** [comment]
Here are some Java Propositions for  : 

- [jar](https://github.com/snowdrop/generator/tree/master/pkg/template/tmpl/rest) packaging = uberjar file  -> Spring Boot Application exposing a REST Greeting endpoint
- [war](https://github.com/snowdrop/generator/tree/master/pkg/template/tmpl/jsp) package file -> Spring Boot App running a JSP/JSTL app deployed as a war

**Comment by jorgemoralespou** [comment]
@kadel:
- https://github.com/openshift-evangelists/Wild-West-Backend (master branch) is a SpringBoot app packaged as jar
- https://github.com/openshift-evangelists/Wild-West-Backend (wildfly branch) is same but packaged as war file to be used on wildfly/EAP

**Comment by cdrage** [comment]
I'm beginning to work on this @jorgemoralespou and @kadel so I may ask you two for help.

With your examples that you linked, I'm going to add these to our e2e tests in order to make sure they're 100% compatible and tested against Odo.

Other than `.jar` and `.war` are we missing anything else?

Doing a quick check through https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples and I can't see any other use-cases.

**Comment by jorgemoralespou** [comment]
@cdrage .ear file is also something that can be deployed to an application server (e.g. EAP/Wildfly).
There's more types of artifacts, but these are the most common.

**Comment by kadel** [comment]
It would be awesome if you could use different builder images, like for example this one: https://access.redhat.com/containers/#/registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift/images/1.5-14 

@cmoulliard Is there a special SpringBoot s2i builder?

**Comment by jorgemoralespou** [comment]
@kadel, that's the java s2i now, easier to remember
https://github.com/openshift/library/blob/master/official/java/imagestreams/java-rhel7.json

It is the same as you referenced but with more adequate name.

**Comment by cdrage** [comment]
I added some *very* simple tests here: https://github.com/redhat-developer/odo/pull/865

Let me know if this is a step in the right direction :+1:
