### ISSUE TITLE
Document how to import builder images to the user's project

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#780]
example using `oc import-image`:
```
oc import-image openjdk18 --from=registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift --confirm 

oc annotate istag/openjdk18:latest tags=builder

**Comment by cmoulliard** [comment]
As the builder annotation is well defined within the openjdk18 openshift image available from the[ Red Hat registry](https://access.redhat.com/containers/?tab=tech-details#/registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift),

```
io.openshift.tags builder,java
```

 OpenShift's engineering team should fix the issue as the annotation is removed during oc import-image command. Who should be contacted for that @kadel  ?

**Comment by kadel** [comment]
Maybe @bparees could help us. Is it intentional that Labels from the container image are not converted to ImageStream tag annotations when using `oc import-image`?

**Comment by bparees** [comment]
> Maybe @bparees could help us. Is it intentional that Labels from the container image are not converted to ImageStream tag annotations when using oc import-image?

Yes, the two are unrelated.

**Comment by cmoulliard** [comment]
Why do you [delete](https://goo.gl/GArqgt) the image's annotations during import = creation of the image @bparees ?

**Comment by bparees** [comment]
That deletes one specific legacy annotation, it does not delete all the image's annotations.  And again, imagestream/imagestreamtag/image-resource annotations are unrelated to docker image Labels.

**Comment by cmoulliard** [comment]
So, the existing openjdk java s2i image should be modified to include openshift annotations in order to avoid to have to do `oc annotate istag/openjdk18:latest tags=builder` after it has been imported then ? If this is not the way to go, should we consider to request to package by default the openjdk java s2i image as this is the case for php, ruby, python, ... on origin or ocp ?

**Comment by bparees** [comment]
The openjdk imagestream, with the builder tag, is shipped in openshift already:

https://github.com/openshift/openshift-ansible/blob/release-3.11/roles/openshift_examples/files/examples/latest/xpaas-streams/openjdk18-image-stream.json#L34

Rather than importing the image manually yourself, you should be installing the imagestream (if for some reason it's not already installed in your cluster).

**Comment by cmoulliard** [comment]
Hmhm. This image should be installed by default using `oc cluster up` or `minishift` without the need to install minishift addon or deploy the xpaas streams

**Comment by bparees** [comment]
> Hmhm. This image should be installed by default using oc cluster up or minishift without the need to install minishift addon or deploy the xpaas streams

[shrug].

it's considered an xpaas image currently.  Given the future of cluster up, i would suggest this needs to be taken up by the minishift team, and not cluster up, in terms of deciding what imagestreams minishift should/should not install.

**Comment by jorgemoralespou** [comment]
Currently, openjdk image is based on RHEL, and hosted being the registry that requires authentication, so can/should not be used on minishift anymore. This is something that has changed recently and @bparees knows, but probably not everyone on this thread or minishift.

This means, that for upstream OKD, there is no way to use Java officially. Maybe we need to add to the openshift/library the fabric8/s2i-java or any other java image based on centos and hosted outside the paywall. I wish the xpaas team or whoever is responsible now would ship that image.

**Comment by cdrage** [comment]
From the above discussion, should we still add this to documentation? I used the above commands and found no issue importing it from the registry (without needing to use authentication). Perhaps that's just a `minishift` feature..
