### ISSUE TITLE
Refactor CLI code to follow kubectl/oc practices

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#785]
Our CLI code is starting to get quite messy. 
It is time to start working on refactoring it.

The best way would be to follow  Complete-Validate-Run pattern used by kubectl and oc.

Resources that will help with refactoring:
- Kubernetes extracted some of the kubectl stuff to re-usable libraries  https://github.com/kubernetes/cli-runtime 
- OpenShift released nice CLI Hacking Guide https://github.com/openshift/origin/blob/master/docs/cli_hacking_guide.adoc

**Comment by kadel** [comment]
It would be a good idea on this on per command basis.

**Comment by kadel** [comment]
review: @surajnarwade @anmolbabu

**Comment by metacosm** [comment]
I will begin with the service command. However, outside of command refactoring to adhere to `oc` patterns, the code will need to move as well. For example, all code currently in `cmd` should move to `pkg/odo/cli` but I think that we should first focus on re-implementing the commands according to the conventions then move the code around.

**Comment by metacosm** [comment]
We probably should follow the standard layout defined in https://github.com/golang-standards/project-layout as well (that, from what I can see, `oc` also follows).

**Comment by kadel** [comment]
> We probably should follow the standard layout defined in https://github.com/golang-standards/project-layout as well (that, from what I can see, `oc` also follows).

agree, but let's do one step at a time. This big refactoring are slowing us down :-(

**Comment by metacosm** [comment]
Actually, this is not finished: #1002 only deals with moving classes to their proper spot, there is still much to do to accomplish the complete refactoring.
