### ISSUE TITLE
Document how to run e2e tests localy

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#788]
Our dev docs should contain information on how to run e2e test suite localy.

**Comment by girishramnani** [comment]
There is already a doc on how to run the [e2e-tests](https://github.com/redhat-developer/odo/blob/master/tests/e2e/README.md), maybe we can add that to the [dev docs](https://github.com/redhat-developer/odo/blob/master/docs/development.md)?

**Comment by cdrage** [comment]
@kadel @girishramnani 

I'll take this up! :+1:  But yes, we should add details on how to run e2e tests locally.
