### ISSUE TITLE
As a developer, I want odo to be able to display valid components that were created via the OpenShift Web UI

### ISSUE THREAD

**Issue by ryanj** [redhat-developer/odo#808]
As a developer, I want odo to be able to display valid components that were created via the OpenShift Web UI

I'd like to be able to share and load templates to jumpstart my development (before switching to odo).

**Comment by jorgemoralespou** [comment]
Also, how many times are you going to open this issue? ;-)
https://github.com/redhat-developer/odo/issues/631

I would close this in favor of that one, and maybe update that one in case it's not clear the intention as it is on this one.

**Comment by ryanj** [comment]
sorry, will follow up over there
