### ISSUE TITLE
Add missing -a/--application to commands

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#814]
There are some commands that should accept to work on an application different than the active one with `-a my-app`or `--application my-app`. Listing here the missing ones.

- [ ] `odo component`
- [ ] `odo component set`
- [ ] `odo component get`
- [ ] `odo create`
- [ ] `odo delete`
- [ ] `odo describe`
- [ ] `odo link`
- [ ] `odo list`
- [ ] `odo log`
- [ ] `odo push`
- [ ] `odo update`
- [ ] `odo watch`
- [ ] `odo service *`
- [ ] `odo storage *`
- [ ] `odo url *`

**Comment by surajnarwade** [comment]
issue is already here https://github.com/redhat-developer/odo/issues/656
and WIP PR is at https://github.com/redhat-developer/odo/pull/683

**Comment by jorgemoralespou** [comment]
Closing in favor of the previous. @surajnarwade just make sure that this (and --component) flag is only present in the relevant commands and not every command, as in some cases will not make sense.
