### ISSUE TITLE
Add missing -c/--component to commands

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#815]
There are some commands that should accept to work on another component than the active one with `-c my-comp` or `--component my-comp`. Listing here the missing ones.

- [ ] `odo storage *`. Missing from flags in help, but available in example in help.
- [ ] `odo url *`. Missing from flags in help, but available in example in help.

**Comment by surajnarwade** [comment]
issue is already here https://github.com/redhat-developer/odo/issues/656
and WIP PR is at https://github.com/redhat-developer/odo/pull/683

**Comment by jorgemoralespou** [comment]
Closing in favor of the previous
