### ISSUE TITLE
Provide debug/port-forward capabilities for the deployment

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#822]
odo components should enable whatever debug capabilities exist in the image and when the component is configured as local/binary, these capabilities should be enabled. odo should also provide a way to express how to connect to the remote container via port-forward.

As the connection cannot always be opened, even if the component is activating a port-forward by default, there should be a mechanism to re establish the port forwarding capabilities.

I can see various options:
- Always enable debug capabilities by default, and provide a way to specify the local port to forward the remote port via a flag
- Provide a flag to enable debug mode and open the port forwarding
- Provide a specific command for enabling debug mode and open the port forward. This requires a redeployment, hence I would not prefer this option.
- Provide a mechanism in the supervisor to activate the debug mode.

I would love to gather some ideas on how debugging should work.

**Comment by gorkem** [comment]
I see this as 3 steps. 

1. Enabling the debug mode on the runtime(JavaVM, node.js etc). This usually ends up with a port opened for debuggers to attach. Different runtimes have different behaviour here. For instance node.js allows opening the debug port while it is running while JVM requires a restart. I feel that it is OK if odo start these runtimes with debug always on. It makes the debugging more agile for things like JVM compared to restarting them all the time.

2. The second step is port forwarding. In this case debugger just needs to tell `odo` which local port it will use and `odo` and `odo` should setup the port forwarding from local port to the container's debug port. 

3. This is where debugger connects to local port and profit!! We will probably write special launch configurations to vscode and Eclipse IDE to invoke `odo` to do this but these are outside the scope of `odo`.

**Comment by Preeticp** [comment]
@boczkowska this is going to affect docs for the 4.2 release, please add a parallel issue to our docs board.
@kadel @sspeiche:
1. We need to have a label "Needs Docs" to identify issues which need docs. So far we tracked issues needing docs using Type/Docs or Kind/Docs but those would be inappropriate for these kind of issues.
2. Also, though I am a member of the OpenShift org I cannot add the above labels, neither create a new one. This makes it difficult for docs team to track such issues. Please let me know if I could get the rights to assign labels and assignees so that the docs team is able to assign issues and labels. Thank you.

**Comment by kadel** [comment]
I can see two paths here:
1.  as @gorkem and @jorgemoralespou described we could enable debug mode by default
2. Enable it only when user requests. This will probably require restarting the application for most of the languages.


I also like the first option. I think that it makes sense as odo is primarily for inner loop development and it makes sense to have this enabled by default. There will be some performance cost, but for inner-loop, it shouldn't matter.

My only worry here is if this model is going to work for other languages like Go, Python etc...

**Comment by kadel** [comment]
I've just created a proposal document describing how odo debug could work. see PR https://github.com/openshift/odo/pull/1995

I also found some changes with NodeJS. It is also described in the document in https://github.com/openshift/odo/pull/1995

**Comment by kadel** [comment]
Broken down tasks for this epic:
- odo debug port-forward command #2012
- add odo debug start command #2013
- add odo debug stop command #2014
- add odo debug status command #2015
- odo debug: provide inner loop scripts with DEBUG support for nodejs and java #2023
