### ISSUE TITLE
odo create nginx and https fails in v0.0.13

### ISSUE THREAD

**Issue by yohanswanepoel** [redhat-developer/odo#842]
[kind/bug]

## Red Hat CDK 3.6, OCP-TAG 3.11.16, ODO version 0.0.13

Operating System : Mac OS

Output of `odo version` : 
odo v0.0.13 (f92c352)
the server could not find the requested resource

## How did you run odo exactly?

odo create nginx
## Expected behavior

Create an nginx container

## Actual behavior
image stream nginx with tag latest not found in openshift and myproject namespaces

## Steps to reproduce the behavior

odo create nginx
odo create httpd

versions 0.10 and 0.09 both do not work with different error

## Any logs, error output, etc?
v.0.13
odo create nginx
image stream nginx with tag latest not found in openshift and myproject namespaces

v.0.10
odo create httpd
Service "httpd-app" is invalid: spec.ports: Required value

## Do you have any idea what may have caused this?
Could be OpenShift 3.11.16?
Works in OpenShift 3.10.45

## Do you have an idea how to solve the issue?
Roll back to version 3.10 of OpenShift

**Comment by yohanswanepoel** [comment]
I have found a workaround by running: o
do create nginx:1.10

That is the only version of the tags from odo catalog list components that work
nginx                                   openshift     1.10,1.12,1.8,latest

**Comment by yohanswanepoel** [comment]
odo push on 0.0.13 does not work, but I could do a push with an older version 0.0.9

**Comment by surajnarwade** [comment]
I tried following steps and works well for me,

```
git clone https://github.com/sclorg/httpd-ex
cd httpd-ex/
odo create nginx
odo push
odo url create --port 8080
```

odo version is:

```
 $ odo version
odo v0.0.14 (HEAD)
```

@yohanswanepoel , can you please try once and let us know the issue

**Comment by surajnarwade** [comment]
I tried again an worked well for me, closing this.

@yohanswanepoel , if you faced problem again, feel free to repoen
