### ISSUE TITLE
Component created with wrong name

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#849]
If i just do:

`odo create wildfly backend`

The component is named `backend-app` but it should be only `backend`

**Comment by kadel** [comment]
It is true that all the OpenShift objects are named using `<component name>-<application name>` but the component is named correctly. The user running odo shouldn't ever see this `backend-app`.

We can't simply name OpenShift objects with the same name as a component. This would make it impossible to create two components with the same name in different applications in the same project.

Namespacing to the OpenShift object was introduced while back in #480 (original issue #214)

```
▶ odo create wildfly  backend
Component 'backend' was created and port 8080/TCP was opened
To push source code to the component run 'odo push'

Component 'backend' is now set as active component.

▶ odo component
The current component is: backend

▶ odo list
ACTIVE     NAME        TYPE
*          backend     wildfly

▶ oc get dc
NAME          REVISION   DESIRED   CURRENT   TRIGGERED BY
backend-app   1          1         1         config,image(wildfly:latest)
```

**Comment by jorgemoralespou** [comment]
so, the problem is that if I want to connect from frontend to backend, the service name is not named as the component, but the service name, the dc, etc... are named differently.

The component name should be the same as the resources you create, otherwise it's a mess.

Just think you do:

```
odo create wildfly backend
```

and then in your wildfly app, if you want to communicate with the backend, you need to curl/access `backend-app`. It took us 30 minutes to figure out how to hack the missing link for components because we were trying to access something that didn't exist.

The in the UI, in oc, everywhere, except `odo list` names the thing (whatever that is) `backend-app`.

I understand this don't strikes at first, but once would expect the things, dcs, svc, configmaps, routes, etc.. be named the same way as you explicitly said, for sake of simplicity.

**Comment by kadel** [comment]
> I understand this don't strikes at first, but once would expect the things, dcs, svc, configmaps, routes, etc.. be named the same way as you explicitly said, for sake of simplicity.


As I mentioned above. If we do that, that means that you won't be able to create two components with the same name in different applications.

For example, the following will fail:
```
odo application create myFirstApp
odo create java
odo application create mySecondApp
odo create java
```
 
Any use will expect that this should be possible.

**Comment by jorgemoralespou** [comment]
I wouldn't think this is what any user would expect, and this is clearly something we should need to maybe document/restrict.

If the user explicitly names a component in an application, then maybe a user will work with same component in multiple applications in same project, but I don't expect or think this will be a common use.

I think that most typical behavior will be:
- use specific project for specific application (have one app per project)
- use autogenerated names for development (would avoid this problem)

This is similar problem as described in https://github.com/redhat-developer/odo/issues/843

We need to honour what the user wants for naming, if that means restricting to one occurrence per project. When there's conflict the user can postpend the app name as suffix and be totally conscious of how the resources will be named.

**Comment by jorgemoralespou** [comment]
After talking on videoconference with @kadel and @geoand I have understood better the reasoning he's providing.

For now, we'll keep things as they are, which means we're appending the app name to the component name to support same component name in different apps, as these should be underlying technical details that shouldn't leak to the user. This also means that `odo link` will be fixed as described in https://github.com/redhat-developer/odo/issues/652 to avoid the need to go to the underlying details for a solution.

If with usage we find out this is not the proper approach, we will re-evaluate in a new issue.

I'm closing this as `lack of technical skills` from my side :-D
