### ISSUE TITLE
Add more information to `odo describe` command output

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#853]
Currently, we are not showing much useful information for the component 

```
▶ odo describe wildfly
Component wildfly of type wildfly with source in file:///Users/tomas/tmp/odo-examples/katacoda-odo-backend
```

We should show more information like env variables and ports
Something like this might look better 
```
▶ odo describe wildfly
Name: backend
Type: wildfly
Source: file:///Users/tomas/tmp/odo-examples/katacoda-odo-backend
Ports: 
  - 8080/tcp,
  - 9090/udp
Environment variables: 
  - VARIABLE=value
  - myothervar=othervalue
```

**Comment by geoand** [comment]
I can work on this @kadel if no one is assigned to it already

**Comment by kadel** [comment]
> I can work on this @kadel if no one is assigned to it already

I'm just thinking how to best approach this as together with https://github.com/redhat-developer/odo/issues/785 https://github.com/redhat-developer/odo/issues/784 and also dived all this work into the smaller pieces so multiple people can work on it.

**Comment by geoand** [comment]
Good idea, I wasn't aware of the other issues.
I am signing up for my fare share of the work when you decide how best to tackle this issue :)

**Comment by kadel** [comment]
This should be done after the new structure of the command is defined by https://github.com/redhat-developer/odo/issues/785

**Comment by kadel** [comment]
review: @geoand @anmolbabu
