### ISSUE TITLE
odo push never returns

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/odo#860]
[kind/bug]

## What versions of software are you using?

Operating System : Windows 10

Output of `odo version` : 
```
odo v0.0.14 (618c6d3)

Server: https://192.168.99.104:8443
OpenShift: v3.9.31
Kubernetes: v1.9.1+a0ce1bc657
```

## How did you run odo exactly?

In a folder where my Spring Boot application is, I ran the following commands:
- start CDK 3.5
- odo create redhat-openjdk18-openshift:1.3 backend --local .
- odo push --local .

## Expected behavior

The odo push command should returns

## Actual behavior
odo push seems to be waiting for the pod to run but it never shows up.

## Do you have any idea what may have caused this?

Seems the pod cannot be deployed but I can't see any infos in the logs

**Comment by cdrage** [comment]
@jeffmaury 

What does it show when you do: `odo push -v 4 --local .` ?

It could be that it's still waiting for a pod to go from pending to running.

**Comment by jeffmaury** [comment]
Here is the output:

```
> odo push -v 4 --local .
I1024 09:34:16.490339   56756 occlient.go:265] Trying to connect to server 192.168.99.104:8443
I1024 09:34:16.627025   56756 occlient.go:271] Server https://192.168.99.104:8443 is up
I1024 09:34:16.999007   56756 occlient.go:248] isLoggedIn err:  <nil>
 output: "developer"
I1024 09:34:17.001936   56756 push.go:45] No component name passed, assuming current component
Pushing changes to component: backend2
I1024 09:34:17.005842   56756 occlient.go:1909] Getting DeploymentConfig: backend2-app
I1024 09:34:17.093711   56756 component.go:386] Source for component backend2 is file:///c:/work/tmp/ododemo (local)
I1024 09:34:17.094689   56756 push.go:93] Copying directory . to pod
I1024 09:34:17.112261   56756 occlient.go:1110] Waiting for deploymentconfig=backend2-app pod
```

**Comment by jeffmaury** [comment]
It turned it has some relation with my CDK VM not being able to pull the supervisord image. So I deleted the CDK VM and recreated it and it now works. Closing
