### ISSUE TITLE
Autodetect path for assemble and run scripts

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#869]
Currently, we are just trying two paths for assembleand run script

https://github.com/redhat-developer/odo-supervisord-image/blob/45fcabbad8e415a422ff84394141fc810ffe5409/assemble-and-restart#L9

But according to [s2i docs]( https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md#assemble) assemble can be in any path, and image label `io.openshift.s2i.assemble-user` is pointing to the correct path.

We should make sure that when we are calling assemble script from the path specified by label (if not overwritten in [local `.s2i` folder](https://github.com/redhat-developer/odo-supervisord-image/blob/45fcabbad8e415a422ff84394141fc810ffe5409/assemble-and-restart#L7)

**Comment by kadel** [comment]
review: @geoand @metacosm

**Comment by geoand** [comment]
A very simple spring boot application that we use with java s2i is: 

`https://github.com/snowdrop/spring-boot-http-booster`

To build the runnable jar, just execute:

`./mvnw clean package`

The jar is then produced in `target/spring-boot-rest-http-1.5.x-y-SNAPSHOT.jar`

**Comment by geoand** [comment]
I am very curious about this :)

As far as I understand, the ` io.openshift.s2i.scripts-url` label is a docker image label. How are those labels going to be queried from inside the container?
Do we plan perhaps to read this label somehow when doing `odo create` (I don't that label being part of the image stream, so again I don't know how it would be read), then setting an environment variable for the supervisord pod which will then be used by the bash script?

Sorry for the potentially n00b question, it's just that I am very interested in what you have in mind :)

**Comment by geoand** [comment]
Looking at the nodejs and python builder images, when I create a supervisord pod with one of them, I see the `STI_SCRIPTS_PATH` environment variable.
Unfortunately java s2i again does not play nice and does not contain it...

**Comment by geoand** [comment]
@surajnarwade You mentioned that you learned a lot about s2i, so I am wondering if anything of the above seems odd to you :)

**Comment by metacosm** [comment]
Any idea why Java s2i behaves so differently? Maybe we'd be better served fixing java s2i than trying to work around its idiosyncrasies?

**Comment by geoand** [comment]
Although fixing Java s2i makes sense, I seriously doubt it can be achieved in a timely and friction-less manner

**Comment by kadel** [comment]
> I am very curious about this :)
> 
> As far as I understand, the ` io.openshift.s2i.scripts-url` label is a docker image label. How are those labels going to be queried from inside the container?

Yes, my idea is to query it from inside the container.

It should be possible to get to labels via `ImageStreamImage` object in OpenShift. Similarly to how we already detect ports exposed by image (https://github.com/redhat-developer/odo/blob/2e6e6beed60f19275d09d07d8b749861620ea920/pkg/occlient/occlient.go#L337)

> Do we plan perhaps to read this label somehow when doing `odo create` (I don't that label being part of the image stream, so again I don't know how it would be read), then setting an environment variable for the supervisord pod which will then be used by the bash script?

I think that this should be part of  [assemble-and-restart](https://github.com/redhat-developer/odo-supervisord-image/blob/master/assemble-and-restart ) script. This doesn't have to be in bash. We should convert it to Go to make it easier to deal with OpenShift API.

**Comment by kadel** [comment]
> Looking at the nodejs and python builder images, when I create a supervisord pod with one of them, I see the `STI_SCRIPTS_PATH` environment variable.

If we can count on`STI_SCRIPTS_PATH` env variable.  I know that some images are using it but s2i documentation just mentions the label :-(

**Comment by jorgemoralespou** [comment]
@bparees what should be the best way for us to know what are the scripts being invoked by s2i?

**Comment by bparees** [comment]
the image label is the appropriate way, the env variables are deprecated.

but of course if the user supplied override scripts either by passing an arg or by providing them in their repo, those would be run instead.  So you would need to be aware of that possibility also.

What exactly are you trying to do that you need this information?

**Comment by geoand** [comment]
> > I am very curious about this :)
> > As far as I understand, the ` io.openshift.s2i.scripts-url` label is a docker image label. How are those labels going to be queried from inside the container?
> 
> Yes, my idea is to query it from inside the container.
> 
> It should be possible to get to labels via `ImageStreamImage` object in OpenShift. Similarly to how we already detect ports exposed by image (
> 
> [odo/pkg/occlient/occlient.go](https://github.com/redhat-developer/odo/blob/2e6e6beed60f19275d09d07d8b749861620ea920/pkg/occlient/occlient.go#L337)
> 
> Line 337 in [2e6e6be](/redhat-developer/odo/commit/2e6e6beed60f19275d09d07d8b749861620ea920)
> 
>  func getExposedPortsFromISI(image *imagev1.ImageStreamImage) ([]corev1.ContainerPort, error) { 
> )
> > Do we plan perhaps to read this label somehow when doing `odo create` (I don't that label being part of the image stream, so again I don't know how it would be read), then setting an environment variable for the supervisord pod which will then be used by the bash script?
> 
> I think that this should be part of [assemble-and-restart](https://github.com/redhat-developer/odo-supervisord-image/blob/master/assemble-and-restart) script. This doesn't have to be in bash. We should convert it to Go to make it easier to deal with OpenShift API.

Cool, I'll check that out

**Comment by jorgemoralespou** [comment]
@bparees the supervisor that is injected in the container will eventually call `assemble` and/or `run` scripts when so instructed from the command line.
This is a pod (currently from a supported s2i image) that is always running and that when `odo push` happens, it will call those 2 scripts to update the application.

AFAIK the first thing we check is that if there is a .s2i folder co-located with the source code, this would be run instead. There would be no way to provide overrides via an arg, as it's not running a BC but a DC with the "always running" container.

@kadel anything I'm missing?

**Comment by geoand** [comment]
I indeed see that we can access the docker image labels from the go code in the same way the we access the exposed ports, cool stuff!

Is there an easy way such information could be accessed via `oc` commands?

**Comment by kadel** [comment]
> AFAIK the first thing we check is that if there is a .s2i folder co-located with the source code, this would be run instead. There would be no way to provide overrides via an arg, as it's not running a BC but a DC with the "always running" container.

@jorgemoralespou correct. and after checking for `.s2i`,  we look for `/usr/libexec/s2i/assemble` and `/usr/local/s2i/assemble`, if assemble is elswere it fails.

**Comment by kadel** [comment]
@geoand 

> Is there an easy way such information could be accessed via `oc` commands?

Not sure but I think it should be possible. But that would mean that we have to add oc binary to the image.

> If not, then @kadel I see your point of converting the `assemble-and-restart` script to a binary built from go code :)

I belive that this is the best way. This will make the script more complicated, and mantaining it as bash script will be painfull.

**Comment by geoand** [comment]
@kadel, the more I think about it, the more I agree with creating a binary from some simple go code :)

**Comment by mik-dass** [comment]
@anmolbabu Why is this issue closed? The fix #924 isn't in yet nor is https://github.com/redhat-developer/odo-supervisord-image/pull/3

**Comment by anmolbabu** [comment]
@mik-dass I am not sure how it got closed I'll reopen it right away

**Comment by kadel** [comment]
> @mik-dass I am not sure how it got closed I'll reopen it right away

it got closed because of your commit message ;-)

**Comment by anmolbabu** [comment]
> > @mik-dass I am not sure how it got closed I'll reopen it right away
> 
> it got closed because of your commit message ;-)

Oh :)

**Comment by anmolbabu** [comment]
Changed the size to `M` from `L` as it turned out way smaller from my previous estimate
I know I am bad at estimation ;) specially when the thing is alien to me :P

**Comment by geoand** [comment]
@anmolbabu let me know if I can help out at all :)

**Comment by anmolbabu** [comment]
> @anmolbabu let me know if I can help out at all :)

@geoand Yes I am sure there might still be things that I might be missing so could you please review https://github.com/redhat-developer/odo/pull/924 and https://github.com/redhat-developer/odo-supervisord-image/pull/3 meanwhile I'll fix the tests

**Comment by geoand** [comment]
@anmolbabu Will do :)

**Comment by anmolbabu** [comment]
> @anmolbabu Will do :)

Yo!! Thanks a double ton @geoand
