### ISSUE TITLE
Rename cmd.checkError to cmd.logErrorAndExit to be more explicit about function

### ISSUE THREAD

**Issue by metacosm** [redhat-developer/odo#874]
[kind/Proposal]

## What is the expected outcome?
Same as before, just with a different, more explicit name. ;)

## Why do you think this is relevant?
Manage expectations with respect to what this function does.

**Comment by metacosm** [comment]
Should probably wait until after #871 is done, though.

**Comment by mohammedzee1000** [comment]
871 appears to be merged. I believe this issue is unblocked?
