### ISSUE TITLE
Enhance the odo service describe

### ISSUE THREAD

**Issue by geoand** [redhat-developer/odo#880]
[kind/Enhancement]

## What should odo do differently? Which functionality do you think we should change?

With the inclusion of #756 we now have a lot of information about the parameters of a service. For instance we now know the parameters that can be used when creating the `ServiceInstance`.
 
There is one issue however that has arisen from that implementation: 
The `required` parameters that are shown are not always strictly "required", since most of them have default values. 
For example, the `postgresql_password` service only really required the `postgresql_password` since the rest of the parameters are reported as required, have default values (for example we have `postgresql_user` defaults to `admin`).

If we don't address this, there two implications:
* User's will be mislead into thinking they need to supply all the parameters when in most cases they only need a few of them
* More importantly, this will prohibit us from providing the correct suggestions to users of the service catalog in the proposed interactive mode. Furthermore, knowing which parameters are really required will allow us to fail fast and with the appropriate error message when service create is called without the necessary parameters.

## What are you trying to do?

Improve the experience of the users of the service catalog since currently it's not crystal clear from the user what parameters need to be supplied and what their values look like. 
Addressing this issue will allow us to build better interactive mode and provide better error messages during failed service creation while also improving the describe output.

**Comment by jorgemoralespou** [comment]
@geoand I've seen that you created the issue and then created a PR, but TBH the issue does provide very little information on what is the problem and how you're going to approach the solution, so seems that you went ahead with an implementation before getting any consensus.

I haven't looked into it, and I'm sure it's really good, but I'm raising this topic as I would think that it's better to spend some time defining in the issue how things are going to be laid out, so one knows before the PR if there's any outstanding concern to be discussed.

Not sure if this has been discussed on mattermost or any of our internal calls, but I think that open discussions or at least, openly publish the intents helps. For many people, issues is the only thing they see, if as me, they don't understand code ;-)

Does it make sense? @kadel ???

**Comment by geoand** [comment]
@jorgemoralespou I apologize if I broke the standard process here!

The issue was brought up in the some of the odo discussions we had on BlueJeans last week but I admit that could have done a better done at defining the issue.

The PR itself doesn't change much of the functionality that the user sees, but it instead provides the building blocks to make subsequent improvements to the service catalog handing. 
One reason why I didn't wait for further consensus is that I believed that the problem was best demonstrated by actually showing the fix, which was also quite small. 

I apologize again for straying from the norms here ☺

**Comment by jorgemoralespou** [comment]
@geoand there's no "norm". It's just that it's easier to discuss on issues than on PRs. So, if you look into the PR, it says it's been discussed here:

> Was the change discussed in an issue? #880

So, either one looks at code to figure out how you've solved the thing, or waits until is merged to see the experience. Remember we do not all understand go ;-)

And also I think @kadel raised a good point with the naming used for Mandatory/optional and default values, to which I agree. I like better the naming he proposes.

**Comment by geoand** [comment]
Thanks for the clarification @jorgemoralespou.

I will update the issue with more information and also implement the change
proposed by @kadel

**Comment by geoand** [comment]
@jorgemoralespou I updated the issue description, hopefully it's better now :)
I also updated the output with the suggestion made by @kadel
