### ISSUE TITLE
Delete operations should check for existence of target entity before asking for confirmation

### ISSUE THREAD

**Issue by metacosm** [redhat-developer/odo#888]
[kind/Proposal]

## What is the expected outcome?
Delete operations should check the existence of the target entity before asking to confirm the deletion.

## Why do you think this is relevant?
Because it is weird for the tool to ask me if I'm sure I want to delete something that doesn't exist… :)

**Comment by kadel** [comment]
`odo delete` and `odo project delete` works correctly, it is just `odo app delete`

```
▶ odo delete ff
Component with the name ff does not exist in the current application

▶ odo project delete fff
The project fff does not exist. Please check the list of projects using `odo project list`

▶ odo app delete fff
Are you sure you want to delete the application: fff? [y/N] y
application fff doesn't exist
```

**Comment by u5surf** [comment]
@metacosm I fix them https://github.com/u5surf/odo/commit/dad10591ef2b637ab29fb8a7e38cb823adb0f9eb

**Comment by surajnarwade** [comment]
Closing since #897 is merged :smile:
