### ISSUE TITLE
Feature: Adding a form of "progress bar" or "circle" when using odo push

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#911]
We should have some form of a progress bar / spinning circle when using `odo push`.

At the moment, it looks like the console has "frozen" as it's stuck on waiting for a Pod. Having a form of progress bar / circle would alleviate the task.

**Comment by kadel** [comment]
We can't create a progress bar :-(. There is no way to know how long push will take.

There already is an issue about improving messaging for `odo push` https://github.com/redhat-developer/odo/issues/829

**Comment by kadel** [comment]
@cdrage can we close this issue as there already is #829 ?

**Comment by cdrage** [comment]
Yup. I'll close this!

I thought about including a "circle" when using `odo push` instead.
