### ISSUE TITLE
Move e2e tests to ci.centos.org

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#952]
We are starting to have quite a few issues with our e2e tests. They are slow and there is a lot of timeouts.

As a first step, let's move all our existing e2e tests from travis-ci to ci.centos.org.

**Comment by syamgk** [comment]
As the step 1. https://wiki.centos.org/QaWiki/CI/GettingStarted#head-e22a33cdce4ad83057616201c437c0bf9097c05e

created request add odo to ci.centos.org here https://bugs.centos.org/view.php?id=15460

**Comment by geoand** [comment]
@syamgk Do you have any idea how long it takes to get approved for ci.centos?

I am asking because if this is going to take a long time, perhaps it makes sense to also explore other options (like Semaphore or CircleCI)

**Comment by geoand** [comment]
@syamgk Do you have any idea how long it takes to get approved for ci.centos?

I am asking because if this is going to take a long time, perhaps it makes sense to also explore other options (like Semaphore or CircleCI)

**Comment by syamgk** [comment]
we got ci.centos.org account as of today!
am working on configuring it

**Comment by syamgk** [comment]
did a mocking by creating a test branch and the results can be found here : https://ci.centos.org/job/odo/job/cico-test/16/

**Comment by amitkrout** [comment]
> did a mocking by creating a test branch and the results can be found here : https://ci.centos.org/job/odo/job/cico-test/16/

Cool!!!
@syamgk Only UT are running in the ci. Can you please start adding the integration test to it. Please let me know if you need any help to address those test in CI.

**Comment by syamgk** [comment]
the remaining part is adding webhoooks pointing to https://ci.centos.org/github-webhook/ for PR events and configuring e2e tests

**Comment by amitkrout** [comment]
Thanks for the update!!!
I can see a big exception of ```java.lang.Exception: Method POST required``` thrown in [1]. Any  reason behind it ?

[1] https://ci.centos.org/github-webhook/.

**Comment by syamgk** [comment]
> Thanks for the update!!!
> I can see a big exception of `java.lang.Exception: Method POST required` thrown in [1]. Any reason behind it ?
> 
> [1] https://ci.centos.org/github-webhook/
> 
>
Its an endpoint which is expecting POST request and when you are accessing it from browser its doing a GET request, hence the error
```
$ curl -I https://ci.centos.org/github-webhook/
HTTP/1.1 405 Method Not Allowed
```

**Comment by syamgk** [comment]
- [ ] configure e2e tests on ci.co

- [ ] adding webhooks from odo repo to ci.co

- [ ] sending pr to master with .cico.pipeline(which is currently residing in cico-test branch)

**Comment by syamgk** [comment]
hitting the same error as specified in this issue https://github.com/openshift/origin/issues/21253 
logs on ci.co https://ci.centos.org/job/odo/job/cico-test/45/console

**Comment by kadel** [comment]
Do you know where exactly it fails?
Have you tried to run `oc cluster up` in verbose mode?

**Comment by amitkrout** [comment]
> Do you know where exactly it fails?
Have you tried to run oc cluster up in verbose mode?

I guess the same ```cluster up``` failure due to ```waiting for condition``` is observed long back https://github.com/openshift/origin/issues/20617 and during that time it was not that important as it was inconsistent on same setup. But after few days it grows like monster I mean in most of the platform the same error appeared consistently. Now you can see many similar kind of error reported in OKD.

@syamgk Can you try out this workaround commented https://github.com/openshift/origin/issues/20617#issuecomment-452996578

**Comment by syamgk** [comment]
Had a discussion with dv and now I'm going to try Minishift against a remote machine

**Comment by kadel** [comment]
> Had a discussion with dv and now I'm going to try Minishift against a remote machine

Isn't minishift doing essentially the same? It is still  `oc cluster up` under the hood.

**Comment by amitkrout** [comment]
> Had a discussion with dv and now I'm going to try Minishift against a remote machine

@syamgk if you are lucky enough then it works for you ;)

**Comment by amitkrout** [comment]
> Isn't minishift doing essentially the same? It is still oc cluster up under the hood.

@kadel Yes, This is the same command with some extra flag arguments what minishuft uses to start the cluster. 

```
/var/lib/minishift/bin/oc cluster up --base-dir /var/lib/minishift/base --image 'openshift/origin-${component}:v3.11.0' --public-hostname 192.168.64.4 --routing-suffix 192.168.64.4.nip.io
```

**Comment by syamgk** [comment]
using minishift for bringing up cluster is working fine and was able to run end2end test on ci.centos.org
logs can be found here: https://ci.centos.org/job/odo/job/cico-test/59/console

**Comment by kadel** [comment]
What needs to be done to complete first step:
 - [ ] current  e2e tests running on centos CI
 - [ ] setup centos CI to run e2e tests on PRs (Let's not worry about any optimizations, doesn't matter if it takes longer than on travis-ci. We will optimize this later)

**Comment by syamgk** [comment]
tested with minishift and ran all tests on ci.centos.org.

- https://ci.centos.org/job/odo/job/cico-test/ 
- https://ci.centos.org/job/odo/job/cico-test/82/

**Comment by amitkrout** [comment]
Currently the complete CI run takes around 1hr10min. Not a bad start i guess as minishift start itself takes almost 8min for each test in series. I am not sure if test can run parallel in centos ci, but this is a discussion material for later as @kadel mentioned.

Well done syam 💯

**Comment by syamgk** [comment]
Since the documents only talks about the older pattern ie, using jjb files 
waiting for the resoponse from brian on how to extract the branch name and pull request number for our case, also for accepting the collaborator request for ci-user account

**Comment by kadel** [comment]
> Since the documents only talks about the older pattern ie, using jjb files
> waiting for the resoponse from brian on how to extract the branch name and pull request number for our case, also for accepting the collaborator request for ci-user account

how are other projects doing that?

**Comment by kadel** [comment]
closing in favor of https://github.com/redhat-developer/odo/issues/1431
