### ISSUE TITLE
odo watch doesn't propagate file deletions

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#988]
When I'm running `odo watch` on a directory and a file gets deleted, `odo watch` should also delete that file from the pod.
Currently, it doesn't do that, instead of that it just tries to push the nonexisting file.

It means that if I deleted a file from my source code, I have to run `odo push` to make sure that remote source code is the same as the local one

**Comment by anmolbabu** [comment]
I have a few observations as under(please note they relate to watch at the moment):
1. Watch detects delete
2. Along with pushing updates, the detected deletes should be deleted for each of the following:
    a. deployments-dir
    b. backup dir -- odo maintained
    c. destination dir
3. Normal build flow
Deletions will be in-effect on component pod
Verified the above steps for:
a. Nodejs

**Comment by anmolbabu** [comment]
The PR(https://github.com/redhat-developer/odo/pull/1125) to fix this has been merged...
Hence closing this issue
